
package br.will.graviola.service;

import java.util.Vector;

import br.will.graviola.model.*;
import br.will.graviola.model.onibus.*;
import br.will.graviola.util.StringUtil;

public class HorarioOnibusService
{
	public static Vector findLinhasByNome(String nome)
	{
		return findLinhasByNome(nome, getLinhasOnibus());
	}
	
	
	public static Vector findLinhasByNome(String nome, Vector linhas) 
	{
		Vector linhasEncontradas = new Vector();
		String nomeUpper = nome.toUpperCase();
		
		for (int i = 0; i < linhas.size(); i++) 
		{
			String linha = (String) linhas.elementAt(i);
			
			if (StringUtil.contem(nomeUpper, linha)) {
				linhasEncontradas.addElement(linha);
			}
		}
		
		return linhasEncontradas;
	}

	public static final String ONIBUSG12 = "A. BRANCA / FAZ. RIO GRANDE";
	public static final String ONIBUS464 = "A. MUNHOZ / J. BOTÂNICO";
	public static final String ONIBUS226 = "ABAETÉ";
	public static final String ONIBUS182 = "ABRANCHES";
	public static final String ONIBUS332 = "ACRÓPOLE";
	public static final String ONIBUS208 = "AEROPORTO";
	public static final String ONIBUS334 = "AGRÍCOLA";
	public static final String ONIBUSC13 = "ÁGUA CLARA";
	public static final String ONIBUS180 = "ÁGUA VERDE/ ABRANCHES";
	public static final String ONIBUSI21 = "AGUDOS DO SUL";
	public static final String ONIBUS265 = "AHÚ / LOS ANGELES";
	public static final String ONIBUS560 = "ALFERES POLI";
	public static final String ONIBUS232 = "ALIANÇA";
	public static final String ONIBUS629 = "ALTO BOQUEIRÃO";
	public static final String ONIBUS373 = "ALTO TARUMÃ";
	public static final String ONIBUSB15 = "ANA TERRA / ADRIANE";
	public static final String ONIBUSH20 = "ANGÉLICA / C. RASO";
	public static final String ONIBUSH21 = "ANGÉLICA / CIC";
	public static final String ONIBUS311 = "ARAGUAIA";
	public static final String ONIBUSI32 = "ARAUCARIA / CAMPO LARGO";
	public static final String ONIBUSH11 = "ARAUCÁRIA / PINHEIRINHO";
	public static final String ONIBUSH12 = "ARAUCÁRIA / PORTÃO";
	public static final String ONIBUSH17 = "ARAUCÁRIA/CATANDUVAS";
	public static final String ONIBUSH16 = "ARAUCARIA/CONTENDA";
	public static final String ONIBUS823 = "AUGUSTA";
	public static final String ONIBUS361 = "AUGUSTO STRESSER";
	public static final String ONIBUS313 = "AVENIDA IRAÍ / C. IMBUIA";
	public static final String ONIBUS342 = "B. ALTO / BOA VISTA";
	public static final String ONIBUSC41 = "B. ALTO / E. PERNETA";
	public static final String ONIBUS341 = "B. ALTO / STA. CÂNDIDA";
	public static final String ONIBUS307 = "B. ALTO / STA. FELICIDADE";
	public static final String ONIBUS506 = "BAIRRO NOVO";
	public static final String ONIBUS542 = "BAIRRO NOVO  B";
	public static final String ONIBUS541 = "BAIRRO NOVO A";
	public static final String ONIBUS547 = "BAIRRO NOVO C";
	public static final String ONIBUS231 = "BANESTADO / CALIFÓRNIA";
	public static final String ONIBUS205 = "BARREIRINHA";
	public static final String ONIBUS206 = "BARREIRINHA / SÃO JOSÉ";
	public static final String ONIBUS875 = "BIGORRILHO";
	public static final String ONIBUS225 = "BOA VISTA / BARREIRINHA";
	public static final String ONIBUSB33 = "BOCAIÚVA DO SUL";
	public static final String ONIBUS922 = "BOM PASTOR";
	public static final String ONIBUS175 = "BOM RETIRO / PUC";
	public static final String ONIBUS503 = "BOQUEIRÃO";
	public static final String ONIBUS505 = "BOQUEIRÃO / C. CÍVICO";
	public static final String ONIBUS540 = "BOQUEIRAO / KRAFT";
	public static final String ONIBUSO71 = "BORDA DO CAMPO";
	public static final String ONIBUS627 = "BOSCH";
	public static final String ONIBUS170 = "BRACATINGA";
	public static final String ONIBUSO75 = "BRITANITE";
	public static final String ONIBUS913 = "BUTIATUVINHA";
	public static final String ONIBUS516 = "C. BELEM / S. FILHO";
	public static final String ONIBUS828 = "C. COMPRIDO / C. RASO";
	public static final String ONIBUS826 = "C. COMPRIDO / CIC";
	public static final String ONIBUS393 = "C. IMBUIA / PQ. BARIGUI";
	public static final String ONIBUSI30 = "C. LARGO / BALSA NOVA";
	public static final String ONIBUS150 = "C. MÚSICA / V. ALEGRE";
	public static final String ONIBUS658 = "C. RASO / CAIUÁ";
	public static final String ONIBUS024 = "C. RASO / CAMP. SIQUEIRA";
	public static final String ONIBUS201 = "CABRAL / BOM RETIRO";
	public static final String ONIBUS215 = "CABRAL / CACHOEIRA";
	public static final String ONIBUSB02 = "CABRAL / MARACANÃ";
	public static final String ONIBUS207 = "CABRAL / OSÓRIO";
	public static final String ONIBUS216 = "CABRAL / PORTÃO";
	public static final String ONIBUS647 = "CACHIMBA";
	public static final String ONIBUS659 = "CACHIMBA / OLARIA";
	public static final String ONIBUS703 = "CAIUÁ";
	public static final String ONIBUS732 = "CAIUA / C.COMPRIDO";
	public static final String ONIBUS386 = "CAJURU";
	public static final String ONIBUS322 = "CAMARGO";
	public static final String ONIBUS801 = "CAMP. SIQUEIRA / BATEL";
	public static final String ONIBUS654 = "CAMPO ALEGRE";
	public static final String ONIBUSJ15 = "CAMPO LARGO";
	public static final String ONIBUS923 = "CAMPO MAGRO";
	public static final String ONIBUS475 = "CANAL BELÉM";
	public static final String ONIBUS628 = "CARBOMAFRA";
	public static final String ONIBUS776 = "CARMELA DUTRA";
	public static final String ONIBUS668 = "CASA DE CUSTÓDIA";
	public static final String ONIBUS224 = "CASSIOPÉIA";
	public static final String ONIBUS305 = "CENTENÁRIO";
	public static final String ONIBUS335 = "CENTENÁRIO / BOQUEIRÃO";
	public static final String ONIBUS303 = "CENTENÁRIO / C. COMPRIDO";
	public static final String ONIBUS338 = "CENTENÁRIO / HAUER";
	public static final String ONIBUS302 = "CENTENÁRIO / RUI BARBOSA";
	public static final String ONIBUS469 = "CENTRO POLITÉCNICO";
	public static final String ONIBUS601 = "CIC / TIRADENTES";
	public static final String ONIBUS002 = "CIRCULAR CENTRO (ANTI-HORÁRIO)";
	public static final String ONIBUS001 = "CIRCULAR CENTRO (HORÁRIO)";
	public static final String ONIBUS602 = "CIRCULAR SUL  (ANTI-HORÁRIO)";
	public static final String ONIBUS502 = "CIRCULAR SUL (HORÁRIO)";
	public static final String ONIBUS211 = "COLINA VERDE";
	public static final String ONIBUSI31 = "COLOMBO / ANG. CARON";
	public static final String ONIBUS607 = "COLOMBO / CIC";
	public static final String ONIBUSI20 = "COLOMBO / SÃO JOSÉ";
	public static final String ONIBUSB24 = "COLÔNIA FARIA";
	public static final String ONIBUS778 = "COTOLENGO";
	public static final String ONIBUS027 = "C.RASO/C.DO SIQUEIRA";
	public static final String ONIBUS385 = "CRISTO REI";
	public static final String ONIBUSC72 = "CTBA  / V. PALMITAL";
	public static final String ONIBUSE02 = "CTBA / APOLO";
	public static final String ONIBUS606 = "CTBA / ARAUCÁRIA";
	public static final String ONIBUSH01 = "CTBA / ARAUCÁRIA";
	public static final String ONIBUSG72 = "CTBA / AREIA BRANCA";
	public static final String ONIBUSP63 = "CTBA / BATEIAS";
	public static final String ONIBUSE67 = "CTBA / BRAGA";
	public static final String ONIBUSN70 = "CTBA / C. GDE  SUL (RAPIDO)";
	public static final String ONIBUSN71 = "CTBA / C. GRANDE DO SUL";
	public static final String ONIBUSJ62 = "CTBA / C. LARGO";
	public static final String ONIBUSG73 = "CTBA / CAMP. DOS PAULAS";
	public static final String ONIBUS805 = "CTBA / CAMPO LARGO";
	public static final String ONIBUSB61 = "CTBA / CAP. DO ATUBA";
	public static final String ONIBUSP64 = "CTBA / CERNE";
	public static final String ONIBUSB80 = "CTBA / COLOMBO (CAMBARÁ)";
	public static final String ONIBUSB81 = "CTBA / COLOMBO (GUARACI)";
	public static final String ONIBUSB72 = "CTBA / COLOMBO (ROD. UVA)";
	public static final String ONIBUSC63 = "CTBA / CONJ. ATUBA";
	public static final String ONIBUSR71 = "CTBA / CONTENDA";
	public static final String ONIBUSN72 = "CTBA / EUGÊNIA MARIA";
	public static final String ONIBUS605 = "CTBA / FAZ. RIO GRANDE";
	public static final String ONIBUSE77 = "CTBA / GUATUPÊ";
	public static final String ONIBUSE66 = "CTBA / INDEPENDÊNCIA";
	public static final String ONIBUSK71 = "CTBA / ITAPERUÇU";
	public static final String ONIBUSB82 = "CTBA / JD. ANA ROSA";
	public static final String ONIBUSB75 = "CTBA / JD. ARAPONGAS";
	public static final String ONIBUSB74 = "CTBA / JD. CÉSAR AUGUSTO";
	public static final String ONIBUSE75 = "CTBA / JD. CRISTAL";
	public static final String ONIBUSE73 = "CTBA / JD. CRUZEIRO";
	public static final String ONIBUSB77 = "CTBA / JD. CURITIBA";
	public static final String ONIBUSE71 = "CTBA / JD. IPÊ";
	public static final String ONIBUSE72 = "CTBA / JD. IZAURA";
	public static final String ONIBUSA73 = "CTBA / JD. MARROCOS";
	public static final String ONIBUSB73 = "CTBA / JD. OSASCO";
	public static final String ONIBUSA72 = "CTBA / JD. PARAÍSO";
	public static final String ONIBUSB78 = "CTBA / JD. SÃO GABRIEL";
	public static final String ONIBUSG71 = "CTBA / MANDIRITUBA";
	public static final String ONIBUSB01 = "CTBA / MARACANÃ";
	public static final String ONIBUSE62 = "CTBA / PEDRO MORO";
	public static final String ONIBUSD61 = "CTBA / PIRAQUARA";
	public static final String ONIBUSD66 = "CTBA / PIRAQUARA (DIRETO)";
	public static final String ONIBUSE76 = "CTBA / POSTO PARIS";
	public static final String ONIBUSO72 = "CTBA / POUSADA";
	public static final String ONIBUSE70 = "CTBA / PUC";
	public static final String ONIBUSO74 = "CTBA / Q. BARRAS (BR 116)";
	public static final String ONIBUSO73 = "CTBA / Q. BARRAS (GRACIOSA)";
	public static final String ONIBUSE68 = "CTBA / QUISISANA";
	public static final String ONIBUSL71 = "CTBA / R. BCO. DO SUL";
	public static final String ONIBUSB79 = "CTBA / ROÇA GRANDE";
	public static final String ONIBUSE78 = "CTBA / ROSEIRA";
	public static final String ONIBUSE05 = "CTBA / SÃO JOSÉ";
	public static final String ONIBUSB76 = "CTBA / SÃO SEBASTIÃO";
	public static final String ONIBUSB83 = "CTBA / STA. TEREZA";
	public static final String ONIBUSA01 = "CTBA / TAMANDARÉ";
	public static final String ONIBUSA07 = "CTBA / TAMANDARÉ (LAMENHA)";
	public static final String ONIBUSA06 = "CTBA / TAMANDARÉ (MINÉRIOS)";
	public static final String ONIBUSA77 = "CTBA / TANGUÁ";
	public static final String ONIBUSP65 = "CTBA / TERRA BOA";
	public static final String ONIBUSN73 = "CTBA / TIMBÚ";
	public static final String ONIBUSN75 = "CTBA / TIMBU (RAPIDO)";
	public static final String ONIBUSE01 = "CTBA / URANO";
	public static final String ONIBUSA78 = "CTBA / V.  MARTA";
	public static final String ONIBUSC66 = "CTBA / V. ZUMBI";
	public static final String ONIBUSE65 = "CTBA / XINGU";
	public static final String ONIBUSB06 = "CTBA/GUARAITUBA(VIA MARACANA)";
	public static final String ONIBUSO76 = "CTBA/Q.BARRAS(RAPIDO)";
	public static final String ONIBUS681 = "DALAGASSA";
	public static final String ONIBUS340 = "DETRAN / B. ALTO";
	public static final String ONIBUS380 = "DETRAN / VIC. MACHADO";
	public static final String ONIBUSC05 = "DIRETO C. IMBUIA";
	public static final String ONIBUSB31 = "DIRETO CABRAL";
	public static final String ONIBUS662 = "DOM ÁTICO";
	public static final String ONIBUS699 = "E. E. ALCINDO FANAYA 1";
	public static final String ONIBUS795 = "E. E. ALCINDO FANAYA 2";
	public static final String ONIBUS298 = "E. E. ALCINDO FANAYA 3";
	public static final String ONIBUS799 = "E. E. ALI BARK 1";
	public static final String ONIBUS798 = "E. E. ALI BARK 2";
	public static final String ONIBUS695 = "E. E. ALTO BOQUEIRÃO";
	public static final String ONIBUS399 = "E. E. APAE 1";
	public static final String ONIBUS596 = "E. E. APAE 2";
	public static final String ONIBUS598 = "E. E. APAE 3";
	public static final String ONIBUS195 = "E. E. APAE 4";
	public static final String ONIBUS199 = "E. E. APAE 5";
	public static final String ONIBUS396 = "E. E. APAE 6";
	public static final String ONIBUS297 = "E. E. ATUBA";
	public static final String ONIBUS694 = "E. E. BAIRRO NOVO";
	public static final String ONIBUS194 = "E. E. BARREIRINHA";
	public static final String ONIBUS198 = "E. E. BOA VISTA";
	public static final String ONIBUS398 = "E. E. C. IMBUIA";
	public static final String ONIBUS397 = "E. E. CAJURU";
	public static final String ONIBUS394 = "E. E. CENTRAU 1";
	public static final String ONIBUS899 = "E. E. CIC";
	public static final String ONIBUS697 = "E. E. ECUMÊNICA 1";
	public static final String ONIBUS897 = "E. E. ECUMÊNICA 2";
	public static final String ONIBUS898 = "E. E. ECUMÊNICA 3";
	public static final String ONIBUS299 = "E. E. ECUMÊNICA 4";
	public static final String ONIBUS295 = "E. E. ECUMÊNICA 5";
	public static final String ONIBUS599 = "E. E. HELENA ANTIPOFF 1";
	public static final String ONIBUS497 = "E. E. HELENA ANTIPOFF 2";
	public static final String ONIBUS197 = "E. E. HELENA ANTIPOFF 3";
	public static final String ONIBUS499 = "E. E. HELENA ANTIPOFF 4";
	public static final String ONIBUS995 = "E. E. LUCY REQUIAO 1";
	public static final String ONIBUS698 = "E. E. NOSSA SRA. DA LUZ";
	public static final String ONIBUS896 = "E. E. NOVO MUNDO";
	public static final String ONIBUS997 = "E. E. ORLEANS";
	public static final String ONIBUS196 = "E. E. PILARZINHO";
	public static final String ONIBUS495 = "E. E. PINHAIS 1";
	public static final String ONIBUS498 = "E. E. PINHAIS 2";
	public static final String ONIBUS696 = "E. E. PINHEIRINHO";
	public static final String ONIBUS391 = "E. E. SAO FRANCISCO DE ASSIS 1";
	public static final String ONIBUS597 = "E. E. SÍTIO CERCADO";
	public static final String ONIBUS296 = "E. E. STA. CÂNDIDA";
	public static final String ONIBUS996 = "E. E. STA. FELICIDADE";
	public static final String ONIBUS796 = "E. E. STA. HELENA";
	public static final String ONIBUS797 = "E. E. STA. QUITÉRIA";
	public static final String ONIBUS895 = "E. E. TATUQUARA";
	public static final String ONIBUS693 = "E. E. THOMAZ EDISON 1";
	public static final String ONIBUS893 = "E. E. TOMAZ EDISON 2";
	public static final String ONIBUS691 = "E. E. TOMAZ EDISON 3";
	public static final String ONIBUS392 = "E. E. TOMAZ EDISON 4";
	public static final String ONIBUS692 = "E. E. TOMAZ EDISON 5";
	public static final String ONIBUS496 = "E. E. UBERABA";
	public static final String ONIBUS395 = "E. E. V. OFICINAS";
	public static final String ONIBUS998 = "E. E. VIVIAN MARCAL 1";
	public static final String ONIBUS894 = "E. E. 29 DE MARÇO 1";
	public static final String ONIBUS533 = "E. VERÍSSIMO / PANTANAL";
	public static final String ONIBUS294 = "E.E. ECUMENICA 6";
	public static final String ONIBUS494 = "E.E. HELENA ANTIPOFF 5";
	public static final String ONIBUS994 = "E.E. NABIL TACLA 1";
	public static final String ONIBUS999 = "E.E. VIVIAN MARCAL 2";
	public static final String ONIBUSC23 = "EMILIANO PERNETA";
	public static final String ONIBUS465 = "ERASTO  GAERTNER";
	public static final String ONIBUSX12 = "ESPECIAL BOQUEIRAO";
	public static final String ONIBUSX19 = "ESPECIAL HASDRUBAL BELLEGARD";
	public static final String ONIBUSX18 = "ESPECIAL PAUL GARFUNKEL";
	public static final String ONIBUS968 = "ESPECIAL TROMBINI";
	public static final String ONIBUSF13 = "ESTADOS";
	public static final String ONIBUS266 = "ESTRIBO AHÚ";
	public static final String ONIBUS466 = "ESTUDANTES";
	public static final String ONIBUSF17 = "EUCALIPTOS";
	public static final String ONIBUSF24 = "EUCALIPTOS II";
	public static final String ONIBUSF27 = "EUCALIPTOS III / PIONEIROS";
	public static final String ONIBUSE64 = "EXECUTIVO / AEROPORTO";
	public static final String ONIBUS621 = "FANNY";
	public static final String ONIBUSF73 = "FAZ. RIO GRANDE / A. BRANCA";
	public static final String ONIBUSF72 = "FAZ. RIO GRANDE / MANDIRITUBA";
	public static final String ONIBUS719 = "FAZEND. / CAIUÁ-FRIGORÍF.";
	public static final String ONIBUSF05 = "FAZENDA / CIC";
	public static final String ONIBUSF01 = "FAZENDA / PINHEIRINHO";
	public static final String ONIBUSF03 = "FAZENDA (DIRETO)";
	public static final String ONIBUS701 = "FAZENDINHA";
	public static final String ONIBUS720 = "FAZENDINHA / C. COMPRIDO";
	public static final String ONIBUS831 = "FAZENDINHA / C.RASO";
	public static final String ONIBUS611 = "FAZENDINHA / PORTÃO";
	public static final String ONIBUS614 = "FAZENDINHA / PUC";
	public static final String ONIBUS702 = "FAZENDINHA / TAMANDARÉ";
	public static final String ONIBUS270 = "FERNANDO DE NORONHA";
	public static final String ONIBUS821 = "FERNÃO DIAS";
	public static final String ONIBUS673 = "FORMOSA";
	public static final String ONIBUS167 = "FREDOLIN WOLF";
	public static final String ONIBUS716 = "FRIGORIFICO";
	public static final String ONIBUS639 = "FUTURAMA";
	public static final String ONIBUS683 = "FUTURAMA / S. CERCADO";
	public static final String ONIBUS822 = "GABINETO";
	public static final String ONIBUS642 = "GANCHINHO";
	public static final String ONIBUSA16 = "GIANNINI";
	public static final String ONIBUSF15 = "GRALHA AZUL";
	public static final String ONIBUS625 = "GRAMADOS";
	public static final String ONIBUS470 = "GUABIROTUBA";
	public static final String ONIBUSB23 = "GUARAITUBA";
	public static final String ONIBUSB05 = "GUARAITUBA / CABRAL";
	public static final String ONIBUSB20 = "GUARAITUBA / CABRAL";
	public static final String ONIBUSB34 = "GUARAITUBA / MARACANA";
	public static final String ONIBUSD22 = "GUARITUBA";
	public static final String ONIBUS561 = "GUILHERMINA";
	public static final String ONIBUS513 = "HAUER / BOQUEIRÃO";
	public static final String ONIBUS371 = "HIGIENÓPOLIS";
	public static final String ONIBUS374 = "HUGO LANGE";
	public static final String ONIBUSF12 = "IGUAÇU I";
	public static final String ONIBUSF21 = "IGUAÇU II";
	public static final String ONIBUS523 = "IGUAPE I";
	public static final String ONIBUS515 = "IGUAPE II";
	public static final String ONIBUSD13 = "INTEGRAR  PIRAQUARA";
	public static final String ONIBUS023 = "INTER 2 ( ANTI-HORÁRIO)";
	public static final String ONIBUS022 = "INTER 2 (HORÁRIO)";
	public static final String ONIBUS011 = "INTERBAIRROS I (ANTI-HORÁRIO)";
	public static final String ONIBUS010 = "INTERBAIRROS I (HORÁRIO)";
	public static final String ONIBUS021 = "INTERBAIRROS II (ANTI-HORÁRIO)";
	public static final String ONIBUS020 = "INTERBAIRROS II (HORÁRIO)";
	public static final String ONIBUS030 = "INTERBAIRROS III";
	public static final String ONIBUS040 = "INTERBAIRROS IV";
	public static final String ONIBUS050 = "INTERBAIRROS V";
	public static final String ONIBUS060 = "INTERBAIRROS VI";
	public static final String ONIBUS378 = "INTERHOSPITAIS";
	public static final String ONIBUS512 = "ITAMARATI";
	public static final String ONIBUSI71 = "ITAPERUÇU / CAIC";
	public static final String ONIBUSK11 = "ITAPERUÇU / TAMANDARÉ";
	public static final String ONIBUS711 = "ITATIAIA";
	public static final String ONIBUS366 = "ITUPAVA / HOSP. MILITAR";
	public static final String ONIBUSC28 = "JACOB MACANHAN";
	public static final String ONIBUSD31 = "JD. BELA VISTA";
	public static final String ONIBUS914 = "JD. BOA VISTA";
	public static final String ONIBUS468 = "JD. CENTAURO";
	public static final String ONIBUS183 = "JD. CHAPARRAL";
	public static final String ONIBUSC20 = "JD. CLÁUDIA";
	public static final String ONIBUSB13 = "JD. DAS GRAÇAS";
	public static final String ONIBUS244 = "JD. DO ARROIO";
	public static final String ONIBUS865 = "JD. ESPLANADA";
	public static final String ONIBUSB26 = "JD. EUCALIPTOS";
	public static final String ONIBUSA14 = "JD. GRAMADOS";
	public static final String ONIBUSA31 = "JD. GRAZIELA";
	public static final String ONIBUSC11 = "JD. HOLANDÊS";
	public static final String ONIBUS712 = "JD. INDEPENDÊNCIA / CIC";
	public static final String ONIBUS917 = "JD. IPÊ";
	public static final String ONIBUSC16 = "JD. IRAÍ";
	public static final String ONIBUS972 = "JD. ITÁLIA";
	public static final String ONIBUS474 = "JD. ITIBERÊ";
	public static final String ONIBUS169 = "JD. KOSMOS";
	public static final String ONIBUS617 = "JD. LUDOVICA";
	public static final String ONIBUS160 = "JD. MERCÊS / GUANABARA";
	public static final String ONIBUSA13 = "JD. MONTE SANTO";
	public static final String ONIBUS655 = "JD. ORDEM";
	public static final String ONIBUSA21 = "JD. PARAÍSO / TAMANDARÉ";
	public static final String ONIBUS532 = "JD. PARANAENSE";
	public static final String ONIBUS921 = "JD. PIONEIRO";
	public static final String ONIBUS365 = "JD. SOCIAL / BATEL";
	public static final String ONIBUSD21 = "JD. STA. MÔNICA";
	public static final String ONIBUSC18 = "JD. TROPICAL";
	public static final String ONIBUSF25 = "JD. VENEZA";
	public static final String ONIBUSC27 = "JOAQUINA";
	public static final String ONIBUS912 = "JOSÉ CULPI";
	public static final String ONIBUS967 = "JÚLIO GRAF";
	public static final String ONIBUS285 = "JUVEVÊ / ÁGUA VERDE";
	public static final String ONIBUS656 = "KAMYR";
	public static final String ONIBUS271 = "LARANJEIRAS";
	public static final String ONIBUS520 = "LD OSTERNACK / S. CERCADO";
	public static final String ONIBUSG13 = "LG. FERREIRAS / PINHEIRINHO";
	public static final String ONIBUS550 = "LIGEIRÃO - PINHEIRINHO / C. GOMES";
	public static final String ONIBUS500 = "LIGEIRAO BOQUEIRAO";
	public static final String ONIBUS661 = "LINDÓIA";
	public static final String ONIBUS635 = "LONDRINA";
	public static final String ONIBUS641 = "LUIZ NICHELE";
	public static final String ONIBUS189 = "MAD. ABRANCHES";
	public static final String ONIBUS549 = "MAD. BAIRRO NOVO";
	public static final String ONIBUS509 = "MAD. BOQUEIRÃO";
	public static final String ONIBUS789 = "MAD. CAIUÁ";
	public static final String ONIBUS802 = "MAD. CAMPO COMPRIDO";
	public static final String ONIBUS809 = "MAD. CAMPO COMPRIDO";
	public static final String ONIBUS309 = "MAD. CENTENÁRIO";
	public static final String ONIBUS308 = "MAD. CENTENÁRIO / RUI BARBOSA";
	public static final String ONIBUS609 = "MAD. CIC";
	public static final String ONIBUSC64 = "MAD. CTBA / PINHAIS";
	public static final String ONIBUSD69 = "MAD. CTBA / PIRAQUARA";
	public static final String ONIBUSB69 = "MAD. CTBA / SÃO DIMAS";
	public static final String ONIBUSE69 = "MAD. CTBA / SÃO JOSÉ";
	public static final String ONIBUSA05 = "MAD. CTBA / TAMANDARÉ";
	public static final String ONIBUSF09 = "MAD. FAZ. RIO GRANDE";
	public static final String ONIBUSJ19 = "MAD. FERRARIA";
	public static final String ONIBUS289 = "MAD. JD. GRAZIELA";
	public static final String ONIBUS229 = "MAD. PENHA / F. NORONHA";
	public static final String ONIBUS489 = "MAD. PETRÓPOLIS / SOLITUDE";
	public static final String ONIBUS188 = "MAD. PILARZINHO / UBERABA";
	public static final String ONIBUS608 = "MAD. PINHEIRINHO";
	public static final String ONIBUS209 = "MAD. S. CÂNDIDA / C. RASO";
	public static final String ONIBUS519 = "MAD. S. FRANCISCO / IGUAPE";
	public static final String ONIBUS689 = "MAD. S. PEDRO / R. NEGRO";
	public static final String ONIBUS889 = "MAD. SÃO BRÁZ";
	public static final String ONIBUS989 = "MAD. STA. FELICIDADE";
	public static final String ONIBUS389 = "MAD. TARUMÃ / AUGUSTA";
	public static final String ONIBUS679 = "MAD. TATUQUARA";
	public static final String ONIBUS788 = "MAD. V. VELHA";
	public static final String ONIBUS260 = "MAL. HERMES / STA. EFIGÊNIA";
	public static final String ONIBUSB25 = "MARACANÃ / B. ALTO";
	public static final String ONIBUSB41 = "MARACANÃ / C. IMBUIA";
	public static final String ONIBUSB42 = "MARACANA / LINHA VERDE";
	public static final String ONIBUSB11 = "MARACANÃ / STA.  CÂNDIDA";
	public static final String ONIBUSB32 = "MARACANÃ / STA. CÂNDIDA";
	public static final String ONIBUS633 = "MARIA ANGÉLICA";
	public static final String ONIBUS522 = "MARINGÁ";
	public static final String ONIBUS721 = "MÁRIO JORGE";
	public static final String ONIBUS181 = "MATEUS LEME";
	public static final String ONIBUS594 = "MENONITAS";
	public static final String ONIBUS331 = "MERCÚRIO";
	public static final String ONIBUS812 = "MONTANA";
	public static final String ONIBUSB19 = "MONTE CASTELO";
	public static final String ONIBUS814 = "MOSSUNGUÊ";
	public static final String ONIBUSF16 = "NAÇÕES I";
	public static final String ONIBUSF22 = "NAÇÕES II";
	public static final String ONIBUS176 = "NILO PEÇANHA";
	public static final String ONIBUS521 = "NIVALDO BRAGA";
	public static final String ONIBUS674 = "NOSSA SRA. DA LUZ";
	public static final String ONIBUS280 = "NOSSA SRA. DE NAZARÉ";
	public static final String ONIBUS360 = "NOVENA";
	public static final String ONIBUS666 = "NOVO MUNDO";
	public static final String ONIBUS233 = "OLARIA";
	public static final String ONIBUS535 = "OSTERNACK / BOQUEIRÃO";
	public static final String ONIBUS548 = "OSTERNACK / S. CERCADO";
	public static final String ONIBUS915 = "OURO VERDE / V. BÁDIA";
	public static final String ONIBUS272 = "PAINEIRAS";
	public static final String ONIBUS640 = "PALMEIRA";
	public static final String ONIBUSB22 = "PALOMA";
	public static final String ONIBUSB36 = "PALOMA / GUARAITUBA";
	public static final String ONIBUS387 = "PALOTINOS";
	public static final String ONIBUS343 = "PARAÍSO";
	public static final String ONIBUS534 = "PARIGOT DE SOUZA";
	public static final String ONIBUS623 = "PARQUE INDUSTRIAL";
	public static final String ONIBUS911 = "PASSAÚNA";
	public static final String ONIBUS462 = "PETRÓPOLIS";
	public static final String ONIBUSC42 = "PINHAIS / B. ALTO";
	public static final String ONIBUS304 = "PINHAIS / C. COMPRIDO";
	public static final String ONIBUSC03 = "PINHAIS / GUADALUPE";
	public static final String ONIBUSD14 = "PINHAIS / PIRAQUARA";
	public static final String ONIBUS301 = "PINHAIS / RUI BARBOSA";
	public static final String ONIBUS603 = "PINHEIRINHO";
	public static final String ONIBUS638 = "PINHEIRINHO";
	public static final String ONIBUS644 = "PINHEIRINHO / CIC";
	public static final String ONIBUS688 = "PINHEIRINHO / ZOOLÓGICO";
	public static final String ONIBUS916 = "PINHEIROS";
	public static final String ONIBUS631 = "PIRATINI / BR 476";
	public static final String ONIBUS649 = "PIRINEUS";
	public static final String ONIBUSB14 = "PLANALTO";
	public static final String ONIBUSD11 = "PLANTA DEODORO";
	public static final String ONIBUSC22 = "PLANTA KARLA";
	public static final String ONIBUS646 = "POMPÉIA";
	public static final String ONIBUS671 = "PORTÃO";
	public static final String ONIBUS612 = "PORTÃO / CIC";
	public static final String ONIBUS616 = "PORTAO / STA. BERNADETHE - L. VERDE";
	public static final String ONIBUSX20 = "PORTAO/SITIO CERCADO";
	public static final String ONIBUSB35 = "PORTEIRA / PALOMA";
	public static final String ONIBUS718 = "PORTO BELO";
	public static final String ONIBUSF18 = "PQ. INDUSTRIAL";
	public static final String ONIBUSE63 = "PRADO VELHO / P. MORO";
	public static final String ONIBUSD16 = "PRESÍDIO";
	public static final String ONIBUS171 = "PRIMAVERA";
	public static final String ONIBUSC26 = "PRIVÊ";
	public static final String ONIBUSX16 = "PUC / RODOFERROVIARIA";
	public static final String ONIBUSE31 = "PUC / SÃO JOSÉ";
	public static final String ONIBUSI41 = "Q. BARRAS / BOCAIÚVA";
	public static final String ONIBUSI40 = "Q. BARRAS / PIRAQUARA";
	public static final String ONIBUSI51 = "Q. BARRAS/T.PAULISTA-ANTI HORARI";
	public static final String ONIBUSI50 = "Q. BARRAS/T.PAULISTA-HORARIO";
	public static final String ONIBUS632 = "QUARTEL GENERAL";
	public static final String ONIBUSG11 = "QUITANDINHA / PINHEIRINHO";
	public static final String ONIBUSL11 = "R. BRANCO / TAMANDARÉ";
	public static final String ONIBUS168 = "RAPOSO TAVARES";
	public static final String ONIBUS165 = "RAQUEL PRADO / PUC";
	public static final String ONIBUSJ12 = "REBOUÇAS";
	public static final String ONIBUS219 = "REFORÇO COLINA";
	public static final String ONIBUSX14 = "REFORÇO HAUER";
	public static final String ONIBUSX21 = "REFORCO HAUER / IFPR";
	public static final String ONIBUS539 = "REFORÇO TERMINAL";
	public static final String ONIBUSB27 = "RIBEIRA / FCO. CORADIN";
	public static final String ONIBUS684 = "RIO BONITO";
	public static final String ONIBUS685 = "RIO BONITO / CIC";
	public static final String ONIBUS636 = "RIO NEGRO";
	public static final String ONIBUS221 = "RIO VERDE";
	public static final String ONIBUS827 = "RIVIERA";
	public static final String ONIBUSB29 = "ROÇA GRANDE /  APDEC";
	public static final String ONIBUS622 = "RONDON";
	public static final String ONIBUSB18 = "ROSEIRA";
	public static final String ONIBUS370 = "RUA XV / BARIGUI";
	public static final String ONIBUS680 = "RURBANA";
	public static final String ONIBUS546 = "S. CERCADO / BOQUEIRÃO";
	public static final String ONIBUS610 = "S. CERCADO / C. RASO";
	public static final String ONIBUS653 = "SABARÁ";
	public static final String ONIBUS375 = "SAGRADO CORAÇÃO";
	public static final String ONIBUSA11 = "SAN FRANCISCO";
	public static final String ONIBUS236 = "SÃO BENEDITO";
	public static final String ONIBUS965 = "SÃO BERNARDO";
	public static final String ONIBUS870 = "SÃO BRAZ";
	public static final String ONIBUSD12 = "SÃO CRISTÓVÃO";
	public static final String ONIBUS511 = "SÃO FRANCISCO";
	public static final String ONIBUS213 = "SÃO JOÃO";
	public static final String ONIBUS670 = "SÃO JORGE";
	public static final String ONIBUSA17 = "SÃO JORGE";
	public static final String ONIBUS824 = "SÃO JOSÉ / D. FINA";
	public static final String ONIBUS811 = "SATURNO";
	public static final String ONIBUS876 = "SAVÓIA";
	public static final String ONIBUSX11 = "SITIO CERCADO / C. RASO";
	public static final String ONIBUS508 = "SÍTIO CERCADO (ANTI-HORÁRIO)";
	public static final String ONIBUS507 = "SÍTIO CERCADO (HORÁRIO)";
	public static final String ONIBUS212 = "SOLAR";
	public static final String ONIBUS463 = "SOLITUDE";
	public static final String ONIBUS713 = "STA. AMÉLIA";
	public static final String ONIBUSJ16 = "STA. ÂNGELA";
	public static final String ONIBUS461 = "STA. BARBARA";
	public static final String ONIBUS203 = "STA. CÂNDIDA / C. RASO";
	public static final String ONIBUS204 = "STA. CÂNDIDA / PINHEIRINHO";
	public static final String ONIBUS620 = "STA. CRUZ";
	public static final String ONIBUS901 = "STA. FELICIDADE";
	public static final String ONIBUS902 = "STA. FELICIDADE";
	public static final String ONIBUS924 = "STA. FELICIDADE / STA. CÂNDIDA";
	public static final String ONIBUS274 = "STA. GEMA";
	public static final String ONIBUSB17 = "STA. HELENA";
	public static final String ONIBUS531 = "STA. INÊS";
	public static final String ONIBUS637 = "STA. JOANA";
	public static final String ONIBUSF14 = "STA. MARIA";
	public static final String ONIBUS760 = "STA. QUITÉRIA";
	public static final String ONIBUS619 = "STA. RITA / CIC";
	public static final String ONIBUS650 = "STA. RITA / PINHEIRINHO";
	public static final String ONIBUS243 = "STA. TEREZINHA";
	public static final String ONIBUSF19 = "STA. TEREZINHA";
	public static final String ONIBUSF26 = "STA. TEREZINHA / IPE";
	public static final String ONIBUSE11 = "T. BOQ. / T. AFONSO PENA";
	public static final String ONIBUSE21 = "T. BOQ. / T. CENTRAL";
	public static final String ONIBUSC04 = "T. C. IMBUIA / T. PINHAIS";
	public static final String ONIBUS806 = "T. C. LARGO / CAMP. SIQUEIRA";
	public static final String ONIBUSI90 = "T. CACHOEIRA / T. MARACANÃ";
	public static final String ONIBUSA02 = "TAMANDARÉ";
	public static final String ONIBUS105 = "TAMANDARÉ / CABRAL";
	public static final String ONIBUS218 = "TAMANDARÉ / CABRAL";
	public static final String ONIBUSI91 = "TAMANDARÉ / COLOMBO";
	public static final String ONIBUSA22 = "TANGUÁ / TAMANDARÉ";
	public static final String ONIBUS372 = "TARUMÃ";
	public static final String ONIBUS667 = "TERMINAL CIC";
	public static final String ONIBUSJ14 = "TIMBOTUVA (EST. NOVA)";
	public static final String ONIBUSJ13 = "TIMBOTUVA (EST. VELHA)";
	public static final String ONIBUS214 = "TINGUI";
	public static final String ONIBUS877 = "TIRADENTES / TUIUTI  BARIGUI";
	public static final String ONIBUS545 = "TRABALHADOR";
	public static final String ONIBUS861 = "TRAMONTINA";
	public static final String ONIBUS321 = "TRINDADE";
	public static final String ONIBUS815 = "TUIUTI / BARIGUI";
	public static final String ONIBUS979 = "TURISMO";
	public static final String ONIBUS472 = "UBERABA";
	public static final String ONIBUS615 = "UBERLÂNDIA";
	public static final String ONIBUS643 = "UMBARÁ";
	public static final String ONIBUSZ01 = "UNIBRASIL / TUBO DETRAN";
	public static final String ONIBUS829 = "UNIV.POSITIVO";
	public static final String ONIBUSC25 = "V. AMÉLIA";
	public static final String ONIBUS323 = "V. AUTÓDROMO";
	public static final String ONIBUS663 = "V. CUBAS";
	public static final String ONIBUS222 = "V. ESPERANÇA";
	public static final String ONIBUSC30 = "V. GRANDE / V. TARUMÃ";
	public static final String ONIBUS761 = "V. IZABEL";
	public static final String ONIBUS242 = "V. LEONICE";
	public static final String ONIBUS467 = "V. MACEDO";
	public static final String ONIBUSD23 = "V. MACEDO";
	public static final String ONIBUSC17 = "V. MARIA ANTONIETA";
	public static final String ONIBUSB28 = "V. MARIA DO ROSÁRIO";
	public static final String ONIBUS714 = "V. MARISA";
	public static final String ONIBUS825 = "V. MARQUETO";
	public static final String ONIBUS166 = "V. NORI";
	public static final String ONIBUSC12 = "V. NOVA";
	public static final String ONIBUSA32 = "V. PRADO";
	public static final String ONIBUS336 = "V. RENO";
	public static final String ONIBUS665 = "V. REX";
	public static final String ONIBUS762 = "V. ROSINHA";
	public static final String ONIBUS860 = "V. SANDRA";
	public static final String ONIBUS471 = "V. SÃO PAULO";
	public static final String ONIBUS624 = "V. SÃO PEDRO";
	public static final String ONIBUS184 = "V. SUIÇA";
	public static final String ONIBUS613 = "V. URANO";
	public static final String ONIBUS777 = "V. VELHA";
	public static final String ONIBUS652 = "V. VERDE";
	public static final String ONIBUS918 = "VENEZA";
	public static final String ONIBUSZ03 = "VIC. DE CARVALHO / C. IMBUIA";
	public static final String ONIBUS779 = "VILA VELHA/BURITI";
	public static final String ONIBUS630 = "VITÓRIA RÉGIA";
	public static final String ONIBUS690 = "V.JULIANA";
	public static final String ONIBUSC15 = "WEISSÓPOLIS";
	public static final String ONIBUS657 = "XAXIM / CAPÃO RASO";
	public static final String ONIBUS551 = "XAXIM / LINHA VERDE";
	public static final String ONIBUS536 = "ZOOLÓGICO";
	public static Vector getLinhasOnibus() {
		Vector linhasOnibus = new Vector();

		linhasOnibus.addElement(ONIBUSG12);
		linhasOnibus.addElement(ONIBUS464);
		linhasOnibus.addElement(ONIBUS226);
		linhasOnibus.addElement(ONIBUS182);
		linhasOnibus.addElement(ONIBUS332);
		linhasOnibus.addElement(ONIBUS208);
		linhasOnibus.addElement(ONIBUS334);
		linhasOnibus.addElement(ONIBUSC13);
		linhasOnibus.addElement(ONIBUS180);
		linhasOnibus.addElement(ONIBUSI21);
		linhasOnibus.addElement(ONIBUS265);
		linhasOnibus.addElement(ONIBUS560);
		linhasOnibus.addElement(ONIBUS232);
		linhasOnibus.addElement(ONIBUS629);
		linhasOnibus.addElement(ONIBUS373);
		linhasOnibus.addElement(ONIBUSB15);
		linhasOnibus.addElement(ONIBUSH20);
		linhasOnibus.addElement(ONIBUSH21);
		linhasOnibus.addElement(ONIBUS311);
		linhasOnibus.addElement(ONIBUSI32);
		linhasOnibus.addElement(ONIBUSH11);
		linhasOnibus.addElement(ONIBUSH12);
		linhasOnibus.addElement(ONIBUSH17);
		linhasOnibus.addElement(ONIBUSH16);
		linhasOnibus.addElement(ONIBUS823);
		linhasOnibus.addElement(ONIBUS361);
		linhasOnibus.addElement(ONIBUS313);
		linhasOnibus.addElement(ONIBUS342);
		linhasOnibus.addElement(ONIBUSC41);
		linhasOnibus.addElement(ONIBUS341);
		linhasOnibus.addElement(ONIBUS307);
		linhasOnibus.addElement(ONIBUS506);
		linhasOnibus.addElement(ONIBUS542);
		linhasOnibus.addElement(ONIBUS541);
		linhasOnibus.addElement(ONIBUS547);
		linhasOnibus.addElement(ONIBUS231);
		linhasOnibus.addElement(ONIBUS205);
		linhasOnibus.addElement(ONIBUS206);
		linhasOnibus.addElement(ONIBUS875);
		linhasOnibus.addElement(ONIBUS225);
		linhasOnibus.addElement(ONIBUSB33);
		linhasOnibus.addElement(ONIBUS922);
		linhasOnibus.addElement(ONIBUS175);
		linhasOnibus.addElement(ONIBUS503);
		linhasOnibus.addElement(ONIBUS505);
		linhasOnibus.addElement(ONIBUS540);
		linhasOnibus.addElement(ONIBUSO71);
		linhasOnibus.addElement(ONIBUS627);
		linhasOnibus.addElement(ONIBUS170);
		linhasOnibus.addElement(ONIBUSO75);
		linhasOnibus.addElement(ONIBUS913);
		linhasOnibus.addElement(ONIBUS516);
		linhasOnibus.addElement(ONIBUS828);
		linhasOnibus.addElement(ONIBUS826);
		linhasOnibus.addElement(ONIBUS393);
		linhasOnibus.addElement(ONIBUSI30);
		linhasOnibus.addElement(ONIBUS150);
		linhasOnibus.addElement(ONIBUS658);
		linhasOnibus.addElement(ONIBUS024);
		linhasOnibus.addElement(ONIBUS201);
		linhasOnibus.addElement(ONIBUS215);
		linhasOnibus.addElement(ONIBUSB02);
		linhasOnibus.addElement(ONIBUS207);
		linhasOnibus.addElement(ONIBUS216);
		linhasOnibus.addElement(ONIBUS647);
		linhasOnibus.addElement(ONIBUS659);
		linhasOnibus.addElement(ONIBUS703);
		linhasOnibus.addElement(ONIBUS732);
		linhasOnibus.addElement(ONIBUS386);
		linhasOnibus.addElement(ONIBUS322);
		linhasOnibus.addElement(ONIBUS801);
		linhasOnibus.addElement(ONIBUS654);
		linhasOnibus.addElement(ONIBUSJ15);
		linhasOnibus.addElement(ONIBUS923);
		linhasOnibus.addElement(ONIBUS475);
		linhasOnibus.addElement(ONIBUS628);
		linhasOnibus.addElement(ONIBUS776);
		linhasOnibus.addElement(ONIBUS668);
		linhasOnibus.addElement(ONIBUS224);
		linhasOnibus.addElement(ONIBUS305);
		linhasOnibus.addElement(ONIBUS335);
		linhasOnibus.addElement(ONIBUS303);
		linhasOnibus.addElement(ONIBUS338);
		linhasOnibus.addElement(ONIBUS302);
		linhasOnibus.addElement(ONIBUS469);
		linhasOnibus.addElement(ONIBUS601);
		linhasOnibus.addElement(ONIBUS002);
		linhasOnibus.addElement(ONIBUS001);
		linhasOnibus.addElement(ONIBUS602);
		linhasOnibus.addElement(ONIBUS502);
		linhasOnibus.addElement(ONIBUS211);
		linhasOnibus.addElement(ONIBUSI31);
		linhasOnibus.addElement(ONIBUS607);
		linhasOnibus.addElement(ONIBUSI20);
		linhasOnibus.addElement(ONIBUSB24);
		linhasOnibus.addElement(ONIBUS778);
		linhasOnibus.addElement(ONIBUS027);
		linhasOnibus.addElement(ONIBUS385);
		linhasOnibus.addElement(ONIBUSC72);
		linhasOnibus.addElement(ONIBUSE02);
		linhasOnibus.addElement(ONIBUS606);
		linhasOnibus.addElement(ONIBUSH01);
		linhasOnibus.addElement(ONIBUSG72);
		linhasOnibus.addElement(ONIBUSP63);
		linhasOnibus.addElement(ONIBUSE67);
		linhasOnibus.addElement(ONIBUSN70);
		linhasOnibus.addElement(ONIBUSN71);
		linhasOnibus.addElement(ONIBUSJ62);
		linhasOnibus.addElement(ONIBUSG73);
		linhasOnibus.addElement(ONIBUS805);
		linhasOnibus.addElement(ONIBUSB61);
		linhasOnibus.addElement(ONIBUSP64);
		linhasOnibus.addElement(ONIBUSB80);
		linhasOnibus.addElement(ONIBUSB81);
		linhasOnibus.addElement(ONIBUSB72);
		linhasOnibus.addElement(ONIBUSC63);
		linhasOnibus.addElement(ONIBUSR71);
		linhasOnibus.addElement(ONIBUSN72);
		linhasOnibus.addElement(ONIBUS605);
		linhasOnibus.addElement(ONIBUSE77);
		linhasOnibus.addElement(ONIBUSE66);
		linhasOnibus.addElement(ONIBUSK71);
		linhasOnibus.addElement(ONIBUSB82);
		linhasOnibus.addElement(ONIBUSB75);
		linhasOnibus.addElement(ONIBUSB74);
		linhasOnibus.addElement(ONIBUSE75);
		linhasOnibus.addElement(ONIBUSE73);
		linhasOnibus.addElement(ONIBUSB77);
		linhasOnibus.addElement(ONIBUSE71);
		linhasOnibus.addElement(ONIBUSE72);
		linhasOnibus.addElement(ONIBUSA73);
		linhasOnibus.addElement(ONIBUSB73);
		linhasOnibus.addElement(ONIBUSA72);
		linhasOnibus.addElement(ONIBUSB78);
		linhasOnibus.addElement(ONIBUSG71);
		linhasOnibus.addElement(ONIBUSB01);
		linhasOnibus.addElement(ONIBUSE62);
		linhasOnibus.addElement(ONIBUSD61);
		linhasOnibus.addElement(ONIBUSD66);
		linhasOnibus.addElement(ONIBUSE76);
		linhasOnibus.addElement(ONIBUSO72);
		linhasOnibus.addElement(ONIBUSE70);
		linhasOnibus.addElement(ONIBUSO74);
		linhasOnibus.addElement(ONIBUSO73);
		linhasOnibus.addElement(ONIBUSE68);
		linhasOnibus.addElement(ONIBUSL71);
		linhasOnibus.addElement(ONIBUSB79);
		linhasOnibus.addElement(ONIBUSE78);
		linhasOnibus.addElement(ONIBUSE05);
		linhasOnibus.addElement(ONIBUSB76);
		linhasOnibus.addElement(ONIBUSB83);
		linhasOnibus.addElement(ONIBUSA01);
		linhasOnibus.addElement(ONIBUSA07);
		linhasOnibus.addElement(ONIBUSA06);
		linhasOnibus.addElement(ONIBUSA77);
		linhasOnibus.addElement(ONIBUSP65);
		linhasOnibus.addElement(ONIBUSN73);
		linhasOnibus.addElement(ONIBUSN75);
		linhasOnibus.addElement(ONIBUSE01);
		linhasOnibus.addElement(ONIBUSA78);
		linhasOnibus.addElement(ONIBUSC66);
		linhasOnibus.addElement(ONIBUSE65);
		linhasOnibus.addElement(ONIBUSB06);
		linhasOnibus.addElement(ONIBUSO76);
		linhasOnibus.addElement(ONIBUS681);
		linhasOnibus.addElement(ONIBUS340);
		linhasOnibus.addElement(ONIBUS380);
		linhasOnibus.addElement(ONIBUSC05);
		linhasOnibus.addElement(ONIBUSB31);
		linhasOnibus.addElement(ONIBUS662);
		linhasOnibus.addElement(ONIBUS699);
		linhasOnibus.addElement(ONIBUS795);
		linhasOnibus.addElement(ONIBUS298);
		linhasOnibus.addElement(ONIBUS799);
		linhasOnibus.addElement(ONIBUS798);
		linhasOnibus.addElement(ONIBUS695);
		linhasOnibus.addElement(ONIBUS399);
		linhasOnibus.addElement(ONIBUS596);
		linhasOnibus.addElement(ONIBUS598);
		linhasOnibus.addElement(ONIBUS195);
		linhasOnibus.addElement(ONIBUS199);
		linhasOnibus.addElement(ONIBUS396);
		linhasOnibus.addElement(ONIBUS297);
		linhasOnibus.addElement(ONIBUS694);
		linhasOnibus.addElement(ONIBUS194);
		linhasOnibus.addElement(ONIBUS198);
		linhasOnibus.addElement(ONIBUS398);
		linhasOnibus.addElement(ONIBUS397);
		linhasOnibus.addElement(ONIBUS394);
		linhasOnibus.addElement(ONIBUS899);
		linhasOnibus.addElement(ONIBUS697);
		linhasOnibus.addElement(ONIBUS897);
		linhasOnibus.addElement(ONIBUS898);
		linhasOnibus.addElement(ONIBUS299);
		linhasOnibus.addElement(ONIBUS295);
		linhasOnibus.addElement(ONIBUS599);
		linhasOnibus.addElement(ONIBUS497);
		linhasOnibus.addElement(ONIBUS197);
		linhasOnibus.addElement(ONIBUS499);
		linhasOnibus.addElement(ONIBUS995);
		linhasOnibus.addElement(ONIBUS698);
		linhasOnibus.addElement(ONIBUS896);
		linhasOnibus.addElement(ONIBUS997);
		linhasOnibus.addElement(ONIBUS196);
		linhasOnibus.addElement(ONIBUS495);
		linhasOnibus.addElement(ONIBUS498);
		linhasOnibus.addElement(ONIBUS696);
		linhasOnibus.addElement(ONIBUS391);
		linhasOnibus.addElement(ONIBUS597);
		linhasOnibus.addElement(ONIBUS296);
		linhasOnibus.addElement(ONIBUS996);
		linhasOnibus.addElement(ONIBUS796);
		linhasOnibus.addElement(ONIBUS797);
		linhasOnibus.addElement(ONIBUS895);
		linhasOnibus.addElement(ONIBUS693);
		linhasOnibus.addElement(ONIBUS893);
		linhasOnibus.addElement(ONIBUS691);
		linhasOnibus.addElement(ONIBUS392);
		linhasOnibus.addElement(ONIBUS692);
		linhasOnibus.addElement(ONIBUS496);
		linhasOnibus.addElement(ONIBUS395);
		linhasOnibus.addElement(ONIBUS998);
		linhasOnibus.addElement(ONIBUS894);
		linhasOnibus.addElement(ONIBUS533);
		linhasOnibus.addElement(ONIBUS294);
		linhasOnibus.addElement(ONIBUS494);
		linhasOnibus.addElement(ONIBUS994);
		linhasOnibus.addElement(ONIBUS999);
		linhasOnibus.addElement(ONIBUSC23);
		linhasOnibus.addElement(ONIBUS465);
		linhasOnibus.addElement(ONIBUSX12);
		linhasOnibus.addElement(ONIBUSX19);
		linhasOnibus.addElement(ONIBUSX18);
		linhasOnibus.addElement(ONIBUS968);
		linhasOnibus.addElement(ONIBUSF13);
		linhasOnibus.addElement(ONIBUS266);
		linhasOnibus.addElement(ONIBUS466);
		linhasOnibus.addElement(ONIBUSF17);
		linhasOnibus.addElement(ONIBUSF24);
		linhasOnibus.addElement(ONIBUSF27);
		linhasOnibus.addElement(ONIBUSE64);
		linhasOnibus.addElement(ONIBUS621);
		linhasOnibus.addElement(ONIBUSF73);
		linhasOnibus.addElement(ONIBUSF72);
		linhasOnibus.addElement(ONIBUS719);
		linhasOnibus.addElement(ONIBUSF05);
		linhasOnibus.addElement(ONIBUSF01);
		linhasOnibus.addElement(ONIBUSF03);
		linhasOnibus.addElement(ONIBUS701);
		linhasOnibus.addElement(ONIBUS720);
		linhasOnibus.addElement(ONIBUS831);
		linhasOnibus.addElement(ONIBUS611);
		linhasOnibus.addElement(ONIBUS614);
		linhasOnibus.addElement(ONIBUS702);
		linhasOnibus.addElement(ONIBUS270);
		linhasOnibus.addElement(ONIBUS821);
		linhasOnibus.addElement(ONIBUS673);
		linhasOnibus.addElement(ONIBUS167);
		linhasOnibus.addElement(ONIBUS716);
		linhasOnibus.addElement(ONIBUS639);
		linhasOnibus.addElement(ONIBUS683);
		linhasOnibus.addElement(ONIBUS822);
		linhasOnibus.addElement(ONIBUS642);
		linhasOnibus.addElement(ONIBUSA16);
		linhasOnibus.addElement(ONIBUSF15);
		linhasOnibus.addElement(ONIBUS625);
		linhasOnibus.addElement(ONIBUS470);
		linhasOnibus.addElement(ONIBUSB23);
		linhasOnibus.addElement(ONIBUSB05);
		linhasOnibus.addElement(ONIBUSB20);
		linhasOnibus.addElement(ONIBUSB34);
		linhasOnibus.addElement(ONIBUSD22);
		linhasOnibus.addElement(ONIBUS561);
		linhasOnibus.addElement(ONIBUS513);
		linhasOnibus.addElement(ONIBUS371);
		linhasOnibus.addElement(ONIBUS374);
		linhasOnibus.addElement(ONIBUSF12);
		linhasOnibus.addElement(ONIBUSF21);
		linhasOnibus.addElement(ONIBUS523);
		linhasOnibus.addElement(ONIBUS515);
		linhasOnibus.addElement(ONIBUSD13);
		linhasOnibus.addElement(ONIBUS023);
		linhasOnibus.addElement(ONIBUS022);
		linhasOnibus.addElement(ONIBUS011);
		linhasOnibus.addElement(ONIBUS010);
		linhasOnibus.addElement(ONIBUS021);
		linhasOnibus.addElement(ONIBUS020);
		linhasOnibus.addElement(ONIBUS030);
		linhasOnibus.addElement(ONIBUS040);
		linhasOnibus.addElement(ONIBUS050);
		linhasOnibus.addElement(ONIBUS060);
		linhasOnibus.addElement(ONIBUS378);
		linhasOnibus.addElement(ONIBUS512);
		linhasOnibus.addElement(ONIBUSI71);
		linhasOnibus.addElement(ONIBUSK11);
		linhasOnibus.addElement(ONIBUS711);
		linhasOnibus.addElement(ONIBUS366);
		linhasOnibus.addElement(ONIBUSC28);
		linhasOnibus.addElement(ONIBUSD31);
		linhasOnibus.addElement(ONIBUS914);
		linhasOnibus.addElement(ONIBUS468);
		linhasOnibus.addElement(ONIBUS183);
		linhasOnibus.addElement(ONIBUSC20);
		linhasOnibus.addElement(ONIBUSB13);
		linhasOnibus.addElement(ONIBUS244);
		linhasOnibus.addElement(ONIBUS865);
		linhasOnibus.addElement(ONIBUSB26);
		linhasOnibus.addElement(ONIBUSA14);
		linhasOnibus.addElement(ONIBUSA31);
		linhasOnibus.addElement(ONIBUSC11);
		linhasOnibus.addElement(ONIBUS712);
		linhasOnibus.addElement(ONIBUS917);
		linhasOnibus.addElement(ONIBUSC16);
		linhasOnibus.addElement(ONIBUS972);
		linhasOnibus.addElement(ONIBUS474);
		linhasOnibus.addElement(ONIBUS169);
		linhasOnibus.addElement(ONIBUS617);
		linhasOnibus.addElement(ONIBUS160);
		linhasOnibus.addElement(ONIBUSA13);
		linhasOnibus.addElement(ONIBUS655);
		linhasOnibus.addElement(ONIBUSA21);
		linhasOnibus.addElement(ONIBUS532);
		linhasOnibus.addElement(ONIBUS921);
		linhasOnibus.addElement(ONIBUS365);
		linhasOnibus.addElement(ONIBUSD21);
		linhasOnibus.addElement(ONIBUSC18);
		linhasOnibus.addElement(ONIBUSF25);
		linhasOnibus.addElement(ONIBUSC27);
		linhasOnibus.addElement(ONIBUS912);
		linhasOnibus.addElement(ONIBUS967);
		linhasOnibus.addElement(ONIBUS285);
		linhasOnibus.addElement(ONIBUS656);
		linhasOnibus.addElement(ONIBUS271);
		linhasOnibus.addElement(ONIBUS520);
		linhasOnibus.addElement(ONIBUSG13);
		linhasOnibus.addElement(ONIBUS550);
		linhasOnibus.addElement(ONIBUS500);
		linhasOnibus.addElement(ONIBUS661);
		linhasOnibus.addElement(ONIBUS635);
		linhasOnibus.addElement(ONIBUS641);
		linhasOnibus.addElement(ONIBUS189);
		linhasOnibus.addElement(ONIBUS549);
		linhasOnibus.addElement(ONIBUS509);
		linhasOnibus.addElement(ONIBUS789);
		linhasOnibus.addElement(ONIBUS802);
		linhasOnibus.addElement(ONIBUS809);
		linhasOnibus.addElement(ONIBUS309);
		linhasOnibus.addElement(ONIBUS308);
		linhasOnibus.addElement(ONIBUS609);
		linhasOnibus.addElement(ONIBUSC64);
		linhasOnibus.addElement(ONIBUSD69);
		linhasOnibus.addElement(ONIBUSB69);
		linhasOnibus.addElement(ONIBUSE69);
		linhasOnibus.addElement(ONIBUSA05);
		linhasOnibus.addElement(ONIBUSF09);
		linhasOnibus.addElement(ONIBUSJ19);
		linhasOnibus.addElement(ONIBUS289);
		linhasOnibus.addElement(ONIBUS229);
		linhasOnibus.addElement(ONIBUS489);
		linhasOnibus.addElement(ONIBUS188);
		linhasOnibus.addElement(ONIBUS608);
		linhasOnibus.addElement(ONIBUS209);
		linhasOnibus.addElement(ONIBUS519);
		linhasOnibus.addElement(ONIBUS689);
		linhasOnibus.addElement(ONIBUS889);
		linhasOnibus.addElement(ONIBUS989);
		linhasOnibus.addElement(ONIBUS389);
		linhasOnibus.addElement(ONIBUS679);
		linhasOnibus.addElement(ONIBUS788);
		linhasOnibus.addElement(ONIBUS260);
		linhasOnibus.addElement(ONIBUSB25);
		linhasOnibus.addElement(ONIBUSB41);
		linhasOnibus.addElement(ONIBUSB42);
		linhasOnibus.addElement(ONIBUSB11);
		linhasOnibus.addElement(ONIBUSB32);
		linhasOnibus.addElement(ONIBUS633);
		linhasOnibus.addElement(ONIBUS522);
		linhasOnibus.addElement(ONIBUS721);
		linhasOnibus.addElement(ONIBUS181);
		linhasOnibus.addElement(ONIBUS594);
		linhasOnibus.addElement(ONIBUS331);
		linhasOnibus.addElement(ONIBUS812);
		linhasOnibus.addElement(ONIBUSB19);
		linhasOnibus.addElement(ONIBUS814);
		linhasOnibus.addElement(ONIBUSF16);
		linhasOnibus.addElement(ONIBUSF22);
		linhasOnibus.addElement(ONIBUS176);
		linhasOnibus.addElement(ONIBUS521);
		linhasOnibus.addElement(ONIBUS674);
		linhasOnibus.addElement(ONIBUS280);
		linhasOnibus.addElement(ONIBUS360);
		linhasOnibus.addElement(ONIBUS666);
		linhasOnibus.addElement(ONIBUS233);
		linhasOnibus.addElement(ONIBUS535);
		linhasOnibus.addElement(ONIBUS548);
		linhasOnibus.addElement(ONIBUS915);
		linhasOnibus.addElement(ONIBUS272);
		linhasOnibus.addElement(ONIBUS640);
		linhasOnibus.addElement(ONIBUSB22);
		linhasOnibus.addElement(ONIBUSB36);
		linhasOnibus.addElement(ONIBUS387);
		linhasOnibus.addElement(ONIBUS343);
		linhasOnibus.addElement(ONIBUS534);
		linhasOnibus.addElement(ONIBUS623);
		linhasOnibus.addElement(ONIBUS911);
		linhasOnibus.addElement(ONIBUS462);
		linhasOnibus.addElement(ONIBUSC42);
		linhasOnibus.addElement(ONIBUS304);
		linhasOnibus.addElement(ONIBUSC03);
		linhasOnibus.addElement(ONIBUSD14);
		linhasOnibus.addElement(ONIBUS301);
		linhasOnibus.addElement(ONIBUS603);
		linhasOnibus.addElement(ONIBUS638);
		linhasOnibus.addElement(ONIBUS644);
		linhasOnibus.addElement(ONIBUS688);
		linhasOnibus.addElement(ONIBUS916);
		linhasOnibus.addElement(ONIBUS631);
		linhasOnibus.addElement(ONIBUS649);
		linhasOnibus.addElement(ONIBUSB14);
		linhasOnibus.addElement(ONIBUSD11);
		linhasOnibus.addElement(ONIBUSC22);
		linhasOnibus.addElement(ONIBUS646);
		linhasOnibus.addElement(ONIBUS671);
		linhasOnibus.addElement(ONIBUS612);
		linhasOnibus.addElement(ONIBUS616);
		linhasOnibus.addElement(ONIBUSX20);
		linhasOnibus.addElement(ONIBUSB35);
		linhasOnibus.addElement(ONIBUS718);
		linhasOnibus.addElement(ONIBUSF18);
		linhasOnibus.addElement(ONIBUSE63);
		linhasOnibus.addElement(ONIBUSD16);
		linhasOnibus.addElement(ONIBUS171);
		linhasOnibus.addElement(ONIBUSC26);
		linhasOnibus.addElement(ONIBUSX16);
		linhasOnibus.addElement(ONIBUSE31);
		linhasOnibus.addElement(ONIBUSI41);
		linhasOnibus.addElement(ONIBUSI40);
		linhasOnibus.addElement(ONIBUSI51);
		linhasOnibus.addElement(ONIBUSI50);
		linhasOnibus.addElement(ONIBUS632);
		linhasOnibus.addElement(ONIBUSG11);
		linhasOnibus.addElement(ONIBUSL11);
		linhasOnibus.addElement(ONIBUS168);
		linhasOnibus.addElement(ONIBUS165);
		linhasOnibus.addElement(ONIBUSJ12);
		linhasOnibus.addElement(ONIBUS219);
		linhasOnibus.addElement(ONIBUSX14);
		linhasOnibus.addElement(ONIBUSX21);
		linhasOnibus.addElement(ONIBUS539);
		linhasOnibus.addElement(ONIBUSB27);
		linhasOnibus.addElement(ONIBUS684);
		linhasOnibus.addElement(ONIBUS685);
		linhasOnibus.addElement(ONIBUS636);
		linhasOnibus.addElement(ONIBUS221);
		linhasOnibus.addElement(ONIBUS827);
		linhasOnibus.addElement(ONIBUSB29);
		linhasOnibus.addElement(ONIBUS622);
		linhasOnibus.addElement(ONIBUSB18);
		linhasOnibus.addElement(ONIBUS370);
		linhasOnibus.addElement(ONIBUS680);
		linhasOnibus.addElement(ONIBUS546);
		linhasOnibus.addElement(ONIBUS610);
		linhasOnibus.addElement(ONIBUS653);
		linhasOnibus.addElement(ONIBUS375);
		linhasOnibus.addElement(ONIBUSA11);
		linhasOnibus.addElement(ONIBUS236);
		linhasOnibus.addElement(ONIBUS965);
		linhasOnibus.addElement(ONIBUS870);
		linhasOnibus.addElement(ONIBUSD12);
		linhasOnibus.addElement(ONIBUS511);
		linhasOnibus.addElement(ONIBUS213);
		linhasOnibus.addElement(ONIBUS670);
		linhasOnibus.addElement(ONIBUSA17);
		linhasOnibus.addElement(ONIBUS824);
		linhasOnibus.addElement(ONIBUS811);
		linhasOnibus.addElement(ONIBUS876);
		linhasOnibus.addElement(ONIBUSX11);
		linhasOnibus.addElement(ONIBUS508);
		linhasOnibus.addElement(ONIBUS507);
		linhasOnibus.addElement(ONIBUS212);
		linhasOnibus.addElement(ONIBUS463);
		linhasOnibus.addElement(ONIBUS713);
		linhasOnibus.addElement(ONIBUSJ16);
		linhasOnibus.addElement(ONIBUS461);
		linhasOnibus.addElement(ONIBUS203);
		linhasOnibus.addElement(ONIBUS204);
		linhasOnibus.addElement(ONIBUS620);
		linhasOnibus.addElement(ONIBUS901);
		linhasOnibus.addElement(ONIBUS902);
		linhasOnibus.addElement(ONIBUS924);
		linhasOnibus.addElement(ONIBUS274);
		linhasOnibus.addElement(ONIBUSB17);
		linhasOnibus.addElement(ONIBUS531);
		linhasOnibus.addElement(ONIBUS637);
		linhasOnibus.addElement(ONIBUSF14);
		linhasOnibus.addElement(ONIBUS760);
		linhasOnibus.addElement(ONIBUS619);
		linhasOnibus.addElement(ONIBUS650);
		linhasOnibus.addElement(ONIBUS243);
		linhasOnibus.addElement(ONIBUSF19);
		linhasOnibus.addElement(ONIBUSF26);
		linhasOnibus.addElement(ONIBUSE11);
		linhasOnibus.addElement(ONIBUSE21);
		linhasOnibus.addElement(ONIBUSC04);
		linhasOnibus.addElement(ONIBUS806);
		linhasOnibus.addElement(ONIBUSI90);
		linhasOnibus.addElement(ONIBUSA02);
		linhasOnibus.addElement(ONIBUS105);
		linhasOnibus.addElement(ONIBUS218);
		linhasOnibus.addElement(ONIBUSI91);
		linhasOnibus.addElement(ONIBUSA22);
		linhasOnibus.addElement(ONIBUS372);
		linhasOnibus.addElement(ONIBUS667);
		linhasOnibus.addElement(ONIBUSJ14);
		linhasOnibus.addElement(ONIBUSJ13);
		linhasOnibus.addElement(ONIBUS214);
		linhasOnibus.addElement(ONIBUS877);
		linhasOnibus.addElement(ONIBUS545);
		linhasOnibus.addElement(ONIBUS861);
		linhasOnibus.addElement(ONIBUS321);
		linhasOnibus.addElement(ONIBUS815);
		linhasOnibus.addElement(ONIBUS979);
		linhasOnibus.addElement(ONIBUS472);
		linhasOnibus.addElement(ONIBUS615);
		linhasOnibus.addElement(ONIBUS643);
		linhasOnibus.addElement(ONIBUSZ01);
		linhasOnibus.addElement(ONIBUS829);
		linhasOnibus.addElement(ONIBUSC25);
		linhasOnibus.addElement(ONIBUS323);
		linhasOnibus.addElement(ONIBUS663);
		linhasOnibus.addElement(ONIBUS222);
		linhasOnibus.addElement(ONIBUSC30);
		linhasOnibus.addElement(ONIBUS761);
		linhasOnibus.addElement(ONIBUS242);
		linhasOnibus.addElement(ONIBUS467);
		linhasOnibus.addElement(ONIBUSD23);
		linhasOnibus.addElement(ONIBUSC17);
		linhasOnibus.addElement(ONIBUSB28);
		linhasOnibus.addElement(ONIBUS714);
		linhasOnibus.addElement(ONIBUS825);
		linhasOnibus.addElement(ONIBUS166);
		linhasOnibus.addElement(ONIBUSC12);
		linhasOnibus.addElement(ONIBUSA32);
		linhasOnibus.addElement(ONIBUS336);
		linhasOnibus.addElement(ONIBUS665);
		linhasOnibus.addElement(ONIBUS762);
		linhasOnibus.addElement(ONIBUS860);
		linhasOnibus.addElement(ONIBUS471);
		linhasOnibus.addElement(ONIBUS624);
		linhasOnibus.addElement(ONIBUS184);
		linhasOnibus.addElement(ONIBUS613);
		linhasOnibus.addElement(ONIBUS777);
		linhasOnibus.addElement(ONIBUS652);
		linhasOnibus.addElement(ONIBUS918);
		linhasOnibus.addElement(ONIBUSZ03);
		linhasOnibus.addElement(ONIBUS779);
		linhasOnibus.addElement(ONIBUS630);
		linhasOnibus.addElement(ONIBUS690);
		linhasOnibus.addElement(ONIBUSC15);
		linhasOnibus.addElement(ONIBUS657);
		linhasOnibus.addElement(ONIBUS551);
		linhasOnibus.addElement(ONIBUS536);	
		return linhasOnibus;
	} 

	public static Onibus getByNome(String nome)
	{
		Onibus onibus = create( nome );
		
		HoraService service = new HoraService();
		
		for (int i = 0; i < onibus.getPontos().size(); i++)
		{
			Ponto ponto = (Ponto) onibus.getPontos().elementAt(i);
			ponto.setHorariosMarcados( service.findProximosHorarios(ponto) );
		}
		
		return onibus;
	}
	
	public static Onibus create(String nome) 
	{

		if (nome.equals( ONIBUSG12 )) return OnibusG12.create();
		if (nome.equals( ONIBUS464 )) return Onibus464.create();
		if (nome.equals( ONIBUS226 )) return Onibus226.create();
		if (nome.equals( ONIBUS182 )) return Onibus182.create();
		if (nome.equals( ONIBUS332 )) return Onibus332.create();
		if (nome.equals( ONIBUS208 )) return Onibus208.create();
		if (nome.equals( ONIBUS334 )) return Onibus334.create();
		if (nome.equals( ONIBUSC13 )) return OnibusC13.create();
		if (nome.equals( ONIBUS180 )) return Onibus180.create();
		if (nome.equals( ONIBUSI21 )) return OnibusI21.create();
		if (nome.equals( ONIBUS265 )) return Onibus265.create();
		if (nome.equals( ONIBUS560 )) return Onibus560.create();
		if (nome.equals( ONIBUS232 )) return Onibus232.create();
		if (nome.equals( ONIBUS629 )) return Onibus629.create();
		if (nome.equals( ONIBUS373 )) return Onibus373.create();
		if (nome.equals( ONIBUSB15 )) return OnibusB15.create();
		if (nome.equals( ONIBUSH20 )) return OnibusH20.create();
		if (nome.equals( ONIBUSH21 )) return OnibusH21.create();
		if (nome.equals( ONIBUS311 )) return Onibus311.create();
		if (nome.equals( ONIBUSI32 )) return OnibusI32.create();
		if (nome.equals( ONIBUSH11 )) return OnibusH11.create();
		if (nome.equals( ONIBUSH12 )) return OnibusH12.create();
		if (nome.equals( ONIBUSH17 )) return OnibusH17.create();
		if (nome.equals( ONIBUSH16 )) return OnibusH16.create();
		if (nome.equals( ONIBUS823 )) return Onibus823.create();
		if (nome.equals( ONIBUS361 )) return Onibus361.create();
		if (nome.equals( ONIBUS313 )) return Onibus313.create();
		if (nome.equals( ONIBUS342 )) return Onibus342.create();
		if (nome.equals( ONIBUSC41 )) return OnibusC41.create();
		if (nome.equals( ONIBUS341 )) return Onibus341.create();
		if (nome.equals( ONIBUS307 )) return Onibus307.create();
		if (nome.equals( ONIBUS506 )) return Onibus506.create();
		if (nome.equals( ONIBUS542 )) return Onibus542.create();
		if (nome.equals( ONIBUS541 )) return Onibus541.create();
		if (nome.equals( ONIBUS547 )) return Onibus547.create();
		if (nome.equals( ONIBUS231 )) return Onibus231.create();
		if (nome.equals( ONIBUS205 )) return Onibus205.create();
		if (nome.equals( ONIBUS206 )) return Onibus206.create();
		if (nome.equals( ONIBUS875 )) return Onibus875.create();
		if (nome.equals( ONIBUS225 )) return Onibus225.create();
		if (nome.equals( ONIBUSB33 )) return OnibusB33.create();
		if (nome.equals( ONIBUS922 )) return Onibus922.create();
		if (nome.equals( ONIBUS175 )) return Onibus175.create();
		if (nome.equals( ONIBUS503 )) return Onibus503.create();
		if (nome.equals( ONIBUS505 )) return Onibus505.create();
		if (nome.equals( ONIBUS540 )) return Onibus540.create();
		if (nome.equals( ONIBUSO71 )) return OnibusO71.create();
		if (nome.equals( ONIBUS627 )) return Onibus627.create();
		if (nome.equals( ONIBUS170 )) return Onibus170.create();
		if (nome.equals( ONIBUSO75 )) return OnibusO75.create();
		if (nome.equals( ONIBUS913 )) return Onibus913.create();
		if (nome.equals( ONIBUS516 )) return Onibus516.create();
		if (nome.equals( ONIBUS828 )) return Onibus828.create();
		if (nome.equals( ONIBUS826 )) return Onibus826.create();
		if (nome.equals( ONIBUS393 )) return Onibus393.create();
		if (nome.equals( ONIBUSI30 )) return OnibusI30.create();
		if (nome.equals( ONIBUS150 )) return Onibus150.create();
		if (nome.equals( ONIBUS658 )) return Onibus658.create();
		if (nome.equals( ONIBUS024 )) return Onibus024.create();
		if (nome.equals( ONIBUS201 )) return Onibus201.create();
		if (nome.equals( ONIBUS215 )) return Onibus215.create();
		if (nome.equals( ONIBUSB02 )) return OnibusB02.create();
		if (nome.equals( ONIBUS207 )) return Onibus207.create();
		if (nome.equals( ONIBUS216 )) return Onibus216.create();
		if (nome.equals( ONIBUS647 )) return Onibus647.create();
		if (nome.equals( ONIBUS659 )) return Onibus659.create();
		if (nome.equals( ONIBUS703 )) return Onibus703.create();
		if (nome.equals( ONIBUS732 )) return Onibus732.create();
		if (nome.equals( ONIBUS386 )) return Onibus386.create();
		if (nome.equals( ONIBUS322 )) return Onibus322.create();
		if (nome.equals( ONIBUS801 )) return Onibus801.create();
		if (nome.equals( ONIBUS654 )) return Onibus654.create();
		if (nome.equals( ONIBUSJ15 )) return OnibusJ15.create();
		if (nome.equals( ONIBUS923 )) return Onibus923.create();
		if (nome.equals( ONIBUS475 )) return Onibus475.create();
		if (nome.equals( ONIBUS628 )) return Onibus628.create();
		if (nome.equals( ONIBUS776 )) return Onibus776.create();
		if (nome.equals( ONIBUS668 )) return Onibus668.create();
		if (nome.equals( ONIBUS224 )) return Onibus224.create();
		if (nome.equals( ONIBUS305 )) return Onibus305.create();
		if (nome.equals( ONIBUS335 )) return Onibus335.create();
		if (nome.equals( ONIBUS303 )) return Onibus303.create();
		if (nome.equals( ONIBUS338 )) return Onibus338.create();
		if (nome.equals( ONIBUS302 )) return Onibus302.create();
		if (nome.equals( ONIBUS469 )) return Onibus469.create();
		if (nome.equals( ONIBUS601 )) return Onibus601.create();
		if (nome.equals( ONIBUS002 )) return Onibus002.create();
		if (nome.equals( ONIBUS001 )) return Onibus001.create();
		if (nome.equals( ONIBUS602 )) return Onibus602.create();
		if (nome.equals( ONIBUS502 )) return Onibus502.create();
		if (nome.equals( ONIBUS211 )) return Onibus211.create();
		if (nome.equals( ONIBUSI31 )) return OnibusI31.create();
		if (nome.equals( ONIBUS607 )) return Onibus607.create();
		if (nome.equals( ONIBUSI20 )) return OnibusI20.create();
		if (nome.equals( ONIBUSB24 )) return OnibusB24.create();
		if (nome.equals( ONIBUS778 )) return Onibus778.create();
		if (nome.equals( ONIBUS027 )) return Onibus027.create();
		if (nome.equals( ONIBUS385 )) return Onibus385.create();
		if (nome.equals( ONIBUSC72 )) return OnibusC72.create();
		if (nome.equals( ONIBUSE02 )) return OnibusE02.create();
		if (nome.equals( ONIBUS606 )) return Onibus606.create();
		if (nome.equals( ONIBUSH01 )) return OnibusH01.create();
		if (nome.equals( ONIBUSG72 )) return OnibusG72.create();
		if (nome.equals( ONIBUSP63 )) return OnibusP63.create();
		if (nome.equals( ONIBUSE67 )) return OnibusE67.create();
		if (nome.equals( ONIBUSN70 )) return OnibusN70.create();
		if (nome.equals( ONIBUSN71 )) return OnibusN71.create();
		if (nome.equals( ONIBUSJ62 )) return OnibusJ62.create();
		if (nome.equals( ONIBUSG73 )) return OnibusG73.create();
		if (nome.equals( ONIBUS805 )) return Onibus805.create();
		if (nome.equals( ONIBUSB61 )) return OnibusB61.create();
		if (nome.equals( ONIBUSP64 )) return OnibusP64.create();
		if (nome.equals( ONIBUSB80 )) return OnibusB80.create();
		if (nome.equals( ONIBUSB81 )) return OnibusB81.create();
		if (nome.equals( ONIBUSB72 )) return OnibusB72.create();
		if (nome.equals( ONIBUSC63 )) return OnibusC63.create();
		if (nome.equals( ONIBUSR71 )) return OnibusR71.create();
		if (nome.equals( ONIBUSN72 )) return OnibusN72.create();
		if (nome.equals( ONIBUS605 )) return Onibus605.create();
		if (nome.equals( ONIBUSE77 )) return OnibusE77.create();
		if (nome.equals( ONIBUSE66 )) return OnibusE66.create();
		if (nome.equals( ONIBUSK71 )) return OnibusK71.create();
		if (nome.equals( ONIBUSB82 )) return OnibusB82.create();
		if (nome.equals( ONIBUSB75 )) return OnibusB75.create();
		if (nome.equals( ONIBUSB74 )) return OnibusB74.create();
		if (nome.equals( ONIBUSE75 )) return OnibusE75.create();
		if (nome.equals( ONIBUSE73 )) return OnibusE73.create();
		if (nome.equals( ONIBUSB77 )) return OnibusB77.create();
		if (nome.equals( ONIBUSE71 )) return OnibusE71.create();
		if (nome.equals( ONIBUSE72 )) return OnibusE72.create();
		if (nome.equals( ONIBUSA73 )) return OnibusA73.create();
		if (nome.equals( ONIBUSB73 )) return OnibusB73.create();
		if (nome.equals( ONIBUSA72 )) return OnibusA72.create();
		if (nome.equals( ONIBUSB78 )) return OnibusB78.create();
		if (nome.equals( ONIBUSG71 )) return OnibusG71.create();
		if (nome.equals( ONIBUSB01 )) return OnibusB01.create();
		if (nome.equals( ONIBUSE62 )) return OnibusE62.create();
		if (nome.equals( ONIBUSD61 )) return OnibusD61.create();
		if (nome.equals( ONIBUSD66 )) return OnibusD66.create();
		if (nome.equals( ONIBUSE76 )) return OnibusE76.create();
		if (nome.equals( ONIBUSO72 )) return OnibusO72.create();
		if (nome.equals( ONIBUSE70 )) return OnibusE70.create();
		if (nome.equals( ONIBUSO74 )) return OnibusO74.create();
		if (nome.equals( ONIBUSO73 )) return OnibusO73.create();
		if (nome.equals( ONIBUSE68 )) return OnibusE68.create();
		if (nome.equals( ONIBUSL71 )) return OnibusL71.create();
		if (nome.equals( ONIBUSB79 )) return OnibusB79.create();
		if (nome.equals( ONIBUSE78 )) return OnibusE78.create();
		if (nome.equals( ONIBUSE05 )) return OnibusE05.create();
		if (nome.equals( ONIBUSB76 )) return OnibusB76.create();
		if (nome.equals( ONIBUSB83 )) return OnibusB83.create();
		if (nome.equals( ONIBUSA01 )) return OnibusA01.create();
		if (nome.equals( ONIBUSA07 )) return OnibusA07.create();
		if (nome.equals( ONIBUSA06 )) return OnibusA06.create();
		if (nome.equals( ONIBUSA77 )) return OnibusA77.create();
		if (nome.equals( ONIBUSP65 )) return OnibusP65.create();
		if (nome.equals( ONIBUSN73 )) return OnibusN73.create();
		if (nome.equals( ONIBUSN75 )) return OnibusN75.create();
		if (nome.equals( ONIBUSE01 )) return OnibusE01.create();
		if (nome.equals( ONIBUSA78 )) return OnibusA78.create();
		if (nome.equals( ONIBUSC66 )) return OnibusC66.create();
		if (nome.equals( ONIBUSE65 )) return OnibusE65.create();
		if (nome.equals( ONIBUSB06 )) return OnibusB06.create();
		if (nome.equals( ONIBUSO76 )) return OnibusO76.create();
		if (nome.equals( ONIBUS681 )) return Onibus681.create();
		if (nome.equals( ONIBUS340 )) return Onibus340.create();
		if (nome.equals( ONIBUS380 )) return Onibus380.create();
		if (nome.equals( ONIBUSC05 )) return OnibusC05.create();
		if (nome.equals( ONIBUSB31 )) return OnibusB31.create();
		if (nome.equals( ONIBUS662 )) return Onibus662.create();
		if (nome.equals( ONIBUS699 )) return Onibus699.create();
		if (nome.equals( ONIBUS795 )) return Onibus795.create();
		if (nome.equals( ONIBUS298 )) return Onibus298.create();
		if (nome.equals( ONIBUS799 )) return Onibus799.create();
		if (nome.equals( ONIBUS798 )) return Onibus798.create();
		if (nome.equals( ONIBUS695 )) return Onibus695.create();
		if (nome.equals( ONIBUS399 )) return Onibus399.create();
		if (nome.equals( ONIBUS596 )) return Onibus596.create();
		if (nome.equals( ONIBUS598 )) return Onibus598.create();
		if (nome.equals( ONIBUS195 )) return Onibus195.create();
		if (nome.equals( ONIBUS199 )) return Onibus199.create();
		if (nome.equals( ONIBUS396 )) return Onibus396.create();
		if (nome.equals( ONIBUS297 )) return Onibus297.create();
		if (nome.equals( ONIBUS694 )) return Onibus694.create();
		if (nome.equals( ONIBUS194 )) return Onibus194.create();
		if (nome.equals( ONIBUS198 )) return Onibus198.create();
		if (nome.equals( ONIBUS398 )) return Onibus398.create();
		if (nome.equals( ONIBUS397 )) return Onibus397.create();
		if (nome.equals( ONIBUS394 )) return Onibus394.create();
		if (nome.equals( ONIBUS899 )) return Onibus899.create();
		if (nome.equals( ONIBUS697 )) return Onibus697.create();
		if (nome.equals( ONIBUS897 )) return Onibus897.create();
		if (nome.equals( ONIBUS898 )) return Onibus898.create();
		if (nome.equals( ONIBUS299 )) return Onibus299.create();
		if (nome.equals( ONIBUS295 )) return Onibus295.create();
		if (nome.equals( ONIBUS599 )) return Onibus599.create();
		if (nome.equals( ONIBUS497 )) return Onibus497.create();
		if (nome.equals( ONIBUS197 )) return Onibus197.create();
		if (nome.equals( ONIBUS499 )) return Onibus499.create();
		if (nome.equals( ONIBUS995 )) return Onibus995.create();
		if (nome.equals( ONIBUS698 )) return Onibus698.create();
		if (nome.equals( ONIBUS896 )) return Onibus896.create();
		if (nome.equals( ONIBUS997 )) return Onibus997.create();
		if (nome.equals( ONIBUS196 )) return Onibus196.create();
		if (nome.equals( ONIBUS495 )) return Onibus495.create();
		if (nome.equals( ONIBUS498 )) return Onibus498.create();
		if (nome.equals( ONIBUS696 )) return Onibus696.create();
		if (nome.equals( ONIBUS391 )) return Onibus391.create();
		if (nome.equals( ONIBUS597 )) return Onibus597.create();
		if (nome.equals( ONIBUS296 )) return Onibus296.create();
		if (nome.equals( ONIBUS996 )) return Onibus996.create();
		if (nome.equals( ONIBUS796 )) return Onibus796.create();
		if (nome.equals( ONIBUS797 )) return Onibus797.create();
		if (nome.equals( ONIBUS895 )) return Onibus895.create();
		if (nome.equals( ONIBUS693 )) return Onibus693.create();
		if (nome.equals( ONIBUS893 )) return Onibus893.create();
		if (nome.equals( ONIBUS691 )) return Onibus691.create();
		if (nome.equals( ONIBUS392 )) return Onibus392.create();
		if (nome.equals( ONIBUS692 )) return Onibus692.create();
		if (nome.equals( ONIBUS496 )) return Onibus496.create();
		if (nome.equals( ONIBUS395 )) return Onibus395.create();
		if (nome.equals( ONIBUS998 )) return Onibus998.create();
		if (nome.equals( ONIBUS894 )) return Onibus894.create();
		if (nome.equals( ONIBUS533 )) return Onibus533.create();
		if (nome.equals( ONIBUS294 )) return Onibus294.create();
		if (nome.equals( ONIBUS494 )) return Onibus494.create();
		if (nome.equals( ONIBUS994 )) return Onibus994.create();
		if (nome.equals( ONIBUS999 )) return Onibus999.create();
		if (nome.equals( ONIBUSC23 )) return OnibusC23.create();
		if (nome.equals( ONIBUS465 )) return Onibus465.create();
		if (nome.equals( ONIBUSX12 )) return OnibusX12.create();
		if (nome.equals( ONIBUSX19 )) return OnibusX19.create();
		if (nome.equals( ONIBUSX18 )) return OnibusX18.create();
		if (nome.equals( ONIBUS968 )) return Onibus968.create();
		if (nome.equals( ONIBUSF13 )) return OnibusF13.create();
		if (nome.equals( ONIBUS266 )) return Onibus266.create();
		if (nome.equals( ONIBUS466 )) return Onibus466.create();
		if (nome.equals( ONIBUSF17 )) return OnibusF17.create();
		if (nome.equals( ONIBUSF24 )) return OnibusF24.create();
		if (nome.equals( ONIBUSF27 )) return OnibusF27.create();
		if (nome.equals( ONIBUSE64 )) return OnibusE64.create();
		if (nome.equals( ONIBUS621 )) return Onibus621.create();
		if (nome.equals( ONIBUSF73 )) return OnibusF73.create();
		if (nome.equals( ONIBUSF72 )) return OnibusF72.create();
		if (nome.equals( ONIBUS719 )) return Onibus719.create();
		if (nome.equals( ONIBUSF05 )) return OnibusF05.create();
		if (nome.equals( ONIBUSF01 )) return OnibusF01.create();
		if (nome.equals( ONIBUSF03 )) return OnibusF03.create();
		if (nome.equals( ONIBUS701 )) return Onibus701.create();
		if (nome.equals( ONIBUS720 )) return Onibus720.create();
		if (nome.equals( ONIBUS831 )) return Onibus831.create();
		if (nome.equals( ONIBUS611 )) return Onibus611.create();
		if (nome.equals( ONIBUS614 )) return Onibus614.create();
		if (nome.equals( ONIBUS702 )) return Onibus702.create();
		if (nome.equals( ONIBUS270 )) return Onibus270.create();
		if (nome.equals( ONIBUS821 )) return Onibus821.create();
		if (nome.equals( ONIBUS673 )) return Onibus673.create();
		if (nome.equals( ONIBUS167 )) return Onibus167.create();
		if (nome.equals( ONIBUS716 )) return Onibus716.create();
		if (nome.equals( ONIBUS639 )) return Onibus639.create();
		if (nome.equals( ONIBUS683 )) return Onibus683.create();
		if (nome.equals( ONIBUS822 )) return Onibus822.create();
		if (nome.equals( ONIBUS642 )) return Onibus642.create();
		if (nome.equals( ONIBUSA16 )) return OnibusA16.create();
		if (nome.equals( ONIBUSF15 )) return OnibusF15.create();
		if (nome.equals( ONIBUS625 )) return Onibus625.create();
		if (nome.equals( ONIBUS470 )) return Onibus470.create();
		if (nome.equals( ONIBUSB23 )) return OnibusB23.create();
		if (nome.equals( ONIBUSB05 )) return OnibusB05.create();
		if (nome.equals( ONIBUSB20 )) return OnibusB20.create();
		if (nome.equals( ONIBUSB34 )) return OnibusB34.create();
		if (nome.equals( ONIBUSD22 )) return OnibusD22.create();
		if (nome.equals( ONIBUS561 )) return Onibus561.create();
		if (nome.equals( ONIBUS513 )) return Onibus513.create();
		if (nome.equals( ONIBUS371 )) return Onibus371.create();
		if (nome.equals( ONIBUS374 )) return Onibus374.create();
		if (nome.equals( ONIBUSF12 )) return OnibusF12.create();
		if (nome.equals( ONIBUSF21 )) return OnibusF21.create();
		if (nome.equals( ONIBUS523 )) return Onibus523.create();
		if (nome.equals( ONIBUS515 )) return Onibus515.create();
		if (nome.equals( ONIBUSD13 )) return OnibusD13.create();
		if (nome.equals( ONIBUS023 )) return Onibus023.create();
		if (nome.equals( ONIBUS022 )) return Onibus022.create();
		if (nome.equals( ONIBUS011 )) return Onibus011.create();
		if (nome.equals( ONIBUS010 )) return Onibus010.create();
		if (nome.equals( ONIBUS021 )) return Onibus021.create();
		if (nome.equals( ONIBUS020 )) return Onibus020.create();
		if (nome.equals( ONIBUS030 )) return Onibus030.create();
		if (nome.equals( ONIBUS040 )) return Onibus040.create();
		if (nome.equals( ONIBUS050 )) return Onibus050.create();
		if (nome.equals( ONIBUS060 )) return Onibus060.create();
		if (nome.equals( ONIBUS378 )) return Onibus378.create();
		if (nome.equals( ONIBUS512 )) return Onibus512.create();
		if (nome.equals( ONIBUSI71 )) return OnibusI71.create();
		if (nome.equals( ONIBUSK11 )) return OnibusK11.create();
		if (nome.equals( ONIBUS711 )) return Onibus711.create();
		if (nome.equals( ONIBUS366 )) return Onibus366.create();
		if (nome.equals( ONIBUSC28 )) return OnibusC28.create();
		if (nome.equals( ONIBUSD31 )) return OnibusD31.create();
		if (nome.equals( ONIBUS914 )) return Onibus914.create();
		if (nome.equals( ONIBUS468 )) return Onibus468.create();
		if (nome.equals( ONIBUS183 )) return Onibus183.create();
		if (nome.equals( ONIBUSC20 )) return OnibusC20.create();
		if (nome.equals( ONIBUSB13 )) return OnibusB13.create();
		if (nome.equals( ONIBUS244 )) return Onibus244.create();
		if (nome.equals( ONIBUS865 )) return Onibus865.create();
		if (nome.equals( ONIBUSB26 )) return OnibusB26.create();
		if (nome.equals( ONIBUSA14 )) return OnibusA14.create();
		if (nome.equals( ONIBUSA31 )) return OnibusA31.create();
		if (nome.equals( ONIBUSC11 )) return OnibusC11.create();
		if (nome.equals( ONIBUS712 )) return Onibus712.create();
		if (nome.equals( ONIBUS917 )) return Onibus917.create();
		if (nome.equals( ONIBUSC16 )) return OnibusC16.create();
		if (nome.equals( ONIBUS972 )) return Onibus972.create();
		if (nome.equals( ONIBUS474 )) return Onibus474.create();
		if (nome.equals( ONIBUS169 )) return Onibus169.create();
		if (nome.equals( ONIBUS617 )) return Onibus617.create();
		if (nome.equals( ONIBUS160 )) return Onibus160.create();
		if (nome.equals( ONIBUSA13 )) return OnibusA13.create();
		if (nome.equals( ONIBUS655 )) return Onibus655.create();
		if (nome.equals( ONIBUSA21 )) return OnibusA21.create();
		if (nome.equals( ONIBUS532 )) return Onibus532.create();
		if (nome.equals( ONIBUS921 )) return Onibus921.create();
		if (nome.equals( ONIBUS365 )) return Onibus365.create();
		if (nome.equals( ONIBUSD21 )) return OnibusD21.create();
		if (nome.equals( ONIBUSC18 )) return OnibusC18.create();
		if (nome.equals( ONIBUSF25 )) return OnibusF25.create();
		if (nome.equals( ONIBUSC27 )) return OnibusC27.create();
		if (nome.equals( ONIBUS912 )) return Onibus912.create();
		if (nome.equals( ONIBUS967 )) return Onibus967.create();
		if (nome.equals( ONIBUS285 )) return Onibus285.create();
		if (nome.equals( ONIBUS656 )) return Onibus656.create();
		if (nome.equals( ONIBUS271 )) return Onibus271.create();
		if (nome.equals( ONIBUS520 )) return Onibus520.create();
		if (nome.equals( ONIBUSG13 )) return OnibusG13.create();
		if (nome.equals( ONIBUS550 )) return Onibus550.create();
		if (nome.equals( ONIBUS500 )) return Onibus500.create();
		if (nome.equals( ONIBUS661 )) return Onibus661.create();
		if (nome.equals( ONIBUS635 )) return Onibus635.create();
		if (nome.equals( ONIBUS641 )) return Onibus641.create();
		if (nome.equals( ONIBUS189 )) return Onibus189.create();
		if (nome.equals( ONIBUS549 )) return Onibus549.create();
		if (nome.equals( ONIBUS509 )) return Onibus509.create();
		if (nome.equals( ONIBUS789 )) return Onibus789.create();
		if (nome.equals( ONIBUS802 )) return Onibus802.create();
		if (nome.equals( ONIBUS809 )) return Onibus809.create();
		if (nome.equals( ONIBUS309 )) return Onibus309.create();
		if (nome.equals( ONIBUS308 )) return Onibus308.create();
		if (nome.equals( ONIBUS609 )) return Onibus609.create();
		if (nome.equals( ONIBUSC64 )) return OnibusC64.create();
		if (nome.equals( ONIBUSD69 )) return OnibusD69.create();
		if (nome.equals( ONIBUSB69 )) return OnibusB69.create();
		if (nome.equals( ONIBUSE69 )) return OnibusE69.create();
		if (nome.equals( ONIBUSA05 )) return OnibusA05.create();
		if (nome.equals( ONIBUSF09 )) return OnibusF09.create();
		if (nome.equals( ONIBUSJ19 )) return OnibusJ19.create();
		if (nome.equals( ONIBUS289 )) return Onibus289.create();
		if (nome.equals( ONIBUS229 )) return Onibus229.create();
		if (nome.equals( ONIBUS489 )) return Onibus489.create();
		if (nome.equals( ONIBUS188 )) return Onibus188.create();
		if (nome.equals( ONIBUS608 )) return Onibus608.create();
		if (nome.equals( ONIBUS209 )) return Onibus209.create();
		if (nome.equals( ONIBUS519 )) return Onibus519.create();
		if (nome.equals( ONIBUS689 )) return Onibus689.create();
		if (nome.equals( ONIBUS889 )) return Onibus889.create();
		if (nome.equals( ONIBUS989 )) return Onibus989.create();
		if (nome.equals( ONIBUS389 )) return Onibus389.create();
		if (nome.equals( ONIBUS679 )) return Onibus679.create();
		if (nome.equals( ONIBUS788 )) return Onibus788.create();
		if (nome.equals( ONIBUS260 )) return Onibus260.create();
		if (nome.equals( ONIBUSB25 )) return OnibusB25.create();
		if (nome.equals( ONIBUSB41 )) return OnibusB41.create();
		if (nome.equals( ONIBUSB42 )) return OnibusB42.create();
		if (nome.equals( ONIBUSB11 )) return OnibusB11.create();
		if (nome.equals( ONIBUSB32 )) return OnibusB32.create();
		if (nome.equals( ONIBUS633 )) return Onibus633.create();
		if (nome.equals( ONIBUS522 )) return Onibus522.create();
		if (nome.equals( ONIBUS721 )) return Onibus721.create();
		if (nome.equals( ONIBUS181 )) return Onibus181.create();
		if (nome.equals( ONIBUS594 )) return Onibus594.create();
		if (nome.equals( ONIBUS331 )) return Onibus331.create();
		if (nome.equals( ONIBUS812 )) return Onibus812.create();
		if (nome.equals( ONIBUSB19 )) return OnibusB19.create();
		if (nome.equals( ONIBUS814 )) return Onibus814.create();
		if (nome.equals( ONIBUSF16 )) return OnibusF16.create();
		if (nome.equals( ONIBUSF22 )) return OnibusF22.create();
		if (nome.equals( ONIBUS176 )) return Onibus176.create();
		if (nome.equals( ONIBUS521 )) return Onibus521.create();
		if (nome.equals( ONIBUS674 )) return Onibus674.create();
		if (nome.equals( ONIBUS280 )) return Onibus280.create();
		if (nome.equals( ONIBUS360 )) return Onibus360.create();
		if (nome.equals( ONIBUS666 )) return Onibus666.create();
		if (nome.equals( ONIBUS233 )) return Onibus233.create();
		if (nome.equals( ONIBUS535 )) return Onibus535.create();
		if (nome.equals( ONIBUS548 )) return Onibus548.create();
		if (nome.equals( ONIBUS915 )) return Onibus915.create();
		if (nome.equals( ONIBUS272 )) return Onibus272.create();
		if (nome.equals( ONIBUS640 )) return Onibus640.create();
		if (nome.equals( ONIBUSB22 )) return OnibusB22.create();
		if (nome.equals( ONIBUSB36 )) return OnibusB36.create();
		if (nome.equals( ONIBUS387 )) return Onibus387.create();
		if (nome.equals( ONIBUS343 )) return Onibus343.create();
		if (nome.equals( ONIBUS534 )) return Onibus534.create();
		if (nome.equals( ONIBUS623 )) return Onibus623.create();
		if (nome.equals( ONIBUS911 )) return Onibus911.create();
		if (nome.equals( ONIBUS462 )) return Onibus462.create();
		if (nome.equals( ONIBUSC42 )) return OnibusC42.create();
		if (nome.equals( ONIBUS304 )) return Onibus304.create();
		if (nome.equals( ONIBUSC03 )) return OnibusC03.create();
		if (nome.equals( ONIBUSD14 )) return OnibusD14.create();
		if (nome.equals( ONIBUS301 )) return Onibus301.create();
		if (nome.equals( ONIBUS603 )) return Onibus603.create();
		if (nome.equals( ONIBUS638 )) return Onibus638.create();
		if (nome.equals( ONIBUS644 )) return Onibus644.create();
		if (nome.equals( ONIBUS688 )) return Onibus688.create();
		if (nome.equals( ONIBUS916 )) return Onibus916.create();
		if (nome.equals( ONIBUS631 )) return Onibus631.create();
		if (nome.equals( ONIBUS649 )) return Onibus649.create();
		if (nome.equals( ONIBUSB14 )) return OnibusB14.create();
		if (nome.equals( ONIBUSD11 )) return OnibusD11.create();
		if (nome.equals( ONIBUSC22 )) return OnibusC22.create();
		if (nome.equals( ONIBUS646 )) return Onibus646.create();
		if (nome.equals( ONIBUS671 )) return Onibus671.create();
		if (nome.equals( ONIBUS612 )) return Onibus612.create();
		if (nome.equals( ONIBUS616 )) return Onibus616.create();
		if (nome.equals( ONIBUSX20 )) return OnibusX20.create();
		if (nome.equals( ONIBUSB35 )) return OnibusB35.create();
		if (nome.equals( ONIBUS718 )) return Onibus718.create();
		if (nome.equals( ONIBUSF18 )) return OnibusF18.create();
		if (nome.equals( ONIBUSE63 )) return OnibusE63.create();
		if (nome.equals( ONIBUSD16 )) return OnibusD16.create();
		if (nome.equals( ONIBUS171 )) return Onibus171.create();
		if (nome.equals( ONIBUSC26 )) return OnibusC26.create();
		if (nome.equals( ONIBUSX16 )) return OnibusX16.create();
		if (nome.equals( ONIBUSE31 )) return OnibusE31.create();
		if (nome.equals( ONIBUSI41 )) return OnibusI41.create();
		if (nome.equals( ONIBUSI40 )) return OnibusI40.create();
		if (nome.equals( ONIBUSI51 )) return OnibusI51.create();
		if (nome.equals( ONIBUSI50 )) return OnibusI50.create();
		if (nome.equals( ONIBUS632 )) return Onibus632.create();
		if (nome.equals( ONIBUSG11 )) return OnibusG11.create();
		if (nome.equals( ONIBUSL11 )) return OnibusL11.create();
		if (nome.equals( ONIBUS168 )) return Onibus168.create();
		if (nome.equals( ONIBUS165 )) return Onibus165.create();
		if (nome.equals( ONIBUSJ12 )) return OnibusJ12.create();
		if (nome.equals( ONIBUS219 )) return Onibus219.create();
		if (nome.equals( ONIBUSX14 )) return OnibusX14.create();
		if (nome.equals( ONIBUSX21 )) return OnibusX21.create();
		if (nome.equals( ONIBUS539 )) return Onibus539.create();
		if (nome.equals( ONIBUSB27 )) return OnibusB27.create();
		if (nome.equals( ONIBUS684 )) return Onibus684.create();
		if (nome.equals( ONIBUS685 )) return Onibus685.create();
		if (nome.equals( ONIBUS636 )) return Onibus636.create();
		if (nome.equals( ONIBUS221 )) return Onibus221.create();
		if (nome.equals( ONIBUS827 )) return Onibus827.create();
		if (nome.equals( ONIBUSB29 )) return OnibusB29.create();
		if (nome.equals( ONIBUS622 )) return Onibus622.create();
		if (nome.equals( ONIBUSB18 )) return OnibusB18.create();
		if (nome.equals( ONIBUS370 )) return Onibus370.create();
		if (nome.equals( ONIBUS680 )) return Onibus680.create();
		if (nome.equals( ONIBUS546 )) return Onibus546.create();
		if (nome.equals( ONIBUS610 )) return Onibus610.create();
		if (nome.equals( ONIBUS653 )) return Onibus653.create();
		if (nome.equals( ONIBUS375 )) return Onibus375.create();
		if (nome.equals( ONIBUSA11 )) return OnibusA11.create();
		if (nome.equals( ONIBUS236 )) return Onibus236.create();
		if (nome.equals( ONIBUS965 )) return Onibus965.create();
		if (nome.equals( ONIBUS870 )) return Onibus870.create();
		if (nome.equals( ONIBUSD12 )) return OnibusD12.create();
		if (nome.equals( ONIBUS511 )) return Onibus511.create();
		if (nome.equals( ONIBUS213 )) return Onibus213.create();
		if (nome.equals( ONIBUS670 )) return Onibus670.create();
		if (nome.equals( ONIBUSA17 )) return OnibusA17.create();
		if (nome.equals( ONIBUS824 )) return Onibus824.create();
		if (nome.equals( ONIBUS811 )) return Onibus811.create();
		if (nome.equals( ONIBUS876 )) return Onibus876.create();
		if (nome.equals( ONIBUSX11 )) return OnibusX11.create();
		if (nome.equals( ONIBUS508 )) return Onibus508.create();
		if (nome.equals( ONIBUS507 )) return Onibus507.create();
		if (nome.equals( ONIBUS212 )) return Onibus212.create();
		if (nome.equals( ONIBUS463 )) return Onibus463.create();
		if (nome.equals( ONIBUS713 )) return Onibus713.create();
		if (nome.equals( ONIBUSJ16 )) return OnibusJ16.create();
		if (nome.equals( ONIBUS461 )) return Onibus461.create();
		if (nome.equals( ONIBUS203 )) return Onibus203.create();
		if (nome.equals( ONIBUS204 )) return Onibus204.create();
		if (nome.equals( ONIBUS620 )) return Onibus620.create();
		if (nome.equals( ONIBUS901 )) return Onibus901.create();
		if (nome.equals( ONIBUS902 )) return Onibus902.create();
		if (nome.equals( ONIBUS924 )) return Onibus924.create();
		if (nome.equals( ONIBUS274 )) return Onibus274.create();
		if (nome.equals( ONIBUSB17 )) return OnibusB17.create();
		if (nome.equals( ONIBUS531 )) return Onibus531.create();
		if (nome.equals( ONIBUS637 )) return Onibus637.create();
		if (nome.equals( ONIBUSF14 )) return OnibusF14.create();
		if (nome.equals( ONIBUS760 )) return Onibus760.create();
		if (nome.equals( ONIBUS619 )) return Onibus619.create();
		if (nome.equals( ONIBUS650 )) return Onibus650.create();
		if (nome.equals( ONIBUS243 )) return Onibus243.create();
		if (nome.equals( ONIBUSF19 )) return OnibusF19.create();
		if (nome.equals( ONIBUSF26 )) return OnibusF26.create();
		if (nome.equals( ONIBUSE11 )) return OnibusE11.create();
		if (nome.equals( ONIBUSE21 )) return OnibusE21.create();
		if (nome.equals( ONIBUSC04 )) return OnibusC04.create();
		if (nome.equals( ONIBUS806 )) return Onibus806.create();
		if (nome.equals( ONIBUSI90 )) return OnibusI90.create();
		if (nome.equals( ONIBUSA02 )) return OnibusA02.create();
		if (nome.equals( ONIBUS105 )) return Onibus105.create();
		if (nome.equals( ONIBUS218 )) return Onibus218.create();
		if (nome.equals( ONIBUSI91 )) return OnibusI91.create();
		if (nome.equals( ONIBUSA22 )) return OnibusA22.create();
		if (nome.equals( ONIBUS372 )) return Onibus372.create();
		if (nome.equals( ONIBUS667 )) return Onibus667.create();
		if (nome.equals( ONIBUSJ14 )) return OnibusJ14.create();
		if (nome.equals( ONIBUSJ13 )) return OnibusJ13.create();
		if (nome.equals( ONIBUS214 )) return Onibus214.create();
		if (nome.equals( ONIBUS877 )) return Onibus877.create();
		if (nome.equals( ONIBUS545 )) return Onibus545.create();
		if (nome.equals( ONIBUS861 )) return Onibus861.create();
		if (nome.equals( ONIBUS321 )) return Onibus321.create();
		if (nome.equals( ONIBUS815 )) return Onibus815.create();
		if (nome.equals( ONIBUS979 )) return Onibus979.create();
		if (nome.equals( ONIBUS472 )) return Onibus472.create();
		if (nome.equals( ONIBUS615 )) return Onibus615.create();
		if (nome.equals( ONIBUS643 )) return Onibus643.create();
		if (nome.equals( ONIBUSZ01 )) return OnibusZ01.create();
		if (nome.equals( ONIBUS829 )) return Onibus829.create();
		if (nome.equals( ONIBUSC25 )) return OnibusC25.create();
		if (nome.equals( ONIBUS323 )) return Onibus323.create();
		if (nome.equals( ONIBUS663 )) return Onibus663.create();
		if (nome.equals( ONIBUS222 )) return Onibus222.create();
		if (nome.equals( ONIBUSC30 )) return OnibusC30.create();
		if (nome.equals( ONIBUS761 )) return Onibus761.create();
		if (nome.equals( ONIBUS242 )) return Onibus242.create();
		if (nome.equals( ONIBUS467 )) return Onibus467.create();
		if (nome.equals( ONIBUSD23 )) return OnibusD23.create();
		if (nome.equals( ONIBUSC17 )) return OnibusC17.create();
		if (nome.equals( ONIBUSB28 )) return OnibusB28.create();
		if (nome.equals( ONIBUS714 )) return Onibus714.create();
		if (nome.equals( ONIBUS825 )) return Onibus825.create();
		if (nome.equals( ONIBUS166 )) return Onibus166.create();
		if (nome.equals( ONIBUSC12 )) return OnibusC12.create();
		if (nome.equals( ONIBUSA32 )) return OnibusA32.create();
		if (nome.equals( ONIBUS336 )) return Onibus336.create();
		if (nome.equals( ONIBUS665 )) return Onibus665.create();
		if (nome.equals( ONIBUS762 )) return Onibus762.create();
		if (nome.equals( ONIBUS860 )) return Onibus860.create();
		if (nome.equals( ONIBUS471 )) return Onibus471.create();
		if (nome.equals( ONIBUS624 )) return Onibus624.create();
		if (nome.equals( ONIBUS184 )) return Onibus184.create();
		if (nome.equals( ONIBUS613 )) return Onibus613.create();
		if (nome.equals( ONIBUS777 )) return Onibus777.create();
		if (nome.equals( ONIBUS652 )) return Onibus652.create();
		if (nome.equals( ONIBUS918 )) return Onibus918.create();
		if (nome.equals( ONIBUSZ03 )) return OnibusZ03.create();
		if (nome.equals( ONIBUS779 )) return Onibus779.create();
		if (nome.equals( ONIBUS630 )) return Onibus630.create();
		if (nome.equals( ONIBUS690 )) return Onibus690.create();
		if (nome.equals( ONIBUSC15 )) return OnibusC15.create();
		if (nome.equals( ONIBUS657 )) return Onibus657.create();
		if (nome.equals( ONIBUS551 )) return Onibus551.create();
		if (nome.equals( ONIBUS536 )) return Onibus536.create();
		throw new IllegalArgumentException("Nenhum onibus com o nome [" + nome + "]");
	}
}