
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusC72 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("C72 - CTBA  / V. PALMITAL");
		  onibus.setCodigo("C72");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO VILA PALMITAL");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("21/11/2011");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:50");
		  ponto0.getHorarios().addElement("06:17");
		  ponto0.getHorarios().addElement("06:44");
		  ponto0.getHorarios().addElement("07:11");
		  ponto0.getHorarios().addElement("07:46");
		  ponto0.getHorarios().addElement("08:05");
		  ponto0.getHorarios().addElement("08:38");
		  ponto0.getHorarios().addElement("09:23");
		  ponto0.getHorarios().addElement("10:08");
		  ponto0.getHorarios().addElement("10:53");
		  ponto0.getHorarios().addElement("11:38");
		  ponto0.getHorarios().addElement("12:23");
		  ponto0.getHorarios().addElement("13:08");
		  ponto0.getHorarios().addElement("13:53");
		  ponto0.getHorarios().addElement("14:38");
		  ponto0.getHorarios().addElement("15:23");
		  ponto0.getHorarios().addElement("16:08");
		  ponto0.getHorarios().addElement("17:01");
		  ponto0.getHorarios().addElement("17:36");
		  ponto0.getHorarios().addElement("18:05");
		  ponto0.getHorarios().addElement("18:33");
		  ponto0.getHorarios().addElement("19:01");
		  ponto0.getHorarios().addElement("20:00");
		  ponto0.getHorarios().addElement("21:30");
		  ponto0.getHorarios().addElement("23:00");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL GUADALUPE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("21/11/2011");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("06:32");
		  ponto1.getHorarios().addElement("06:59");
		  ponto1.getHorarios().addElement("07:26");
		  ponto1.getHorarios().addElement("07:53");
		  ponto1.getHorarios().addElement("08:38");
		  ponto1.getHorarios().addElement("09:23");
		  ponto1.getHorarios().addElement("10:08");
		  ponto1.getHorarios().addElement("10:53");
		  ponto1.getHorarios().addElement("11:38");
		  ponto1.getHorarios().addElement("12:23");
		  ponto1.getHorarios().addElement("13:08");
		  ponto1.getHorarios().addElement("13:53");
		  ponto1.getHorarios().addElement("14:38");
		  ponto1.getHorarios().addElement("15:23");
		  ponto1.getHorarios().addElement("16:08");
		  ponto1.getHorarios().addElement("16:53");
		  ponto1.getHorarios().addElement("17:22");
		  ponto1.getHorarios().addElement("17:50");
		  ponto1.getHorarios().addElement("18:18");
		  ponto1.getHorarios().addElement("18:47");
		  ponto1.getHorarios().addElement("19:15");
		  ponto1.getHorarios().addElement("19:43");
		  ponto1.getHorarios().addElement("20:45");
		  ponto1.getHorarios().addElement("22:15");
		  ponto1.getHorarios().addElement("23:45");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO VILA PALMITAL");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("26/11/2011");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:50");
		  ponto2.getHorarios().addElement("06:31");
		  ponto2.getHorarios().addElement("07:12");
		  ponto2.getHorarios().addElement("07:53");
		  ponto2.getHorarios().addElement("08:38");
		  ponto2.getHorarios().addElement("09:23");
		  ponto2.getHorarios().addElement("10:08");
		  ponto2.getHorarios().addElement("10:53");
		  ponto2.getHorarios().addElement("11:38");
		  ponto2.getHorarios().addElement("12:23");
		  ponto2.getHorarios().addElement("13:08");
		  ponto2.getHorarios().addElement("13:53");
		  ponto2.getHorarios().addElement("15:23");
		  ponto2.getHorarios().addElement("16:53");
		  ponto2.getHorarios().addElement("18:23");
		  ponto2.getHorarios().addElement("19:53");
		  ponto2.getHorarios().addElement("21:23");
		  ponto2.getHorarios().addElement("23:00");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL GUADALUPE");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("26/11/2011");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:31");
		  ponto3.getHorarios().addElement("07:12");
		  ponto3.getHorarios().addElement("07:53");
		  ponto3.getHorarios().addElement("08:38");
		  ponto3.getHorarios().addElement("09:23");
		  ponto3.getHorarios().addElement("10:08");
		  ponto3.getHorarios().addElement("10:53");
		  ponto3.getHorarios().addElement("11:38");
		  ponto3.getHorarios().addElement("12:23");
		  ponto3.getHorarios().addElement("13:08");
		  ponto3.getHorarios().addElement("13:53");
		  ponto3.getHorarios().addElement("14:38");
		  ponto3.getHorarios().addElement("16:08");
		  ponto3.getHorarios().addElement("17:38");
		  ponto3.getHorarios().addElement("19:08");
		  ponto3.getHorarios().addElement("20:38");
		  ponto3.getHorarios().addElement("22:08");
		  ponto3.getHorarios().addElement("23:45");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO VILA PALMITAL");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("02/11/2004");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:15");
		  ponto4.getHorarios().addElement("08:00");
		  ponto4.getHorarios().addElement("09:30");
		  ponto4.getHorarios().addElement("11:00");
		  ponto4.getHorarios().addElement("12:30");
		  ponto4.getHorarios().addElement("14:00");
		  ponto4.getHorarios().addElement("15:30");
		  ponto4.getHorarios().addElement("17:00");
		  ponto4.getHorarios().addElement("18:30");
		  ponto4.getHorarios().addElement("20:00");
		  ponto4.getHorarios().addElement("21:30");
		  ponto4.getHorarios().addElement("23:00");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL GUADALUPE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("02/11/2004");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("07:05");
		  ponto5.getHorarios().addElement("08:45");
		  ponto5.getHorarios().addElement("10:15");
		  ponto5.getHorarios().addElement("11:45");
		  ponto5.getHorarios().addElement("13:15");
		  ponto5.getHorarios().addElement("14:45");
		  ponto5.getHorarios().addElement("16:15");
		  ponto5.getHorarios().addElement("17:45");
		  ponto5.getHorarios().addElement("19:15");
		  ponto5.getHorarios().addElement("20:45");
		  ponto5.getHorarios().addElement("22:15");
		  ponto5.getHorarios().addElement("23:45");
		  return onibus;
		  }
	  }