
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusF14 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("F14 - STA. MARIA");
		onibus.setCodigo("F14");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("T.FAZENDA/FINAL R.CTBA.");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("24/09/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("04:25");
		ponto0.getHorarios().addElement("05:00");
		ponto0.getHorarios().addElement("05:50");
		ponto0.getHorarios().addElement("06:30");
		ponto0.getHorarios().addElement("07:10");
		ponto0.getHorarios().addElement("18:30");
		ponto0.getHorarios().addElement("19:10");
		ponto0.getHorarios().addElement("19:50");
		ponto0.getHorarios().addElement("20:30");
		ponto0.getHorarios().addElement("21:10");
		ponto0.getHorarios().addElement("21:50");
		ponto0.getHorarios().addElement("22:30");
		ponto0.getHorarios().addElement("23:10");
		ponto0.getHorarios().addElement("23:50");
		ponto0.getHorarios().addElement("00:35");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERM.FAZENDA/STA.MARIA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("24/09/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("04:50");
		ponto1.getHorarios().addElement("05:30");
		ponto1.getHorarios().addElement("06:10");
		ponto1.getHorarios().addElement("06:50");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("07:50");
		ponto1.getHorarios().addElement("08:30");
		ponto1.getHorarios().addElement("09:10");
		ponto1.getHorarios().addElement("09:50");
		ponto1.getHorarios().addElement("10:30");
		ponto1.getHorarios().addElement("11:10");
		ponto1.getHorarios().addElement("11:50");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:10");
		ponto1.getHorarios().addElement("13:50");
		ponto1.getHorarios().addElement("14:30");
		ponto1.getHorarios().addElement("15:10");
		ponto1.getHorarios().addElement("15:50");
		ponto1.getHorarios().addElement("16:30");
		ponto1.getHorarios().addElement("16:50");
		ponto1.getHorarios().addElement("17:10");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("17:50");
		ponto1.getHorarios().addElement("18:10");
		ponto1.getHorarios().addElement("18:50");
		ponto1.getHorarios().addElement("19:30");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("T.FAZENDA/FINAL R.CTBA.");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("24/03/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("04:30");
		ponto2.getHorarios().addElement("05:10");
		ponto2.getHorarios().addElement("05:50");
		ponto2.getHorarios().addElement("06:30");
		ponto2.getHorarios().addElement("07:10");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERM.FAZENDA/STA.MARIA");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("24/03/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("07:50");
		ponto3.getHorarios().addElement("08:30");
		ponto3.getHorarios().addElement("09:10");
		ponto3.getHorarios().addElement("09:50");
		ponto3.getHorarios().addElement("10:30");
		ponto3.getHorarios().addElement("11:10");
		ponto3.getHorarios().addElement("11:50");
		ponto3.getHorarios().addElement("12:30");
		ponto3.getHorarios().addElement("13:10");
		ponto3.getHorarios().addElement("13:50");
		ponto3.getHorarios().addElement("14:30");
		ponto3.getHorarios().addElement("15:10");
		ponto3.getHorarios().addElement("15:50");
		ponto3.getHorarios().addElement("16:30");
		ponto3.getHorarios().addElement("17:10");
		ponto3.getHorarios().addElement("17:50");
		ponto3.getHorarios().addElement("18:30");
		ponto3.getHorarios().addElement("19:10");
		ponto3.getHorarios().addElement("19:50");
		ponto3.getHorarios().addElement("20:30");
		ponto3.getHorarios().addElement("21:10");
		ponto3.getHorarios().addElement("21:50");
		ponto3.getHorarios().addElement("22:30");
		ponto3.getHorarios().addElement("23:05");
		ponto3.getHorarios().addElement("23:39");
		ponto3.getHorarios().addElement("00:13");
		ponto3.getHorarios().addElement("00:46");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERM.FAZENDA/STA.MARIA");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("29/01/2012");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("04:30");
		ponto4.getHorarios().addElement("05:10");
		ponto4.getHorarios().addElement("05:50");
		ponto4.getHorarios().addElement("06:30");
		ponto4.getHorarios().addElement("07:10");
		ponto4.getHorarios().addElement("07:50");
		ponto4.getHorarios().addElement("08:30");
		ponto4.getHorarios().addElement("09:10");
		ponto4.getHorarios().addElement("09:50");
		ponto4.getHorarios().addElement("10:30");
		ponto4.getHorarios().addElement("11:10");
		ponto4.getHorarios().addElement("11:50");
		ponto4.getHorarios().addElement("12:30");
		ponto4.getHorarios().addElement("13:10");
		ponto4.getHorarios().addElement("13:50");
		ponto4.getHorarios().addElement("14:30");
		ponto4.getHorarios().addElement("15:10");
		ponto4.getHorarios().addElement("15:50");
		ponto4.getHorarios().addElement("16:30");
		ponto4.getHorarios().addElement("17:10");
		ponto4.getHorarios().addElement("17:50");
		ponto4.getHorarios().addElement("18:30");
		ponto4.getHorarios().addElement("19:10");
		ponto4.getHorarios().addElement("19:50");
		ponto4.getHorarios().addElement("20:30");
		ponto4.getHorarios().addElement("21:10");
		ponto4.getHorarios().addElement("21:50");
		ponto4.getHorarios().addElement("22:30");
		ponto4.getHorarios().addElement("23:05");
		ponto4.getHorarios().addElement("23:39");
		ponto4.getHorarios().addElement("00:13");
		ponto4.getHorarios().addElement("00:46");
		return onibus;
		}
	}