
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusF05 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("F05 - FAZENDA / CIC");
		  onibus.setCodigo("F05");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("TERMINAL CIC");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("10/10/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("05:52");
		  ponto0.getHorarios().addElement("06:08");
		  ponto0.getHorarios().addElement("06:18");
		  ponto0.getHorarios().addElement("06:40");
		  ponto0.getHorarios().addElement("06:56");
		  ponto0.getHorarios().addElement("07:12");
		  ponto0.getHorarios().addElement("07:32");
		  ponto0.getHorarios().addElement("07:44");
		  ponto0.getHorarios().addElement("08:27");
		  ponto0.getHorarios().addElement("08:48");
		  ponto0.getHorarios().addElement("10:13");
		  ponto0.getHorarios().addElement("11:38");
		  ponto0.getHorarios().addElement("13:03");
		  ponto0.getHorarios().addElement("13:24");
		  ponto0.getHorarios().addElement("13:46");
		  ponto0.getHorarios().addElement("14:07");
		  ponto0.getHorarios().addElement("14:33");
		  ponto0.getHorarios().addElement("14:49");
		  ponto0.getHorarios().addElement("15:11");
		  ponto0.getHorarios().addElement("15:32");
		  ponto0.getHorarios().addElement("15:53");
		  ponto0.getHorarios().addElement("16:11");
		  ponto0.getHorarios().addElement("16:29");
		  ponto0.getHorarios().addElement("16:47");
		  ponto0.getHorarios().addElement("17:05");
		  ponto0.getHorarios().addElement("17:23");
		  ponto0.getHorarios().addElement("17:41");
		  ponto0.getHorarios().addElement("17:59");
		  ponto0.getHorarios().addElement("18:17");
		  ponto0.getHorarios().addElement("18:35");
		  ponto0.getHorarios().addElement("18:53");
		  ponto0.getHorarios().addElement("19:11");
		  ponto0.getHorarios().addElement("19:20");
		  ponto0.getHorarios().addElement("19:47");
		  ponto0.getHorarios().addElement("20:01");
		  ponto0.getHorarios().addElement("20:13");
		  ponto0.getHorarios().addElement("20:58");
		  ponto0.getHorarios().addElement("21:33");
		  ponto0.getHorarios().addElement("22:18");
		  ponto0.getHorarios().addElement("22:44");
		  ponto0.getHorarios().addElement("23:15");
		  ponto0.getHorarios().addElement("23:45");
		  ponto0.getHorarios().addElement("00:15");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL FAZENDA RIO GRANDE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("10/10/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:00");
		  ponto1.getHorarios().addElement("05:10");
		  ponto1.getHorarios().addElement("05:20");
		  ponto1.getHorarios().addElement("05:40");
		  ponto1.getHorarios().addElement("06:00");
		  ponto1.getHorarios().addElement("06:15");
		  ponto1.getHorarios().addElement("06:27");
		  ponto1.getHorarios().addElement("06:39");
		  ponto1.getHorarios().addElement("06:50");
		  ponto1.getHorarios().addElement("07:02");
		  ponto1.getHorarios().addElement("07:21");
		  ponto1.getHorarios().addElement("07:39");
		  ponto1.getHorarios().addElement("07:57");
		  ponto1.getHorarios().addElement("08:10");
		  ponto1.getHorarios().addElement("08:26");
		  ponto1.getHorarios().addElement("09:30");
		  ponto1.getHorarios().addElement("10:55");
		  ponto1.getHorarios().addElement("12:20");
		  ponto1.getHorarios().addElement("12:41");
		  ponto1.getHorarios().addElement("13:03");
		  ponto1.getHorarios().addElement("13:24");
		  ponto1.getHorarios().addElement("13:45");
		  ponto1.getHorarios().addElement("14:06");
		  ponto1.getHorarios().addElement("14:28");
		  ponto1.getHorarios().addElement("14:49");
		  ponto1.getHorarios().addElement("15:10");
		  ponto1.getHorarios().addElement("15:39");
		  ponto1.getHorarios().addElement("15:59");
		  ponto1.getHorarios().addElement("16:18");
		  ponto1.getHorarios().addElement("16:39");
		  ponto1.getHorarios().addElement("16:57");
		  ponto1.getHorarios().addElement("17:15");
		  ponto1.getHorarios().addElement("17:33");
		  ponto1.getHorarios().addElement("17:51");
		  ponto1.getHorarios().addElement("18:09");
		  ponto1.getHorarios().addElement("18:27");
		  ponto1.getHorarios().addElement("19:03");
		  ponto1.getHorarios().addElement("19:21");
		  ponto1.getHorarios().addElement("19:33");
		  ponto1.getHorarios().addElement("20:18");
		  ponto1.getHorarios().addElement("20:53");
		  ponto1.getHorarios().addElement("21:38");
		  ponto1.getHorarios().addElement("22:13");
		  ponto1.getHorarios().addElement("22:48");
		  ponto1.getHorarios().addElement("23:15");
		  ponto1.getHorarios().addElement("23:48");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("EMPRESA KRAFT");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("10/10/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:33");
		  ponto2.getHorarios().addElement("14:50");
		  ponto2.getHorarios().addElement("23:00");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("T.FAZ. GRALHA AZUL+JD.PALMEIRA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto3.setValidoAPartirDe("10/10/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:05");
		  ponto3.getHorarios().addElement("05:35");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TERMINAL CIC");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("28/01/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("05:30");
		  ponto4.getHorarios().addElement("05:45");
		  ponto4.getHorarios().addElement("06:40");
		  ponto4.getHorarios().addElement("06:55");
		  ponto4.getHorarios().addElement("07:50");
		  ponto4.getHorarios().addElement("08:05");
		  ponto4.getHorarios().addElement("09:00");
		  ponto4.getHorarios().addElement("09:20");
		  ponto4.getHorarios().addElement("10:20");
		  ponto4.getHorarios().addElement("10:50");
		  ponto4.getHorarios().addElement("11:40");
		  ponto4.getHorarios().addElement("12:10");
		  ponto4.getHorarios().addElement("13:00");
		  ponto4.getHorarios().addElement("13:30");
		  ponto4.getHorarios().addElement("14:20");
		  ponto4.getHorarios().addElement("14:44");
		  ponto4.getHorarios().addElement("15:40");
		  ponto4.getHorarios().addElement("16:20");
		  ponto4.getHorarios().addElement("17:00");
		  ponto4.getHorarios().addElement("17:40");
		  ponto4.getHorarios().addElement("18:20");
		  ponto4.getHorarios().addElement("19:00");
		  ponto4.getHorarios().addElement("19:40");
		  ponto4.getHorarios().addElement("21:00");
		  ponto4.getHorarios().addElement("22:00");
		  ponto4.getHorarios().addElement("23:00");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL FAZENDA RIO GRANDE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("28/01/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("04:55");
		  ponto5.getHorarios().addElement("05:10");
		  ponto5.getHorarios().addElement("06:05");
		  ponto5.getHorarios().addElement("06:20");
		  ponto5.getHorarios().addElement("07:15");
		  ponto5.getHorarios().addElement("07:30");
		  ponto5.getHorarios().addElement("08:25");
		  ponto5.getHorarios().addElement("08:40");
		  ponto5.getHorarios().addElement("09:40");
		  ponto5.getHorarios().addElement("10:05");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("11:30");
		  ponto5.getHorarios().addElement("12:20");
		  ponto5.getHorarios().addElement("12:50");
		  ponto5.getHorarios().addElement("13:40");
		  ponto5.getHorarios().addElement("14:07");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("15:35");
		  ponto5.getHorarios().addElement("16:20");
		  ponto5.getHorarios().addElement("17:00");
		  ponto5.getHorarios().addElement("17:40");
		  ponto5.getHorarios().addElement("18:20");
		  ponto5.getHorarios().addElement("19:00");
		  ponto5.getHorarios().addElement("20:20");
		  ponto5.getHorarios().addElement("21:30");
		  ponto5.getHorarios().addElement("22:30");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("EMPRESA KRAFT");
		  ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto6.setValidoAPartirDe("28/01/2012");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("14:55");
		  ponto6.getHorarios().addElement("23:10");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("TERMINAL CIC");
		  ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto7.setValidoAPartirDe("12/02/2012");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("05:55");
		  ponto7.getHorarios().addElement("14:30");
		  ponto7.getHorarios().addElement("22:40");
		  Ponto ponto8 = new Ponto();
		  ponto8.setNome("TERMINAL FAZENDA RIO GRANDE");
		  ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto8.setValidoAPartirDe("12/02/2012");
		  onibus.getPontos().addElement(ponto8);
		  ponto8.getHorarios().addElement("05:05");
		  ponto8.getHorarios().addElement("13:30");
		  ponto8.getHorarios().addElement("21:40");
		  Ponto ponto9 = new Ponto();
		  ponto9.setNome("EMPRESA KRAFT");
		  ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto9.setValidoAPartirDe("12/02/2012");
		  onibus.getPontos().addElement(ponto9);
		  ponto9.getHorarios().addElement("06:30");
		  ponto9.getHorarios().addElement("14:50");
		  ponto9.getHorarios().addElement("23:05");
		  return onibus;
		  }
	  }