
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus184 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("184 - V. SUIÇA");
		  onibus.setCodigo("184");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO VILA SUICA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("03/10/2011");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("05:50");
		  ponto0.getHorarios().addElement("06:10");
		  ponto0.getHorarios().addElement("06:30");
		  ponto0.getHorarios().addElement("06:50");
		  ponto0.getHorarios().addElement("07:10");
		  ponto0.getHorarios().addElement("07:30");
		  ponto0.getHorarios().addElement("07:50");
		  ponto0.getHorarios().addElement("08:12");
		  ponto0.getHorarios().addElement("08:45");
		  ponto0.getHorarios().addElement("09:21");
		  ponto0.getHorarios().addElement("09:57");
		  ponto0.getHorarios().addElement("10:33");
		  ponto0.getHorarios().addElement("11:09");
		  ponto0.getHorarios().addElement("11:45");
		  ponto0.getHorarios().addElement("12:17");
		  ponto0.getHorarios().addElement("12:49");
		  ponto0.getHorarios().addElement("13:22");
		  ponto0.getHorarios().addElement("13:55");
		  ponto0.getHorarios().addElement("14:28");
		  ponto0.getHorarios().addElement("15:01");
		  ponto0.getHorarios().addElement("15:34");
		  ponto0.getHorarios().addElement("16:08");
		  ponto0.getHorarios().addElement("16:43");
		  ponto0.getHorarios().addElement("17:13");
		  ponto0.getHorarios().addElement("17:35");
		  ponto0.getHorarios().addElement("17:57");
		  ponto0.getHorarios().addElement("18:19");
		  ponto0.getHorarios().addElement("18:41");
		  ponto0.getHorarios().addElement("19:05");
		  ponto0.getHorarios().addElement("19:35");
		  ponto0.getHorarios().addElement("20:10");
		  ponto0.getHorarios().addElement("20:40");
		  ponto0.getHorarios().addElement("21:10");
		  ponto0.getHorarios().addElement("21:40");
		  ponto0.getHorarios().addElement("22:13");
		  ponto0.getHorarios().addElement("23:20");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("PRACA TIRADENTES");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("03/10/2011");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("06:02");
		  ponto1.getHorarios().addElement("06:22");
		  ponto1.getHorarios().addElement("06:42");
		  ponto1.getHorarios().addElement("07:02");
		  ponto1.getHorarios().addElement("07:22");
		  ponto1.getHorarios().addElement("07:42");
		  ponto1.getHorarios().addElement("08:11");
		  ponto1.getHorarios().addElement("08:47");
		  ponto1.getHorarios().addElement("09:23");
		  ponto1.getHorarios().addElement("09:59");
		  ponto1.getHorarios().addElement("10:35");
		  ponto1.getHorarios().addElement("11:11");
		  ponto1.getHorarios().addElement("11:47");
		  ponto1.getHorarios().addElement("12:19");
		  ponto1.getHorarios().addElement("12:51");
		  ponto1.getHorarios().addElement("13:24");
		  ponto1.getHorarios().addElement("13:57");
		  ponto1.getHorarios().addElement("14:30");
		  ponto1.getHorarios().addElement("15:03");
		  ponto1.getHorarios().addElement("15:36");
		  ponto1.getHorarios().addElement("16:09");
		  ponto1.getHorarios().addElement("16:42");
		  ponto1.getHorarios().addElement("17:04");
		  ponto1.getHorarios().addElement("17:26");
		  ponto1.getHorarios().addElement("17:48");
		  ponto1.getHorarios().addElement("18:10");
		  ponto1.getHorarios().addElement("18:32");
		  ponto1.getHorarios().addElement("18:54");
		  ponto1.getHorarios().addElement("19:16");
		  ponto1.getHorarios().addElement("19:42");
		  ponto1.getHorarios().addElement("20:12");
		  ponto1.getHorarios().addElement("20:42");
		  ponto1.getHorarios().addElement("21:12");
		  ponto1.getHorarios().addElement("21:42");
		  ponto1.getHorarios().addElement("22:14");
		  ponto1.getHorarios().addElement("22:50");
		  ponto1.getHorarios().addElement("23:55");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("VOTORANTIM (R.DEP.A.RODRIGUES)");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("03/10/2011");
		  onibus.getPontos().addElement(ponto2);
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("BAIRRO VILA SUICA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("01/10/2011");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:30");
		  ponto3.getHorarios().addElement("06:00");
		  ponto3.getHorarios().addElement("06:30");
		  ponto3.getHorarios().addElement("07:00");
		  ponto3.getHorarios().addElement("07:30");
		  ponto3.getHorarios().addElement("08:00");
		  ponto3.getHorarios().addElement("08:30");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("09:30");
		  ponto3.getHorarios().addElement("10:00");
		  ponto3.getHorarios().addElement("10:30");
		  ponto3.getHorarios().addElement("11:00");
		  ponto3.getHorarios().addElement("11:30");
		  ponto3.getHorarios().addElement("12:00");
		  ponto3.getHorarios().addElement("12:30");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("13:30");
		  ponto3.getHorarios().addElement("14:30");
		  ponto3.getHorarios().addElement("15:30");
		  ponto3.getHorarios().addElement("16:30");
		  ponto3.getHorarios().addElement("17:30");
		  ponto3.getHorarios().addElement("18:30");
		  ponto3.getHorarios().addElement("19:30");
		  ponto3.getHorarios().addElement("20:30");
		  ponto3.getHorarios().addElement("21:30");
		  ponto3.getHorarios().addElement("22:30");
		  ponto3.getHorarios().addElement("23:30");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("PRACA TIRADENTES");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("01/10/2011");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:02");
		  ponto4.getHorarios().addElement("06:32");
		  ponto4.getHorarios().addElement("07:02");
		  ponto4.getHorarios().addElement("07:32");
		  ponto4.getHorarios().addElement("08:02");
		  ponto4.getHorarios().addElement("08:32");
		  ponto4.getHorarios().addElement("09:02");
		  ponto4.getHorarios().addElement("09:32");
		  ponto4.getHorarios().addElement("10:02");
		  ponto4.getHorarios().addElement("10:32");
		  ponto4.getHorarios().addElement("11:02");
		  ponto4.getHorarios().addElement("11:32");
		  ponto4.getHorarios().addElement("12:02");
		  ponto4.getHorarios().addElement("12:32");
		  ponto4.getHorarios().addElement("13:02");
		  ponto4.getHorarios().addElement("13:32");
		  ponto4.getHorarios().addElement("14:02");
		  ponto4.getHorarios().addElement("15:02");
		  ponto4.getHorarios().addElement("16:02");
		  ponto4.getHorarios().addElement("17:02");
		  ponto4.getHorarios().addElement("18:02");
		  ponto4.getHorarios().addElement("19:02");
		  ponto4.getHorarios().addElement("20:02");
		  ponto4.getHorarios().addElement("21:02");
		  ponto4.getHorarios().addElement("22:02");
		  ponto4.getHorarios().addElement("23:02");
		  ponto4.getHorarios().addElement("23:58");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("VOTORANTIM (R.DEP.A.RODRIGUES)");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("01/10/2011");
		  onibus.getPontos().addElement(ponto5);
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("BAIRRO VILA SUICA");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("02/10/2011");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("05:30");
		  ponto6.getHorarios().addElement("06:20");
		  ponto6.getHorarios().addElement("07:20");
		  ponto6.getHorarios().addElement("08:20");
		  ponto6.getHorarios().addElement("09:20");
		  ponto6.getHorarios().addElement("10:20");
		  ponto6.getHorarios().addElement("11:20");
		  ponto6.getHorarios().addElement("12:20");
		  ponto6.getHorarios().addElement("13:20");
		  ponto6.getHorarios().addElement("14:20");
		  ponto6.getHorarios().addElement("15:20");
		  ponto6.getHorarios().addElement("16:20");
		  ponto6.getHorarios().addElement("17:20");
		  ponto6.getHorarios().addElement("18:20");
		  ponto6.getHorarios().addElement("19:20");
		  ponto6.getHorarios().addElement("20:30");
		  ponto6.getHorarios().addElement("21:30");
		  ponto6.getHorarios().addElement("22:30");
		  ponto6.getHorarios().addElement("23:30");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("PRACA TIRADENTES");
		  ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto7.setValidoAPartirDe("02/10/2011");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("05:55");
		  ponto7.getHorarios().addElement("06:52");
		  ponto7.getHorarios().addElement("07:52");
		  ponto7.getHorarios().addElement("08:52");
		  ponto7.getHorarios().addElement("09:52");
		  ponto7.getHorarios().addElement("10:52");
		  ponto7.getHorarios().addElement("11:52");
		  ponto7.getHorarios().addElement("12:52");
		  ponto7.getHorarios().addElement("13:52");
		  ponto7.getHorarios().addElement("14:52");
		  ponto7.getHorarios().addElement("15:52");
		  ponto7.getHorarios().addElement("16:52");
		  ponto7.getHorarios().addElement("17:52");
		  ponto7.getHorarios().addElement("18:52");
		  ponto7.getHorarios().addElement("19:57");
		  ponto7.getHorarios().addElement("21:02");
		  ponto7.getHorarios().addElement("22:02");
		  ponto7.getHorarios().addElement("23:02");
		  ponto7.getHorarios().addElement("23:58");
		  Ponto ponto8 = new Ponto();
		  ponto8.setNome("VOTORANTIM (R.DEP.A.RODRIGUES)");
		  ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto8.setValidoAPartirDe("02/10/2011");
		  onibus.getPontos().addElement(ponto8);
		  return onibus;
		  }
	  }