
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusI51 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("I51 - Q. BARRAS/T.PAULISTA-ANTI HORARI");
		  onibus.setCodigo("I51");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("T.Q.BARRAS (VIA CARON)");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("26/03/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:47");
		  ponto0.getHorarios().addElement("06:47");
		  ponto0.getHorarios().addElement("07:47");
		  ponto0.getHorarios().addElement("08:47");
		  ponto0.getHorarios().addElement("09:47");
		  ponto0.getHorarios().addElement("10:47");
		  ponto0.getHorarios().addElement("11:47");
		  ponto0.getHorarios().addElement("12:47");
		  ponto0.getHorarios().addElement("13:47");
		  ponto0.getHorarios().addElement("14:47");
		  ponto0.getHorarios().addElement("15:47");
		  ponto0.getHorarios().addElement("16:47");
		  ponto0.getHorarios().addElement("17:47");
		  ponto0.getHorarios().addElement("18:47");
		  ponto0.getHorarios().addElement("19:47");
		  ponto0.getHorarios().addElement("20:47");
		  ponto0.getHorarios().addElement("21:47");
		  ponto0.getHorarios().addElement("22:47");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("JD.PAULISTA(VIA EUGENIA MARIA)");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("26/03/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:05");
		  ponto1.getHorarios().addElement("06:05");
		  ponto1.getHorarios().addElement("07:05");
		  ponto1.getHorarios().addElement("08:05");
		  ponto1.getHorarios().addElement("09:05");
		  ponto1.getHorarios().addElement("10:05");
		  ponto1.getHorarios().addElement("11:05");
		  ponto1.getHorarios().addElement("12:05");
		  ponto1.getHorarios().addElement("13:05");
		  ponto1.getHorarios().addElement("14:05");
		  ponto1.getHorarios().addElement("15:05");
		  ponto1.getHorarios().addElement("16:05");
		  ponto1.getHorarios().addElement("17:05");
		  ponto1.getHorarios().addElement("18:05");
		  ponto1.getHorarios().addElement("19:05");
		  ponto1.getHorarios().addElement("20:05");
		  ponto1.getHorarios().addElement("21:05");
		  ponto1.getHorarios().addElement("22:05");
		  ponto1.getHorarios().addElement("23:05");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("JD.PAULISTA(VIA MENINO DEUS)");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("26/03/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:30");
		  ponto2.getHorarios().addElement("06:30");
		  ponto2.getHorarios().addElement("07:30");
		  ponto2.getHorarios().addElement("08:30");
		  ponto2.getHorarios().addElement("09:30");
		  ponto2.getHorarios().addElement("10:30");
		  ponto2.getHorarios().addElement("11:30");
		  ponto2.getHorarios().addElement("12:30");
		  ponto2.getHorarios().addElement("13:30");
		  ponto2.getHorarios().addElement("14:30");
		  ponto2.getHorarios().addElement("15:30");
		  ponto2.getHorarios().addElement("16:30");
		  ponto2.getHorarios().addElement("17:30");
		  ponto2.getHorarios().addElement("18:30");
		  ponto2.getHorarios().addElement("19:30");
		  ponto2.getHorarios().addElement("20:30");
		  ponto2.getHorarios().addElement("21:30");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("23:30");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("T.Q.BARRAS (VIA CARON)");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("31/12/2011");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:37");
		  ponto3.getHorarios().addElement("06:37");
		  ponto3.getHorarios().addElement("07:37");
		  ponto3.getHorarios().addElement("08:37");
		  ponto3.getHorarios().addElement("09:37");
		  ponto3.getHorarios().addElement("10:37");
		  ponto3.getHorarios().addElement("11:37");
		  ponto3.getHorarios().addElement("12:37");
		  ponto3.getHorarios().addElement("13:37");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("JD.PAULISTA(VIA EUGENIA MARIA)");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("31/12/2011");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("04:55");
		  ponto4.getHorarios().addElement("05:55");
		  ponto4.getHorarios().addElement("06:55");
		  ponto4.getHorarios().addElement("07:55");
		  ponto4.getHorarios().addElement("08:55");
		  ponto4.getHorarios().addElement("09:55");
		  ponto4.getHorarios().addElement("10:55");
		  ponto4.getHorarios().addElement("11:55");
		  ponto4.getHorarios().addElement("12:55");
		  ponto4.getHorarios().addElement("13:55");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("JD.PAULISTA(VIA MENINO DEUS)");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("31/12/2011");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:20");
		  ponto5.getHorarios().addElement("06:20");
		  ponto5.getHorarios().addElement("07:20");
		  ponto5.getHorarios().addElement("08:20");
		  ponto5.getHorarios().addElement("09:20");
		  ponto5.getHorarios().addElement("10:20");
		  ponto5.getHorarios().addElement("11:20");
		  ponto5.getHorarios().addElement("12:20");
		  ponto5.getHorarios().addElement("13:20");
		  ponto5.getHorarios().addElement("14:20");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("PALMITAL");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("12/08/2012");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("06:35");
		  ponto6.getHorarios().addElement("07:05");
		  ponto6.getHorarios().addElement("14:20");
		  ponto6.getHorarios().addElement("15:00");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("T.Q.BARRAS (VIA CARON)");
		  ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto7.setValidoAPartirDe("12/08/2012");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("05:32");
		  ponto7.getHorarios().addElement("06:32");
		  ponto7.getHorarios().addElement("06:50");
		  ponto7.getHorarios().addElement("07:30");
		  ponto7.getHorarios().addElement("08:32");
		  ponto7.getHorarios().addElement("09:32");
		  ponto7.getHorarios().addElement("10:32");
		  ponto7.getHorarios().addElement("11:32");
		  ponto7.getHorarios().addElement("12:32");
		  ponto7.getHorarios().addElement("13:32");
		  ponto7.getHorarios().addElement("14:40");
		  ponto7.getHorarios().addElement("15:32");
		  ponto7.getHorarios().addElement("16:32");
		  ponto7.getHorarios().addElement("17:32");
		  ponto7.getHorarios().addElement("18:32");
		  ponto7.getHorarios().addElement("19:32");
		  ponto7.getHorarios().addElement("20:32");
		  ponto7.getHorarios().addElement("21:32");
		  ponto7.getHorarios().addElement("22:32");
		  Ponto ponto8 = new Ponto();
		  ponto8.setNome("JD.PAULISTA(VIA EUGENIA MARIA)");
		  ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto8.setValidoAPartirDe("12/08/2012");
		  onibus.getPontos().addElement(ponto8);
		  ponto8.getHorarios().addElement("05:50");
		  ponto8.getHorarios().addElement("06:15");
		  ponto8.getHorarios().addElement("07:50");
		  ponto8.getHorarios().addElement("08:50");
		  ponto8.getHorarios().addElement("09:50");
		  ponto8.getHorarios().addElement("10:50");
		  ponto8.getHorarios().addElement("11:50");
		  ponto8.getHorarios().addElement("12:50");
		  ponto8.getHorarios().addElement("13:50");
		  ponto8.getHorarios().addElement("15:50");
		  ponto8.getHorarios().addElement("16:50");
		  ponto8.getHorarios().addElement("17:50");
		  ponto8.getHorarios().addElement("18:50");
		  ponto8.getHorarios().addElement("19:50");
		  ponto8.getHorarios().addElement("20:50");
		  ponto8.getHorarios().addElement("21:50");
		  ponto8.getHorarios().addElement("22:50");
		  Ponto ponto9 = new Ponto();
		  ponto9.setNome("JD.PAULISTA(VIA MENINO DEUS)");
		  ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto9.setValidoAPartirDe("12/08/2012");
		  onibus.getPontos().addElement(ponto9);
		  ponto9.getHorarios().addElement("05:15");
		  ponto9.getHorarios().addElement("08:15");
		  ponto9.getHorarios().addElement("09:15");
		  ponto9.getHorarios().addElement("10:15");
		  ponto9.getHorarios().addElement("11:15");
		  ponto9.getHorarios().addElement("12:15");
		  ponto9.getHorarios().addElement("13:15");
		  ponto9.getHorarios().addElement("16:15");
		  ponto9.getHorarios().addElement("17:15");
		  ponto9.getHorarios().addElement("18:15");
		  ponto9.getHorarios().addElement("19:15");
		  ponto9.getHorarios().addElement("20:15");
		  ponto9.getHorarios().addElement("21:15");
		  ponto9.getHorarios().addElement("22:15");
		  ponto9.getHorarios().addElement("23:15");
		  return onibus;
		  }
	  }