
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusD14 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("D14 - PINHAIS / PIRAQUARA");
		  onibus.setCodigo("D14");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("TERMINAL PINHAIS");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("25/06/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("06:00");
		  ponto0.getHorarios().addElement("06:34");
		  ponto0.getHorarios().addElement("07:07");
		  ponto0.getHorarios().addElement("07:47");
		  ponto0.getHorarios().addElement("08:53");
		  ponto0.getHorarios().addElement("09:47");
		  ponto0.getHorarios().addElement("10:45");
		  ponto0.getHorarios().addElement("11:39");
		  ponto0.getHorarios().addElement("12:37");
		  ponto0.getHorarios().addElement("13:31");
		  ponto0.getHorarios().addElement("14:29");
		  ponto0.getHorarios().addElement("15:23");
		  ponto0.getHorarios().addElement("16:21");
		  ponto0.getHorarios().addElement("16:48");
		  ponto0.getHorarios().addElement("17:22");
		  ponto0.getHorarios().addElement("18:13");
		  ponto0.getHorarios().addElement("18:40");
		  ponto0.getHorarios().addElement("19:14");
		  ponto0.getHorarios().addElement("20:01");
		  ponto0.getHorarios().addElement("20:32");
		  ponto0.getHorarios().addElement("21:00");
		  ponto0.getHorarios().addElement("21:54");
		  ponto0.getHorarios().addElement("22:40");
		  ponto0.getHorarios().addElement("23:40");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL PIRAQUARA");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("25/06/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:10");
		  ponto1.getHorarios().addElement("05:44");
		  ponto1.getHorarios().addElement("06:17");
		  ponto1.getHorarios().addElement("06:50");
		  ponto1.getHorarios().addElement("07:24");
		  ponto1.getHorarios().addElement("07:57");
		  ponto1.getHorarios().addElement("08:44");
		  ponto1.getHorarios().addElement("09:49");
		  ponto1.getHorarios().addElement("10:43");
		  ponto1.getHorarios().addElement("11:41");
		  ponto1.getHorarios().addElement("12:35");
		  ponto1.getHorarios().addElement("13:33");
		  ponto1.getHorarios().addElement("14:27");
		  ponto1.getHorarios().addElement("15:25");
		  ponto1.getHorarios().addElement("16:19");
		  ponto1.getHorarios().addElement("17:17");
		  ponto1.getHorarios().addElement("17:44");
		  ponto1.getHorarios().addElement("18:18");
		  ponto1.getHorarios().addElement("19:09");
		  ponto1.getHorarios().addElement("19:36");
		  ponto1.getHorarios().addElement("20:10");
		  ponto1.getHorarios().addElement("21:04");
		  ponto1.getHorarios().addElement("21:50");
		  ponto1.getHorarios().addElement("22:45");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL PINHAIS");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("26/05/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:40");
		  ponto2.getHorarios().addElement("07:35");
		  ponto2.getHorarios().addElement("08:20");
		  ponto2.getHorarios().addElement("09:15");
		  ponto2.getHorarios().addElement("10:04");
		  ponto2.getHorarios().addElement("10:59");
		  ponto2.getHorarios().addElement("11:52");
		  ponto2.getHorarios().addElement("12:47");
		  ponto2.getHorarios().addElement("13:40");
		  ponto2.getHorarios().addElement("14:35");
		  ponto2.getHorarios().addElement("15:28");
		  ponto2.getHorarios().addElement("16:23");
		  ponto2.getHorarios().addElement("17:16");
		  ponto2.getHorarios().addElement("18:11");
		  ponto2.getHorarios().addElement("19:02");
		  ponto2.getHorarios().addElement("19:57");
		  ponto2.getHorarios().addElement("21:40");
		  ponto2.getHorarios().addElement("23:20");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL PIRAQUARA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("26/05/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:50");
		  ponto3.getHorarios().addElement("06:45");
		  ponto3.getHorarios().addElement("07:30");
		  ponto3.getHorarios().addElement("08:25");
		  ponto3.getHorarios().addElement("09:10");
		  ponto3.getHorarios().addElement("10:05");
		  ponto3.getHorarios().addElement("10:58");
		  ponto3.getHorarios().addElement("11:53");
		  ponto3.getHorarios().addElement("12:46");
		  ponto3.getHorarios().addElement("13:41");
		  ponto3.getHorarios().addElement("14:34");
		  ponto3.getHorarios().addElement("15:29");
		  ponto3.getHorarios().addElement("16:22");
		  ponto3.getHorarios().addElement("17:17");
		  ponto3.getHorarios().addElement("18:10");
		  ponto3.getHorarios().addElement("19:05");
		  ponto3.getHorarios().addElement("20:50");
		  ponto3.getHorarios().addElement("22:30");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TERMINAL PINHAIS");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("27/05/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:50");
		  ponto4.getHorarios().addElement("07:20");
		  ponto4.getHorarios().addElement("08:32");
		  ponto4.getHorarios().addElement("09:24");
		  ponto4.getHorarios().addElement("10:18");
		  ponto4.getHorarios().addElement("11:12");
		  ponto4.getHorarios().addElement("12:06");
		  ponto4.getHorarios().addElement("13:00");
		  ponto4.getHorarios().addElement("13:54");
		  ponto4.getHorarios().addElement("14:48");
		  ponto4.getHorarios().addElement("15:42");
		  ponto4.getHorarios().addElement("16:36");
		  ponto4.getHorarios().addElement("17:28");
		  ponto4.getHorarios().addElement("18:22");
		  ponto4.getHorarios().addElement("20:07");
		  ponto4.getHorarios().addElement("21:50");
		  ponto4.getHorarios().addElement("23:35");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL PIRAQUARA");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("27/05/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:00");
		  ponto5.getHorarios().addElement("07:40");
		  ponto5.getHorarios().addElement("08:30");
		  ponto5.getHorarios().addElement("09:24");
		  ponto5.getHorarios().addElement("10:18");
		  ponto5.getHorarios().addElement("11:12");
		  ponto5.getHorarios().addElement("12:06");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:54");
		  ponto5.getHorarios().addElement("14:48");
		  ponto5.getHorarios().addElement("15:42");
		  ponto5.getHorarios().addElement("16:36");
		  ponto5.getHorarios().addElement("17:30");
		  ponto5.getHorarios().addElement("19:15");
		  ponto5.getHorarios().addElement("21:00");
		  ponto5.getHorarios().addElement("22:40");
		  return onibus;
		  }
	  }