
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus244 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("244 - JD. DO ARROIO");
		  onibus.setCodigo("244");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO JD. DO ARROIO");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("06/06/2011");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:25");
		  ponto0.getHorarios().addElement("06:00");
		  ponto0.getHorarios().addElement("06:30");
		  ponto0.getHorarios().addElement("07:00");
		  ponto0.getHorarios().addElement("07:30");
		  ponto0.getHorarios().addElement("08:00");
		  ponto0.getHorarios().addElement("08:30");
		  ponto0.getHorarios().addElement("09:05");
		  ponto0.getHorarios().addElement("09:45");
		  ponto0.getHorarios().addElement("10:25");
		  ponto0.getHorarios().addElement("11:05");
		  ponto0.getHorarios().addElement("11:45");
		  ponto0.getHorarios().addElement("12:25");
		  ponto0.getHorarios().addElement("13:05");
		  ponto0.getHorarios().addElement("13:45");
		  ponto0.getHorarios().addElement("14:25");
		  ponto0.getHorarios().addElement("15:05");
		  ponto0.getHorarios().addElement("15:45");
		  ponto0.getHorarios().addElement("16:25");
		  ponto0.getHorarios().addElement("17:01");
		  ponto0.getHorarios().addElement("17:31");
		  ponto0.getHorarios().addElement("18:01");
		  ponto0.getHorarios().addElement("18:31");
		  ponto0.getHorarios().addElement("19:01");
		  ponto0.getHorarios().addElement("19:31");
		  ponto0.getHorarios().addElement("20:01");
		  ponto0.getHorarios().addElement("20:31");
		  ponto0.getHorarios().addElement("21:05");
		  ponto0.getHorarios().addElement("21:40");
		  ponto0.getHorarios().addElement("22:20");
		  ponto0.getHorarios().addElement("23:00");
		  ponto0.getHorarios().addElement("23:40");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL BARREIRINHA");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("06/06/2011");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:40");
		  ponto1.getHorarios().addElement("06:17");
		  ponto1.getHorarios().addElement("06:47");
		  ponto1.getHorarios().addElement("07:17");
		  ponto1.getHorarios().addElement("07:47");
		  ponto1.getHorarios().addElement("08:17");
		  ponto1.getHorarios().addElement("08:47");
		  ponto1.getHorarios().addElement("09:25");
		  ponto1.getHorarios().addElement("10:05");
		  ponto1.getHorarios().addElement("10:45");
		  ponto1.getHorarios().addElement("11:25");
		  ponto1.getHorarios().addElement("12:05");
		  ponto1.getHorarios().addElement("12:45");
		  ponto1.getHorarios().addElement("13:25");
		  ponto1.getHorarios().addElement("14:05");
		  ponto1.getHorarios().addElement("14:45");
		  ponto1.getHorarios().addElement("15:25");
		  ponto1.getHorarios().addElement("16:05");
		  ponto1.getHorarios().addElement("16:45");
		  ponto1.getHorarios().addElement("17:15");
		  ponto1.getHorarios().addElement("17:45");
		  ponto1.getHorarios().addElement("18:15");
		  ponto1.getHorarios().addElement("18:45");
		  ponto1.getHorarios().addElement("19:15");
		  ponto1.getHorarios().addElement("19:45");
		  ponto1.getHorarios().addElement("20:15");
		  ponto1.getHorarios().addElement("20:45");
		  ponto1.getHorarios().addElement("21:20");
		  ponto1.getHorarios().addElement("22:00");
		  ponto1.getHorarios().addElement("22:40");
		  ponto1.getHorarios().addElement("23:20");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO JD. DO ARROIO");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("20/10/2007");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:00");
		  ponto2.getHorarios().addElement("06:40");
		  ponto2.getHorarios().addElement("07:20");
		  ponto2.getHorarios().addElement("08:00");
		  ponto2.getHorarios().addElement("08:40");
		  ponto2.getHorarios().addElement("09:20");
		  ponto2.getHorarios().addElement("10:00");
		  ponto2.getHorarios().addElement("10:40");
		  ponto2.getHorarios().addElement("11:20");
		  ponto2.getHorarios().addElement("12:00");
		  ponto2.getHorarios().addElement("12:40");
		  ponto2.getHorarios().addElement("13:20");
		  ponto2.getHorarios().addElement("14:00");
		  ponto2.getHorarios().addElement("14:40");
		  ponto2.getHorarios().addElement("15:20");
		  ponto2.getHorarios().addElement("16:00");
		  ponto2.getHorarios().addElement("16:40");
		  ponto2.getHorarios().addElement("17:20");
		  ponto2.getHorarios().addElement("18:00");
		  ponto2.getHorarios().addElement("18:40");
		  ponto2.getHorarios().addElement("19:20");
		  ponto2.getHorarios().addElement("20:00");
		  ponto2.getHorarios().addElement("20:40");
		  ponto2.getHorarios().addElement("21:20");
		  ponto2.getHorarios().addElement("22:00");
		  ponto2.getHorarios().addElement("22:40");
		  ponto2.getHorarios().addElement("23:20");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL BARREIRINHA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("20/10/2007");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:20");
		  ponto3.getHorarios().addElement("07:00");
		  ponto3.getHorarios().addElement("07:40");
		  ponto3.getHorarios().addElement("08:20");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("09:40");
		  ponto3.getHorarios().addElement("10:20");
		  ponto3.getHorarios().addElement("11:00");
		  ponto3.getHorarios().addElement("11:40");
		  ponto3.getHorarios().addElement("12:20");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("13:40");
		  ponto3.getHorarios().addElement("14:20");
		  ponto3.getHorarios().addElement("15:00");
		  ponto3.getHorarios().addElement("15:40");
		  ponto3.getHorarios().addElement("16:20");
		  ponto3.getHorarios().addElement("17:00");
		  ponto3.getHorarios().addElement("17:40");
		  ponto3.getHorarios().addElement("18:20");
		  ponto3.getHorarios().addElement("19:00");
		  ponto3.getHorarios().addElement("19:40");
		  ponto3.getHorarios().addElement("20:20");
		  ponto3.getHorarios().addElement("21:00");
		  ponto3.getHorarios().addElement("21:40");
		  ponto3.getHorarios().addElement("22:20");
		  ponto3.getHorarios().addElement("23:00");
		  ponto3.getHorarios().addElement("23:45");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO JD. DO ARROIO");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("21/10/2007");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:00");
		  ponto4.getHorarios().addElement("06:40");
		  ponto4.getHorarios().addElement("07:20");
		  ponto4.getHorarios().addElement("08:00");
		  ponto4.getHorarios().addElement("08:40");
		  ponto4.getHorarios().addElement("09:20");
		  ponto4.getHorarios().addElement("10:00");
		  ponto4.getHorarios().addElement("10:40");
		  ponto4.getHorarios().addElement("11:20");
		  ponto4.getHorarios().addElement("12:00");
		  ponto4.getHorarios().addElement("12:40");
		  ponto4.getHorarios().addElement("13:20");
		  ponto4.getHorarios().addElement("14:00");
		  ponto4.getHorarios().addElement("14:40");
		  ponto4.getHorarios().addElement("15:20");
		  ponto4.getHorarios().addElement("16:00");
		  ponto4.getHorarios().addElement("16:40");
		  ponto4.getHorarios().addElement("17:20");
		  ponto4.getHorarios().addElement("18:00");
		  ponto4.getHorarios().addElement("18:40");
		  ponto4.getHorarios().addElement("19:20");
		  ponto4.getHorarios().addElement("20:00");
		  ponto4.getHorarios().addElement("20:40");
		  ponto4.getHorarios().addElement("21:20");
		  ponto4.getHorarios().addElement("22:00");
		  ponto4.getHorarios().addElement("22:40");
		  ponto4.getHorarios().addElement("23:20");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL BARREIRINHA");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("21/10/2007");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:20");
		  ponto5.getHorarios().addElement("07:00");
		  ponto5.getHorarios().addElement("07:40");
		  ponto5.getHorarios().addElement("08:20");
		  ponto5.getHorarios().addElement("09:00");
		  ponto5.getHorarios().addElement("09:40");
		  ponto5.getHorarios().addElement("10:20");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("11:40");
		  ponto5.getHorarios().addElement("12:20");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:40");
		  ponto5.getHorarios().addElement("14:20");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("15:40");
		  ponto5.getHorarios().addElement("16:20");
		  ponto5.getHorarios().addElement("17:00");
		  ponto5.getHorarios().addElement("17:40");
		  ponto5.getHorarios().addElement("18:20");
		  ponto5.getHorarios().addElement("19:00");
		  ponto5.getHorarios().addElement("19:40");
		  ponto5.getHorarios().addElement("20:20");
		  ponto5.getHorarios().addElement("21:00");
		  ponto5.getHorarios().addElement("21:40");
		  ponto5.getHorarios().addElement("22:20");
		  ponto5.getHorarios().addElement("23:00");
		  ponto5.getHorarios().addElement("23:45");
		  return onibus;
		  }
	  }