
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class Onibus540 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("540 - BOQUEIRAO / KRAFT");
		onibus.setCodigo("540");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("TERMINAL BOQUEIRAO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("12/03/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:03");
		ponto0.getHorarios().addElement("05:10");
		ponto0.getHorarios().addElement("13:02");
		ponto0.getHorarios().addElement("13:10");
		ponto0.getHorarios().addElement("13:15");
		ponto0.getHorarios().addElement("21:27");
		ponto0.getHorarios().addElement("21:32");
		ponto0.getHorarios().addElement("21:39");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("EMPRESA KRAFT");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("12/03/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:31");
		ponto1.getHorarios().addElement("05:43");
		ponto1.getHorarios().addElement("06:25");
		ponto1.getHorarios().addElement("06:35");
		ponto1.getHorarios().addElement("13:35");
		ponto1.getHorarios().addElement("13:43");
		ponto1.getHorarios().addElement("13:48");
		ponto1.getHorarios().addElement("14:40");
		ponto1.getHorarios().addElement("14:45");
		ponto1.getHorarios().addElement("14:50");
		ponto1.getHorarios().addElement("22:00");
		ponto1.getHorarios().addElement("22:05");
		ponto1.getHorarios().addElement("22:12");
		ponto1.getHorarios().addElement("22:50");
		ponto1.getHorarios().addElement("22:55");
		ponto1.getHorarios().addElement("23:00");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("SITIO CERCADO SENTIDO KRAFT");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("12/03/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:16");
		ponto2.getHorarios().addElement("05:25");
		ponto2.getHorarios().addElement("13:15");
		ponto2.getHorarios().addElement("13:23");
		ponto2.getHorarios().addElement("13:28");
		ponto2.getHorarios().addElement("21:40");
		ponto2.getHorarios().addElement("21:45");
		ponto2.getHorarios().addElement("21:52");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("T.S.CERCADO SENT.BOQUEIRAO");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("12/03/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:45");
		ponto3.getHorarios().addElement("06:55");
		ponto3.getHorarios().addElement("15:00");
		ponto3.getHorarios().addElement("15:05");
		ponto3.getHorarios().addElement("15:10");
		ponto3.getHorarios().addElement("23:10");
		ponto3.getHorarios().addElement("23:15");
		ponto3.getHorarios().addElement("23:20");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL BOQUEIRAO");
		ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto4.setValidoAPartirDe("01/10/2012");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:03");
		ponto4.getHorarios().addElement("05:10");
		ponto4.getHorarios().addElement("13:15");
		ponto4.getHorarios().addElement("21:39");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("EMPRESA KRAFT");
		ponto5.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto5.setValidoAPartirDe("01/10/2012");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:31");
		ponto5.getHorarios().addElement("05:43");
		ponto5.getHorarios().addElement("06:25");
		ponto5.getHorarios().addElement("06:35");
		ponto5.getHorarios().addElement("13:48");
		ponto5.getHorarios().addElement("14:50");
		ponto5.getHorarios().addElement("22:12");
		ponto5.getHorarios().addElement("23:00");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("SITIO CERCADO SENTIDO KRAFT");
		ponto6.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto6.setValidoAPartirDe("01/10/2012");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("05:16");
		ponto6.getHorarios().addElement("05:25");
		ponto6.getHorarios().addElement("13:28");
		ponto6.getHorarios().addElement("21:52");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("T.S.CERCADO SENT.BOQUEIRAO");
		ponto7.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto7.setValidoAPartirDe("01/10/2012");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("06:45");
		ponto7.getHorarios().addElement("06:55");
		ponto7.getHorarios().addElement("15:10");
		ponto7.getHorarios().addElement("23:20");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("TERMINAL BOQUEIRAO");
		ponto8.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto8.setValidoAPartirDe("30/06/2012");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("05:05");
		ponto8.getHorarios().addElement("13:15");
		ponto8.getHorarios().addElement("21:30");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("EMPRESA KRAFT");
		ponto9.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto9.setValidoAPartirDe("30/06/2012");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("13:48");
		ponto9.getHorarios().addElement("14:40");
		ponto9.getHorarios().addElement("22:03");
		ponto9.getHorarios().addElement("22:55");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("SITIO CERCADO SENTIDO KRAFT");
		ponto10.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto10.setValidoAPartirDe("30/06/2012");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("05:17");
		ponto10.getHorarios().addElement("13:28");
		ponto10.getHorarios().addElement("21:43");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("T.S.CERCADO SENT.BOQUEIRAO");
		ponto11.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto11.setValidoAPartirDe("30/06/2012");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("15:00");
		ponto11.getHorarios().addElement("23:15");
		Ponto ponto12 = new Ponto();
		ponto12.setNome("TERMINAL BOQUEIRAO");
		ponto12.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto12.setValidoAPartirDe("01/07/2012");
		onibus.getPontos().addElement(ponto12);
		ponto12.getHorarios().addElement("05:05");
		ponto12.getHorarios().addElement("13:15");
		ponto12.getHorarios().addElement("21:30");
		Ponto ponto13 = new Ponto();
		ponto13.setNome("EMPRESA KRAFT");
		ponto13.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto13.setValidoAPartirDe("01/07/2012");
		onibus.getPontos().addElement(ponto13);
		ponto13.getHorarios().addElement("13:48");
		ponto13.getHorarios().addElement("14:40");
		ponto13.getHorarios().addElement("22:03");
		ponto13.getHorarios().addElement("22:55");
		Ponto ponto14 = new Ponto();
		ponto14.setNome("SITIO CERCADO SENTIDO KRAFT");
		ponto14.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto14.setValidoAPartirDe("01/07/2012");
		onibus.getPontos().addElement(ponto14);
		ponto14.getHorarios().addElement("05:17");
		ponto14.getHorarios().addElement("13:28");
		ponto14.getHorarios().addElement("21:43");
		Ponto ponto15 = new Ponto();
		ponto15.setNome("T.S.CERCADO SENT.BOQUEIRAO");
		ponto15.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto15.setValidoAPartirDe("01/07/2012");
		onibus.getPontos().addElement(ponto15);
		ponto15.getHorarios().addElement("15:00");
		ponto15.getHorarios().addElement("23:15");
		return onibus;
		}
	}