
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusC18 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("C18 - JD. TROPICAL");
		  onibus.setCodigo("C18");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO JD.TROPICAL");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("22/09/2008");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:10");
		  ponto0.getHorarios().addElement("05:27");
		  ponto0.getHorarios().addElement("05:44");
		  ponto0.getHorarios().addElement("06:01");
		  ponto0.getHorarios().addElement("06:18");
		  ponto0.getHorarios().addElement("06:35");
		  ponto0.getHorarios().addElement("06:52");
		  ponto0.getHorarios().addElement("07:09");
		  ponto0.getHorarios().addElement("07:26");
		  ponto0.getHorarios().addElement("07:43");
		  ponto0.getHorarios().addElement("08:17");
		  ponto0.getHorarios().addElement("08:51");
		  ponto0.getHorarios().addElement("09:25");
		  ponto0.getHorarios().addElement("09:59");
		  ponto0.getHorarios().addElement("10:33");
		  ponto0.getHorarios().addElement("11:07");
		  ponto0.getHorarios().addElement("11:41");
		  ponto0.getHorarios().addElement("12:15");
		  ponto0.getHorarios().addElement("12:49");
		  ponto0.getHorarios().addElement("13:23");
		  ponto0.getHorarios().addElement("13:57");
		  ponto0.getHorarios().addElement("14:31");
		  ponto0.getHorarios().addElement("15:05");
		  ponto0.getHorarios().addElement("15:39");
		  ponto0.getHorarios().addElement("16:13");
		  ponto0.getHorarios().addElement("16:47");
		  ponto0.getHorarios().addElement("17:04");
		  ponto0.getHorarios().addElement("17:21");
		  ponto0.getHorarios().addElement("17:38");
		  ponto0.getHorarios().addElement("17:55");
		  ponto0.getHorarios().addElement("18:12");
		  ponto0.getHorarios().addElement("18:29");
		  ponto0.getHorarios().addElement("18:46");
		  ponto0.getHorarios().addElement("19:03");
		  ponto0.getHorarios().addElement("19:20");
		  ponto0.getHorarios().addElement("19:37");
		  ponto0.getHorarios().addElement("20:11");
		  ponto0.getHorarios().addElement("20:45");
		  ponto0.getHorarios().addElement("21:19");
		  ponto0.getHorarios().addElement("21:53");
		  ponto0.getHorarios().addElement("22:27");
		  ponto0.getHorarios().addElement("23:05");
		  ponto0.getHorarios().addElement("23:43");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL PINHAIS");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("22/09/2008");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:27");
		  ponto1.getHorarios().addElement("05:44");
		  ponto1.getHorarios().addElement("06:01");
		  ponto1.getHorarios().addElement("06:18");
		  ponto1.getHorarios().addElement("06:35");
		  ponto1.getHorarios().addElement("06:52");
		  ponto1.getHorarios().addElement("07:09");
		  ponto1.getHorarios().addElement("07:26");
		  ponto1.getHorarios().addElement("08:00");
		  ponto1.getHorarios().addElement("08:34");
		  ponto1.getHorarios().addElement("09:08");
		  ponto1.getHorarios().addElement("09:42");
		  ponto1.getHorarios().addElement("10:16");
		  ponto1.getHorarios().addElement("10:50");
		  ponto1.getHorarios().addElement("11:24");
		  ponto1.getHorarios().addElement("11:58");
		  ponto1.getHorarios().addElement("12:32");
		  ponto1.getHorarios().addElement("13:06");
		  ponto1.getHorarios().addElement("13:40");
		  ponto1.getHorarios().addElement("14:14");
		  ponto1.getHorarios().addElement("14:48");
		  ponto1.getHorarios().addElement("15:22");
		  ponto1.getHorarios().addElement("15:56");
		  ponto1.getHorarios().addElement("16:30");
		  ponto1.getHorarios().addElement("16:47");
		  ponto1.getHorarios().addElement("17:04");
		  ponto1.getHorarios().addElement("17:21");
		  ponto1.getHorarios().addElement("17:38");
		  ponto1.getHorarios().addElement("17:55");
		  ponto1.getHorarios().addElement("18:12");
		  ponto1.getHorarios().addElement("18:29");
		  ponto1.getHorarios().addElement("18:46");
		  ponto1.getHorarios().addElement("19:03");
		  ponto1.getHorarios().addElement("19:20");
		  ponto1.getHorarios().addElement("19:37");
		  ponto1.getHorarios().addElement("19:54");
		  ponto1.getHorarios().addElement("20:28");
		  ponto1.getHorarios().addElement("21:02");
		  ponto1.getHorarios().addElement("21:36");
		  ponto1.getHorarios().addElement("22:10");
		  ponto1.getHorarios().addElement("22:44");
		  ponto1.getHorarios().addElement("23:25");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO JD.TROPICAL");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("22/09/2007");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:30");
		  ponto2.getHorarios().addElement("06:00");
		  ponto2.getHorarios().addElement("06:40");
		  ponto2.getHorarios().addElement("07:20");
		  ponto2.getHorarios().addElement("08:00");
		  ponto2.getHorarios().addElement("08:40");
		  ponto2.getHorarios().addElement("09:20");
		  ponto2.getHorarios().addElement("10:00");
		  ponto2.getHorarios().addElement("10:40");
		  ponto2.getHorarios().addElement("11:20");
		  ponto2.getHorarios().addElement("12:00");
		  ponto2.getHorarios().addElement("12:40");
		  ponto2.getHorarios().addElement("13:20");
		  ponto2.getHorarios().addElement("14:00");
		  ponto2.getHorarios().addElement("14:40");
		  ponto2.getHorarios().addElement("15:20");
		  ponto2.getHorarios().addElement("16:00");
		  ponto2.getHorarios().addElement("16:40");
		  ponto2.getHorarios().addElement("17:20");
		  ponto2.getHorarios().addElement("18:00");
		  ponto2.getHorarios().addElement("18:40");
		  ponto2.getHorarios().addElement("19:30");
		  ponto2.getHorarios().addElement("20:30");
		  ponto2.getHorarios().addElement("21:30");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("23:30");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL PINHAIS");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("22/09/2007");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:45");
		  ponto3.getHorarios().addElement("06:20");
		  ponto3.getHorarios().addElement("07:00");
		  ponto3.getHorarios().addElement("07:40");
		  ponto3.getHorarios().addElement("08:20");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("09:40");
		  ponto3.getHorarios().addElement("10:20");
		  ponto3.getHorarios().addElement("11:00");
		  ponto3.getHorarios().addElement("11:40");
		  ponto3.getHorarios().addElement("12:20");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("13:40");
		  ponto3.getHorarios().addElement("14:20");
		  ponto3.getHorarios().addElement("15:00");
		  ponto3.getHorarios().addElement("15:40");
		  ponto3.getHorarios().addElement("16:20");
		  ponto3.getHorarios().addElement("17:00");
		  ponto3.getHorarios().addElement("17:40");
		  ponto3.getHorarios().addElement("18:20");
		  ponto3.getHorarios().addElement("19:00");
		  ponto3.getHorarios().addElement("20:00");
		  ponto3.getHorarios().addElement("21:00");
		  ponto3.getHorarios().addElement("22:00");
		  ponto3.getHorarios().addElement("23:00");
		  ponto3.getHorarios().addElement("00:00");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO JD.TROPICAL");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("23/09/2007");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:00");
		  ponto4.getHorarios().addElement("06:40");
		  ponto4.getHorarios().addElement("07:20");
		  ponto4.getHorarios().addElement("08:00");
		  ponto4.getHorarios().addElement("08:40");
		  ponto4.getHorarios().addElement("09:20");
		  ponto4.getHorarios().addElement("10:00");
		  ponto4.getHorarios().addElement("10:40");
		  ponto4.getHorarios().addElement("11:20");
		  ponto4.getHorarios().addElement("12:00");
		  ponto4.getHorarios().addElement("12:40");
		  ponto4.getHorarios().addElement("13:20");
		  ponto4.getHorarios().addElement("14:00");
		  ponto4.getHorarios().addElement("14:40");
		  ponto4.getHorarios().addElement("15:20");
		  ponto4.getHorarios().addElement("16:00");
		  ponto4.getHorarios().addElement("16:40");
		  ponto4.getHorarios().addElement("17:20");
		  ponto4.getHorarios().addElement("18:00");
		  ponto4.getHorarios().addElement("18:40");
		  ponto4.getHorarios().addElement("19:30");
		  ponto4.getHorarios().addElement("20:30");
		  ponto4.getHorarios().addElement("21:30");
		  ponto4.getHorarios().addElement("22:30");
		  ponto4.getHorarios().addElement("23:30");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL PINHAIS");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("23/09/2007");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:20");
		  ponto5.getHorarios().addElement("07:00");
		  ponto5.getHorarios().addElement("07:40");
		  ponto5.getHorarios().addElement("08:20");
		  ponto5.getHorarios().addElement("09:00");
		  ponto5.getHorarios().addElement("09:40");
		  ponto5.getHorarios().addElement("10:20");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("11:40");
		  ponto5.getHorarios().addElement("12:20");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:40");
		  ponto5.getHorarios().addElement("14:20");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("15:40");
		  ponto5.getHorarios().addElement("16:20");
		  ponto5.getHorarios().addElement("17:00");
		  ponto5.getHorarios().addElement("17:40");
		  ponto5.getHorarios().addElement("18:20");
		  ponto5.getHorarios().addElement("19:00");
		  ponto5.getHorarios().addElement("20:00");
		  ponto5.getHorarios().addElement("21:00");
		  ponto5.getHorarios().addElement("22:00");
		  ponto5.getHorarios().addElement("23:00");
		  ponto5.getHorarios().addElement("00:00");
		  return onibus;
		  }
	  }