
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus640 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("640 - PALMEIRA");
		  onibus.setCodigo("640");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO PALMEIRA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("27/12/2010");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:10");
		  ponto0.getHorarios().addElement("05:33");
		  ponto0.getHorarios().addElement("05:56");
		  ponto0.getHorarios().addElement("06:19");
		  ponto0.getHorarios().addElement("06:42");
		  ponto0.getHorarios().addElement("07:05");
		  ponto0.getHorarios().addElement("07:28");
		  ponto0.getHorarios().addElement("07:51");
		  ponto0.getHorarios().addElement("08:16");
		  ponto0.getHorarios().addElement("09:04");
		  ponto0.getHorarios().addElement("09:52");
		  ponto0.getHorarios().addElement("10:40");
		  ponto0.getHorarios().addElement("11:28");
		  ponto0.getHorarios().addElement("12:16");
		  ponto0.getHorarios().addElement("13:04");
		  ponto0.getHorarios().addElement("13:52");
		  ponto0.getHorarios().addElement("14:40");
		  ponto0.getHorarios().addElement("15:28");
		  ponto0.getHorarios().addElement("16:16");
		  ponto0.getHorarios().addElement("17:04");
		  ponto0.getHorarios().addElement("17:28");
		  ponto0.getHorarios().addElement("17:52");
		  ponto0.getHorarios().addElement("18:16");
		  ponto0.getHorarios().addElement("18:40");
		  ponto0.getHorarios().addElement("19:04");
		  ponto0.getHorarios().addElement("19:28");
		  ponto0.getHorarios().addElement("20:16");
		  ponto0.getHorarios().addElement("21:04");
		  ponto0.getHorarios().addElement("21:50");
		  ponto0.getHorarios().addElement("22:30");
		  ponto0.getHorarios().addElement("23:10");
		  ponto0.getHorarios().addElement("23:52");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL PINHEIRINHO");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("27/12/2010");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:34");
		  ponto1.getHorarios().addElement("05:57");
		  ponto1.getHorarios().addElement("06:20");
		  ponto1.getHorarios().addElement("06:43");
		  ponto1.getHorarios().addElement("07:06");
		  ponto1.getHorarios().addElement("07:29");
		  ponto1.getHorarios().addElement("07:52");
		  ponto1.getHorarios().addElement("08:40");
		  ponto1.getHorarios().addElement("09:28");
		  ponto1.getHorarios().addElement("10:16");
		  ponto1.getHorarios().addElement("11:04");
		  ponto1.getHorarios().addElement("11:52");
		  ponto1.getHorarios().addElement("12:40");
		  ponto1.getHorarios().addElement("13:28");
		  ponto1.getHorarios().addElement("14:16");
		  ponto1.getHorarios().addElement("15:04");
		  ponto1.getHorarios().addElement("15:52");
		  ponto1.getHorarios().addElement("16:40");
		  ponto1.getHorarios().addElement("17:04");
		  ponto1.getHorarios().addElement("17:28");
		  ponto1.getHorarios().addElement("17:52");
		  ponto1.getHorarios().addElement("18:16");
		  ponto1.getHorarios().addElement("18:40");
		  ponto1.getHorarios().addElement("19:04");
		  ponto1.getHorarios().addElement("19:28");
		  ponto1.getHorarios().addElement("19:52");
		  ponto1.getHorarios().addElement("20:40");
		  ponto1.getHorarios().addElement("21:28");
		  ponto1.getHorarios().addElement("22:10");
		  ponto1.getHorarios().addElement("22:50");
		  ponto1.getHorarios().addElement("23:33");
		  ponto1.getHorarios().addElement("00:10");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("EMPRESA DESTRO");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("27/12/2010");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:15");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("BAIRRO PALMEIRA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("20/09/2008");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:40");
		  ponto3.getHorarios().addElement("06:28");
		  ponto3.getHorarios().addElement("07:16");
		  ponto3.getHorarios().addElement("08:04");
		  ponto3.getHorarios().addElement("08:52");
		  ponto3.getHorarios().addElement("09:40");
		  ponto3.getHorarios().addElement("10:28");
		  ponto3.getHorarios().addElement("11:16");
		  ponto3.getHorarios().addElement("12:04");
		  ponto3.getHorarios().addElement("12:52");
		  ponto3.getHorarios().addElement("13:40");
		  ponto3.getHorarios().addElement("14:28");
		  ponto3.getHorarios().addElement("15:16");
		  ponto3.getHorarios().addElement("16:04");
		  ponto3.getHorarios().addElement("16:52");
		  ponto3.getHorarios().addElement("17:40");
		  ponto3.getHorarios().addElement("18:28");
		  ponto3.getHorarios().addElement("19:16");
		  ponto3.getHorarios().addElement("20:04");
		  ponto3.getHorarios().addElement("20:52");
		  ponto3.getHorarios().addElement("21:40");
		  ponto3.getHorarios().addElement("22:28");
		  ponto3.getHorarios().addElement("23:16");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TERMINAL PINHEIRINHO");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("20/09/2008");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:04");
		  ponto4.getHorarios().addElement("06:52");
		  ponto4.getHorarios().addElement("07:40");
		  ponto4.getHorarios().addElement("08:28");
		  ponto4.getHorarios().addElement("09:16");
		  ponto4.getHorarios().addElement("10:04");
		  ponto4.getHorarios().addElement("10:52");
		  ponto4.getHorarios().addElement("11:40");
		  ponto4.getHorarios().addElement("12:28");
		  ponto4.getHorarios().addElement("13:16");
		  ponto4.getHorarios().addElement("14:04");
		  ponto4.getHorarios().addElement("14:52");
		  ponto4.getHorarios().addElement("15:40");
		  ponto4.getHorarios().addElement("16:28");
		  ponto4.getHorarios().addElement("17:16");
		  ponto4.getHorarios().addElement("18:04");
		  ponto4.getHorarios().addElement("18:52");
		  ponto4.getHorarios().addElement("19:40");
		  ponto4.getHorarios().addElement("20:28");
		  ponto4.getHorarios().addElement("21:16");
		  ponto4.getHorarios().addElement("22:04");
		  ponto4.getHorarios().addElement("22:52");
		  ponto4.getHorarios().addElement("23:45");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("BAIRRO PALMEIRA");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("21/09/2008");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:00");
		  ponto5.getHorarios().addElement("06:48");
		  ponto5.getHorarios().addElement("07:36");
		  ponto5.getHorarios().addElement("08:24");
		  ponto5.getHorarios().addElement("09:12");
		  ponto5.getHorarios().addElement("10:00");
		  ponto5.getHorarios().addElement("10:48");
		  ponto5.getHorarios().addElement("11:36");
		  ponto5.getHorarios().addElement("12:24");
		  ponto5.getHorarios().addElement("13:12");
		  ponto5.getHorarios().addElement("14:00");
		  ponto5.getHorarios().addElement("14:48");
		  ponto5.getHorarios().addElement("15:36");
		  ponto5.getHorarios().addElement("16:24");
		  ponto5.getHorarios().addElement("17:12");
		  ponto5.getHorarios().addElement("18:00");
		  ponto5.getHorarios().addElement("18:48");
		  ponto5.getHorarios().addElement("19:36");
		  ponto5.getHorarios().addElement("20:24");
		  ponto5.getHorarios().addElement("21:12");
		  ponto5.getHorarios().addElement("22:00");
		  ponto5.getHorarios().addElement("22:48");
		  ponto5.getHorarios().addElement("23:36");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("TERMINAL PINHEIRINHO");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("21/09/2008");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("06:24");
		  ponto6.getHorarios().addElement("07:12");
		  ponto6.getHorarios().addElement("08:00");
		  ponto6.getHorarios().addElement("08:48");
		  ponto6.getHorarios().addElement("09:36");
		  ponto6.getHorarios().addElement("10:24");
		  ponto6.getHorarios().addElement("11:12");
		  ponto6.getHorarios().addElement("12:00");
		  ponto6.getHorarios().addElement("12:48");
		  ponto6.getHorarios().addElement("13:36");
		  ponto6.getHorarios().addElement("14:24");
		  ponto6.getHorarios().addElement("15:12");
		  ponto6.getHorarios().addElement("16:00");
		  ponto6.getHorarios().addElement("16:48");
		  ponto6.getHorarios().addElement("17:36");
		  ponto6.getHorarios().addElement("18:24");
		  ponto6.getHorarios().addElement("19:12");
		  ponto6.getHorarios().addElement("20:00");
		  ponto6.getHorarios().addElement("20:48");
		  ponto6.getHorarios().addElement("21:36");
		  ponto6.getHorarios().addElement("22:24");
		  ponto6.getHorarios().addElement("23:12");
		  ponto6.getHorarios().addElement("00:00");
		  return onibus;
		  }
	  }