
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus911 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("911 - PASSAÚNA");
		  onibus.setCodigo("911");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO PASSAUNA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("08/11/2010");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:15");
		  ponto0.getHorarios().addElement("05:35");
		  ponto0.getHorarios().addElement("05:55");
		  ponto0.getHorarios().addElement("06:18");
		  ponto0.getHorarios().addElement("06:39");
		  ponto0.getHorarios().addElement("07:01");
		  ponto0.getHorarios().addElement("07:23");
		  ponto0.getHorarios().addElement("07:45");
		  ponto0.getHorarios().addElement("08:07");
		  ponto0.getHorarios().addElement("08:54");
		  ponto0.getHorarios().addElement("09:39");
		  ponto0.getHorarios().addElement("10:24");
		  ponto0.getHorarios().addElement("11:08");
		  ponto0.getHorarios().addElement("11:52");
		  ponto0.getHorarios().addElement("12:36");
		  ponto0.getHorarios().addElement("13:20");
		  ponto0.getHorarios().addElement("14:04");
		  ponto0.getHorarios().addElement("14:48");
		  ponto0.getHorarios().addElement("15:32");
		  ponto0.getHorarios().addElement("16:16");
		  ponto0.getHorarios().addElement("17:00");
		  ponto0.getHorarios().addElement("17:24");
		  ponto0.getHorarios().addElement("17:46");
		  ponto0.getHorarios().addElement("18:08");
		  ponto0.getHorarios().addElement("18:30");
		  ponto0.getHorarios().addElement("18:52");
		  ponto0.getHorarios().addElement("19:14");
		  ponto0.getHorarios().addElement("19:36");
		  ponto0.getHorarios().addElement("20:20");
		  ponto0.getHorarios().addElement("21:00");
		  ponto0.getHorarios().addElement("21:40");
		  ponto0.getHorarios().addElement("22:20");
		  ponto0.getHorarios().addElement("23:00");
		  ponto0.getHorarios().addElement("23:40");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL SANTA FELICIDADE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("08/11/2010");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:33");
		  ponto1.getHorarios().addElement("05:57");
		  ponto1.getHorarios().addElement("06:17");
		  ponto1.getHorarios().addElement("06:39");
		  ponto1.getHorarios().addElement("07:01");
		  ponto1.getHorarios().addElement("07:23");
		  ponto1.getHorarios().addElement("07:45");
		  ponto1.getHorarios().addElement("08:29");
		  ponto1.getHorarios().addElement("09:20");
		  ponto1.getHorarios().addElement("10:02");
		  ponto1.getHorarios().addElement("10:46");
		  ponto1.getHorarios().addElement("11:30");
		  ponto1.getHorarios().addElement("12:14");
		  ponto1.getHorarios().addElement("12:58");
		  ponto1.getHorarios().addElement("13:42");
		  ponto1.getHorarios().addElement("14:26");
		  ponto1.getHorarios().addElement("15:10");
		  ponto1.getHorarios().addElement("15:54");
		  ponto1.getHorarios().addElement("16:38");
		  ponto1.getHorarios().addElement("17:00");
		  ponto1.getHorarios().addElement("17:22");
		  ponto1.getHorarios().addElement("17:44");
		  ponto1.getHorarios().addElement("18:06");
		  ponto1.getHorarios().addElement("18:28");
		  ponto1.getHorarios().addElement("18:50");
		  ponto1.getHorarios().addElement("19:12");
		  ponto1.getHorarios().addElement("19:34");
		  ponto1.getHorarios().addElement("20:00");
		  ponto1.getHorarios().addElement("20:40");
		  ponto1.getHorarios().addElement("21:20");
		  ponto1.getHorarios().addElement("22:00");
		  ponto1.getHorarios().addElement("22:40");
		  ponto1.getHorarios().addElement("23:20");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO PASSAUNA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("13/11/2010");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:15");
		  ponto2.getHorarios().addElement("05:55");
		  ponto2.getHorarios().addElement("06:35");
		  ponto2.getHorarios().addElement("07:15");
		  ponto2.getHorarios().addElement("07:55");
		  ponto2.getHorarios().addElement("08:35");
		  ponto2.getHorarios().addElement("09:15");
		  ponto2.getHorarios().addElement("09:55");
		  ponto2.getHorarios().addElement("10:35");
		  ponto2.getHorarios().addElement("11:15");
		  ponto2.getHorarios().addElement("11:55");
		  ponto2.getHorarios().addElement("12:35");
		  ponto2.getHorarios().addElement("13:15");
		  ponto2.getHorarios().addElement("13:55");
		  ponto2.getHorarios().addElement("14:35");
		  ponto2.getHorarios().addElement("15:15");
		  ponto2.getHorarios().addElement("15:55");
		  ponto2.getHorarios().addElement("16:35");
		  ponto2.getHorarios().addElement("17:15");
		  ponto2.getHorarios().addElement("17:55");
		  ponto2.getHorarios().addElement("18:35");
		  ponto2.getHorarios().addElement("19:15");
		  ponto2.getHorarios().addElement("19:55");
		  ponto2.getHorarios().addElement("20:35");
		  ponto2.getHorarios().addElement("21:15");
		  ponto2.getHorarios().addElement("21:55");
		  ponto2.getHorarios().addElement("22:35");
		  ponto2.getHorarios().addElement("23:15");
		  ponto2.getHorarios().addElement("23:55");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL SANTA FELICIDADE");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("13/11/2010");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:35");
		  ponto3.getHorarios().addElement("06:15");
		  ponto3.getHorarios().addElement("06:55");
		  ponto3.getHorarios().addElement("07:35");
		  ponto3.getHorarios().addElement("08:15");
		  ponto3.getHorarios().addElement("08:55");
		  ponto3.getHorarios().addElement("09:35");
		  ponto3.getHorarios().addElement("10:15");
		  ponto3.getHorarios().addElement("10:55");
		  ponto3.getHorarios().addElement("11:35");
		  ponto3.getHorarios().addElement("12:15");
		  ponto3.getHorarios().addElement("12:55");
		  ponto3.getHorarios().addElement("13:35");
		  ponto3.getHorarios().addElement("14:15");
		  ponto3.getHorarios().addElement("14:55");
		  ponto3.getHorarios().addElement("15:35");
		  ponto3.getHorarios().addElement("16:15");
		  ponto3.getHorarios().addElement("16:55");
		  ponto3.getHorarios().addElement("17:35");
		  ponto3.getHorarios().addElement("18:15");
		  ponto3.getHorarios().addElement("18:55");
		  ponto3.getHorarios().addElement("19:35");
		  ponto3.getHorarios().addElement("20:15");
		  ponto3.getHorarios().addElement("20:55");
		  ponto3.getHorarios().addElement("21:35");
		  ponto3.getHorarios().addElement("22:15");
		  ponto3.getHorarios().addElement("22:55");
		  ponto3.getHorarios().addElement("23:35");
		  ponto3.getHorarios().addElement("00:15");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO PASSAUNA");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("07/11/2010");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("05:15");
		  ponto4.getHorarios().addElement("05:55");
		  ponto4.getHorarios().addElement("06:35");
		  ponto4.getHorarios().addElement("07:15");
		  ponto4.getHorarios().addElement("07:55");
		  ponto4.getHorarios().addElement("08:35");
		  ponto4.getHorarios().addElement("09:15");
		  ponto4.getHorarios().addElement("09:55");
		  ponto4.getHorarios().addElement("10:35");
		  ponto4.getHorarios().addElement("11:15");
		  ponto4.getHorarios().addElement("11:55");
		  ponto4.getHorarios().addElement("12:35");
		  ponto4.getHorarios().addElement("13:15");
		  ponto4.getHorarios().addElement("13:55");
		  ponto4.getHorarios().addElement("14:35");
		  ponto4.getHorarios().addElement("15:15");
		  ponto4.getHorarios().addElement("15:55");
		  ponto4.getHorarios().addElement("16:35");
		  ponto4.getHorarios().addElement("17:15");
		  ponto4.getHorarios().addElement("17:55");
		  ponto4.getHorarios().addElement("18:35");
		  ponto4.getHorarios().addElement("19:15");
		  ponto4.getHorarios().addElement("19:55");
		  ponto4.getHorarios().addElement("20:35");
		  ponto4.getHorarios().addElement("21:15");
		  ponto4.getHorarios().addElement("21:55");
		  ponto4.getHorarios().addElement("22:35");
		  ponto4.getHorarios().addElement("23:15");
		  ponto4.getHorarios().addElement("23:55");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL SANTA FELICIDADE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("07/11/2010");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:35");
		  ponto5.getHorarios().addElement("06:15");
		  ponto5.getHorarios().addElement("06:55");
		  ponto5.getHorarios().addElement("07:35");
		  ponto5.getHorarios().addElement("08:15");
		  ponto5.getHorarios().addElement("08:55");
		  ponto5.getHorarios().addElement("09:35");
		  ponto5.getHorarios().addElement("10:15");
		  ponto5.getHorarios().addElement("10:55");
		  ponto5.getHorarios().addElement("11:35");
		  ponto5.getHorarios().addElement("12:15");
		  ponto5.getHorarios().addElement("12:55");
		  ponto5.getHorarios().addElement("13:35");
		  ponto5.getHorarios().addElement("14:15");
		  ponto5.getHorarios().addElement("14:55");
		  ponto5.getHorarios().addElement("15:35");
		  ponto5.getHorarios().addElement("16:15");
		  ponto5.getHorarios().addElement("16:55");
		  ponto5.getHorarios().addElement("17:35");
		  ponto5.getHorarios().addElement("18:15");
		  ponto5.getHorarios().addElement("18:55");
		  ponto5.getHorarios().addElement("19:35");
		  ponto5.getHorarios().addElement("20:15");
		  ponto5.getHorarios().addElement("20:55");
		  ponto5.getHorarios().addElement("21:35");
		  ponto5.getHorarios().addElement("22:15");
		  ponto5.getHorarios().addElement("22:55");
		  ponto5.getHorarios().addElement("23:35");
		  ponto5.getHorarios().addElement("00:15");
		  return onibus;
		  }
	  }