
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusB29 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("ROÇA GRANDE /  APDEC");
		onibus.setCodigo("B29");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("APAE/MARACANA");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("23/11/2009");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:30");
		ponto0.getHorarios().addElement("08:30");
		ponto0.getHorarios().addElement("10:30");
		ponto0.getHorarios().addElement("12:30");
		ponto0.getHorarios().addElement("14:30");
		ponto0.getHorarios().addElement("16:30");
		ponto0.getHorarios().addElement("18:30");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("APAE/ROCA GRAND");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("23/11/2009");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("09:30");
		ponto1.getHorarios().addElement("11:30");
		ponto1.getHorarios().addElement("13:30");
		ponto1.getHorarios().addElement("15:30");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("19:25");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("APDEC/MARACANA");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("23/11/2009");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("07:00");
		ponto2.getHorarios().addElement("09:00");
		ponto2.getHorarios().addElement("11:00");
		ponto2.getHorarios().addElement("13:00");
		ponto2.getHorarios().addElement("15:00");
		ponto2.getHorarios().addElement("17:00");
		ponto2.getHorarios().addElement("19:00");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL MARACANA/APAE");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("23/11/2009");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("07:18");
		ponto3.getHorarios().addElement("09:18");
		ponto3.getHorarios().addElement("11:18");
		ponto3.getHorarios().addElement("13:18");
		ponto3.getHorarios().addElement("15:18");
		ponto3.getHorarios().addElement("17:18");
		ponto3.getHorarios().addElement("19:18");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL MARACANA/APDEC");
		ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto4.setValidoAPartirDe("23/11/2009");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:42");
		ponto4.getHorarios().addElement("08:42");
		ponto4.getHorarios().addElement("10:42");
		ponto4.getHorarios().addElement("12:42");
		ponto4.getHorarios().addElement("14:42");
		ponto4.getHorarios().addElement("16:42");
		ponto4.getHorarios().addElement("18:42");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL ROCA GRANDE");
		ponto5.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto5.setValidoAPartirDe("23/11/2009");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:00");
		ponto5.getHorarios().addElement("08:00");
		ponto5.getHorarios().addElement("10:00");
		ponto5.getHorarios().addElement("12:00");
		ponto5.getHorarios().addElement("14:00");
		ponto5.getHorarios().addElement("16:00");
		ponto5.getHorarios().addElement("18:00");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("APAE/MARACANA");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("21/11/2009");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:30");
		ponto6.getHorarios().addElement("08:30");
		ponto6.getHorarios().addElement("10:30");
		ponto6.getHorarios().addElement("12:30");
		ponto6.getHorarios().addElement("14:30");
		ponto6.getHorarios().addElement("16:30");
		ponto6.getHorarios().addElement("18:30");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("APAE/ROCA GRAND");
		ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto7.setValidoAPartirDe("21/11/2009");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("07:30");
		ponto7.getHorarios().addElement("09:30");
		ponto7.getHorarios().addElement("11:30");
		ponto7.getHorarios().addElement("13:30");
		ponto7.getHorarios().addElement("15:30");
		ponto7.getHorarios().addElement("17:30");
		ponto7.getHorarios().addElement("19:25");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("APDEC/MARACANA");
		ponto8.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto8.setValidoAPartirDe("21/11/2009");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("07:00");
		ponto8.getHorarios().addElement("09:00");
		ponto8.getHorarios().addElement("11:00");
		ponto8.getHorarios().addElement("13:00");
		ponto8.getHorarios().addElement("15:00");
		ponto8.getHorarios().addElement("17:00");
		ponto8.getHorarios().addElement("19:00");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("TERMINAL MARACANA/APAE");
		ponto9.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto9.setValidoAPartirDe("21/11/2009");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("07:18");
		ponto9.getHorarios().addElement("09:18");
		ponto9.getHorarios().addElement("11:18");
		ponto9.getHorarios().addElement("13:18");
		ponto9.getHorarios().addElement("15:18");
		ponto9.getHorarios().addElement("17:18");
		ponto9.getHorarios().addElement("19:18");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("TERMINAL MARACANA/APDEC");
		ponto10.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto10.setValidoAPartirDe("21/11/2009");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("06:42");
		ponto10.getHorarios().addElement("08:42");
		ponto10.getHorarios().addElement("10:42");
		ponto10.getHorarios().addElement("12:42");
		ponto10.getHorarios().addElement("14:42");
		ponto10.getHorarios().addElement("16:42");
		ponto10.getHorarios().addElement("18:42");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("TERMINAL ROCA GRANDE");
		ponto11.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto11.setValidoAPartirDe("21/11/2009");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("06:00");
		ponto11.getHorarios().addElement("08:00");
		ponto11.getHorarios().addElement("10:00");
		ponto11.getHorarios().addElement("12:00");
		ponto11.getHorarios().addElement("14:00");
		ponto11.getHorarios().addElement("16:00");
		ponto11.getHorarios().addElement("18:00");
		Ponto ponto12 = new Ponto();
		ponto12.setNome("APAE/MARACANA");
		ponto12.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto12.setValidoAPartirDe("22/11/2009");
		onibus.getPontos().addElement(ponto12);
		ponto12.getHorarios().addElement("06:30");
		ponto12.getHorarios().addElement("08:30");
		ponto12.getHorarios().addElement("10:30");
		ponto12.getHorarios().addElement("12:30");
		ponto12.getHorarios().addElement("14:30");
		ponto12.getHorarios().addElement("16:30");
		ponto12.getHorarios().addElement("18:30");
		Ponto ponto13 = new Ponto();
		ponto13.setNome("APAE/ROCA GRAND");
		ponto13.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto13.setValidoAPartirDe("22/11/2009");
		onibus.getPontos().addElement(ponto13);
		ponto13.getHorarios().addElement("07:30");
		ponto13.getHorarios().addElement("09:30");
		ponto13.getHorarios().addElement("11:30");
		ponto13.getHorarios().addElement("13:30");
		ponto13.getHorarios().addElement("15:30");
		ponto13.getHorarios().addElement("17:30");
		ponto13.getHorarios().addElement("19:25");
		Ponto ponto14 = new Ponto();
		ponto14.setNome("APDEC/MARACANA");
		ponto14.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto14.setValidoAPartirDe("22/11/2009");
		onibus.getPontos().addElement(ponto14);
		ponto14.getHorarios().addElement("07:00");
		ponto14.getHorarios().addElement("09:00");
		ponto14.getHorarios().addElement("11:00");
		ponto14.getHorarios().addElement("13:00");
		ponto14.getHorarios().addElement("15:00");
		ponto14.getHorarios().addElement("17:00");
		ponto14.getHorarios().addElement("19:00");
		Ponto ponto15 = new Ponto();
		ponto15.setNome("TERMINAL MARACANA/APAE");
		ponto15.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto15.setValidoAPartirDe("22/11/2009");
		onibus.getPontos().addElement(ponto15);
		ponto15.getHorarios().addElement("07:18");
		ponto15.getHorarios().addElement("09:18");
		ponto15.getHorarios().addElement("11:18");
		ponto15.getHorarios().addElement("13:18");
		ponto15.getHorarios().addElement("15:18");
		ponto15.getHorarios().addElement("17:18");
		ponto15.getHorarios().addElement("19:18");
		Ponto ponto16 = new Ponto();
		ponto16.setNome("TERMINAL MARACANA/APDEC");
		ponto16.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto16.setValidoAPartirDe("22/11/2009");
		onibus.getPontos().addElement(ponto16);
		ponto16.getHorarios().addElement("06:42");
		ponto16.getHorarios().addElement("08:42");
		ponto16.getHorarios().addElement("10:42");
		ponto16.getHorarios().addElement("12:42");
		ponto16.getHorarios().addElement("14:42");
		ponto16.getHorarios().addElement("16:42");
		ponto16.getHorarios().addElement("18:42");
		Ponto ponto17 = new Ponto();
		ponto17.setNome("TERMINAL ROCA GRANDE");
		ponto17.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto17.setValidoAPartirDe("22/11/2009");
		onibus.getPontos().addElement(ponto17);
		ponto17.getHorarios().addElement("06:00");
		ponto17.getHorarios().addElement("08:00");
		ponto17.getHorarios().addElement("10:00");
		ponto17.getHorarios().addElement("12:00");
		ponto17.getHorarios().addElement("14:00");
		ponto17.getHorarios().addElement("16:00");
		ponto17.getHorarios().addElement("18:00");
		return onibus;
		}
	}