
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class Onibus644 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("PINHEIRINHO / CIC");
		onibus.setCodigo("644");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("TERMINAL CIC");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("11/05/2009");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:50");
		ponto0.getHorarios().addElement("06:30");
		ponto0.getHorarios().addElement("07:10");
		ponto0.getHorarios().addElement("07:50");
		ponto0.getHorarios().addElement("08:30");
		ponto0.getHorarios().addElement("09:10");
		ponto0.getHorarios().addElement("09:50");
		ponto0.getHorarios().addElement("10:30");
		ponto0.getHorarios().addElement("11:10");
		ponto0.getHorarios().addElement("11:50");
		ponto0.getHorarios().addElement("12:30");
		ponto0.getHorarios().addElement("13:10");
		ponto0.getHorarios().addElement("13:50");
		ponto0.getHorarios().addElement("14:30");
		ponto0.getHorarios().addElement("15:10");
		ponto0.getHorarios().addElement("15:50");
		ponto0.getHorarios().addElement("16:30");
		ponto0.getHorarios().addElement("17:10");
		ponto0.getHorarios().addElement("17:50");
		ponto0.getHorarios().addElement("18:30");
		ponto0.getHorarios().addElement("19:10");
		ponto0.getHorarios().addElement("19:55");
		ponto0.getHorarios().addElement("20:50");
		ponto0.getHorarios().addElement("21:45");
		ponto0.getHorarios().addElement("22:35");
		ponto0.getHorarios().addElement("23:30");
		ponto0.getHorarios().addElement("00:10");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL PINHEIRINHO");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("11/05/2009");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:30");
		ponto1.getHorarios().addElement("06:10");
		ponto1.getHorarios().addElement("06:50");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("08:10");
		ponto1.getHorarios().addElement("08:50");
		ponto1.getHorarios().addElement("09:30");
		ponto1.getHorarios().addElement("10:10");
		ponto1.getHorarios().addElement("10:50");
		ponto1.getHorarios().addElement("11:30");
		ponto1.getHorarios().addElement("12:10");
		ponto1.getHorarios().addElement("12:50");
		ponto1.getHorarios().addElement("13:30");
		ponto1.getHorarios().addElement("14:10");
		ponto1.getHorarios().addElement("14:50");
		ponto1.getHorarios().addElement("15:30");
		ponto1.getHorarios().addElement("16:10");
		ponto1.getHorarios().addElement("16:50");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("18:10");
		ponto1.getHorarios().addElement("18:50");
		ponto1.getHorarios().addElement("19:30");
		ponto1.getHorarios().addElement("20:20");
		ponto1.getHorarios().addElement("21:20");
		ponto1.getHorarios().addElement("22:10");
		ponto1.getHorarios().addElement("23:00");
		ponto1.getHorarios().addElement("23:50");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL CIC");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("09/05/2009");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:50");
		ponto2.getHorarios().addElement("06:30");
		ponto2.getHorarios().addElement("07:10");
		ponto2.getHorarios().addElement("07:50");
		ponto2.getHorarios().addElement("08:30");
		ponto2.getHorarios().addElement("09:10");
		ponto2.getHorarios().addElement("09:50");
		ponto2.getHorarios().addElement("10:30");
		ponto2.getHorarios().addElement("11:10");
		ponto2.getHorarios().addElement("11:50");
		ponto2.getHorarios().addElement("12:30");
		ponto2.getHorarios().addElement("13:10");
		ponto2.getHorarios().addElement("13:50");
		ponto2.getHorarios().addElement("14:40");
		ponto2.getHorarios().addElement("15:30");
		ponto2.getHorarios().addElement("16:20");
		ponto2.getHorarios().addElement("17:10");
		ponto2.getHorarios().addElement("18:00");
		ponto2.getHorarios().addElement("18:50");
		ponto2.getHorarios().addElement("19:40");
		ponto2.getHorarios().addElement("20:30");
		ponto2.getHorarios().addElement("21:20");
		ponto2.getHorarios().addElement("22:10");
		ponto2.getHorarios().addElement("23:00");
		ponto2.getHorarios().addElement("23:40");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL PINHEIRINHO");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("09/05/2009");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:30");
		ponto3.getHorarios().addElement("06:10");
		ponto3.getHorarios().addElement("06:50");
		ponto3.getHorarios().addElement("07:30");
		ponto3.getHorarios().addElement("08:10");
		ponto3.getHorarios().addElement("08:50");
		ponto3.getHorarios().addElement("09:30");
		ponto3.getHorarios().addElement("10:10");
		ponto3.getHorarios().addElement("10:50");
		ponto3.getHorarios().addElement("11:30");
		ponto3.getHorarios().addElement("12:10");
		ponto3.getHorarios().addElement("12:50");
		ponto3.getHorarios().addElement("13:30");
		ponto3.getHorarios().addElement("14:15");
		ponto3.getHorarios().addElement("15:05");
		ponto3.getHorarios().addElement("15:55");
		ponto3.getHorarios().addElement("16:45");
		ponto3.getHorarios().addElement("17:35");
		ponto3.getHorarios().addElement("18:25");
		ponto3.getHorarios().addElement("19:15");
		ponto3.getHorarios().addElement("20:05");
		ponto3.getHorarios().addElement("20:55");
		ponto3.getHorarios().addElement("21:45");
		ponto3.getHorarios().addElement("22:35");
		ponto3.getHorarios().addElement("23:20");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL CIC");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("03/04/2011");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:00");
		ponto4.getHorarios().addElement("07:00");
		ponto4.getHorarios().addElement("07:50");
		ponto4.getHorarios().addElement("17:00");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL PINHEIRINHO");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("03/04/2011");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:30");
		ponto5.getHorarios().addElement("06:30");
		ponto5.getHorarios().addElement("07:30");
		ponto5.getHorarios().addElement("17:20");
		return onibus;
		}
	}