
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class Onibus181 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("181 - MATEUS LEME");
		onibus.setCodigo("181");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO MATEUS LEME");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("11/07/2008");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:20");
		ponto0.getHorarios().addElement("09:22");
		ponto0.getHorarios().addElement("10:26");
		ponto0.getHorarios().addElement("11:30");
		ponto0.getHorarios().addElement("14:50");
		ponto0.getHorarios().addElement("15:54");
		ponto0.getHorarios().addElement("20:45");
		ponto0.getHorarios().addElement("22:05");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("PRACA TIRADENTES");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("11/07/2008");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:50");
		ponto1.getHorarios().addElement("06:50");
		ponto1.getHorarios().addElement("07:50");
		ponto1.getHorarios().addElement("08:50");
		ponto1.getHorarios().addElement("09:54");
		ponto1.getHorarios().addElement("10:58");
		ponto1.getHorarios().addElement("12:02");
		ponto1.getHorarios().addElement("13:10");
		ponto1.getHorarios().addElement("14:18");
		ponto1.getHorarios().addElement("15:22");
		ponto1.getHorarios().addElement("16:28");
		ponto1.getHorarios().addElement("17:40");
		ponto1.getHorarios().addElement("18:52");
		ponto1.getHorarios().addElement("20:05");
		ponto1.getHorarios().addElement("21:25");
		ponto1.getHorarios().addElement("22:45");
		ponto1.getHorarios().addElement("23:45");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("CAPELA SAO FRANCISCO XAVIER");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("11/07/2008");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:20");
		ponto2.getHorarios().addElement("07:20");
		ponto2.getHorarios().addElement("08:20");
		ponto2.getHorarios().addElement("12:36");
		ponto2.getHorarios().addElement("13:44");
		ponto2.getHorarios().addElement("17:04");
		ponto2.getHorarios().addElement("18:16");
		ponto2.getHorarios().addElement("19:28");
		ponto2.getHorarios().addElement("23:15");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("BAIRRO MATEUS LEME");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("13/10/2007");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:25");
		ponto3.getHorarios().addElement("06:15");
		ponto3.getHorarios().addElement("07:15");
		ponto3.getHorarios().addElement("08:15");
		ponto3.getHorarios().addElement("09:15");
		ponto3.getHorarios().addElement("10:15");
		ponto3.getHorarios().addElement("11:15");
		ponto3.getHorarios().addElement("12:15");
		ponto3.getHorarios().addElement("13:15");
		ponto3.getHorarios().addElement("14:10");
		ponto3.getHorarios().addElement("15:10");
		ponto3.getHorarios().addElement("16:10");
		ponto3.getHorarios().addElement("17:10");
		ponto3.getHorarios().addElement("18:10");
		ponto3.getHorarios().addElement("19:10");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("PRACA TIRADENTES");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("13/10/2007");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:50");
		ponto4.getHorarios().addElement("06:45");
		ponto4.getHorarios().addElement("07:45");
		ponto4.getHorarios().addElement("08:45");
		ponto4.getHorarios().addElement("09:45");
		ponto4.getHorarios().addElement("10:45");
		ponto4.getHorarios().addElement("11:45");
		ponto4.getHorarios().addElement("12:45");
		ponto4.getHorarios().addElement("13:40");
		ponto4.getHorarios().addElement("14:40");
		ponto4.getHorarios().addElement("15:40");
		ponto4.getHorarios().addElement("16:40");
		ponto4.getHorarios().addElement("17:40");
		ponto4.getHorarios().addElement("18:40");
		ponto4.getHorarios().addElement("19:40");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("BAIRRO MATEUS LEME");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("23/09/2012");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:40");
		ponto5.getHorarios().addElement("06:40");
		ponto5.getHorarios().addElement("07:40");
		ponto5.getHorarios().addElement("08:40");
		ponto5.getHorarios().addElement("09:40");
		ponto5.getHorarios().addElement("10:40");
		ponto5.getHorarios().addElement("11:40");
		ponto5.getHorarios().addElement("12:40");
		ponto5.getHorarios().addElement("13:40");
		ponto5.getHorarios().addElement("14:40");
		ponto5.getHorarios().addElement("15:40");
		ponto5.getHorarios().addElement("16:40");
		ponto5.getHorarios().addElement("17:40");
		ponto5.getHorarios().addElement("18:40");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("PRACA TIRADENTES");
		ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto6.setValidoAPartirDe("23/09/2012");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:10");
		ponto6.getHorarios().addElement("07:10");
		ponto6.getHorarios().addElement("08:10");
		ponto6.getHorarios().addElement("09:10");
		ponto6.getHorarios().addElement("10:10");
		ponto6.getHorarios().addElement("11:10");
		ponto6.getHorarios().addElement("12:10");
		ponto6.getHorarios().addElement("13:10");
		ponto6.getHorarios().addElement("14:10");
		ponto6.getHorarios().addElement("15:10");
		ponto6.getHorarios().addElement("16:10");
		ponto6.getHorarios().addElement("17:10");
		ponto6.getHorarios().addElement("18:10");
		ponto6.getHorarios().addElement("19:10");
		return onibus;
		}
	}