
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus182 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("182 - ABRANCHES");
		  onibus.setCodigo("182");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("PARQUE SAO LOURENCO");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("27/06/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("PRACA TIRADENTES");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("27/06/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:55");
		  ponto1.getHorarios().addElement("06:12");
		  ponto1.getHorarios().addElement("06:29");
		  ponto1.getHorarios().addElement("06:46");
		  ponto1.getHorarios().addElement("07:03");
		  ponto1.getHorarios().addElement("07:20");
		  ponto1.getHorarios().addElement("07:36");
		  ponto1.getHorarios().addElement("07:52");
		  ponto1.getHorarios().addElement("08:08");
		  ponto1.getHorarios().addElement("08:40");
		  ponto1.getHorarios().addElement("09:16");
		  ponto1.getHorarios().addElement("09:52");
		  ponto1.getHorarios().addElement("10:27");
		  ponto1.getHorarios().addElement("11:03");
		  ponto1.getHorarios().addElement("11:38");
		  ponto1.getHorarios().addElement("12:02");
		  ponto1.getHorarios().addElement("12:26");
		  ponto1.getHorarios().addElement("12:50");
		  ponto1.getHorarios().addElement("13:15");
		  ponto1.getHorarios().addElement("13:39");
		  ponto1.getHorarios().addElement("14:03");
		  ponto1.getHorarios().addElement("14:26");
		  ponto1.getHorarios().addElement("15:01");
		  ponto1.getHorarios().addElement("15:36");
		  ponto1.getHorarios().addElement("16:13");
		  ponto1.getHorarios().addElement("16:31");
		  ponto1.getHorarios().addElement("16:50");
		  ponto1.getHorarios().addElement("17:09");
		  ponto1.getHorarios().addElement("17:28");
		  ponto1.getHorarios().addElement("17:47");
		  ponto1.getHorarios().addElement("18:06");
		  ponto1.getHorarios().addElement("18:25");
		  ponto1.getHorarios().addElement("18:44");
		  ponto1.getHorarios().addElement("19:03");
		  ponto1.getHorarios().addElement("19:22");
		  ponto1.getHorarios().addElement("19:42");
		  ponto1.getHorarios().addElement("20:05");
		  ponto1.getHorarios().addElement("20:41");
		  ponto1.getHorarios().addElement("21:17");
		  ponto1.getHorarios().addElement("21:53");
		  ponto1.getHorarios().addElement("22:29");
		  ponto1.getHorarios().addElement("23:05");
		  ponto1.getHorarios().addElement("23:40");
		  ponto1.getHorarios().addElement("00:15");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL BARREIRINHA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("27/06/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:20");
		  ponto2.getHorarios().addElement("05:37");
		  ponto2.getHorarios().addElement("05:54");
		  ponto2.getHorarios().addElement("06:11");
		  ponto2.getHorarios().addElement("06:28");
		  ponto2.getHorarios().addElement("06:45");
		  ponto2.getHorarios().addElement("07:01");
		  ponto2.getHorarios().addElement("07:17");
		  ponto2.getHorarios().addElement("07:33");
		  ponto2.getHorarios().addElement("07:50");
		  ponto2.getHorarios().addElement("08:06");
		  ponto2.getHorarios().addElement("08:23");
		  ponto2.getHorarios().addElement("08:40");
		  ponto2.getHorarios().addElement("09:16");
		  ponto2.getHorarios().addElement("09:52");
		  ponto2.getHorarios().addElement("10:28");
		  ponto2.getHorarios().addElement("11:03");
		  ponto2.getHorarios().addElement("11:39");
		  ponto2.getHorarios().addElement("12:14");
		  ponto2.getHorarios().addElement("12:38");
		  ponto2.getHorarios().addElement("13:02");
		  ponto2.getHorarios().addElement("13:26");
		  ponto2.getHorarios().addElement("13:50");
		  ponto2.getHorarios().addElement("14:24");
		  ponto2.getHorarios().addElement("15:00");
		  ponto2.getHorarios().addElement("15:37");
		  ponto2.getHorarios().addElement("16:13");
		  ponto2.getHorarios().addElement("16:50");
		  ponto2.getHorarios().addElement("17:11");
		  ponto2.getHorarios().addElement("17:30");
		  ponto2.getHorarios().addElement("17:49");
		  ponto2.getHorarios().addElement("18:08");
		  ponto2.getHorarios().addElement("18:27");
		  ponto2.getHorarios().addElement("18:46");
		  ponto2.getHorarios().addElement("19:05");
		  ponto2.getHorarios().addElement("19:30");
		  ponto2.getHorarios().addElement("20:06");
		  ponto2.getHorarios().addElement("20:42");
		  ponto2.getHorarios().addElement("21:18");
		  ponto2.getHorarios().addElement("21:54");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("23:05");
		  ponto2.getHorarios().addElement("23:40");
		  ponto2.getHorarios().addElement("00:15");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("PRACA TIRADENTES");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("05/05/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:57");
		  ponto3.getHorarios().addElement("06:32");
		  ponto3.getHorarios().addElement("07:07");
		  ponto3.getHorarios().addElement("07:42");
		  ponto3.getHorarios().addElement("08:17");
		  ponto3.getHorarios().addElement("08:52");
		  ponto3.getHorarios().addElement("09:31");
		  ponto3.getHorarios().addElement("10:08");
		  ponto3.getHorarios().addElement("10:45");
		  ponto3.getHorarios().addElement("11:22");
		  ponto3.getHorarios().addElement("11:59");
		  ponto3.getHorarios().addElement("12:36");
		  ponto3.getHorarios().addElement("13:13");
		  ponto3.getHorarios().addElement("13:50");
		  ponto3.getHorarios().addElement("14:27");
		  ponto3.getHorarios().addElement("15:04");
		  ponto3.getHorarios().addElement("15:41");
		  ponto3.getHorarios().addElement("16:18");
		  ponto3.getHorarios().addElement("16:55");
		  ponto3.getHorarios().addElement("17:32");
		  ponto3.getHorarios().addElement("18:09");
		  ponto3.getHorarios().addElement("18:46");
		  ponto3.getHorarios().addElement("19:23");
		  ponto3.getHorarios().addElement("20:37");
		  ponto3.getHorarios().addElement("21:50");
		  ponto3.getHorarios().addElement("23:00");
		  ponto3.getHorarios().addElement("00:15");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TERMINAL BARREIRINHA");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("05/05/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("05:20");
		  ponto4.getHorarios().addElement("05:55");
		  ponto4.getHorarios().addElement("06:30");
		  ponto4.getHorarios().addElement("07:05");
		  ponto4.getHorarios().addElement("07:40");
		  ponto4.getHorarios().addElement("08:15");
		  ponto4.getHorarios().addElement("08:54");
		  ponto4.getHorarios().addElement("09:31");
		  ponto4.getHorarios().addElement("10:08");
		  ponto4.getHorarios().addElement("10:45");
		  ponto4.getHorarios().addElement("11:22");
		  ponto4.getHorarios().addElement("11:59");
		  ponto4.getHorarios().addElement("12:36");
		  ponto4.getHorarios().addElement("13:13");
		  ponto4.getHorarios().addElement("13:50");
		  ponto4.getHorarios().addElement("14:27");
		  ponto4.getHorarios().addElement("15:04");
		  ponto4.getHorarios().addElement("15:41");
		  ponto4.getHorarios().addElement("16:18");
		  ponto4.getHorarios().addElement("16:55");
		  ponto4.getHorarios().addElement("17:32");
		  ponto4.getHorarios().addElement("18:09");
		  ponto4.getHorarios().addElement("18:46");
		  ponto4.getHorarios().addElement("20:00");
		  ponto4.getHorarios().addElement("21:15");
		  ponto4.getHorarios().addElement("22:25");
		  ponto4.getHorarios().addElement("23:35");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("PRACA TIRADENTES");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("06/05/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:57");
		  ponto5.getHorarios().addElement("06:32");
		  ponto5.getHorarios().addElement("07:07");
		  ponto5.getHorarios().addElement("07:42");
		  ponto5.getHorarios().addElement("08:17");
		  ponto5.getHorarios().addElement("08:52");
		  ponto5.getHorarios().addElement("09:31");
		  ponto5.getHorarios().addElement("10:08");
		  ponto5.getHorarios().addElement("10:45");
		  ponto5.getHorarios().addElement("11:22");
		  ponto5.getHorarios().addElement("11:59");
		  ponto5.getHorarios().addElement("12:36");
		  ponto5.getHorarios().addElement("13:13");
		  ponto5.getHorarios().addElement("13:50");
		  ponto5.getHorarios().addElement("14:27");
		  ponto5.getHorarios().addElement("15:04");
		  ponto5.getHorarios().addElement("15:41");
		  ponto5.getHorarios().addElement("16:18");
		  ponto5.getHorarios().addElement("16:55");
		  ponto5.getHorarios().addElement("17:32");
		  ponto5.getHorarios().addElement("18:09");
		  ponto5.getHorarios().addElement("18:46");
		  ponto5.getHorarios().addElement("19:23");
		  ponto5.getHorarios().addElement("20:37");
		  ponto5.getHorarios().addElement("21:50");
		  ponto5.getHorarios().addElement("23:00");
		  ponto5.getHorarios().addElement("00:20");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("TERMINAL BARREIRINHA");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("06/05/2012");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("05:20");
		  ponto6.getHorarios().addElement("05:55");
		  ponto6.getHorarios().addElement("06:30");
		  ponto6.getHorarios().addElement("07:05");
		  ponto6.getHorarios().addElement("07:40");
		  ponto6.getHorarios().addElement("08:15");
		  ponto6.getHorarios().addElement("08:54");
		  ponto6.getHorarios().addElement("09:31");
		  ponto6.getHorarios().addElement("10:08");
		  ponto6.getHorarios().addElement("10:45");
		  ponto6.getHorarios().addElement("11:22");
		  ponto6.getHorarios().addElement("11:59");
		  ponto6.getHorarios().addElement("12:36");
		  ponto6.getHorarios().addElement("13:13");
		  ponto6.getHorarios().addElement("13:50");
		  ponto6.getHorarios().addElement("14:27");
		  ponto6.getHorarios().addElement("15:04");
		  ponto6.getHorarios().addElement("15:41");
		  ponto6.getHorarios().addElement("16:18");
		  ponto6.getHorarios().addElement("16:55");
		  ponto6.getHorarios().addElement("17:32");
		  ponto6.getHorarios().addElement("18:09");
		  ponto6.getHorarios().addElement("18:46");
		  ponto6.getHorarios().addElement("20:00");
		  ponto6.getHorarios().addElement("21:15");
		  ponto6.getHorarios().addElement("22:25");
		  ponto6.getHorarios().addElement("23:40");
		  return onibus;
		  }
	  }