
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class Onibus188 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("MAD. PILARZINHO / UBERABA");
		onibus.setCodigo("188");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO M.PILARZINHO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("02/08/1999");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("01:30");
		ponto0.getHorarios().addElement("02:25");
		ponto0.getHorarios().addElement("03:25");
		ponto0.getHorarios().addElement("04:18");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("BAIRRO M.UBERABA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("02/08/1999");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("01:25");
		ponto1.getHorarios().addElement("02:25");
		ponto1.getHorarios().addElement("03:25");
		ponto1.getHorarios().addElement("04:25");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("NESTOR DE CASTRO/CHEGADA");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("02/08/1999");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("01:00");
		ponto2.getHorarios().addElement("01:50");
		ponto2.getHorarios().addElement("02:50");
		ponto2.getHorarios().addElement("03:50");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("NESTOR DE CASTRO/SAIDA");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("02/08/1999");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("01:10");
		ponto3.getHorarios().addElement("02:00");
		ponto3.getHorarios().addElement("03:00");
		ponto3.getHorarios().addElement("04:00");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("RUI BARBOSA/CHEGADA");
		ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto4.setValidoAPartirDe("02/08/1999");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("00:50");
		ponto4.getHorarios().addElement("01:50");
		ponto4.getHorarios().addElement("02:50");
		ponto4.getHorarios().addElement("03:50");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("RUI BARBOSA/SAIDA");
		ponto5.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto5.setValidoAPartirDe("02/08/1999");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("01:00");
		ponto5.getHorarios().addElement("02:00");
		ponto5.getHorarios().addElement("03:00");
		ponto5.getHorarios().addElement("04:00");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("BAIRRO M.PILARZINHO");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("07/08/1999");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("01:30");
		ponto6.getHorarios().addElement("02:25");
		ponto6.getHorarios().addElement("03:25");
		ponto6.getHorarios().addElement("04:18");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("BAIRRO M.UBERABA");
		ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto7.setValidoAPartirDe("07/08/1999");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("01:25");
		ponto7.getHorarios().addElement("02:25");
		ponto7.getHorarios().addElement("03:25");
		ponto7.getHorarios().addElement("04:25");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("NESTOR DE CASTRO/CHEGADA");
		ponto8.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto8.setValidoAPartirDe("07/08/1999");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("01:00");
		ponto8.getHorarios().addElement("01:50");
		ponto8.getHorarios().addElement("02:50");
		ponto8.getHorarios().addElement("03:50");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("NESTOR DE CASTRO/SAIDA");
		ponto9.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto9.setValidoAPartirDe("07/08/1999");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("01:10");
		ponto9.getHorarios().addElement("02:00");
		ponto9.getHorarios().addElement("03:00");
		ponto9.getHorarios().addElement("04:00");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("RUI BARBOSA/CHEGADA");
		ponto10.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto10.setValidoAPartirDe("07/08/1999");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("00:50");
		ponto10.getHorarios().addElement("01:50");
		ponto10.getHorarios().addElement("02:50");
		ponto10.getHorarios().addElement("03:50");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("RUI BARBOSA/SAIDA");
		ponto11.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto11.setValidoAPartirDe("07/08/1999");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("01:00");
		ponto11.getHorarios().addElement("02:00");
		ponto11.getHorarios().addElement("03:00");
		ponto11.getHorarios().addElement("04:00");
		Ponto ponto12 = new Ponto();
		ponto12.setNome("BAIRRO M.PILARZINHO");
		ponto12.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto12.setValidoAPartirDe("08/08/1999");
		onibus.getPontos().addElement(ponto12);
		ponto12.getHorarios().addElement("01:25");
		ponto12.getHorarios().addElement("02:25");
		ponto12.getHorarios().addElement("03:25");
		ponto12.getHorarios().addElement("04:18");
		Ponto ponto13 = new Ponto();
		ponto13.setNome("BAIRRO M.UBERABA");
		ponto13.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto13.setValidoAPartirDe("08/08/1999");
		onibus.getPontos().addElement(ponto13);
		ponto13.getHorarios().addElement("01:25");
		ponto13.getHorarios().addElement("02:25");
		ponto13.getHorarios().addElement("03:25");
		ponto13.getHorarios().addElement("04:25");
		Ponto ponto14 = new Ponto();
		ponto14.setNome("NESTOR DE CASTRO/CHEGADA");
		ponto14.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto14.setValidoAPartirDe("08/08/1999");
		onibus.getPontos().addElement(ponto14);
		ponto14.getHorarios().addElement("00:50");
		ponto14.getHorarios().addElement("01:50");
		ponto14.getHorarios().addElement("02:50");
		ponto14.getHorarios().addElement("03:50");
		Ponto ponto15 = new Ponto();
		ponto15.setNome("NESTOR DE CASTRO/SAIDA");
		ponto15.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto15.setValidoAPartirDe("08/08/1999");
		onibus.getPontos().addElement(ponto15);
		ponto15.getHorarios().addElement("01:00");
		ponto15.getHorarios().addElement("02:00");
		ponto15.getHorarios().addElement("03:00");
		ponto15.getHorarios().addElement("04:00");
		Ponto ponto16 = new Ponto();
		ponto16.setNome("RUI BARBOSA/CHEGADA");
		ponto16.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto16.setValidoAPartirDe("08/08/1999");
		onibus.getPontos().addElement(ponto16);
		ponto16.getHorarios().addElement("00:50");
		ponto16.getHorarios().addElement("01:50");
		ponto16.getHorarios().addElement("02:50");
		ponto16.getHorarios().addElement("03:50");
		Ponto ponto17 = new Ponto();
		ponto17.setNome("RUI BARBOSA/SAIDA");
		ponto17.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto17.setValidoAPartirDe("08/08/1999");
		onibus.getPontos().addElement(ponto17);
		ponto17.getHorarios().addElement("01:00");
		ponto17.getHorarios().addElement("02:00");
		ponto17.getHorarios().addElement("03:00");
		ponto17.getHorarios().addElement("04:00");
		return onibus;
		}
	}