
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusJ12 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("REBOUÇAS");
		onibus.setCodigo("J12");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO REBOUCAS");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("04/07/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:25");
		ponto0.getHorarios().addElement("06:15");
		ponto0.getHorarios().addElement("07:10");
		ponto0.getHorarios().addElement("08:07");
		ponto0.getHorarios().addElement("09:05");
		ponto0.getHorarios().addElement("10:05");
		ponto0.getHorarios().addElement("11:10");
		ponto0.getHorarios().addElement("12:15");
		ponto0.getHorarios().addElement("13:15");
		ponto0.getHorarios().addElement("14:15");
		ponto0.getHorarios().addElement("15:15");
		ponto0.getHorarios().addElement("16:19");
		ponto0.getHorarios().addElement("17:22");
		ponto0.getHorarios().addElement("18:22");
		ponto0.getHorarios().addElement("19:22");
		ponto0.getHorarios().addElement("20:22");
		ponto0.getHorarios().addElement("21:25");
		ponto0.getHorarios().addElement("22:29");
		ponto0.getHorarios().addElement("23:35");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL CAMPO COMPRIDO");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("04/07/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:50");
		ponto1.getHorarios().addElement("06:43");
		ponto1.getHorarios().addElement("07:40");
		ponto1.getHorarios().addElement("08:35");
		ponto1.getHorarios().addElement("09:35");
		ponto1.getHorarios().addElement("10:35");
		ponto1.getHorarios().addElement("11:45");
		ponto1.getHorarios().addElement("12:45");
		ponto1.getHorarios().addElement("13:45");
		ponto1.getHorarios().addElement("14:45");
		ponto1.getHorarios().addElement("15:45");
		ponto1.getHorarios().addElement("16:51");
		ponto1.getHorarios().addElement("17:51");
		ponto1.getHorarios().addElement("18:51");
		ponto1.getHorarios().addElement("19:51");
		ponto1.getHorarios().addElement("20:54");
		ponto1.getHorarios().addElement("21:58");
		ponto1.getHorarios().addElement("23:00");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERM.C.COMPRIDO VIA STA.ANGELA");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("04/07/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("00:05");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("BAIRRO REBOUCAS");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("06/09/2008");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:00");
		ponto3.getHorarios().addElement("05:55");
		ponto3.getHorarios().addElement("06:50");
		ponto3.getHorarios().addElement("07:45");
		ponto3.getHorarios().addElement("08:40");
		ponto3.getHorarios().addElement("09:40");
		ponto3.getHorarios().addElement("10:40");
		ponto3.getHorarios().addElement("11:40");
		ponto3.getHorarios().addElement("12:40");
		ponto3.getHorarios().addElement("13:40");
		ponto3.getHorarios().addElement("14:40");
		ponto3.getHorarios().addElement("15:40");
		ponto3.getHorarios().addElement("16:40");
		ponto3.getHorarios().addElement("17:40");
		ponto3.getHorarios().addElement("18:40");
		ponto3.getHorarios().addElement("19:40");
		ponto3.getHorarios().addElement("20:40");
		ponto3.getHorarios().addElement("21:40");
		ponto3.getHorarios().addElement("22:40");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL CAMPO COMPRIDO");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("06/09/2008");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:28");
		ponto4.getHorarios().addElement("06:23");
		ponto4.getHorarios().addElement("07:18");
		ponto4.getHorarios().addElement("08:13");
		ponto4.getHorarios().addElement("09:10");
		ponto4.getHorarios().addElement("10:10");
		ponto4.getHorarios().addElement("11:10");
		ponto4.getHorarios().addElement("12:10");
		ponto4.getHorarios().addElement("13:10");
		ponto4.getHorarios().addElement("14:10");
		ponto4.getHorarios().addElement("15:10");
		ponto4.getHorarios().addElement("16:10");
		ponto4.getHorarios().addElement("17:10");
		ponto4.getHorarios().addElement("18:10");
		ponto4.getHorarios().addElement("19:10");
		ponto4.getHorarios().addElement("20:10");
		ponto4.getHorarios().addElement("21:10");
		ponto4.getHorarios().addElement("22:10");
		ponto4.getHorarios().addElement("23:10");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("BAIRRO REBOUCAS");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("07/09/2008");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:45");
		ponto5.getHorarios().addElement("06:45");
		ponto5.getHorarios().addElement("07:45");
		ponto5.getHorarios().addElement("08:45");
		ponto5.getHorarios().addElement("09:45");
		ponto5.getHorarios().addElement("10:45");
		ponto5.getHorarios().addElement("11:45");
		ponto5.getHorarios().addElement("12:45");
		ponto5.getHorarios().addElement("13:45");
		ponto5.getHorarios().addElement("14:45");
		ponto5.getHorarios().addElement("15:45");
		ponto5.getHorarios().addElement("16:45");
		ponto5.getHorarios().addElement("17:45");
		ponto5.getHorarios().addElement("18:45");
		ponto5.getHorarios().addElement("19:45");
		ponto5.getHorarios().addElement("20:45");
		ponto5.getHorarios().addElement("21:45");
		ponto5.getHorarios().addElement("22:45");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL CAMPO COMPRIDO");
		ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto6.setValidoAPartirDe("07/09/2008");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:15");
		ponto6.getHorarios().addElement("07:15");
		ponto6.getHorarios().addElement("08:15");
		ponto6.getHorarios().addElement("09:15");
		ponto6.getHorarios().addElement("10:15");
		ponto6.getHorarios().addElement("11:15");
		ponto6.getHorarios().addElement("12:15");
		ponto6.getHorarios().addElement("13:15");
		ponto6.getHorarios().addElement("14:15");
		ponto6.getHorarios().addElement("15:15");
		ponto6.getHorarios().addElement("16:15");
		ponto6.getHorarios().addElement("17:15");
		ponto6.getHorarios().addElement("18:15");
		ponto6.getHorarios().addElement("19:15");
		ponto6.getHorarios().addElement("20:15");
		ponto6.getHorarios().addElement("21:15");
		ponto6.getHorarios().addElement("22:15");
		ponto6.getHorarios().addElement("23:15");
		return onibus;
		}
	}