
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusJ15 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("J15 - CAMPO LARGO");
		onibus.setCodigo("J15");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("TERMINAL CAMPO COMPRIDO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("25/11/2011");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:30");
		ponto0.getHorarios().addElement("07:32");
		ponto0.getHorarios().addElement("08:30");
		ponto0.getHorarios().addElement("09:30");
		ponto0.getHorarios().addElement("10:30");
		ponto0.getHorarios().addElement("11:30");
		ponto0.getHorarios().addElement("12:30");
		ponto0.getHorarios().addElement("13:30");
		ponto0.getHorarios().addElement("14:30");
		ponto0.getHorarios().addElement("15:30");
		ponto0.getHorarios().addElement("16:30");
		ponto0.getHorarios().addElement("17:31");
		ponto0.getHorarios().addElement("18:29");
		ponto0.getHorarios().addElement("19:30");
		ponto0.getHorarios().addElement("20:30");
		ponto0.getHorarios().addElement("21:30");
		ponto0.getHorarios().addElement("22:30");
		ponto0.getHorarios().addElement("23:30");
		ponto0.getHorarios().addElement("00:35");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TER.CAMPO LARGO(VIA EST.VELHA)");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("25/11/2011");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:30");
		ponto1.getHorarios().addElement("06:30");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("08:31");
		ponto1.getHorarios().addElement("09:30");
		ponto1.getHorarios().addElement("10:30");
		ponto1.getHorarios().addElement("11:30");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:30");
		ponto1.getHorarios().addElement("14:30");
		ponto1.getHorarios().addElement("15:30");
		ponto1.getHorarios().addElement("16:30");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("18:30");
		ponto1.getHorarios().addElement("19:30");
		ponto1.getHorarios().addElement("20:30");
		ponto1.getHorarios().addElement("21:30");
		ponto1.getHorarios().addElement("22:30");
		ponto1.getHorarios().addElement("23:30");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL CAMPO COMPRIDO");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("26/11/2011");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:30");
		ponto2.getHorarios().addElement("07:30");
		ponto2.getHorarios().addElement("08:30");
		ponto2.getHorarios().addElement("09:30");
		ponto2.getHorarios().addElement("10:30");
		ponto2.getHorarios().addElement("11:30");
		ponto2.getHorarios().addElement("12:30");
		ponto2.getHorarios().addElement("13:30");
		ponto2.getHorarios().addElement("14:30");
		ponto2.getHorarios().addElement("15:30");
		ponto2.getHorarios().addElement("16:30");
		ponto2.getHorarios().addElement("17:30");
		ponto2.getHorarios().addElement("18:30");
		ponto2.getHorarios().addElement("19:30");
		ponto2.getHorarios().addElement("20:30");
		ponto2.getHorarios().addElement("21:30");
		ponto2.getHorarios().addElement("22:30");
		ponto2.getHorarios().addElement("23:30");
		ponto2.getHorarios().addElement("00:35");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TER.CAMPO LARGO(VIA EST.VELHA)");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("26/11/2011");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:30");
		ponto3.getHorarios().addElement("06:30");
		ponto3.getHorarios().addElement("07:30");
		ponto3.getHorarios().addElement("08:30");
		ponto3.getHorarios().addElement("09:30");
		ponto3.getHorarios().addElement("10:30");
		ponto3.getHorarios().addElement("11:30");
		ponto3.getHorarios().addElement("12:30");
		ponto3.getHorarios().addElement("13:30");
		ponto3.getHorarios().addElement("14:30");
		ponto3.getHorarios().addElement("15:30");
		ponto3.getHorarios().addElement("16:30");
		ponto3.getHorarios().addElement("17:30");
		ponto3.getHorarios().addElement("18:30");
		ponto3.getHorarios().addElement("19:30");
		ponto3.getHorarios().addElement("20:30");
		ponto3.getHorarios().addElement("21:30");
		ponto3.getHorarios().addElement("22:30");
		ponto3.getHorarios().addElement("23:30");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL CAMPO COMPRIDO");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("27/11/2011");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:30");
		ponto4.getHorarios().addElement("07:30");
		ponto4.getHorarios().addElement("08:30");
		ponto4.getHorarios().addElement("09:30");
		ponto4.getHorarios().addElement("10:30");
		ponto4.getHorarios().addElement("11:30");
		ponto4.getHorarios().addElement("12:30");
		ponto4.getHorarios().addElement("13:30");
		ponto4.getHorarios().addElement("14:30");
		ponto4.getHorarios().addElement("15:30");
		ponto4.getHorarios().addElement("16:30");
		ponto4.getHorarios().addElement("17:30");
		ponto4.getHorarios().addElement("18:30");
		ponto4.getHorarios().addElement("19:30");
		ponto4.getHorarios().addElement("20:30");
		ponto4.getHorarios().addElement("21:30");
		ponto4.getHorarios().addElement("22:30");
		ponto4.getHorarios().addElement("23:30");
		ponto4.getHorarios().addElement("00:35");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TER.CAMPO LARGO(VIA EST.VELHA)");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("27/11/2011");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:30");
		ponto5.getHorarios().addElement("06:30");
		ponto5.getHorarios().addElement("07:30");
		ponto5.getHorarios().addElement("08:30");
		ponto5.getHorarios().addElement("09:30");
		ponto5.getHorarios().addElement("10:30");
		ponto5.getHorarios().addElement("11:30");
		ponto5.getHorarios().addElement("12:30");
		ponto5.getHorarios().addElement("13:30");
		ponto5.getHorarios().addElement("14:30");
		ponto5.getHorarios().addElement("15:30");
		ponto5.getHorarios().addElement("16:30");
		ponto5.getHorarios().addElement("17:30");
		ponto5.getHorarios().addElement("18:30");
		ponto5.getHorarios().addElement("19:30");
		ponto5.getHorarios().addElement("20:30");
		ponto5.getHorarios().addElement("21:30");
		ponto5.getHorarios().addElement("22:30");
		ponto5.getHorarios().addElement("23:30");
		return onibus;
		}
	}