
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusB36 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("PALOMA / GUARAITUBA");
		onibus.setCodigo("B36");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO GUARAITUBA");
		ponto0.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto0.setValidoAPartirDe("30/11/2008");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:25");
		ponto0.getHorarios().addElement("06:15");
		ponto0.getHorarios().addElement("07:05");
		ponto0.getHorarios().addElement("07:55");
		ponto0.getHorarios().addElement("08:45");
		ponto0.getHorarios().addElement("09:35");
		ponto0.getHorarios().addElement("10:25");
		ponto0.getHorarios().addElement("11:15");
		ponto0.getHorarios().addElement("12:05");
		ponto0.getHorarios().addElement("12:55");
		ponto0.getHorarios().addElement("13:45");
		ponto0.getHorarios().addElement("14:35");
		ponto0.getHorarios().addElement("15:25");
		ponto0.getHorarios().addElement("16:15");
		ponto0.getHorarios().addElement("17:05");
		ponto0.getHorarios().addElement("17:55");
		ponto0.getHorarios().addElement("18:45");
		ponto0.getHorarios().addElement("19:35");
		ponto0.getHorarios().addElement("20:25");
		ponto0.getHorarios().addElement("21:15");
		ponto0.getHorarios().addElement("22:05");
		ponto0.getHorarios().addElement("22:55");
		ponto0.getHorarios().addElement("23:40");
		ponto0.getHorarios().addElement("00:20");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("BAIRRO PALOMA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto1.setValidoAPartirDe("30/11/2008");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:00");
		ponto1.getHorarios().addElement("05:50");
		ponto1.getHorarios().addElement("06:40");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("08:20");
		ponto1.getHorarios().addElement("09:10");
		ponto1.getHorarios().addElement("10:00");
		ponto1.getHorarios().addElement("10:50");
		ponto1.getHorarios().addElement("11:40");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:20");
		ponto1.getHorarios().addElement("14:10");
		ponto1.getHorarios().addElement("15:00");
		ponto1.getHorarios().addElement("15:50");
		ponto1.getHorarios().addElement("16:40");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("18:20");
		ponto1.getHorarios().addElement("19:10");
		ponto1.getHorarios().addElement("20:00");
		ponto1.getHorarios().addElement("20:50");
		ponto1.getHorarios().addElement("21:40");
		ponto1.getHorarios().addElement("22:30");
		ponto1.getHorarios().addElement("23:20");
		ponto1.getHorarios().addElement("00:00");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL GUARAITUBA / PALOMA");
		ponto2.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto2.setValidoAPartirDe("30/11/2008");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:35");
		ponto2.getHorarios().addElement("06:25");
		ponto2.getHorarios().addElement("07:15");
		ponto2.getHorarios().addElement("08:05");
		ponto2.getHorarios().addElement("08:55");
		ponto2.getHorarios().addElement("09:45");
		ponto2.getHorarios().addElement("10:35");
		ponto2.getHorarios().addElement("11:25");
		ponto2.getHorarios().addElement("12:15");
		ponto2.getHorarios().addElement("13:05");
		ponto2.getHorarios().addElement("13:55");
		ponto2.getHorarios().addElement("14:45");
		ponto2.getHorarios().addElement("15:35");
		ponto2.getHorarios().addElement("16:25");
		ponto2.getHorarios().addElement("17:15");
		ponto2.getHorarios().addElement("18:05");
		ponto2.getHorarios().addElement("18:55");
		ponto2.getHorarios().addElement("19:45");
		ponto2.getHorarios().addElement("20:35");
		ponto2.getHorarios().addElement("21:25");
		ponto2.getHorarios().addElement("22:15");
		ponto2.getHorarios().addElement("23:05");
		ponto2.getHorarios().addElement("23:50");
		ponto2.getHorarios().addElement("00:30");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL GUARAITUBA / GUARAITU");
		ponto3.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto3.setValidoAPartirDe("30/11/2008");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:15");
		ponto3.getHorarios().addElement("06:05");
		ponto3.getHorarios().addElement("06:55");
		ponto3.getHorarios().addElement("07:45");
		ponto3.getHorarios().addElement("08:35");
		ponto3.getHorarios().addElement("09:25");
		ponto3.getHorarios().addElement("10:15");
		ponto3.getHorarios().addElement("11:05");
		ponto3.getHorarios().addElement("11:55");
		ponto3.getHorarios().addElement("12:45");
		ponto3.getHorarios().addElement("13:35");
		ponto3.getHorarios().addElement("14:25");
		ponto3.getHorarios().addElement("15:15");
		ponto3.getHorarios().addElement("16:05");
		ponto3.getHorarios().addElement("16:55");
		ponto3.getHorarios().addElement("17:45");
		ponto3.getHorarios().addElement("18:35");
		ponto3.getHorarios().addElement("19:25");
		ponto3.getHorarios().addElement("20:15");
		ponto3.getHorarios().addElement("21:05");
		ponto3.getHorarios().addElement("21:55");
		ponto3.getHorarios().addElement("22:45");
		ponto3.getHorarios().addElement("23:30");
		ponto3.getHorarios().addElement("00:10");
		return onibus;
		}
	}