
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusB25 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("MARACANÃ / B. ALTO");
		onibus.setCodigo("B25");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("TERMINAL BAIRRO ALTO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("04/01/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:40");
		ponto0.getHorarios().addElement("06:35");
		ponto0.getHorarios().addElement("07:05");
		ponto0.getHorarios().addElement("07:35");
		ponto0.getHorarios().addElement("08:05");
		ponto0.getHorarios().addElement("08:35");
		ponto0.getHorarios().addElement("09:35");
		ponto0.getHorarios().addElement("10:35");
		ponto0.getHorarios().addElement("11:35");
		ponto0.getHorarios().addElement("12:35");
		ponto0.getHorarios().addElement("13:35");
		ponto0.getHorarios().addElement("14:35");
		ponto0.getHorarios().addElement("15:35");
		ponto0.getHorarios().addElement("16:35");
		ponto0.getHorarios().addElement("17:05");
		ponto0.getHorarios().addElement("17:35");
		ponto0.getHorarios().addElement("18:05");
		ponto0.getHorarios().addElement("18:35");
		ponto0.getHorarios().addElement("19:05");
		ponto0.getHorarios().addElement("19:35");
		ponto0.getHorarios().addElement("20:35");
		ponto0.getHorarios().addElement("21:35");
		ponto0.getHorarios().addElement("22:35");
		ponto0.getHorarios().addElement("23:35");
		ponto0.getHorarios().addElement("00:35");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL MARACANA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("04/01/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:15");
		ponto1.getHorarios().addElement("06:06");
		ponto1.getHorarios().addElement("06:35");
		ponto1.getHorarios().addElement("07:05");
		ponto1.getHorarios().addElement("07:35");
		ponto1.getHorarios().addElement("08:05");
		ponto1.getHorarios().addElement("09:05");
		ponto1.getHorarios().addElement("10:05");
		ponto1.getHorarios().addElement("11:05");
		ponto1.getHorarios().addElement("12:05");
		ponto1.getHorarios().addElement("13:05");
		ponto1.getHorarios().addElement("14:05");
		ponto1.getHorarios().addElement("15:05");
		ponto1.getHorarios().addElement("16:05");
		ponto1.getHorarios().addElement("16:35");
		ponto1.getHorarios().addElement("17:05");
		ponto1.getHorarios().addElement("17:35");
		ponto1.getHorarios().addElement("18:05");
		ponto1.getHorarios().addElement("18:35");
		ponto1.getHorarios().addElement("19:05");
		ponto1.getHorarios().addElement("20:05");
		ponto1.getHorarios().addElement("21:05");
		ponto1.getHorarios().addElement("22:05");
		ponto1.getHorarios().addElement("23:05");
		ponto1.getHorarios().addElement("00:05");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("V.MARIA DO ROSARIO");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("04/01/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:13");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL GUARAITUBA");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("04/01/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:28");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL BAIRRO ALTO");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("02/04/2011");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:15");
		ponto4.getHorarios().addElement("07:15");
		ponto4.getHorarios().addElement("08:15");
		ponto4.getHorarios().addElement("09:15");
		ponto4.getHorarios().addElement("10:15");
		ponto4.getHorarios().addElement("11:15");
		ponto4.getHorarios().addElement("12:15");
		ponto4.getHorarios().addElement("13:15");
		ponto4.getHorarios().addElement("14:15");
		ponto4.getHorarios().addElement("15:15");
		ponto4.getHorarios().addElement("16:15");
		ponto4.getHorarios().addElement("17:15");
		ponto4.getHorarios().addElement("18:15");
		ponto4.getHorarios().addElement("19:15");
		ponto4.getHorarios().addElement("20:15");
		ponto4.getHorarios().addElement("21:10");
		ponto4.getHorarios().addElement("22:10");
		ponto4.getHorarios().addElement("23:10");
		ponto4.getHorarios().addElement("00:15");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL MARACANA");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("02/04/2011");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:50");
		ponto5.getHorarios().addElement("06:45");
		ponto5.getHorarios().addElement("07:45");
		ponto5.getHorarios().addElement("08:45");
		ponto5.getHorarios().addElement("09:45");
		ponto5.getHorarios().addElement("10:45");
		ponto5.getHorarios().addElement("11:45");
		ponto5.getHorarios().addElement("12:45");
		ponto5.getHorarios().addElement("13:45");
		ponto5.getHorarios().addElement("14:45");
		ponto5.getHorarios().addElement("15:45");
		ponto5.getHorarios().addElement("16:45");
		ponto5.getHorarios().addElement("17:45");
		ponto5.getHorarios().addElement("18:45");
		ponto5.getHorarios().addElement("19:45");
		ponto5.getHorarios().addElement("20:43");
		ponto5.getHorarios().addElement("21:40");
		ponto5.getHorarios().addElement("22:40");
		ponto5.getHorarios().addElement("23:40");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL BAIRRO ALTO");
		ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto6.setValidoAPartirDe("21/11/2010");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:10");
		ponto6.getHorarios().addElement("07:10");
		ponto6.getHorarios().addElement("08:10");
		ponto6.getHorarios().addElement("09:10");
		ponto6.getHorarios().addElement("10:10");
		ponto6.getHorarios().addElement("11:10");
		ponto6.getHorarios().addElement("12:10");
		ponto6.getHorarios().addElement("13:10");
		ponto6.getHorarios().addElement("14:10");
		ponto6.getHorarios().addElement("15:10");
		ponto6.getHorarios().addElement("16:10");
		ponto6.getHorarios().addElement("17:10");
		ponto6.getHorarios().addElement("18:10");
		ponto6.getHorarios().addElement("19:10");
		ponto6.getHorarios().addElement("20:10");
		ponto6.getHorarios().addElement("21:10");
		ponto6.getHorarios().addElement("22:10");
		ponto6.getHorarios().addElement("23:10");
		ponto6.getHorarios().addElement("00:15");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("TERMINAL MARACANA");
		ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto7.setValidoAPartirDe("21/11/2010");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("05:40");
		ponto7.getHorarios().addElement("06:40");
		ponto7.getHorarios().addElement("07:40");
		ponto7.getHorarios().addElement("08:40");
		ponto7.getHorarios().addElement("09:40");
		ponto7.getHorarios().addElement("10:40");
		ponto7.getHorarios().addElement("11:40");
		ponto7.getHorarios().addElement("12:40");
		ponto7.getHorarios().addElement("13:40");
		ponto7.getHorarios().addElement("14:40");
		ponto7.getHorarios().addElement("15:40");
		ponto7.getHorarios().addElement("16:40");
		ponto7.getHorarios().addElement("17:40");
		ponto7.getHorarios().addElement("18:40");
		ponto7.getHorarios().addElement("19:40");
		ponto7.getHorarios().addElement("20:40");
		ponto7.getHorarios().addElement("21:40");
		ponto7.getHorarios().addElement("22:40");
		ponto7.getHorarios().addElement("23:40");
		return onibus;
		}
	}