
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusO73 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("O73 - CTBA / Q. BARRAS (GRACIOSA)");
		onibus.setCodigo("O73");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO BORDA DO CAMPO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("17/09/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:20");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL GUADALUPE");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("17/09/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:27");
		ponto1.getHorarios().addElement("06:46");
		ponto1.getHorarios().addElement("07:08");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("07:40");
		ponto1.getHorarios().addElement("08:14");
		ponto1.getHorarios().addElement("09:00");
		ponto1.getHorarios().addElement("09:46");
		ponto1.getHorarios().addElement("10:24");
		ponto1.getHorarios().addElement("11:10");
		ponto1.getHorarios().addElement("11:51");
		ponto1.getHorarios().addElement("12:34");
		ponto1.getHorarios().addElement("13:20");
		ponto1.getHorarios().addElement("14:06");
		ponto1.getHorarios().addElement("14:44");
		ponto1.getHorarios().addElement("15:35");
		ponto1.getHorarios().addElement("16:15");
		ponto1.getHorarios().addElement("17:00");
		ponto1.getHorarios().addElement("17:26");
		ponto1.getHorarios().addElement("18:14");
		ponto1.getHorarios().addElement("18:40");
		ponto1.getHorarios().addElement("19:06");
		ponto1.getHorarios().addElement("19:32");
		ponto1.getHorarios().addElement("19:58");
		ponto1.getHorarios().addElement("20:50");
		ponto1.getHorarios().addElement("21:30");
		ponto1.getHorarios().addElement("22:15");
		ponto1.getHorarios().addElement("23:00");
		ponto1.getHorarios().addElement("23:40");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL QUATRO BARRAS");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("17/09/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:27");
		ponto2.getHorarios().addElement("05:46");
		ponto2.getHorarios().addElement("06:08");
		ponto2.getHorarios().addElement("06:25");
		ponto2.getHorarios().addElement("06:40");
		ponto2.getHorarios().addElement("07:05");
		ponto2.getHorarios().addElement("07:25");
		ponto2.getHorarios().addElement("07:50");
		ponto2.getHorarios().addElement("08:12");
		ponto2.getHorarios().addElement("08:40");
		ponto2.getHorarios().addElement("09:19");
		ponto2.getHorarios().addElement("10:05");
		ponto2.getHorarios().addElement("10:46");
		ponto2.getHorarios().addElement("11:29");
		ponto2.getHorarios().addElement("12:15");
		ponto2.getHorarios().addElement("12:56");
		ponto2.getHorarios().addElement("13:39");
		ponto2.getHorarios().addElement("14:25");
		ponto2.getHorarios().addElement("15:06");
		ponto2.getHorarios().addElement("15:49");
		ponto2.getHorarios().addElement("16:45");
		ponto2.getHorarios().addElement("17:22");
		ponto2.getHorarios().addElement("17:40");
		ponto2.getHorarios().addElement("18:10");
		ponto2.getHorarios().addElement("18:36");
		ponto2.getHorarios().addElement("19:34");
		ponto2.getHorarios().addElement("20:30");
		ponto2.getHorarios().addElement("21:10");
		ponto2.getHorarios().addElement("21:50");
		ponto2.getHorarios().addElement("22:35");
		ponto2.getHorarios().addElement("23:15");
		ponto2.getHorarios().addElement("23:50");
		ponto2.getHorarios().addElement("00:35");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL GUADALUPE2");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("17/09/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("16:35");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO BORDA DO CAMPO");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("11/08/2012");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("23:20");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("Q.BARRAS (VIA ADALTO BOTELHO)");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("11/08/2012");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:14");
		ponto5.getHorarios().addElement("12:15");
		ponto5.getHorarios().addElement("16:20");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL GUADALUPE");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("11/08/2012");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:14");
		ponto6.getHorarios().addElement("07:19");
		ponto6.getHorarios().addElement("09:14");
		ponto6.getHorarios().addElement("10:14");
		ponto6.getHorarios().addElement("11:14");
		ponto6.getHorarios().addElement("12:14");
		ponto6.getHorarios().addElement("15:14");
		ponto6.getHorarios().addElement("16:14");
		ponto6.getHorarios().addElement("17:20");
		ponto6.getHorarios().addElement("19:15");
		ponto6.getHorarios().addElement("20:14");
		ponto6.getHorarios().addElement("21:00");
		ponto6.getHorarios().addElement("22:09");
		ponto6.getHorarios().addElement("23:00");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("TERMINAL QUATRO BARRAS");
		ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto7.setValidoAPartirDe("11/08/2012");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("05:19");
		ponto7.getHorarios().addElement("07:14");
		ponto7.getHorarios().addElement("08:14");
		ponto7.getHorarios().addElement("09:14");
		ponto7.getHorarios().addElement("10:14");
		ponto7.getHorarios().addElement("11:14");
		ponto7.getHorarios().addElement("13:14");
		ponto7.getHorarios().addElement("14:14");
		ponto7.getHorarios().addElement("15:14");
		ponto7.getHorarios().addElement("17:14");
		ponto7.getHorarios().addElement("18:15");
		ponto7.getHorarios().addElement("19:14");
		ponto7.getHorarios().addElement("20:09");
		ponto7.getHorarios().addElement("21:14");
		ponto7.getHorarios().addElement("22:00");
		ponto7.getHorarios().addElement("23:05");
		ponto7.getHorarios().addElement("23:50");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("GUADALUPE VIA ADALTO BOTELHO");
		ponto8.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto8.setValidoAPartirDe("11/08/2012");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("08:14");
		ponto8.getHorarios().addElement("13:19");
		ponto8.getHorarios().addElement("14:14");
		ponto8.getHorarios().addElement("18:14");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("BAIRRO BORDA DO CAMPO");
		ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto9.setValidoAPartirDe("21/08/2012");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("06:25");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("Q.BARRAS (VIA ADALTO BOTELHO)");
		ponto10.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto10.setValidoAPartirDe("21/08/2012");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("06:10");
		ponto10.getHorarios().addElement("12:40");
		ponto10.getHorarios().addElement("15:45");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("TERMINAL GUADALUPE");
		ponto11.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto11.setValidoAPartirDe("21/08/2012");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("07:20");
		ponto11.getHorarios().addElement("09:20");
		ponto11.getHorarios().addElement("10:15");
		ponto11.getHorarios().addElement("11:25");
		ponto11.getHorarios().addElement("13:45");
		ponto11.getHorarios().addElement("14:35");
		ponto11.getHorarios().addElement("15:50");
		ponto11.getHorarios().addElement("16:55");
		ponto11.getHorarios().addElement("18:00");
		ponto11.getHorarios().addElement("20:10");
		ponto11.getHorarios().addElement("21:05");
		ponto11.getHorarios().addElement("22:20");
		ponto11.getHorarios().addElement("23:05");
		Ponto ponto12 = new Ponto();
		ponto12.setNome("TERMINAL QUATRO BARRAS");
		ponto12.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto12.setValidoAPartirDe("21/08/2012");
		onibus.getPontos().addElement(ponto12);
		ponto12.getHorarios().addElement("06:00");
		ponto12.getHorarios().addElement("07:05");
		ponto12.getHorarios().addElement("08:20");
		ponto12.getHorarios().addElement("09:15");
		ponto12.getHorarios().addElement("10:20");
		ponto12.getHorarios().addElement("11:20");
		ponto12.getHorarios().addElement("13:35");
		ponto12.getHorarios().addElement("14:50");
		ponto12.getHorarios().addElement("16:50");
		ponto12.getHorarios().addElement("17:55");
		ponto12.getHorarios().addElement("19:10");
		ponto12.getHorarios().addElement("19:55");
		ponto12.getHorarios().addElement("21:10");
		ponto12.getHorarios().addElement("22:05");
		ponto12.getHorarios().addElement("23:20");
		ponto12.getHorarios().addElement("00:05");
		Ponto ponto13 = new Ponto();
		ponto13.setNome("GUADALUPE VIA ADALTO BOTELHO");
		ponto13.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto13.setValidoAPartirDe("21/08/2012");
		onibus.getPontos().addElement(ponto13);
		ponto13.getHorarios().addElement("08:05");
		ponto13.getHorarios().addElement("12:25");
		ponto13.getHorarios().addElement("18:55");
		return onibus;
		}
	}