
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusE67 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("CTBA / BRAGA");
		onibus.setCodigo("E67");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO POSTO CONSUL");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("12/03/2007");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("04:50");
		ponto0.getHorarios().addElement("05:45");
		ponto0.getHorarios().addElement("06:50");
		ponto0.getHorarios().addElement("10:55");
		ponto0.getHorarios().addElement("16:40");
		ponto0.getHorarios().addElement("23:00");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("CAMPUS DA PUC");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("12/03/2007");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:25");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("08:00");
		ponto1.getHorarios().addElement("09:10");
		ponto1.getHorarios().addElement("09:35");
		ponto1.getHorarios().addElement("10:35");
		ponto1.getHorarios().addElement("11:25");
		ponto1.getHorarios().addElement("12:10");
		ponto1.getHorarios().addElement("13:05");
		ponto1.getHorarios().addElement("13:55");
		ponto1.getHorarios().addElement("14:45");
		ponto1.getHorarios().addElement("15:35");
		ponto1.getHorarios().addElement("16:25");
		ponto1.getHorarios().addElement("17:15");
		ponto1.getHorarios().addElement("18:05");
		ponto1.getHorarios().addElement("18:55");
		ponto1.getHorarios().addElement("20:35");
		ponto1.getHorarios().addElement("22:20");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL GUADALUPE");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("12/03/2007");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:40");
		ponto2.getHorarios().addElement("06:42");
		ponto2.getHorarios().addElement("07:10");
		ponto2.getHorarios().addElement("07:50");
		ponto2.getHorarios().addElement("08:20");
		ponto2.getHorarios().addElement("08:45");
		ponto2.getHorarios().addElement("09:50");
		ponto2.getHorarios().addElement("10:25");
		ponto2.getHorarios().addElement("11:20");
		ponto2.getHorarios().addElement("11:50");
		ponto2.getHorarios().addElement("12:15");
		ponto2.getHorarios().addElement("12:55");
		ponto2.getHorarios().addElement("13:50");
		ponto2.getHorarios().addElement("14:40");
		ponto2.getHorarios().addElement("15:35");
		ponto2.getHorarios().addElement("16:20");
		ponto2.getHorarios().addElement("17:10");
		ponto2.getHorarios().addElement("17:37");
		ponto2.getHorarios().addElement("18:00");
		ponto2.getHorarios().addElement("19:00");
		ponto2.getHorarios().addElement("19:41");
		ponto2.getHorarios().addElement("21:15");
		ponto2.getHorarios().addElement("23:00");
		ponto2.getHorarios().addElement("23:45");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("BAIRRO POSTO CONSUL");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("24/09/2005");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:00");
		ponto3.getHorarios().addElement("08:10");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("CAMPUS DA PUC");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("24/09/2005");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("07:30");
		ponto4.getHorarios().addElement("09:10");
		ponto4.getHorarios().addElement("09:50");
		ponto4.getHorarios().addElement("10:35");
		ponto4.getHorarios().addElement("11:15");
		ponto4.getHorarios().addElement("12:05");
		ponto4.getHorarios().addElement("12:50");
		ponto4.getHorarios().addElement("14:20");
		ponto4.getHorarios().addElement("15:45");
		ponto4.getHorarios().addElement("17:15");
		ponto4.getHorarios().addElement("18:45");
		ponto4.getHorarios().addElement("20:15");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL GUADALUPE");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("24/09/2005");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:45");
		ponto5.getHorarios().addElement("08:15");
		ponto5.getHorarios().addElement("09:05");
		ponto5.getHorarios().addElement("09:50");
		ponto5.getHorarios().addElement("10:25");
		ponto5.getHorarios().addElement("11:20");
		ponto5.getHorarios().addElement("12:00");
		ponto5.getHorarios().addElement("12:45");
		ponto5.getHorarios().addElement("13:35");
		ponto5.getHorarios().addElement("15:00");
		ponto5.getHorarios().addElement("16:28");
		ponto5.getHorarios().addElement("17:56");
		ponto5.getHorarios().addElement("19:30");
		ponto5.getHorarios().addElement("21:00");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("BAIRRO POSTO CONSUL");
		ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto6.setValidoAPartirDe("25/09/2005");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:30");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("CAMPUS DA PUC");
		ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto7.setValidoAPartirDe("25/09/2005");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("08:05");
		ponto7.getHorarios().addElement("09:35");
		ponto7.getHorarios().addElement("11:05");
		ponto7.getHorarios().addElement("12:35");
		ponto7.getHorarios().addElement("14:05");
		ponto7.getHorarios().addElement("15:35");
		ponto7.getHorarios().addElement("17:05");
		ponto7.getHorarios().addElement("18:35");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("TERMINAL GUADALUPE");
		ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto8.setValidoAPartirDe("25/09/2005");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("07:15");
		ponto8.getHorarios().addElement("08:45");
		ponto8.getHorarios().addElement("10:15");
		ponto8.getHorarios().addElement("11:45");
		ponto8.getHorarios().addElement("13:15");
		ponto8.getHorarios().addElement("14:45");
		ponto8.getHorarios().addElement("16:15");
		ponto8.getHorarios().addElement("17:45");
		ponto8.getHorarios().addElement("19:15");
		return onibus;
		}
	}