
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus260 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("260 - MAL. HERMES / STA. EFIGÊNIA");
		  onibus.setCodigo("260");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("AV MARECHAL FLORIANO");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("24/08/2009");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("06:02");
		  ponto0.getHorarios().addElement("06:20");
		  ponto0.getHorarios().addElement("06:38");
		  ponto0.getHorarios().addElement("06:56");
		  ponto0.getHorarios().addElement("07:14");
		  ponto0.getHorarios().addElement("07:32");
		  ponto0.getHorarios().addElement("07:50");
		  ponto0.getHorarios().addElement("08:08");
		  ponto0.getHorarios().addElement("08:28");
		  ponto0.getHorarios().addElement("08:48");
		  ponto0.getHorarios().addElement("09:08");
		  ponto0.getHorarios().addElement("09:41");
		  ponto0.getHorarios().addElement("10:14");
		  ponto0.getHorarios().addElement("10:47");
		  ponto0.getHorarios().addElement("11:20");
		  ponto0.getHorarios().addElement("11:53");
		  ponto0.getHorarios().addElement("12:26");
		  ponto0.getHorarios().addElement("12:59");
		  ponto0.getHorarios().addElement("13:32");
		  ponto0.getHorarios().addElement("14:05");
		  ponto0.getHorarios().addElement("14:38");
		  ponto0.getHorarios().addElement("15:11");
		  ponto0.getHorarios().addElement("15:44");
		  ponto0.getHorarios().addElement("16:17");
		  ponto0.getHorarios().addElement("16:50");
		  ponto0.getHorarios().addElement("17:12");
		  ponto0.getHorarios().addElement("17:34");
		  ponto0.getHorarios().addElement("17:56");
		  ponto0.getHorarios().addElement("18:18");
		  ponto0.getHorarios().addElement("18:40");
		  ponto0.getHorarios().addElement("19:02");
		  ponto0.getHorarios().addElement("19:24");
		  ponto0.getHorarios().addElement("19:46");
		  ponto0.getHorarios().addElement("20:06");
		  ponto0.getHorarios().addElement("21:00");
		  ponto0.getHorarios().addElement("22:00");
		  ponto0.getHorarios().addElement("23:00");
		  ponto0.getHorarios().addElement("00:00");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("BAIRRO MARECHAL HERMES");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("24/08/2009");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:35");
		  ponto1.getHorarios().addElement("05:53");
		  ponto1.getHorarios().addElement("06:11");
		  ponto1.getHorarios().addElement("06:29");
		  ponto1.getHorarios().addElement("06:47");
		  ponto1.getHorarios().addElement("07:05");
		  ponto1.getHorarios().addElement("07:23");
		  ponto1.getHorarios().addElement("07:41");
		  ponto1.getHorarios().addElement("07:59");
		  ponto1.getHorarios().addElement("08:17");
		  ponto1.getHorarios().addElement("08:35");
		  ponto1.getHorarios().addElement("09:08");
		  ponto1.getHorarios().addElement("09:41");
		  ponto1.getHorarios().addElement("10:14");
		  ponto1.getHorarios().addElement("10:47");
		  ponto1.getHorarios().addElement("11:20");
		  ponto1.getHorarios().addElement("11:53");
		  ponto1.getHorarios().addElement("12:26");
		  ponto1.getHorarios().addElement("12:59");
		  ponto1.getHorarios().addElement("13:32");
		  ponto1.getHorarios().addElement("14:05");
		  ponto1.getHorarios().addElement("14:38");
		  ponto1.getHorarios().addElement("15:11");
		  ponto1.getHorarios().addElement("15:44");
		  ponto1.getHorarios().addElement("16:17");
		  ponto1.getHorarios().addElement("16:50");
		  ponto1.getHorarios().addElement("17:23");
		  ponto1.getHorarios().addElement("17:45");
		  ponto1.getHorarios().addElement("18:07");
		  ponto1.getHorarios().addElement("18:29");
		  ponto1.getHorarios().addElement("18:51");
		  ponto1.getHorarios().addElement("19:13");
		  ponto1.getHorarios().addElement("19:35");
		  ponto1.getHorarios().addElement("20:30");
		  ponto1.getHorarios().addElement("21:30");
		  ponto1.getHorarios().addElement("22:30");
		  ponto1.getHorarios().addElement("23:30");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("AV MARECHAL FLORIANO");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("13/10/2007");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:30");
		  ponto2.getHorarios().addElement("07:30");
		  ponto2.getHorarios().addElement("08:30");
		  ponto2.getHorarios().addElement("09:30");
		  ponto2.getHorarios().addElement("10:30");
		  ponto2.getHorarios().addElement("11:30");
		  ponto2.getHorarios().addElement("12:30");
		  ponto2.getHorarios().addElement("13:30");
		  ponto2.getHorarios().addElement("14:30");
		  ponto2.getHorarios().addElement("15:30");
		  ponto2.getHorarios().addElement("16:30");
		  ponto2.getHorarios().addElement("17:30");
		  ponto2.getHorarios().addElement("18:30");
		  ponto2.getHorarios().addElement("19:30");
		  ponto2.getHorarios().addElement("20:30");
		  ponto2.getHorarios().addElement("21:30");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("23:30");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("BAIRRO MARECHAL HERMES");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("13/10/2007");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:00");
		  ponto3.getHorarios().addElement("07:00");
		  ponto3.getHorarios().addElement("08:00");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("10:00");
		  ponto3.getHorarios().addElement("11:00");
		  ponto3.getHorarios().addElement("12:00");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("14:00");
		  ponto3.getHorarios().addElement("15:00");
		  ponto3.getHorarios().addElement("16:00");
		  ponto3.getHorarios().addElement("17:00");
		  ponto3.getHorarios().addElement("18:00");
		  ponto3.getHorarios().addElement("19:00");
		  ponto3.getHorarios().addElement("20:00");
		  ponto3.getHorarios().addElement("21:00");
		  ponto3.getHorarios().addElement("22:00");
		  ponto3.getHorarios().addElement("23:00");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("AV MARECHAL FLORIANO");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("23/09/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:30");
		  ponto4.getHorarios().addElement("07:30");
		  ponto4.getHorarios().addElement("08:30");
		  ponto4.getHorarios().addElement("09:30");
		  ponto4.getHorarios().addElement("10:30");
		  ponto4.getHorarios().addElement("11:30");
		  ponto4.getHorarios().addElement("12:30");
		  ponto4.getHorarios().addElement("13:30");
		  ponto4.getHorarios().addElement("14:30");
		  ponto4.getHorarios().addElement("15:30");
		  ponto4.getHorarios().addElement("16:30");
		  ponto4.getHorarios().addElement("17:30");
		  ponto4.getHorarios().addElement("18:30");
		  ponto4.getHorarios().addElement("19:30");
		  ponto4.getHorarios().addElement("20:30");
		  ponto4.getHorarios().addElement("21:30");
		  ponto4.getHorarios().addElement("22:30");
		  ponto4.getHorarios().addElement("23:30");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("BAIRRO MARECHAL HERMES");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("23/09/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:00");
		  ponto5.getHorarios().addElement("07:00");
		  ponto5.getHorarios().addElement("08:00");
		  ponto5.getHorarios().addElement("09:00");
		  ponto5.getHorarios().addElement("10:00");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("12:00");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("14:00");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("16:00");
		  ponto5.getHorarios().addElement("17:00");
		  ponto5.getHorarios().addElement("18:00");
		  ponto5.getHorarios().addElement("19:00");
		  ponto5.getHorarios().addElement("20:00");
		  ponto5.getHorarios().addElement("21:00");
		  ponto5.getHorarios().addElement("22:00");
		  ponto5.getHorarios().addElement("23:00");
		  return onibus;
		  }
	  }