
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus719 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("719 - FAZEND. / CAIUÁ-FRIGORÍF.");
		  onibus.setCodigo("719");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO FRIGORIFICO/TERM.CAIUA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("11/05/2009");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:08");
		  ponto0.getHorarios().addElement("05:28");
		  ponto0.getHorarios().addElement("05:48");
		  ponto0.getHorarios().addElement("06:08");
		  ponto0.getHorarios().addElement("06:28");
		  ponto0.getHorarios().addElement("06:48");
		  ponto0.getHorarios().addElement("07:08");
		  ponto0.getHorarios().addElement("07:28");
		  ponto0.getHorarios().addElement("07:48");
		  ponto0.getHorarios().addElement("08:08");
		  ponto0.getHorarios().addElement("08:28");
		  ponto0.getHorarios().addElement("09:08");
		  ponto0.getHorarios().addElement("09:48");
		  ponto0.getHorarios().addElement("10:28");
		  ponto0.getHorarios().addElement("11:08");
		  ponto0.getHorarios().addElement("11:48");
		  ponto0.getHorarios().addElement("12:28");
		  ponto0.getHorarios().addElement("13:08");
		  ponto0.getHorarios().addElement("13:48");
		  ponto0.getHorarios().addElement("14:28");
		  ponto0.getHorarios().addElement("15:08");
		  ponto0.getHorarios().addElement("15:48");
		  ponto0.getHorarios().addElement("16:28");
		  ponto0.getHorarios().addElement("17:08");
		  ponto0.getHorarios().addElement("17:28");
		  ponto0.getHorarios().addElement("17:48");
		  ponto0.getHorarios().addElement("18:08");
		  ponto0.getHorarios().addElement("18:28");
		  ponto0.getHorarios().addElement("18:48");
		  ponto0.getHorarios().addElement("19:08");
		  ponto0.getHorarios().addElement("19:28");
		  ponto0.getHorarios().addElement("19:48");
		  ponto0.getHorarios().addElement("20:28");
		  ponto0.getHorarios().addElement("21:08");
		  ponto0.getHorarios().addElement("21:48");
		  ponto0.getHorarios().addElement("22:28");
		  ponto0.getHorarios().addElement("23:08");
		  ponto0.getHorarios().addElement("23:48");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERM.CAIUA/BAIRRO FRIGORIFICO");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("11/05/2009");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:40");
		  ponto1.getHorarios().addElement("06:00");
		  ponto1.getHorarios().addElement("06:20");
		  ponto1.getHorarios().addElement("06:40");
		  ponto1.getHorarios().addElement("07:00");
		  ponto1.getHorarios().addElement("07:20");
		  ponto1.getHorarios().addElement("07:40");
		  ponto1.getHorarios().addElement("08:00");
		  ponto1.getHorarios().addElement("08:20");
		  ponto1.getHorarios().addElement("09:00");
		  ponto1.getHorarios().addElement("09:40");
		  ponto1.getHorarios().addElement("10:20");
		  ponto1.getHorarios().addElement("11:00");
		  ponto1.getHorarios().addElement("11:40");
		  ponto1.getHorarios().addElement("12:20");
		  ponto1.getHorarios().addElement("13:00");
		  ponto1.getHorarios().addElement("13:40");
		  ponto1.getHorarios().addElement("14:20");
		  ponto1.getHorarios().addElement("15:00");
		  ponto1.getHorarios().addElement("15:40");
		  ponto1.getHorarios().addElement("16:20");
		  ponto1.getHorarios().addElement("17:00");
		  ponto1.getHorarios().addElement("17:20");
		  ponto1.getHorarios().addElement("17:40");
		  ponto1.getHorarios().addElement("18:00");
		  ponto1.getHorarios().addElement("18:20");
		  ponto1.getHorarios().addElement("18:40");
		  ponto1.getHorarios().addElement("19:00");
		  ponto1.getHorarios().addElement("19:20");
		  ponto1.getHorarios().addElement("19:40");
		  ponto1.getHorarios().addElement("20:00");
		  ponto1.getHorarios().addElement("20:20");
		  ponto1.getHorarios().addElement("21:00");
		  ponto1.getHorarios().addElement("21:40");
		  ponto1.getHorarios().addElement("22:20");
		  ponto1.getHorarios().addElement("23:00");
		  ponto1.getHorarios().addElement("23:40");
		  ponto1.getHorarios().addElement("00:20");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL CAIUA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("11/05/2009");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:16");
		  ponto2.getHorarios().addElement("05:36");
		  ponto2.getHorarios().addElement("05:56");
		  ponto2.getHorarios().addElement("06:16");
		  ponto2.getHorarios().addElement("06:36");
		  ponto2.getHorarios().addElement("06:56");
		  ponto2.getHorarios().addElement("07:16");
		  ponto2.getHorarios().addElement("07:36");
		  ponto2.getHorarios().addElement("07:56");
		  ponto2.getHorarios().addElement("08:16");
		  ponto2.getHorarios().addElement("08:36");
		  ponto2.getHorarios().addElement("09:16");
		  ponto2.getHorarios().addElement("09:56");
		  ponto2.getHorarios().addElement("10:36");
		  ponto2.getHorarios().addElement("11:16");
		  ponto2.getHorarios().addElement("11:56");
		  ponto2.getHorarios().addElement("12:36");
		  ponto2.getHorarios().addElement("13:16");
		  ponto2.getHorarios().addElement("13:56");
		  ponto2.getHorarios().addElement("14:36");
		  ponto2.getHorarios().addElement("15:16");
		  ponto2.getHorarios().addElement("15:56");
		  ponto2.getHorarios().addElement("16:36");
		  ponto2.getHorarios().addElement("17:16");
		  ponto2.getHorarios().addElement("17:36");
		  ponto2.getHorarios().addElement("17:56");
		  ponto2.getHorarios().addElement("18:16");
		  ponto2.getHorarios().addElement("18:36");
		  ponto2.getHorarios().addElement("18:56");
		  ponto2.getHorarios().addElement("19:16");
		  ponto2.getHorarios().addElement("19:36");
		  ponto2.getHorarios().addElement("19:56");
		  ponto2.getHorarios().addElement("20:36");
		  ponto2.getHorarios().addElement("21:16");
		  ponto2.getHorarios().addElement("21:56");
		  ponto2.getHorarios().addElement("22:36");
		  ponto2.getHorarios().addElement("23:16");
		  ponto2.getHorarios().addElement("23:56");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL FAZENDINHA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto3.setValidoAPartirDe("11/05/2009");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:28");
		  ponto3.getHorarios().addElement("05:48");
		  ponto3.getHorarios().addElement("06:08");
		  ponto3.getHorarios().addElement("06:28");
		  ponto3.getHorarios().addElement("06:48");
		  ponto3.getHorarios().addElement("07:08");
		  ponto3.getHorarios().addElement("07:28");
		  ponto3.getHorarios().addElement("07:48");
		  ponto3.getHorarios().addElement("08:08");
		  ponto3.getHorarios().addElement("08:48");
		  ponto3.getHorarios().addElement("09:28");
		  ponto3.getHorarios().addElement("10:08");
		  ponto3.getHorarios().addElement("10:48");
		  ponto3.getHorarios().addElement("11:28");
		  ponto3.getHorarios().addElement("12:08");
		  ponto3.getHorarios().addElement("12:48");
		  ponto3.getHorarios().addElement("13:28");
		  ponto3.getHorarios().addElement("14:08");
		  ponto3.getHorarios().addElement("14:48");
		  ponto3.getHorarios().addElement("15:28");
		  ponto3.getHorarios().addElement("16:08");
		  ponto3.getHorarios().addElement("16:48");
		  ponto3.getHorarios().addElement("17:08");
		  ponto3.getHorarios().addElement("17:28");
		  ponto3.getHorarios().addElement("17:48");
		  ponto3.getHorarios().addElement("18:08");
		  ponto3.getHorarios().addElement("18:28");
		  ponto3.getHorarios().addElement("18:48");
		  ponto3.getHorarios().addElement("19:08");
		  ponto3.getHorarios().addElement("19:28");
		  ponto3.getHorarios().addElement("19:48");
		  ponto3.getHorarios().addElement("20:08");
		  ponto3.getHorarios().addElement("20:48");
		  ponto3.getHorarios().addElement("21:28");
		  ponto3.getHorarios().addElement("22:08");
		  ponto3.getHorarios().addElement("22:48");
		  ponto3.getHorarios().addElement("23:28");
		  ponto3.getHorarios().addElement("00:08");
		  return onibus;
		  }
	  }