
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusA16 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("GIANNINI");
		onibus.setCodigo("A16");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO BOMFIM");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:41");
		ponto0.getHorarios().addElement("06:13");
		ponto0.getHorarios().addElement("06:48");
		ponto0.getHorarios().addElement("07:19");
		ponto0.getHorarios().addElement("07:50");
		ponto0.getHorarios().addElement("08:21");
		ponto0.getHorarios().addElement("08:52");
		ponto0.getHorarios().addElement("17:10");
		ponto0.getHorarios().addElement("17:43");
		ponto0.getHorarios().addElement("18:16");
		ponto0.getHorarios().addElement("18:47");
		ponto0.getHorarios().addElement("19:21");
		ponto0.getHorarios().addElement("19:53");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("BAIRRO GIANNINI");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:10");
		ponto1.getHorarios().addElement("05:42");
		ponto1.getHorarios().addElement("06:17");
		ponto1.getHorarios().addElement("06:48");
		ponto1.getHorarios().addElement("07:19");
		ponto1.getHorarios().addElement("07:50");
		ponto1.getHorarios().addElement("08:21");
		ponto1.getHorarios().addElement("09:30");
		ponto1.getHorarios().addElement("10:30");
		ponto1.getHorarios().addElement("11:30");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:30");
		ponto1.getHorarios().addElement("14:30");
		ponto1.getHorarios().addElement("15:30");
		ponto1.getHorarios().addElement("16:38");
		ponto1.getHorarios().addElement("17:10");
		ponto1.getHorarios().addElement("17:44");
		ponto1.getHorarios().addElement("18:12");
		ponto1.getHorarios().addElement("18:48");
		ponto1.getHorarios().addElement("19:20");
		ponto1.getHorarios().addElement("19:55");
		ponto1.getHorarios().addElement("20:45");
		ponto1.getHorarios().addElement("21:35");
		ponto1.getHorarios().addElement("22:25");
		ponto1.getHorarios().addElement("23:10");
		ponto1.getHorarios().addElement("23:55");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL CACHOEIRA");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:50");
		ponto2.getHorarios().addElement("06:25");
		ponto2.getHorarios().addElement("06:56");
		ponto2.getHorarios().addElement("07:27");
		ponto2.getHorarios().addElement("07:58");
		ponto2.getHorarios().addElement("08:29");
		ponto2.getHorarios().addElement("09:00");
		ponto2.getHorarios().addElement("10:00");
		ponto2.getHorarios().addElement("11:00");
		ponto2.getHorarios().addElement("12:00");
		ponto2.getHorarios().addElement("13:00");
		ponto2.getHorarios().addElement("14:00");
		ponto2.getHorarios().addElement("15:00");
		ponto2.getHorarios().addElement("16:05");
		ponto2.getHorarios().addElement("16:40");
		ponto2.getHorarios().addElement("17:20");
		ponto2.getHorarios().addElement("17:50");
		ponto2.getHorarios().addElement("18:25");
		ponto2.getHorarios().addElement("18:55");
		ponto2.getHorarios().addElement("19:30");
		ponto2.getHorarios().addElement("20:00");
		ponto2.getHorarios().addElement("20:20");
		ponto2.getHorarios().addElement("21:10");
		ponto2.getHorarios().addElement("22:00");
		ponto2.getHorarios().addElement("22:45");
		ponto2.getHorarios().addElement("23:30");
		ponto2.getHorarios().addElement("00:15");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL CACHOEIRA BOMFIM");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:35");
		ponto3.getHorarios().addElement("06:08");
		ponto3.getHorarios().addElement("06:42");
		ponto3.getHorarios().addElement("07:13");
		ponto3.getHorarios().addElement("07:44");
		ponto3.getHorarios().addElement("08:15");
		ponto3.getHorarios().addElement("08:46");
		ponto3.getHorarios().addElement("17:00");
		ponto3.getHorarios().addElement("17:34");
		ponto3.getHorarios().addElement("18:06");
		ponto3.getHorarios().addElement("18:37");
		ponto3.getHorarios().addElement("19:11");
		ponto3.getHorarios().addElement("19:45");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO BOMFIM");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("03/12/2011");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:41");
		ponto4.getHorarios().addElement("06:48");
		ponto4.getHorarios().addElement("07:50");
		ponto4.getHorarios().addElement("08:52");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("BAIRRO GIANNINI");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("03/12/2011");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:10");
		ponto5.getHorarios().addElement("06:17");
		ponto5.getHorarios().addElement("06:48");
		ponto5.getHorarios().addElement("07:19");
		ponto5.getHorarios().addElement("08:21");
		ponto5.getHorarios().addElement("09:25");
		ponto5.getHorarios().addElement("10:15");
		ponto5.getHorarios().addElement("11:05");
		ponto5.getHorarios().addElement("12:00");
		ponto5.getHorarios().addElement("13:00");
		ponto5.getHorarios().addElement("14:00");
		ponto5.getHorarios().addElement("15:10");
		ponto5.getHorarios().addElement("16:00");
		ponto5.getHorarios().addElement("17:00");
		ponto5.getHorarios().addElement("18:00");
		ponto5.getHorarios().addElement("19:00");
		ponto5.getHorarios().addElement("20:00");
		ponto5.getHorarios().addElement("21:00");
		ponto5.getHorarios().addElement("22:10");
		ponto5.getHorarios().addElement("23:10");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL CACHOEIRA");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("03/12/2011");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("05:50");
		ponto6.getHorarios().addElement("06:25");
		ponto6.getHorarios().addElement("06:56");
		ponto6.getHorarios().addElement("07:58");
		ponto6.getHorarios().addElement("09:00");
		ponto6.getHorarios().addElement("09:50");
		ponto6.getHorarios().addElement("10:40");
		ponto6.getHorarios().addElement("11:30");
		ponto6.getHorarios().addElement("12:30");
		ponto6.getHorarios().addElement("13:30");
		ponto6.getHorarios().addElement("14:30");
		ponto6.getHorarios().addElement("15:35");
		ponto6.getHorarios().addElement("16:30");
		ponto6.getHorarios().addElement("17:30");
		ponto6.getHorarios().addElement("18:30");
		ponto6.getHorarios().addElement("19:30");
		ponto6.getHorarios().addElement("20:30");
		ponto6.getHorarios().addElement("21:35");
		ponto6.getHorarios().addElement("22:35");
		ponto6.getHorarios().addElement("23:40");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("TERMINAL CACHOEIRA BOMFIM");
		ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto7.setValidoAPartirDe("03/12/2011");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("05:35");
		ponto7.getHorarios().addElement("06:42");
		ponto7.getHorarios().addElement("07:44");
		ponto7.getHorarios().addElement("08:46");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("BAIRRO GIANNINI");
		ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto8.setValidoAPartirDe("23/09/2007");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("05:30");
		ponto8.getHorarios().addElement("06:50");
		ponto8.getHorarios().addElement("07:40");
		ponto8.getHorarios().addElement("08:30");
		ponto8.getHorarios().addElement("09:30");
		ponto8.getHorarios().addElement("10:30");
		ponto8.getHorarios().addElement("11:30");
		ponto8.getHorarios().addElement("12:30");
		ponto8.getHorarios().addElement("13:30");
		ponto8.getHorarios().addElement("14:30");
		ponto8.getHorarios().addElement("15:30");
		ponto8.getHorarios().addElement("16:30");
		ponto8.getHorarios().addElement("17:30");
		ponto8.getHorarios().addElement("18:30");
		ponto8.getHorarios().addElement("19:30");
		ponto8.getHorarios().addElement("20:30");
		ponto8.getHorarios().addElement("21:30");
		ponto8.getHorarios().addElement("22:30");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("TERMINAL CACHOEIRA");
		ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto9.setValidoAPartirDe("23/09/2007");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("06:00");
		ponto9.getHorarios().addElement("07:15");
		ponto9.getHorarios().addElement("08:05");
		ponto9.getHorarios().addElement("09:00");
		ponto9.getHorarios().addElement("10:00");
		ponto9.getHorarios().addElement("11:00");
		ponto9.getHorarios().addElement("12:00");
		ponto9.getHorarios().addElement("13:00");
		ponto9.getHorarios().addElement("14:00");
		ponto9.getHorarios().addElement("15:00");
		ponto9.getHorarios().addElement("16:00");
		ponto9.getHorarios().addElement("17:00");
		ponto9.getHorarios().addElement("18:00");
		ponto9.getHorarios().addElement("19:00");
		ponto9.getHorarios().addElement("20:00");
		ponto9.getHorarios().addElement("21:00");
		ponto9.getHorarios().addElement("22:00");
		ponto9.getHorarios().addElement("23:00");
		return onibus;
		}
	}