
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusO73 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("CTBA / Q. BARRAS (GRACIOSA)");
		onibus.setCodigo("O73");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO BORDA DO CAMPO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:20");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL GUADALUPE");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:27");
		ponto1.getHorarios().addElement("06:46");
		ponto1.getHorarios().addElement("07:08");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("07:40");
		ponto1.getHorarios().addElement("08:10");
		ponto1.getHorarios().addElement("08:57");
		ponto1.getHorarios().addElement("09:41");
		ponto1.getHorarios().addElement("10:24");
		ponto1.getHorarios().addElement("11:07");
		ponto1.getHorarios().addElement("11:51");
		ponto1.getHorarios().addElement("12:34");
		ponto1.getHorarios().addElement("13:17");
		ponto1.getHorarios().addElement("14:01");
		ponto1.getHorarios().addElement("14:44");
		ponto1.getHorarios().addElement("15:34");
		ponto1.getHorarios().addElement("16:15");
		ponto1.getHorarios().addElement("16:35");
		ponto1.getHorarios().addElement("17:00");
		ponto1.getHorarios().addElement("17:22");
		ponto1.getHorarios().addElement("18:00");
		ponto1.getHorarios().addElement("18:08");
		ponto1.getHorarios().addElement("18:27");
		ponto1.getHorarios().addElement("18:46");
		ponto1.getHorarios().addElement("19:20");
		ponto1.getHorarios().addElement("19:35");
		ponto1.getHorarios().addElement("20:15");
		ponto1.getHorarios().addElement("20:43");
		ponto1.getHorarios().addElement("21:30");
		ponto1.getHorarios().addElement("22:15");
		ponto1.getHorarios().addElement("22:57");
		ponto1.getHorarios().addElement("23:40");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL QUATRO BARRAS");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:27");
		ponto2.getHorarios().addElement("05:46");
		ponto2.getHorarios().addElement("06:08");
		ponto2.getHorarios().addElement("06:30");
		ponto2.getHorarios().addElement("06:40");
		ponto2.getHorarios().addElement("07:05");
		ponto2.getHorarios().addElement("07:25");
		ponto2.getHorarios().addElement("07:50");
		ponto2.getHorarios().addElement("08:12");
		ponto2.getHorarios().addElement("08:36");
		ponto2.getHorarios().addElement("09:19");
		ponto2.getHorarios().addElement("10:02");
		ponto2.getHorarios().addElement("10:46");
		ponto2.getHorarios().addElement("11:29");
		ponto2.getHorarios().addElement("12:12");
		ponto2.getHorarios().addElement("12:56");
		ponto2.getHorarios().addElement("13:39");
		ponto2.getHorarios().addElement("14:22");
		ponto2.getHorarios().addElement("15:06");
		ponto2.getHorarios().addElement("15:49");
		ponto2.getHorarios().addElement("16:45");
		ponto2.getHorarios().addElement("17:22");
		ponto2.getHorarios().addElement("17:40");
		ponto2.getHorarios().addElement("18:10");
		ponto2.getHorarios().addElement("18:35");
		ponto2.getHorarios().addElement("19:15");
		ponto2.getHorarios().addElement("19:32");
		ponto2.getHorarios().addElement("19:51");
		ponto2.getHorarios().addElement("20:30");
		ponto2.getHorarios().addElement("21:10");
		ponto2.getHorarios().addElement("21:52");
		ponto2.getHorarios().addElement("22:35");
		ponto2.getHorarios().addElement("23:15");
		ponto2.getHorarios().addElement("00:35");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("Q.BARRAS (VIA ADALTO BOTELHO)");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("19/09/2009");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:14");
		ponto3.getHorarios().addElement("12:15");
		ponto3.getHorarios().addElement("16:14");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL GUADALUPE");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("19/09/2009");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:14");
		ponto4.getHorarios().addElement("07:19");
		ponto4.getHorarios().addElement("09:14");
		ponto4.getHorarios().addElement("10:14");
		ponto4.getHorarios().addElement("11:14");
		ponto4.getHorarios().addElement("12:14");
		ponto4.getHorarios().addElement("15:14");
		ponto4.getHorarios().addElement("16:14");
		ponto4.getHorarios().addElement("17:14");
		ponto4.getHorarios().addElement("19:14");
		ponto4.getHorarios().addElement("20:14");
		ponto4.getHorarios().addElement("21:00");
		ponto4.getHorarios().addElement("22:09");
		ponto4.getHorarios().addElement("23:00");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL QUATRO BARRAS");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("19/09/2009");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:19");
		ponto5.getHorarios().addElement("07:14");
		ponto5.getHorarios().addElement("08:14");
		ponto5.getHorarios().addElement("09:14");
		ponto5.getHorarios().addElement("10:14");
		ponto5.getHorarios().addElement("11:14");
		ponto5.getHorarios().addElement("13:14");
		ponto5.getHorarios().addElement("14:14");
		ponto5.getHorarios().addElement("15:14");
		ponto5.getHorarios().addElement("17:14");
		ponto5.getHorarios().addElement("18:15");
		ponto5.getHorarios().addElement("19:14");
		ponto5.getHorarios().addElement("20:09");
		ponto5.getHorarios().addElement("21:14");
		ponto5.getHorarios().addElement("22:00");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("GUADALUPE VIA ADALTO BOTELHO");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("19/09/2009");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("08:14");
		ponto6.getHorarios().addElement("13:19");
		ponto6.getHorarios().addElement("14:14");
		ponto6.getHorarios().addElement("18:14");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("Q.BARRAS (VIA ADALTO BOTELHO)");
		ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto7.setValidoAPartirDe("16/01/2011");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("06:10");
		ponto7.getHorarios().addElement("12:40");
		ponto7.getHorarios().addElement("15:45");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("TERMINAL GUADALUPE");
		ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto8.setValidoAPartirDe("16/01/2011");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("07:20");
		ponto8.getHorarios().addElement("09:20");
		ponto8.getHorarios().addElement("10:15");
		ponto8.getHorarios().addElement("11:25");
		ponto8.getHorarios().addElement("13:45");
		ponto8.getHorarios().addElement("14:35");
		ponto8.getHorarios().addElement("15:50");
		ponto8.getHorarios().addElement("16:55");
		ponto8.getHorarios().addElement("18:00");
		ponto8.getHorarios().addElement("20:10");
		ponto8.getHorarios().addElement("21:05");
		ponto8.getHorarios().addElement("22:20");
		ponto8.getHorarios().addElement("23:05");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("TERMINAL QUATRO BARRAS");
		ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto9.setValidoAPartirDe("16/01/2011");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("07:05");
		ponto9.getHorarios().addElement("08:20");
		ponto9.getHorarios().addElement("09:15");
		ponto9.getHorarios().addElement("10:20");
		ponto9.getHorarios().addElement("11:20");
		ponto9.getHorarios().addElement("13:35");
		ponto9.getHorarios().addElement("14:50");
		ponto9.getHorarios().addElement("16:50");
		ponto9.getHorarios().addElement("17:55");
		ponto9.getHorarios().addElement("19:10");
		ponto9.getHorarios().addElement("19:55");
		ponto9.getHorarios().addElement("21:10");
		ponto9.getHorarios().addElement("22:05");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("GUADALUPE VIA ADALTO BOTELHO");
		ponto10.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto10.setValidoAPartirDe("16/01/2011");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("08:05");
		ponto10.getHorarios().addElement("12:25");
		ponto10.getHorarios().addElement("18:55");
		return onibus;
		}
	}