
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus271 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("271 - LARANJEIRAS");
		  onibus.setCodigo("271");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO LARANJEIRAS");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("11/06/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:36");
		  ponto0.getHorarios().addElement("05:55");
		  ponto0.getHorarios().addElement("06:15");
		  ponto0.getHorarios().addElement("06:26");
		  ponto0.getHorarios().addElement("06:42");
		  ponto0.getHorarios().addElement("07:01");
		  ponto0.getHorarios().addElement("07:21");
		  ponto0.getHorarios().addElement("07:30");
		  ponto0.getHorarios().addElement("07:52");
		  ponto0.getHorarios().addElement("08:17");
		  ponto0.getHorarios().addElement("08:37");
		  ponto0.getHorarios().addElement("08:46");
		  ponto0.getHorarios().addElement("09:20");
		  ponto0.getHorarios().addElement("09:59");
		  ponto0.getHorarios().addElement("10:37");
		  ponto0.getHorarios().addElement("11:13");
		  ponto0.getHorarios().addElement("11:47");
		  ponto0.getHorarios().addElement("12:30");
		  ponto0.getHorarios().addElement("13:02");
		  ponto0.getHorarios().addElement("13:44");
		  ponto0.getHorarios().addElement("14:19");
		  ponto0.getHorarios().addElement("14:57");
		  ponto0.getHorarios().addElement("15:34");
		  ponto0.getHorarios().addElement("16:13");
		  ponto0.getHorarios().addElement("16:53");
		  ponto0.getHorarios().addElement("17:30");
		  ponto0.getHorarios().addElement("17:53");
		  ponto0.getHorarios().addElement("18:18");
		  ponto0.getHorarios().addElement("18:42");
		  ponto0.getHorarios().addElement("18:52");
		  ponto0.getHorarios().addElement("19:15");
		  ponto0.getHorarios().addElement("19:40");
		  ponto0.getHorarios().addElement("20:10");
		  ponto0.getHorarios().addElement("20:45");
		  ponto0.getHorarios().addElement("21:17");
		  ponto0.getHorarios().addElement("21:50");
		  ponto0.getHorarios().addElement("22:25");
		  ponto0.getHorarios().addElement("23:00");
		  ponto0.getHorarios().addElement("23:35");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TRAVESSA MOREIRA GARCEZ");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("11/06/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("06:11");
		  ponto1.getHorarios().addElement("06:33");
		  ponto1.getHorarios().addElement("06:51");
		  ponto1.getHorarios().addElement("07:00");
		  ponto1.getHorarios().addElement("07:17");
		  ponto1.getHorarios().addElement("07:41");
		  ponto1.getHorarios().addElement("08:02");
		  ponto1.getHorarios().addElement("08:10");
		  ponto1.getHorarios().addElement("08:40");
		  ponto1.getHorarios().addElement("09:24");
		  ponto1.getHorarios().addElement("09:59");
		  ponto1.getHorarios().addElement("10:35");
		  ponto1.getHorarios().addElement("11:11");
		  ponto1.getHorarios().addElement("11:49");
		  ponto1.getHorarios().addElement("12:25");
		  ponto1.getHorarios().addElement("13:07");
		  ponto1.getHorarios().addElement("13:42");
		  ponto1.getHorarios().addElement("14:21");
		  ponto1.getHorarios().addElement("14:57");
		  ponto1.getHorarios().addElement("15:35");
		  ponto1.getHorarios().addElement("16:11");
		  ponto1.getHorarios().addElement("16:50");
		  ponto1.getHorarios().addElement("17:11");
		  ponto1.getHorarios().addElement("17:36");
		  ponto1.getHorarios().addElement("17:58");
		  ponto1.getHorarios().addElement("18:09");
		  ponto1.getHorarios().addElement("18:30");
		  ponto1.getHorarios().addElement("18:56");
		  ponto1.getHorarios().addElement("19:20");
		  ponto1.getHorarios().addElement("19:30");
		  ponto1.getHorarios().addElement("19:50");
		  ponto1.getHorarios().addElement("20:15");
		  ponto1.getHorarios().addElement("20:45");
		  ponto1.getHorarios().addElement("21:16");
		  ponto1.getHorarios().addElement("21:50");
		  ponto1.getHorarios().addElement("22:25");
		  ponto1.getHorarios().addElement("23:00");
		  ponto1.getHorarios().addElement("23:35");
		  ponto1.getHorarios().addElement("00:05");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO LARANJEIRAS");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("05/07/2008");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:03");
		  ponto2.getHorarios().addElement("06:38");
		  ponto2.getHorarios().addElement("07:13");
		  ponto2.getHorarios().addElement("07:48");
		  ponto2.getHorarios().addElement("08:23");
		  ponto2.getHorarios().addElement("08:58");
		  ponto2.getHorarios().addElement("09:33");
		  ponto2.getHorarios().addElement("10:08");
		  ponto2.getHorarios().addElement("10:43");
		  ponto2.getHorarios().addElement("11:18");
		  ponto2.getHorarios().addElement("11:53");
		  ponto2.getHorarios().addElement("12:28");
		  ponto2.getHorarios().addElement("13:03");
		  ponto2.getHorarios().addElement("13:38");
		  ponto2.getHorarios().addElement("14:13");
		  ponto2.getHorarios().addElement("14:48");
		  ponto2.getHorarios().addElement("15:23");
		  ponto2.getHorarios().addElement("15:58");
		  ponto2.getHorarios().addElement("16:33");
		  ponto2.getHorarios().addElement("17:08");
		  ponto2.getHorarios().addElement("17:43");
		  ponto2.getHorarios().addElement("18:18");
		  ponto2.getHorarios().addElement("18:58");
		  ponto2.getHorarios().addElement("20:18");
		  ponto2.getHorarios().addElement("21:30");
		  ponto2.getHorarios().addElement("22:40");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TRAVESSA MOREIRA GARCEZ");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("05/07/2008");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:38");
		  ponto3.getHorarios().addElement("07:13");
		  ponto3.getHorarios().addElement("07:48");
		  ponto3.getHorarios().addElement("08:23");
		  ponto3.getHorarios().addElement("08:58");
		  ponto3.getHorarios().addElement("09:33");
		  ponto3.getHorarios().addElement("10:08");
		  ponto3.getHorarios().addElement("10:43");
		  ponto3.getHorarios().addElement("11:18");
		  ponto3.getHorarios().addElement("11:53");
		  ponto3.getHorarios().addElement("12:28");
		  ponto3.getHorarios().addElement("13:03");
		  ponto3.getHorarios().addElement("13:38");
		  ponto3.getHorarios().addElement("14:13");
		  ponto3.getHorarios().addElement("14:48");
		  ponto3.getHorarios().addElement("15:23");
		  ponto3.getHorarios().addElement("15:58");
		  ponto3.getHorarios().addElement("16:33");
		  ponto3.getHorarios().addElement("17:08");
		  ponto3.getHorarios().addElement("17:43");
		  ponto3.getHorarios().addElement("18:18");
		  ponto3.getHorarios().addElement("18:53");
		  ponto3.getHorarios().addElement("19:38");
		  ponto3.getHorarios().addElement("20:55");
		  ponto3.getHorarios().addElement("22:05");
		  ponto3.getHorarios().addElement("23:15");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO LARANJEIRAS");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("23/09/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:00");
		  ponto4.getHorarios().addElement("07:10");
		  ponto4.getHorarios().addElement("08:20");
		  ponto4.getHorarios().addElement("09:30");
		  ponto4.getHorarios().addElement("10:40");
		  ponto4.getHorarios().addElement("11:50");
		  ponto4.getHorarios().addElement("13:00");
		  ponto4.getHorarios().addElement("14:10");
		  ponto4.getHorarios().addElement("15:20");
		  ponto4.getHorarios().addElement("16:30");
		  ponto4.getHorarios().addElement("17:40");
		  ponto4.getHorarios().addElement("18:50");
		  ponto4.getHorarios().addElement("20:00");
		  ponto4.getHorarios().addElement("21:10");
		  ponto4.getHorarios().addElement("22:20");
		  ponto4.getHorarios().addElement("23:20");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TRAVESSA MOREIRA GARCEZ");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("23/09/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:35");
		  ponto5.getHorarios().addElement("07:45");
		  ponto5.getHorarios().addElement("08:55");
		  ponto5.getHorarios().addElement("10:05");
		  ponto5.getHorarios().addElement("11:15");
		  ponto5.getHorarios().addElement("12:25");
		  ponto5.getHorarios().addElement("13:35");
		  ponto5.getHorarios().addElement("14:45");
		  ponto5.getHorarios().addElement("15:55");
		  ponto5.getHorarios().addElement("17:05");
		  ponto5.getHorarios().addElement("18:15");
		  ponto5.getHorarios().addElement("19:25");
		  ponto5.getHorarios().addElement("20:35");
		  ponto5.getHorarios().addElement("21:45");
		  ponto5.getHorarios().addElement("22:50");
		  ponto5.getHorarios().addElement("23:50");
		  return onibus;
		  }
	  }