
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusB75 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("B75 - CTBA / JD. ARAPONGAS");
		  onibus.setCodigo("B75");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("JARDIM ARAPONGAS");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("26/03/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:55");
		  ponto0.getHorarios().addElement("06:30");
		  ponto0.getHorarios().addElement("07:20");
		  ponto0.getHorarios().addElement("07:55");
		  ponto0.getHorarios().addElement("08:45");
		  ponto0.getHorarios().addElement("09:20");
		  ponto0.getHorarios().addElement("10:10");
		  ponto0.getHorarios().addElement("11:35");
		  ponto0.getHorarios().addElement("12:05");
		  ponto0.getHorarios().addElement("13:07");
		  ponto0.getHorarios().addElement("13:40");
		  ponto0.getHorarios().addElement("15:05");
		  ponto0.getHorarios().addElement("16:33");
		  ponto0.getHorarios().addElement("17:38");
		  ponto0.getHorarios().addElement("18:11");
		  ponto0.getHorarios().addElement("19:13");
		  ponto0.getHorarios().addElement("19:55");
		  ponto0.getHorarios().addElement("20:40");
		  ponto0.getHorarios().addElement("21:20");
		  ponto0.getHorarios().addElement("22:05");
		  ponto0.getHorarios().addElement("22:45");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL GUADALUPE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("26/03/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("06:40");
		  ponto1.getHorarios().addElement("07:15");
		  ponto1.getHorarios().addElement("08:05");
		  ponto1.getHorarios().addElement("08:40");
		  ponto1.getHorarios().addElement("09:30");
		  ponto1.getHorarios().addElement("10:05");
		  ponto1.getHorarios().addElement("10:55");
		  ponto1.getHorarios().addElement("12:20");
		  ponto1.getHorarios().addElement("12:53");
		  ponto1.getHorarios().addElement("13:55");
		  ponto1.getHorarios().addElement("14:28");
		  ponto1.getHorarios().addElement("15:45");
		  ponto1.getHorarios().addElement("16:48");
		  ponto1.getHorarios().addElement("17:20");
		  ponto1.getHorarios().addElement("18:23");
		  ponto1.getHorarios().addElement("18:55");
		  ponto1.getHorarios().addElement("20:00");
		  ponto1.getHorarios().addElement("20:40");
		  ponto1.getHorarios().addElement("21:20");
		  ponto1.getHorarios().addElement("22:00");
		  ponto1.getHorarios().addElement("22:45");
		  ponto1.getHorarios().addElement("23:25");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("JARDIM ARAPONGAS");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("25/07/2009");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:00");
		  ponto2.getHorarios().addElement("06:30");
		  ponto2.getHorarios().addElement("07:10");
		  ponto2.getHorarios().addElement("07:50");
		  ponto2.getHorarios().addElement("08:20");
		  ponto2.getHorarios().addElement("09:00");
		  ponto2.getHorarios().addElement("10:15");
		  ponto2.getHorarios().addElement("11:30");
		  ponto2.getHorarios().addElement("12:15");
		  ponto2.getHorarios().addElement("12:40");
		  ponto2.getHorarios().addElement("13:30");
		  ponto2.getHorarios().addElement("14:45");
		  ponto2.getHorarios().addElement("16:40");
		  ponto2.getHorarios().addElement("17:15");
		  ponto2.getHorarios().addElement("18:00");
		  ponto2.getHorarios().addElement("18:40");
		  ponto2.getHorarios().addElement("19:20");
		  ponto2.getHorarios().addElement("19:55");
		  ponto2.getHorarios().addElement("20:30");
		  ponto2.getHorarios().addElement("21:20");
		  ponto2.getHorarios().addElement("22:00");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL GUADALUPE");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("25/07/2009");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:35");
		  ponto3.getHorarios().addElement("07:10");
		  ponto3.getHorarios().addElement("07:50");
		  ponto3.getHorarios().addElement("08:25");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("09:40");
		  ponto3.getHorarios().addElement("10:55");
		  ponto3.getHorarios().addElement("12:05");
		  ponto3.getHorarios().addElement("12:55");
		  ponto3.getHorarios().addElement("13:25");
		  ponto3.getHorarios().addElement("14:10");
		  ponto3.getHorarios().addElement("15:25");
		  ponto3.getHorarios().addElement("17:25");
		  ponto3.getHorarios().addElement("17:55");
		  ponto3.getHorarios().addElement("18:40");
		  ponto3.getHorarios().addElement("19:20");
		  ponto3.getHorarios().addElement("19:55");
		  ponto3.getHorarios().addElement("20:30");
		  ponto3.getHorarios().addElement("21:15");
		  ponto3.getHorarios().addElement("22:00");
		  ponto3.getHorarios().addElement("22:45");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("JARDIM ARAPONGAS");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("26/07/2009");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("07:30");
		  ponto4.getHorarios().addElement("09:00");
		  ponto4.getHorarios().addElement("10:30");
		  ponto4.getHorarios().addElement("13:00");
		  ponto4.getHorarios().addElement("13:30");
		  ponto4.getHorarios().addElement("14:30");
		  ponto4.getHorarios().addElement("15:00");
		  ponto4.getHorarios().addElement("16:00");
		  ponto4.getHorarios().addElement("16:30");
		  ponto4.getHorarios().addElement("17:30");
		  ponto4.getHorarios().addElement("18:00");
		  ponto4.getHorarios().addElement("19:00");
		  ponto4.getHorarios().addElement("20:30");
		  ponto4.getHorarios().addElement("22:00");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL GUADALUPE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("26/07/2009");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("08:15");
		  ponto5.getHorarios().addElement("09:45");
		  ponto5.getHorarios().addElement("11:15");
		  ponto5.getHorarios().addElement("13:45");
		  ponto5.getHorarios().addElement("14:15");
		  ponto5.getHorarios().addElement("15:15");
		  ponto5.getHorarios().addElement("15:45");
		  ponto5.getHorarios().addElement("16:45");
		  ponto5.getHorarios().addElement("17:15");
		  ponto5.getHorarios().addElement("18:15");
		  ponto5.getHorarios().addElement("18:45");
		  ponto5.getHorarios().addElement("19:45");
		  ponto5.getHorarios().addElement("21:15");
		  ponto5.getHorarios().addElement("22:45");
		  return onibus;
		  }
	  }