
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus965 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("965 - SÃO BERNARDO");
		  onibus.setCodigo("965");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("RUA LAURO MALLIN (TROMBINNI 2)");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("10/09/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("23:05");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("RUA BARAO DO CERRO AZUL");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("10/09/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("06:19");
		  ponto1.getHorarios().addElement("06:36");
		  ponto1.getHorarios().addElement("06:53");
		  ponto1.getHorarios().addElement("07:10");
		  ponto1.getHorarios().addElement("07:27");
		  ponto1.getHorarios().addElement("07:45");
		  ponto1.getHorarios().addElement("08:05");
		  ponto1.getHorarios().addElement("08:25");
		  ponto1.getHorarios().addElement("08:37");
		  ponto1.getHorarios().addElement("08:55");
		  ponto1.getHorarios().addElement("09:18");
		  ponto1.getHorarios().addElement("09:43");
		  ponto1.getHorarios().addElement("10:08");
		  ponto1.getHorarios().addElement("10:33");
		  ponto1.getHorarios().addElement("10:58");
		  ponto1.getHorarios().addElement("11:23");
		  ponto1.getHorarios().addElement("11:48");
		  ponto1.getHorarios().addElement("12:12");
		  ponto1.getHorarios().addElement("12:36");
		  ponto1.getHorarios().addElement("13:01");
		  ponto1.getHorarios().addElement("13:26");
		  ponto1.getHorarios().addElement("13:51");
		  ponto1.getHorarios().addElement("14:17");
		  ponto1.getHorarios().addElement("14:42");
		  ponto1.getHorarios().addElement("15:08");
		  ponto1.getHorarios().addElement("15:34");
		  ponto1.getHorarios().addElement("15:56");
		  ponto1.getHorarios().addElement("16:14");
		  ponto1.getHorarios().addElement("16:33");
		  ponto1.getHorarios().addElement("16:54");
		  ponto1.getHorarios().addElement("17:14");
		  ponto1.getHorarios().addElement("17:34");
		  ponto1.getHorarios().addElement("17:55");
		  ponto1.getHorarios().addElement("18:14");
		  ponto1.getHorarios().addElement("18:32");
		  ponto1.getHorarios().addElement("18:52");
		  ponto1.getHorarios().addElement("19:13");
		  ponto1.getHorarios().addElement("19:35");
		  ponto1.getHorarios().addElement("19:58");
		  ponto1.getHorarios().addElement("20:29");
		  ponto1.getHorarios().addElement("21:00");
		  ponto1.getHorarios().addElement("21:30");
		  ponto1.getHorarios().addElement("22:00");
		  ponto1.getHorarios().addElement("22:29");
		  ponto1.getHorarios().addElement("23:00");
		  ponto1.getHorarios().addElement("23:30");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL SANTA FELICIDADE");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("10/09/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:46");
		  ponto2.getHorarios().addElement("06:02");
		  ponto2.getHorarios().addElement("06:19");
		  ponto2.getHorarios().addElement("06:36");
		  ponto2.getHorarios().addElement("06:53");
		  ponto2.getHorarios().addElement("07:10");
		  ponto2.getHorarios().addElement("07:27");
		  ponto2.getHorarios().addElement("07:44");
		  ponto2.getHorarios().addElement("08:02");
		  ponto2.getHorarios().addElement("08:20");
		  ponto2.getHorarios().addElement("08:42");
		  ponto2.getHorarios().addElement("09:06");
		  ponto2.getHorarios().addElement("09:30");
		  ponto2.getHorarios().addElement("09:55");
		  ponto2.getHorarios().addElement("10:20");
		  ponto2.getHorarios().addElement("10:45");
		  ponto2.getHorarios().addElement("11:10");
		  ponto2.getHorarios().addElement("11:35");
		  ponto2.getHorarios().addElement("12:00");
		  ponto2.getHorarios().addElement("12:25");
		  ponto2.getHorarios().addElement("12:49");
		  ponto2.getHorarios().addElement("13:13");
		  ponto2.getHorarios().addElement("13:37");
		  ponto2.getHorarios().addElement("14:03");
		  ponto2.getHorarios().addElement("14:29");
		  ponto2.getHorarios().addElement("14:55");
		  ponto2.getHorarios().addElement("15:21");
		  ponto2.getHorarios().addElement("15:48");
		  ponto2.getHorarios().addElement("16:13");
		  ponto2.getHorarios().addElement("16:35");
		  ponto2.getHorarios().addElement("16:55");
		  ponto2.getHorarios().addElement("17:15");
		  ponto2.getHorarios().addElement("17:35");
		  ponto2.getHorarios().addElement("17:55");
		  ponto2.getHorarios().addElement("18:15");
		  ponto2.getHorarios().addElement("18:36");
		  ponto2.getHorarios().addElement("18:58");
		  ponto2.getHorarios().addElement("19:20");
		  ponto2.getHorarios().addElement("19:54");
		  ponto2.getHorarios().addElement("20:28");
		  ponto2.getHorarios().addElement("21:00");
		  ponto2.getHorarios().addElement("21:30");
		  ponto2.getHorarios().addElement("22:00");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("22:55");
		  ponto2.getHorarios().addElement("23:30");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("PRACA DIVINA PASTORA (M.RIBAS)");
		  ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto3.setValidoAPartirDe("10/09/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:35");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("R.BARAO DO CERRO AZUL-CHEGADA");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto4.setValidoAPartirDe("10/09/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("23:20");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("RUA BARAO DO CERRO AZUL");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("28/08/2010");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:23");
		  ponto5.getHorarios().addElement("06:53");
		  ponto5.getHorarios().addElement("07:29");
		  ponto5.getHorarios().addElement("07:59");
		  ponto5.getHorarios().addElement("08:35");
		  ponto5.getHorarios().addElement("09:07");
		  ponto5.getHorarios().addElement("09:45");
		  ponto5.getHorarios().addElement("10:17");
		  ponto5.getHorarios().addElement("10:55");
		  ponto5.getHorarios().addElement("11:27");
		  ponto5.getHorarios().addElement("12:05");
		  ponto5.getHorarios().addElement("12:37");
		  ponto5.getHorarios().addElement("13:15");
		  ponto5.getHorarios().addElement("13:47");
		  ponto5.getHorarios().addElement("14:25");
		  ponto5.getHorarios().addElement("15:30");
		  ponto5.getHorarios().addElement("16:30");
		  ponto5.getHorarios().addElement("17:30");
		  ponto5.getHorarios().addElement("18:30");
		  ponto5.getHorarios().addElement("19:30");
		  ponto5.getHorarios().addElement("20:30");
		  ponto5.getHorarios().addElement("21:30");
		  ponto5.getHorarios().addElement("22:30");
		  ponto5.getHorarios().addElement("23:30");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("TERMINAL SANTA FELICIDADE");
		  ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto6.setValidoAPartirDe("28/08/2010");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("05:50");
		  ponto6.getHorarios().addElement("06:20");
		  ponto6.getHorarios().addElement("06:56");
		  ponto6.getHorarios().addElement("07:26");
		  ponto6.getHorarios().addElement("08:02");
		  ponto6.getHorarios().addElement("08:32");
		  ponto6.getHorarios().addElement("09:10");
		  ponto6.getHorarios().addElement("09:42");
		  ponto6.getHorarios().addElement("10:20");
		  ponto6.getHorarios().addElement("10:52");
		  ponto6.getHorarios().addElement("11:30");
		  ponto6.getHorarios().addElement("12:02");
		  ponto6.getHorarios().addElement("12:40");
		  ponto6.getHorarios().addElement("13:12");
		  ponto6.getHorarios().addElement("13:50");
		  ponto6.getHorarios().addElement("15:00");
		  ponto6.getHorarios().addElement("16:00");
		  ponto6.getHorarios().addElement("17:00");
		  ponto6.getHorarios().addElement("18:00");
		  ponto6.getHorarios().addElement("19:00");
		  ponto6.getHorarios().addElement("20:00");
		  ponto6.getHorarios().addElement("21:00");
		  ponto6.getHorarios().addElement("22:00");
		  ponto6.getHorarios().addElement("23:00");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("RUA BARAO DO CERRO AZUL");
		  ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto7.setValidoAPartirDe("10/09/2006");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("06:30");
		  ponto7.getHorarios().addElement("07:30");
		  ponto7.getHorarios().addElement("08:30");
		  ponto7.getHorarios().addElement("09:30");
		  ponto7.getHorarios().addElement("10:30");
		  ponto7.getHorarios().addElement("11:30");
		  ponto7.getHorarios().addElement("12:30");
		  ponto7.getHorarios().addElement("13:30");
		  ponto7.getHorarios().addElement("14:30");
		  ponto7.getHorarios().addElement("15:30");
		  ponto7.getHorarios().addElement("16:30");
		  ponto7.getHorarios().addElement("17:30");
		  ponto7.getHorarios().addElement("18:30");
		  ponto7.getHorarios().addElement("19:30");
		  ponto7.getHorarios().addElement("20:30");
		  ponto7.getHorarios().addElement("21:30");
		  ponto7.getHorarios().addElement("22:30");
		  ponto7.getHorarios().addElement("23:30");
		  Ponto ponto8 = new Ponto();
		  ponto8.setNome("TERMINAL SANTA FELICIDADE");
		  ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto8.setValidoAPartirDe("10/09/2006");
		  onibus.getPontos().addElement(ponto8);
		  ponto8.getHorarios().addElement("06:00");
		  ponto8.getHorarios().addElement("07:00");
		  ponto8.getHorarios().addElement("08:00");
		  ponto8.getHorarios().addElement("09:00");
		  ponto8.getHorarios().addElement("10:00");
		  ponto8.getHorarios().addElement("11:00");
		  ponto8.getHorarios().addElement("12:00");
		  ponto8.getHorarios().addElement("13:00");
		  ponto8.getHorarios().addElement("14:00");
		  ponto8.getHorarios().addElement("15:00");
		  ponto8.getHorarios().addElement("16:00");
		  ponto8.getHorarios().addElement("17:00");
		  ponto8.getHorarios().addElement("18:00");
		  ponto8.getHorarios().addElement("19:00");
		  ponto8.getHorarios().addElement("20:00");
		  ponto8.getHorarios().addElement("21:00");
		  ponto8.getHorarios().addElement("22:00");
		  ponto8.getHorarios().addElement("23:00");
		  return onibus;
		  }
	  }