
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class Onibus474 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("474 - JD. ITIBERÊ");
		onibus.setCodigo("474");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO ITIBERE");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("16/05/2011");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:55");
		ponto0.getHorarios().addElement("06:19");
		ponto0.getHorarios().addElement("06:42");
		ponto0.getHorarios().addElement("07:05");
		ponto0.getHorarios().addElement("07:29");
		ponto0.getHorarios().addElement("07:52");
		ponto0.getHorarios().addElement("08:15");
		ponto0.getHorarios().addElement("08:40");
		ponto0.getHorarios().addElement("09:52");
		ponto0.getHorarios().addElement("11:04");
		ponto0.getHorarios().addElement("12:16");
		ponto0.getHorarios().addElement("12:52");
		ponto0.getHorarios().addElement("13:28");
		ponto0.getHorarios().addElement("14:04");
		ponto0.getHorarios().addElement("14:40");
		ponto0.getHorarios().addElement("15:52");
		ponto0.getHorarios().addElement("17:04");
		ponto0.getHorarios().addElement("17:46");
		ponto0.getHorarios().addElement("18:24");
		ponto0.getHorarios().addElement("18:50");
		ponto0.getHorarios().addElement("19:17");
		ponto0.getHorarios().addElement("19:40");
		ponto0.getHorarios().addElement("20:50");
		ponto0.getHorarios().addElement("22:00");
		ponto0.getHorarios().addElement("23:02");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("PRACA RUI BARBOSA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("16/05/2011");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:31");
		ponto1.getHorarios().addElement("06:55");
		ponto1.getHorarios().addElement("07:18");
		ponto1.getHorarios().addElement("07:41");
		ponto1.getHorarios().addElement("08:05");
		ponto1.getHorarios().addElement("09:17");
		ponto1.getHorarios().addElement("10:29");
		ponto1.getHorarios().addElement("11:41");
		ponto1.getHorarios().addElement("12:17");
		ponto1.getHorarios().addElement("12:53");
		ponto1.getHorarios().addElement("13:29");
		ponto1.getHorarios().addElement("14:05");
		ponto1.getHorarios().addElement("15:17");
		ponto1.getHorarios().addElement("16:29");
		ponto1.getHorarios().addElement("17:07");
		ponto1.getHorarios().addElement("17:45");
		ponto1.getHorarios().addElement("18:10");
		ponto1.getHorarios().addElement("18:35");
		ponto1.getHorarios().addElement("19:00");
		ponto1.getHorarios().addElement("19:25");
		ponto1.getHorarios().addElement("19:50");
		ponto1.getHorarios().addElement("20:15");
		ponto1.getHorarios().addElement("21:25");
		ponto1.getHorarios().addElement("22:35");
		ponto1.getHorarios().addElement("23:33");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("BAIRRO ITIBERE");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("19/03/2011");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:13");
		ponto2.getHorarios().addElement("07:22");
		ponto2.getHorarios().addElement("08:31");
		ponto2.getHorarios().addElement("09:40");
		ponto2.getHorarios().addElement("10:49");
		ponto2.getHorarios().addElement("11:58");
		ponto2.getHorarios().addElement("13:07");
		ponto2.getHorarios().addElement("14:16");
		ponto2.getHorarios().addElement("15:25");
		ponto2.getHorarios().addElement("16:34");
		ponto2.getHorarios().addElement("17:43");
		ponto2.getHorarios().addElement("18:52");
		ponto2.getHorarios().addElement("20:13");
		ponto2.getHorarios().addElement("21:27");
		ponto2.getHorarios().addElement("22:34");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("PRACA RUI BARBOSA");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("19/03/2011");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:48");
		ponto3.getHorarios().addElement("07:57");
		ponto3.getHorarios().addElement("09:06");
		ponto3.getHorarios().addElement("10:15");
		ponto3.getHorarios().addElement("11:24");
		ponto3.getHorarios().addElement("12:33");
		ponto3.getHorarios().addElement("13:42");
		ponto3.getHorarios().addElement("14:51");
		ponto3.getHorarios().addElement("16:00");
		ponto3.getHorarios().addElement("17:09");
		ponto3.getHorarios().addElement("18:17");
		ponto3.getHorarios().addElement("19:33");
		ponto3.getHorarios().addElement("20:53");
		ponto3.getHorarios().addElement("22:00");
		ponto3.getHorarios().addElement("23:10");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO ITIBERE");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("05/12/2010");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:20");
		ponto4.getHorarios().addElement("07:29");
		ponto4.getHorarios().addElement("08:38");
		ponto4.getHorarios().addElement("09:47");
		ponto4.getHorarios().addElement("10:56");
		ponto4.getHorarios().addElement("12:05");
		ponto4.getHorarios().addElement("13:14");
		ponto4.getHorarios().addElement("14:23");
		ponto4.getHorarios().addElement("15:32");
		ponto4.getHorarios().addElement("16:41");
		ponto4.getHorarios().addElement("17:50");
		ponto4.getHorarios().addElement("18:58");
		ponto4.getHorarios().addElement("20:02");
		ponto4.getHorarios().addElement("21:06");
		ponto4.getHorarios().addElement("22:10");
		ponto4.getHorarios().addElement("23:18");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("PRACA RUI BARBOSA");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("05/12/2010");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:55");
		ponto5.getHorarios().addElement("08:04");
		ponto5.getHorarios().addElement("09:12");
		ponto5.getHorarios().addElement("10:22");
		ponto5.getHorarios().addElement("11:31");
		ponto5.getHorarios().addElement("12:40");
		ponto5.getHorarios().addElement("13:49");
		ponto5.getHorarios().addElement("14:58");
		ponto5.getHorarios().addElement("16:07");
		ponto5.getHorarios().addElement("17:16");
		ponto5.getHorarios().addElement("18:23");
		ponto5.getHorarios().addElement("19:30");
		ponto5.getHorarios().addElement("20:34");
		ponto5.getHorarios().addElement("21:38");
		ponto5.getHorarios().addElement("22:43");
		ponto5.getHorarios().addElement("23:52");
		return onibus;
		}
	}