
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusC66 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("CTBA / V. ZUMBI");
		onibus.setCodigo("C66");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO VILA ZUMBI");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("21/11/2011");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:20");
		ponto0.getHorarios().addElement("05:45");
		ponto0.getHorarios().addElement("06:20");
		ponto0.getHorarios().addElement("06:50");
		ponto0.getHorarios().addElement("07:20");
		ponto0.getHorarios().addElement("07:50");
		ponto0.getHorarios().addElement("08:20");
		ponto0.getHorarios().addElement("08:53");
		ponto0.getHorarios().addElement("09:35");
		ponto0.getHorarios().addElement("10:29");
		ponto0.getHorarios().addElement("11:17");
		ponto0.getHorarios().addElement("12:05");
		ponto0.getHorarios().addElement("12:53");
		ponto0.getHorarios().addElement("13:41");
		ponto0.getHorarios().addElement("14:29");
		ponto0.getHorarios().addElement("15:17");
		ponto0.getHorarios().addElement("16:13");
		ponto0.getHorarios().addElement("16:53");
		ponto0.getHorarios().addElement("17:25");
		ponto0.getHorarios().addElement("17:57");
		ponto0.getHorarios().addElement("18:29");
		ponto0.getHorarios().addElement("19:01");
		ponto0.getHorarios().addElement("19:38");
		ponto0.getHorarios().addElement("20:10");
		ponto0.getHorarios().addElement("21:05");
		ponto0.getHorarios().addElement("21:50");
		ponto0.getHorarios().addElement("22:35");
		ponto0.getHorarios().addElement("23:20");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL GUADALUPE");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("21/11/2011");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:05");
		ponto1.getHorarios().addElement("06:25");
		ponto1.getHorarios().addElement("07:00");
		ponto1.getHorarios().addElement("07:35");
		ponto1.getHorarios().addElement("08:05");
		ponto1.getHorarios().addElement("08:50");
		ponto1.getHorarios().addElement("09:41");
		ponto1.getHorarios().addElement("10:29");
		ponto1.getHorarios().addElement("11:17");
		ponto1.getHorarios().addElement("12:05");
		ponto1.getHorarios().addElement("12:53");
		ponto1.getHorarios().addElement("13:41");
		ponto1.getHorarios().addElement("14:29");
		ponto1.getHorarios().addElement("15:17");
		ponto1.getHorarios().addElement("16:05");
		ponto1.getHorarios().addElement("16:37");
		ponto1.getHorarios().addElement("17:09");
		ponto1.getHorarios().addElement("17:41");
		ponto1.getHorarios().addElement("18:13");
		ponto1.getHorarios().addElement("18:45");
		ponto1.getHorarios().addElement("19:17");
		ponto1.getHorarios().addElement("19:49");
		ponto1.getHorarios().addElement("20:30");
		ponto1.getHorarios().addElement("21:05");
		ponto1.getHorarios().addElement("21:50");
		ponto1.getHorarios().addElement("22:35");
		ponto1.getHorarios().addElement("23:20");
		ponto1.getHorarios().addElement("00:05");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("BAIRRO VILA ZUMBI");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("14/05/2005");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:30");
		ponto2.getHorarios().addElement("06:15");
		ponto2.getHorarios().addElement("07:00");
		ponto2.getHorarios().addElement("07:45");
		ponto2.getHorarios().addElement("08:30");
		ponto2.getHorarios().addElement("09:15");
		ponto2.getHorarios().addElement("10:45");
		ponto2.getHorarios().addElement("12:15");
		ponto2.getHorarios().addElement("13:00");
		ponto2.getHorarios().addElement("13:45");
		ponto2.getHorarios().addElement("15:15");
		ponto2.getHorarios().addElement("16:45");
		ponto2.getHorarios().addElement("18:15");
		ponto2.getHorarios().addElement("19:45");
		ponto2.getHorarios().addElement("21:15");
		ponto2.getHorarios().addElement("22:35");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL GUADALUPE");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("14/05/2005");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:15");
		ponto3.getHorarios().addElement("07:00");
		ponto3.getHorarios().addElement("07:45");
		ponto3.getHorarios().addElement("08:30");
		ponto3.getHorarios().addElement("10:00");
		ponto3.getHorarios().addElement("11:30");
		ponto3.getHorarios().addElement("12:15");
		ponto3.getHorarios().addElement("13:00");
		ponto3.getHorarios().addElement("13:50");
		ponto3.getHorarios().addElement("14:30");
		ponto3.getHorarios().addElement("16:00");
		ponto3.getHorarios().addElement("17:30");
		ponto3.getHorarios().addElement("19:00");
		ponto3.getHorarios().addElement("20:30");
		ponto3.getHorarios().addElement("21:55");
		ponto3.getHorarios().addElement("23:15");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO VILA ZUMBI");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("04/03/2007");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:50");
		ponto4.getHorarios().addElement("07:00");
		ponto4.getHorarios().addElement("08:30");
		ponto4.getHorarios().addElement("10:00");
		ponto4.getHorarios().addElement("11:30");
		ponto4.getHorarios().addElement("13:00");
		ponto4.getHorarios().addElement("14:30");
		ponto4.getHorarios().addElement("16:00");
		ponto4.getHorarios().addElement("17:30");
		ponto4.getHorarios().addElement("19:00");
		ponto4.getHorarios().addElement("20:30");
		ponto4.getHorarios().addElement("22:00");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL GUADALUPE");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("04/03/2007");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:25");
		ponto5.getHorarios().addElement("07:45");
		ponto5.getHorarios().addElement("09:15");
		ponto5.getHorarios().addElement("10:45");
		ponto5.getHorarios().addElement("12:15");
		ponto5.getHorarios().addElement("13:50");
		ponto5.getHorarios().addElement("15:15");
		ponto5.getHorarios().addElement("16:45");
		ponto5.getHorarios().addElement("18:15");
		ponto5.getHorarios().addElement("19:45");
		ponto5.getHorarios().addElement("21:15");
		ponto5.getHorarios().addElement("22:45");
		return onibus;
		}
	}