
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusE21 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("T. BOQ. / T. CENTRAL");
		onibus.setCodigo("E21");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("TERMINAL BOQUEIRAO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("04/07/2011");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:37");
		ponto0.getHorarios().addElement("07:04");
		ponto0.getHorarios().addElement("07:34");
		ponto0.getHorarios().addElement("08:04");
		ponto0.getHorarios().addElement("08:34");
		ponto0.getHorarios().addElement("09:03");
		ponto0.getHorarios().addElement("09:33");
		ponto0.getHorarios().addElement("10:03");
		ponto0.getHorarios().addElement("10:33");
		ponto0.getHorarios().addElement("11:03");
		ponto0.getHorarios().addElement("11:33");
		ponto0.getHorarios().addElement("12:03");
		ponto0.getHorarios().addElement("12:33");
		ponto0.getHorarios().addElement("13:03");
		ponto0.getHorarios().addElement("13:33");
		ponto0.getHorarios().addElement("14:03");
		ponto0.getHorarios().addElement("14:33");
		ponto0.getHorarios().addElement("15:03");
		ponto0.getHorarios().addElement("15:33");
		ponto0.getHorarios().addElement("16:03");
		ponto0.getHorarios().addElement("16:33");
		ponto0.getHorarios().addElement("17:03");
		ponto0.getHorarios().addElement("17:35");
		ponto0.getHorarios().addElement("18:00");
		ponto0.getHorarios().addElement("18:20");
		ponto0.getHorarios().addElement("18:40");
		ponto0.getHorarios().addElement("19:00");
		ponto0.getHorarios().addElement("19:15");
		ponto0.getHorarios().addElement("19:35");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL CENTRAL");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("04/07/2011");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:25");
		ponto1.getHorarios().addElement("06:50");
		ponto1.getHorarios().addElement("07:20");
		ponto1.getHorarios().addElement("07:50");
		ponto1.getHorarios().addElement("08:20");
		ponto1.getHorarios().addElement("08:50");
		ponto1.getHorarios().addElement("09:20");
		ponto1.getHorarios().addElement("09:50");
		ponto1.getHorarios().addElement("10:20");
		ponto1.getHorarios().addElement("10:50");
		ponto1.getHorarios().addElement("11:20");
		ponto1.getHorarios().addElement("11:50");
		ponto1.getHorarios().addElement("12:20");
		ponto1.getHorarios().addElement("12:50");
		ponto1.getHorarios().addElement("13:20");
		ponto1.getHorarios().addElement("13:50");
		ponto1.getHorarios().addElement("14:20");
		ponto1.getHorarios().addElement("14:50");
		ponto1.getHorarios().addElement("15:20");
		ponto1.getHorarios().addElement("15:50");
		ponto1.getHorarios().addElement("16:20");
		ponto1.getHorarios().addElement("16:50");
		ponto1.getHorarios().addElement("17:20");
		ponto1.getHorarios().addElement("17:40");
		ponto1.getHorarios().addElement("18:00");
		ponto1.getHorarios().addElement("18:20");
		ponto1.getHorarios().addElement("18:40");
		ponto1.getHorarios().addElement("19:00");
		ponto1.getHorarios().addElement("19:20");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL BOQUEIRAO");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("30/07/2011");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("07:22");
		ponto2.getHorarios().addElement("07:49");
		ponto2.getHorarios().addElement("08:16");
		ponto2.getHorarios().addElement("08:47");
		ponto2.getHorarios().addElement("09:19");
		ponto2.getHorarios().addElement("09:51");
		ponto2.getHorarios().addElement("10:23");
		ponto2.getHorarios().addElement("10:55");
		ponto2.getHorarios().addElement("11:25");
		ponto2.getHorarios().addElement("11:55");
		ponto2.getHorarios().addElement("12:25");
		ponto2.getHorarios().addElement("12:55");
		ponto2.getHorarios().addElement("13:25");
		ponto2.getHorarios().addElement("13:55");
		ponto2.getHorarios().addElement("14:25");
		ponto2.getHorarios().addElement("14:55");
		ponto2.getHorarios().addElement("15:25");
		ponto2.getHorarios().addElement("15:55");
		ponto2.getHorarios().addElement("16:25");
		ponto2.getHorarios().addElement("16:55");
		ponto2.getHorarios().addElement("17:25");
		ponto2.getHorarios().addElement("17:55");
		ponto2.getHorarios().addElement("18:25");
		ponto2.getHorarios().addElement("18:55");
		ponto2.getHorarios().addElement("19:25");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL CENTRAL");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("30/07/2011");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("07:10");
		ponto3.getHorarios().addElement("07:37");
		ponto3.getHorarios().addElement("08:04");
		ponto3.getHorarios().addElement("08:31");
		ponto3.getHorarios().addElement("09:03");
		ponto3.getHorarios().addElement("09:35");
		ponto3.getHorarios().addElement("10:07");
		ponto3.getHorarios().addElement("10:40");
		ponto3.getHorarios().addElement("11:10");
		ponto3.getHorarios().addElement("11:40");
		ponto3.getHorarios().addElement("12:10");
		ponto3.getHorarios().addElement("12:40");
		ponto3.getHorarios().addElement("13:10");
		ponto3.getHorarios().addElement("13:40");
		ponto3.getHorarios().addElement("14:10");
		ponto3.getHorarios().addElement("14:40");
		ponto3.getHorarios().addElement("15:10");
		ponto3.getHorarios().addElement("15:40");
		ponto3.getHorarios().addElement("16:10");
		ponto3.getHorarios().addElement("16:40");
		ponto3.getHorarios().addElement("17:10");
		ponto3.getHorarios().addElement("17:40");
		ponto3.getHorarios().addElement("18:10");
		ponto3.getHorarios().addElement("18:40");
		ponto3.getHorarios().addElement("19:10");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL BOQUEIRAO");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("28/05/2006");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("15:55");
		ponto4.getHorarios().addElement("16:25");
		ponto4.getHorarios().addElement("16:55");
		ponto4.getHorarios().addElement("17:25");
		ponto4.getHorarios().addElement("17:55");
		ponto4.getHorarios().addElement("18:25");
		ponto4.getHorarios().addElement("18:55");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL CENTRAL");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("28/05/2006");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("15:40");
		ponto5.getHorarios().addElement("16:10");
		ponto5.getHorarios().addElement("16:40");
		ponto5.getHorarios().addElement("17:10");
		ponto5.getHorarios().addElement("17:40");
		ponto5.getHorarios().addElement("18:10");
		ponto5.getHorarios().addElement("18:40");
		return onibus;
		}
	}