
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus918 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("918 - VENEZA");
		  onibus.setCodigo("918");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO VENEZA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("29/09/2008");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("06:05");
		  ponto0.getHorarios().addElement("06:45");
		  ponto0.getHorarios().addElement("07:25");
		  ponto0.getHorarios().addElement("08:05");
		  ponto0.getHorarios().addElement("08:45");
		  ponto0.getHorarios().addElement("09:27");
		  ponto0.getHorarios().addElement("10:12");
		  ponto0.getHorarios().addElement("10:57");
		  ponto0.getHorarios().addElement("11:40");
		  ponto0.getHorarios().addElement("12:20");
		  ponto0.getHorarios().addElement("13:00");
		  ponto0.getHorarios().addElement("13:40");
		  ponto0.getHorarios().addElement("14:20");
		  ponto0.getHorarios().addElement("15:00");
		  ponto0.getHorarios().addElement("15:40");
		  ponto0.getHorarios().addElement("16:20");
		  ponto0.getHorarios().addElement("17:00");
		  ponto0.getHorarios().addElement("17:40");
		  ponto0.getHorarios().addElement("18:20");
		  ponto0.getHorarios().addElement("19:00");
		  ponto0.getHorarios().addElement("19:40");
		  ponto0.getHorarios().addElement("20:20");
		  ponto0.getHorarios().addElement("21:00");
		  ponto0.getHorarios().addElement("21:40");
		  ponto0.getHorarios().addElement("22:23");
		  ponto0.getHorarios().addElement("23:00");
		  ponto0.getHorarios().addElement("23:35");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL SANTA FELICIDADE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("29/09/2008");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:48");
		  ponto1.getHorarios().addElement("06:25");
		  ponto1.getHorarios().addElement("07:05");
		  ponto1.getHorarios().addElement("07:45");
		  ponto1.getHorarios().addElement("08:25");
		  ponto1.getHorarios().addElement("09:05");
		  ponto1.getHorarios().addElement("09:50");
		  ponto1.getHorarios().addElement("10:35");
		  ponto1.getHorarios().addElement("11:20");
		  ponto1.getHorarios().addElement("12:00");
		  ponto1.getHorarios().addElement("12:40");
		  ponto1.getHorarios().addElement("13:20");
		  ponto1.getHorarios().addElement("14:00");
		  ponto1.getHorarios().addElement("14:40");
		  ponto1.getHorarios().addElement("15:20");
		  ponto1.getHorarios().addElement("16:00");
		  ponto1.getHorarios().addElement("16:40");
		  ponto1.getHorarios().addElement("17:20");
		  ponto1.getHorarios().addElement("18:00");
		  ponto1.getHorarios().addElement("18:40");
		  ponto1.getHorarios().addElement("19:20");
		  ponto1.getHorarios().addElement("20:00");
		  ponto1.getHorarios().addElement("20:40");
		  ponto1.getHorarios().addElement("21:20");
		  ponto1.getHorarios().addElement("22:03");
		  ponto1.getHorarios().addElement("22:45");
		  ponto1.getHorarios().addElement("23:20");
		  ponto1.getHorarios().addElement("23:55");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO VENEZA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("18/03/2006");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:00");
		  ponto2.getHorarios().addElement("06:40");
		  ponto2.getHorarios().addElement("07:20");
		  ponto2.getHorarios().addElement("08:00");
		  ponto2.getHorarios().addElement("08:40");
		  ponto2.getHorarios().addElement("09:20");
		  ponto2.getHorarios().addElement("10:00");
		  ponto2.getHorarios().addElement("10:40");
		  ponto2.getHorarios().addElement("11:20");
		  ponto2.getHorarios().addElement("12:00");
		  ponto2.getHorarios().addElement("12:40");
		  ponto2.getHorarios().addElement("13:20");
		  ponto2.getHorarios().addElement("14:00");
		  ponto2.getHorarios().addElement("14:40");
		  ponto2.getHorarios().addElement("15:20");
		  ponto2.getHorarios().addElement("16:00");
		  ponto2.getHorarios().addElement("16:40");
		  ponto2.getHorarios().addElement("17:20");
		  ponto2.getHorarios().addElement("18:00");
		  ponto2.getHorarios().addElement("18:40");
		  ponto2.getHorarios().addElement("19:20");
		  ponto2.getHorarios().addElement("20:00");
		  ponto2.getHorarios().addElement("20:40");
		  ponto2.getHorarios().addElement("21:20");
		  ponto2.getHorarios().addElement("22:00");
		  ponto2.getHorarios().addElement("22:40");
		  ponto2.getHorarios().addElement("23:20");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL SANTA FELICIDADE");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("18/03/2006");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:20");
		  ponto3.getHorarios().addElement("07:00");
		  ponto3.getHorarios().addElement("07:40");
		  ponto3.getHorarios().addElement("08:20");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("09:40");
		  ponto3.getHorarios().addElement("10:20");
		  ponto3.getHorarios().addElement("11:00");
		  ponto3.getHorarios().addElement("11:40");
		  ponto3.getHorarios().addElement("12:20");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("13:40");
		  ponto3.getHorarios().addElement("14:20");
		  ponto3.getHorarios().addElement("15:00");
		  ponto3.getHorarios().addElement("15:40");
		  ponto3.getHorarios().addElement("16:20");
		  ponto3.getHorarios().addElement("17:00");
		  ponto3.getHorarios().addElement("17:40");
		  ponto3.getHorarios().addElement("18:20");
		  ponto3.getHorarios().addElement("19:00");
		  ponto3.getHorarios().addElement("19:40");
		  ponto3.getHorarios().addElement("20:20");
		  ponto3.getHorarios().addElement("21:00");
		  ponto3.getHorarios().addElement("21:40");
		  ponto3.getHorarios().addElement("22:20");
		  ponto3.getHorarios().addElement("23:00");
		  ponto3.getHorarios().addElement("23:40");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO VENEZA");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("19/03/2006");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:00");
		  ponto4.getHorarios().addElement("06:40");
		  ponto4.getHorarios().addElement("07:20");
		  ponto4.getHorarios().addElement("08:00");
		  ponto4.getHorarios().addElement("08:40");
		  ponto4.getHorarios().addElement("09:20");
		  ponto4.getHorarios().addElement("10:00");
		  ponto4.getHorarios().addElement("10:40");
		  ponto4.getHorarios().addElement("11:20");
		  ponto4.getHorarios().addElement("12:00");
		  ponto4.getHorarios().addElement("12:40");
		  ponto4.getHorarios().addElement("13:20");
		  ponto4.getHorarios().addElement("14:00");
		  ponto4.getHorarios().addElement("14:40");
		  ponto4.getHorarios().addElement("15:20");
		  ponto4.getHorarios().addElement("16:00");
		  ponto4.getHorarios().addElement("16:40");
		  ponto4.getHorarios().addElement("17:20");
		  ponto4.getHorarios().addElement("18:00");
		  ponto4.getHorarios().addElement("18:40");
		  ponto4.getHorarios().addElement("19:20");
		  ponto4.getHorarios().addElement("20:00");
		  ponto4.getHorarios().addElement("20:40");
		  ponto4.getHorarios().addElement("21:20");
		  ponto4.getHorarios().addElement("22:00");
		  ponto4.getHorarios().addElement("22:40");
		  ponto4.getHorarios().addElement("23:20");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL SANTA FELICIDADE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("19/03/2006");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:20");
		  ponto5.getHorarios().addElement("07:00");
		  ponto5.getHorarios().addElement("07:40");
		  ponto5.getHorarios().addElement("08:20");
		  ponto5.getHorarios().addElement("09:00");
		  ponto5.getHorarios().addElement("09:40");
		  ponto5.getHorarios().addElement("10:20");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("11:40");
		  ponto5.getHorarios().addElement("12:20");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:40");
		  ponto5.getHorarios().addElement("14:20");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("15:40");
		  ponto5.getHorarios().addElement("16:20");
		  ponto5.getHorarios().addElement("17:00");
		  ponto5.getHorarios().addElement("17:40");
		  ponto5.getHorarios().addElement("18:20");
		  ponto5.getHorarios().addElement("19:00");
		  ponto5.getHorarios().addElement("19:40");
		  ponto5.getHorarios().addElement("20:20");
		  ponto5.getHorarios().addElement("21:00");
		  ponto5.getHorarios().addElement("21:40");
		  ponto5.getHorarios().addElement("22:20");
		  ponto5.getHorarios().addElement("23:00");
		  ponto5.getHorarios().addElement("23:40");
		  return onibus;
		  }
	  }