
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusO75 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("O75 - BRITANITE");
		  onibus.setCodigo("O75");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BRITANITE");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("03/12/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("04:50");
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("06:20");
		  ponto0.getHorarios().addElement("07:30");
		  ponto0.getHorarios().addElement("08:00");
		  ponto0.getHorarios().addElement("08:55");
		  ponto0.getHorarios().addElement("10:15");
		  ponto0.getHorarios().addElement("13:15");
		  ponto0.getHorarios().addElement("14:20");
		  ponto0.getHorarios().addElement("15:15");
		  ponto0.getHorarios().addElement("15:45");
		  ponto0.getHorarios().addElement("16:40");
		  ponto0.getHorarios().addElement("17:35");
		  ponto0.getHorarios().addElement("18:05");
		  ponto0.getHorarios().addElement("19:00");
		  ponto0.getHorarios().addElement("19:30");
		  ponto0.getHorarios().addElement("20:25");
		  ponto0.getHorarios().addElement("21:10");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("FLORESTAL");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("03/12/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:10");
		  ponto1.getHorarios().addElement("05:55");
		  ponto1.getHorarios().addElement("06:45");
		  ponto1.getHorarios().addElement("07:05");
		  ponto1.getHorarios().addElement("08:25");
		  ponto1.getHorarios().addElement("11:50");
		  ponto1.getHorarios().addElement("13:45");
		  ponto1.getHorarios().addElement("14:45");
		  ponto1.getHorarios().addElement("16:15");
		  ponto1.getHorarios().addElement("17:05");
		  ponto1.getHorarios().addElement("18:30");
		  ponto1.getHorarios().addElement("19:55");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERM.Q.BARRAS/BRITANITE");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("03/12/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:20");
		  ponto2.getHorarios().addElement("06:10");
		  ponto2.getHorarios().addElement("07:20");
		  ponto2.getHorarios().addElement("07:50");
		  ponto2.getHorarios().addElement("08:40");
		  ponto2.getHorarios().addElement("10:05");
		  ponto2.getHorarios().addElement("13:00");
		  ponto2.getHorarios().addElement("14:00");
		  ponto2.getHorarios().addElement("15:00");
		  ponto2.getHorarios().addElement("15:30");
		  ponto2.getHorarios().addElement("16:30");
		  ponto2.getHorarios().addElement("17:20");
		  ponto2.getHorarios().addElement("17:50");
		  ponto2.getHorarios().addElement("18:45");
		  ponto2.getHorarios().addElement("19:15");
		  ponto2.getHorarios().addElement("20:15");
		  ponto2.getHorarios().addElement("21:00");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("Q.BARRAS/COHAB-FLORESTAL");
		  ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto3.setValidoAPartirDe("03/12/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:00");
		  ponto3.getHorarios().addElement("05:45");
		  ponto3.getHorarios().addElement("06:35");
		  ponto3.getHorarios().addElement("06:55");
		  ponto3.getHorarios().addElement("08:10");
		  ponto3.getHorarios().addElement("09:10");
		  ponto3.getHorarios().addElement("10:40");
		  ponto3.getHorarios().addElement("13:30");
		  ponto3.getHorarios().addElement("14:30");
		  ponto3.getHorarios().addElement("16:00");
		  ponto3.getHorarios().addElement("16:55");
		  ponto3.getHorarios().addElement("18:20");
		  ponto3.getHorarios().addElement("19:45");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BRITANITE");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto4.setValidoAPartirDe("25/07/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("04:50");
		  ponto4.getHorarios().addElement("05:30");
		  ponto4.getHorarios().addElement("06:20");
		  ponto4.getHorarios().addElement("06:45");
		  ponto4.getHorarios().addElement("07:35");
		  ponto4.getHorarios().addElement("08:00");
		  ponto4.getHorarios().addElement("08:55");
		  ponto4.getHorarios().addElement("09:25");
		  ponto4.getHorarios().addElement("10:15");
		  ponto4.getHorarios().addElement("10:45");
		  ponto4.getHorarios().addElement("11:15");
		  ponto4.getHorarios().addElement("12:15");
		  ponto4.getHorarios().addElement("12:45");
		  ponto4.getHorarios().addElement("13:45");
		  ponto4.getHorarios().addElement("14:15");
		  ponto4.getHorarios().addElement("15:15");
		  ponto4.getHorarios().addElement("15:45");
		  ponto4.getHorarios().addElement("16:40");
		  ponto4.getHorarios().addElement("17:35");
		  ponto4.getHorarios().addElement("18:05");
		  ponto4.getHorarios().addElement("19:00");
		  ponto4.getHorarios().addElement("19:30");
		  ponto4.getHorarios().addElement("20:25");
		  ponto4.getHorarios().addElement("21:20");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERM.Q.BARRAS/BRITANITE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto5.setValidoAPartirDe("25/07/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:20");
		  ponto5.getHorarios().addElement("06:10");
		  ponto5.getHorarios().addElement("06:35");
		  ponto5.getHorarios().addElement("07:25");
		  ponto5.getHorarios().addElement("07:50");
		  ponto5.getHorarios().addElement("08:40");
		  ponto5.getHorarios().addElement("09:10");
		  ponto5.getHorarios().addElement("10:05");
		  ponto5.getHorarios().addElement("10:30");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("12:00");
		  ponto5.getHorarios().addElement("12:30");
		  ponto5.getHorarios().addElement("13:30");
		  ponto5.getHorarios().addElement("14:00");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("15:30");
		  ponto5.getHorarios().addElement("16:30");
		  ponto5.getHorarios().addElement("17:20");
		  ponto5.getHorarios().addElement("17:50");
		  ponto5.getHorarios().addElement("18:45");
		  ponto5.getHorarios().addElement("19:15");
		  ponto5.getHorarios().addElement("20:10");
		  ponto5.getHorarios().addElement("21:05");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("Q.BARRAS/COHAB-FLORESTAL");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto6.setValidoAPartirDe("25/07/2012");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("05:00");
		  ponto6.getHorarios().addElement("05:45");
		  ponto6.getHorarios().addElement("07:00");
		  ponto6.getHorarios().addElement("08:15");
		  ponto6.getHorarios().addElement("09:40");
		  ponto6.getHorarios().addElement("11:30");
		  ponto6.getHorarios().addElement("13:00");
		  ponto6.getHorarios().addElement("14:30");
		  ponto6.getHorarios().addElement("16:00");
		  ponto6.getHorarios().addElement("16:55");
		  ponto6.getHorarios().addElement("18:20");
		  ponto6.getHorarios().addElement("19:45");
		  ponto6.getHorarios().addElement("20:40");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("BRITANITE");
		  ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto7.setValidoAPartirDe("08/12/2012");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("17:55");
		  ponto7.getHorarios().addElement("19:10");
		  ponto7.getHorarios().addElement("20:40");
		  Ponto ponto8 = new Ponto();
		  ponto8.setNome("TERMINAL PIRAQUARA");
		  ponto8.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto8.setValidoAPartirDe("08/12/2012");
		  onibus.getPontos().addElement(ponto8);
		  ponto8.getHorarios().addElement("09:42");
		  ponto8.getHorarios().addElement("10:55");
		  ponto8.getHorarios().addElement("12:20");
		  ponto8.getHorarios().addElement("13:40");
		  ponto8.getHorarios().addElement("18:30");
		  ponto8.getHorarios().addElement("20:00");
		  Ponto ponto9 = new Ponto();
		  ponto9.setNome("TERMINAL QUATRO BARRAS");
		  ponto9.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto9.setValidoAPartirDe("08/12/2012");
		  onibus.getPontos().addElement(ponto9);
		  ponto9.getHorarios().addElement("18:05");
		  ponto9.getHorarios().addElement("19:30");
		  Ponto ponto10 = new Ponto();
		  ponto10.setNome("TERM.Q.BARRAS/BRITANITE");
		  ponto10.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto10.setValidoAPartirDe("08/12/2012");
		  onibus.getPontos().addElement(ponto10);
		  ponto10.getHorarios().addElement("05:30");
		  ponto10.getHorarios().addElement("06:15");
		  ponto10.getHorarios().addElement("07:30");
		  ponto10.getHorarios().addElement("09:15");
		  ponto10.getHorarios().addElement("10:05");
		  ponto10.getHorarios().addElement("11:20");
		  ponto10.getHorarios().addElement("11:50");
		  ponto10.getHorarios().addElement("12:45");
		  ponto10.getHorarios().addElement("13:15");
		  Ponto ponto11 = new Ponto();
		  ponto11.setNome("T.Q.BARRAS (VIA S.PEDRO)");
		  ponto11.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto11.setValidoAPartirDe("08/12/2012");
		  onibus.getPontos().addElement(ponto11);
		  ponto11.getHorarios().addElement("17:45");
		  ponto11.getHorarios().addElement("19:00");
		  ponto11.getHorarios().addElement("20:30");
		  Ponto ponto12 = new Ponto();
		  ponto12.setNome("BRITANITE (VIA S.PEDRO)");
		  ponto12.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto12.setValidoAPartirDe("08/12/2012");
		  onibus.getPontos().addElement(ponto12);
		  ponto12.getHorarios().addElement("05:15");
		  ponto12.getHorarios().addElement("06:25");
		  ponto12.getHorarios().addElement("07:40");
		  ponto12.getHorarios().addElement("10:15");
		  ponto12.getHorarios().addElement("11:35");
		  ponto12.getHorarios().addElement("13:00");
		  Ponto ponto13 = new Ponto();
		  ponto13.setNome("BRITANITE");
		  ponto13.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto13.setValidoAPartirDe("09/12/2012");
		  onibus.getPontos().addElement(ponto13);
		  ponto13.getHorarios().addElement("11:35");
		  ponto13.getHorarios().addElement("17:55");
		  ponto13.getHorarios().addElement("20:15");
		  Ponto ponto14 = new Ponto();
		  ponto14.setNome("TERMINAL PIRAQUARA");
		  ponto14.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto14.setValidoAPartirDe("09/12/2012");
		  onibus.getPontos().addElement(ponto14);
		  ponto14.getHorarios().addElement("09:42");
		  ponto14.getHorarios().addElement("10:50");
		  ponto14.getHorarios().addElement("12:20");
		  ponto14.getHorarios().addElement("13:10");
		  ponto14.getHorarios().addElement("19:40");
		  Ponto ponto15 = new Ponto();
		  ponto15.setNome("TERMINAL QUATRO BARRAS");
		  ponto15.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto15.setValidoAPartirDe("09/12/2012");
		  onibus.getPontos().addElement(ponto15);
		  ponto15.getHorarios().addElement("09:15");
		  ponto15.getHorarios().addElement("10:10");
		  ponto15.getHorarios().addElement("11:55");
		  ponto15.getHorarios().addElement("12:45");
		  ponto15.getHorarios().addElement("19:15");
		  Ponto ponto16 = new Ponto();
		  ponto16.setNome("TERM.Q.BARRAS/BRITANITE");
		  ponto16.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto16.setValidoAPartirDe("09/12/2012");
		  onibus.getPontos().addElement(ponto16);
		  ponto16.getHorarios().addElement("08:50");
		  ponto16.getHorarios().addElement("11:15");
		  ponto16.getHorarios().addElement("20:05");
		  Ponto ponto17 = new Ponto();
		  ponto17.setNome("T.Q.BARRAS (VIA S.PEDRO)");
		  ponto17.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto17.setValidoAPartirDe("09/12/2012");
		  onibus.getPontos().addElement(ponto17);
		  ponto17.getHorarios().addElement("17:45");
		  Ponto ponto18 = new Ponto();
		  ponto18.setNome("BRITANITE (VIA S.PEDRO)");
		  ponto18.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto18.setValidoAPartirDe("09/12/2012");
		  onibus.getPontos().addElement(ponto18);
		  ponto18.getHorarios().addElement("09:00");
		  return onibus;
		  }
	  }