
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusC23 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("C23 - EMILIANO PERNETA");
		  onibus.setCodigo("C23");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("TERMINAL PINHAIS");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("18/07/2011");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("06:00");
		  ponto0.getHorarios().addElement("06:30");
		  ponto0.getHorarios().addElement("07:00");
		  ponto0.getHorarios().addElement("07:30");
		  ponto0.getHorarios().addElement("08:00");
		  ponto0.getHorarios().addElement("08:35");
		  ponto0.getHorarios().addElement("09:10");
		  ponto0.getHorarios().addElement("09:45");
		  ponto0.getHorarios().addElement("10:20");
		  ponto0.getHorarios().addElement("10:55");
		  ponto0.getHorarios().addElement("11:30");
		  ponto0.getHorarios().addElement("12:05");
		  ponto0.getHorarios().addElement("12:40");
		  ponto0.getHorarios().addElement("13:15");
		  ponto0.getHorarios().addElement("13:50");
		  ponto0.getHorarios().addElement("14:25");
		  ponto0.getHorarios().addElement("15:00");
		  ponto0.getHorarios().addElement("15:35");
		  ponto0.getHorarios().addElement("16:10");
		  ponto0.getHorarios().addElement("16:45");
		  ponto0.getHorarios().addElement("17:20");
		  ponto0.getHorarios().addElement("17:55");
		  ponto0.getHorarios().addElement("18:30");
		  ponto0.getHorarios().addElement("19:05");
		  ponto0.getHorarios().addElement("19:45");
		  ponto0.getHorarios().addElement("20:25");
		  ponto0.getHorarios().addElement("21:00");
		  ponto0.getHorarios().addElement("21:30");
		  ponto0.getHorarios().addElement("22:00");
		  ponto0.getHorarios().addElement("22:30");
		  ponto0.getHorarios().addElement("23:00");
		  ponto0.getHorarios().addElement("23:30");
		  ponto0.getHorarios().addElement("00:00");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL PINHAIS");
		  ponto1.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto1.setValidoAPartirDe("20/09/2008");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:30");
		  ponto1.getHorarios().addElement("06:00");
		  ponto1.getHorarios().addElement("06:30");
		  ponto1.getHorarios().addElement("07:00");
		  ponto1.getHorarios().addElement("07:30");
		  ponto1.getHorarios().addElement("08:00");
		  ponto1.getHorarios().addElement("08:30");
		  ponto1.getHorarios().addElement("09:00");
		  ponto1.getHorarios().addElement("09:30");
		  ponto1.getHorarios().addElement("10:00");
		  ponto1.getHorarios().addElement("10:30");
		  ponto1.getHorarios().addElement("11:00");
		  ponto1.getHorarios().addElement("11:30");
		  ponto1.getHorarios().addElement("12:00");
		  ponto1.getHorarios().addElement("12:30");
		  ponto1.getHorarios().addElement("13:00");
		  ponto1.getHorarios().addElement("13:30");
		  ponto1.getHorarios().addElement("14:00");
		  ponto1.getHorarios().addElement("14:30");
		  ponto1.getHorarios().addElement("15:00");
		  ponto1.getHorarios().addElement("15:30");
		  ponto1.getHorarios().addElement("16:00");
		  ponto1.getHorarios().addElement("16:30");
		  ponto1.getHorarios().addElement("17:00");
		  ponto1.getHorarios().addElement("17:30");
		  ponto1.getHorarios().addElement("18:00");
		  ponto1.getHorarios().addElement("18:30");
		  ponto1.getHorarios().addElement("19:00");
		  ponto1.getHorarios().addElement("19:30");
		  ponto1.getHorarios().addElement("20:00");
		  ponto1.getHorarios().addElement("20:30");
		  ponto1.getHorarios().addElement("21:00");
		  ponto1.getHorarios().addElement("21:30");
		  ponto1.getHorarios().addElement("22:00");
		  ponto1.getHorarios().addElement("22:30");
		  ponto1.getHorarios().addElement("23:00");
		  ponto1.getHorarios().addElement("23:30");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL PINHAIS");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto2.setValidoAPartirDe("21/09/2008");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:00");
		  ponto2.getHorarios().addElement("06:30");
		  ponto2.getHorarios().addElement("07:00");
		  ponto2.getHorarios().addElement("07:30");
		  ponto2.getHorarios().addElement("08:00");
		  ponto2.getHorarios().addElement("08:30");
		  ponto2.getHorarios().addElement("09:00");
		  ponto2.getHorarios().addElement("09:30");
		  ponto2.getHorarios().addElement("10:00");
		  ponto2.getHorarios().addElement("10:30");
		  ponto2.getHorarios().addElement("11:00");
		  ponto2.getHorarios().addElement("11:30");
		  ponto2.getHorarios().addElement("12:00");
		  ponto2.getHorarios().addElement("12:30");
		  ponto2.getHorarios().addElement("13:00");
		  ponto2.getHorarios().addElement("13:30");
		  ponto2.getHorarios().addElement("14:00");
		  ponto2.getHorarios().addElement("14:30");
		  ponto2.getHorarios().addElement("15:00");
		  ponto2.getHorarios().addElement("15:30");
		  ponto2.getHorarios().addElement("16:00");
		  ponto2.getHorarios().addElement("16:30");
		  ponto2.getHorarios().addElement("17:00");
		  ponto2.getHorarios().addElement("17:30");
		  ponto2.getHorarios().addElement("18:00");
		  ponto2.getHorarios().addElement("18:30");
		  ponto2.getHorarios().addElement("19:00");
		  ponto2.getHorarios().addElement("19:30");
		  ponto2.getHorarios().addElement("20:00");
		  ponto2.getHorarios().addElement("20:30");
		  ponto2.getHorarios().addElement("21:00");
		  ponto2.getHorarios().addElement("21:30");
		  ponto2.getHorarios().addElement("22:00");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("23:00");
		  ponto2.getHorarios().addElement("23:30");
		  ponto2.getHorarios().addElement("00:00");
		  return onibus;
		  }
	  }