
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusB18 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("ROSEIRA");
		onibus.setCodigo("B18");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO ROSEIRA");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("01/12/2008");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:00");
		ponto0.getHorarios().addElement("06:00");
		ponto0.getHorarios().addElement("07:00");
		ponto0.getHorarios().addElement("08:00");
		ponto0.getHorarios().addElement("09:00");
		ponto0.getHorarios().addElement("10:00");
		ponto0.getHorarios().addElement("11:00");
		ponto0.getHorarios().addElement("12:00");
		ponto0.getHorarios().addElement("13:00");
		ponto0.getHorarios().addElement("14:00");
		ponto0.getHorarios().addElement("15:00");
		ponto0.getHorarios().addElement("16:00");
		ponto0.getHorarios().addElement("17:00");
		ponto0.getHorarios().addElement("18:00");
		ponto0.getHorarios().addElement("19:00");
		ponto0.getHorarios().addElement("20:00");
		ponto0.getHorarios().addElement("21:00");
		ponto0.getHorarios().addElement("22:00");
		ponto0.getHorarios().addElement("23:00");
		ponto0.getHorarios().addElement("00:00");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL GUARAITUBA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("01/12/2008");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:30");
		ponto1.getHorarios().addElement("06:30");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("08:30");
		ponto1.getHorarios().addElement("09:30");
		ponto1.getHorarios().addElement("10:30");
		ponto1.getHorarios().addElement("11:30");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:30");
		ponto1.getHorarios().addElement("14:30");
		ponto1.getHorarios().addElement("15:30");
		ponto1.getHorarios().addElement("16:30");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("18:30");
		ponto1.getHorarios().addElement("19:30");
		ponto1.getHorarios().addElement("20:30");
		ponto1.getHorarios().addElement("21:30");
		ponto1.getHorarios().addElement("22:30");
		ponto1.getHorarios().addElement("23:30");
		ponto1.getHorarios().addElement("00:30");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("BAIRRO ROSEIRA");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("29/11/2008");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:50");
		ponto2.getHorarios().addElement("07:00");
		ponto2.getHorarios().addElement("08:00");
		ponto2.getHorarios().addElement("09:00");
		ponto2.getHorarios().addElement("10:00");
		ponto2.getHorarios().addElement("11:00");
		ponto2.getHorarios().addElement("12:00");
		ponto2.getHorarios().addElement("13:00");
		ponto2.getHorarios().addElement("14:00");
		ponto2.getHorarios().addElement("15:00");
		ponto2.getHorarios().addElement("16:00");
		ponto2.getHorarios().addElement("17:00");
		ponto2.getHorarios().addElement("18:00");
		ponto2.getHorarios().addElement("19:00");
		ponto2.getHorarios().addElement("20:00");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL GUARAITUBA");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("29/11/2008");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:30");
		ponto3.getHorarios().addElement("07:30");
		ponto3.getHorarios().addElement("08:30");
		ponto3.getHorarios().addElement("09:30");
		ponto3.getHorarios().addElement("10:30");
		ponto3.getHorarios().addElement("11:30");
		ponto3.getHorarios().addElement("12:30");
		ponto3.getHorarios().addElement("13:30");
		ponto3.getHorarios().addElement("14:30");
		ponto3.getHorarios().addElement("15:30");
		ponto3.getHorarios().addElement("16:30");
		ponto3.getHorarios().addElement("17:30");
		ponto3.getHorarios().addElement("18:30");
		ponto3.getHorarios().addElement("19:30");
		ponto3.getHorarios().addElement("20:30");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO ROSEIRA");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("30/11/2008");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:50");
		ponto4.getHorarios().addElement("07:00");
		ponto4.getHorarios().addElement("08:00");
		ponto4.getHorarios().addElement("09:00");
		ponto4.getHorarios().addElement("10:00");
		ponto4.getHorarios().addElement("11:00");
		ponto4.getHorarios().addElement("12:00");
		ponto4.getHorarios().addElement("13:00");
		ponto4.getHorarios().addElement("14:00");
		ponto4.getHorarios().addElement("15:00");
		ponto4.getHorarios().addElement("16:00");
		ponto4.getHorarios().addElement("17:00");
		ponto4.getHorarios().addElement("18:00");
		ponto4.getHorarios().addElement("19:00");
		ponto4.getHorarios().addElement("20:00");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL GUARAITUBA");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("30/11/2008");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:30");
		ponto5.getHorarios().addElement("07:30");
		ponto5.getHorarios().addElement("08:30");
		ponto5.getHorarios().addElement("09:30");
		ponto5.getHorarios().addElement("10:30");
		ponto5.getHorarios().addElement("11:30");
		ponto5.getHorarios().addElement("12:30");
		ponto5.getHorarios().addElement("13:30");
		ponto5.getHorarios().addElement("14:30");
		ponto5.getHorarios().addElement("15:30");
		ponto5.getHorarios().addElement("16:30");
		ponto5.getHorarios().addElement("17:30");
		ponto5.getHorarios().addElement("18:30");
		ponto5.getHorarios().addElement("19:30");
		ponto5.getHorarios().addElement("20:30");
		return onibus;
		}
	}