
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class Onibus614 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("FAZENDINHA / PUC");
		onibus.setCodigo("614");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO SANTA RITA");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:19");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("PONT.UNIVERSIDADE CATOLICA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("07:08");
		ponto1.getHorarios().addElement("07:24");
		ponto1.getHorarios().addElement("07:42");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL CIC");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:48");
		ponto2.getHorarios().addElement("06:53");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL FAZENDINHA");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:33");
		ponto3.getHorarios().addElement("06:49");
		ponto3.getHorarios().addElement("07:07");
		ponto3.getHorarios().addElement("07:24");
		ponto3.getHorarios().addElement("07:38");
		ponto3.getHorarios().addElement("07:51");
		ponto3.getHorarios().addElement("08:08");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL PINHEIRINHO");
		ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto4.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:55");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("EMPRESA KRAFT");
		ponto5.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto5.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:35");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("BAIRRO RIO BONITO");
		ponto6.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto6.setValidoAPartirDe("25/06/2012");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:24");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("BAIRRO SANTA RITA");
		ponto7.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto7.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("06:19");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("PONT.UNIVERSIDADE CATOLICA");
		ponto8.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto8.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("07:08");
		ponto8.getHorarios().addElement("07:16");
		ponto8.getHorarios().addElement("07:24");
		ponto8.getHorarios().addElement("07:33");
		ponto8.getHorarios().addElement("07:42");
		ponto8.getHorarios().addElement("11:30");
		ponto8.getHorarios().addElement("11:45");
		ponto8.getHorarios().addElement("12:10");
		ponto8.getHorarios().addElement("12:34");
		ponto8.getHorarios().addElement("12:51");
		ponto8.getHorarios().addElement("13:24");
		ponto8.getHorarios().addElement("17:05");
		ponto8.getHorarios().addElement("17:15");
		ponto8.getHorarios().addElement("17:24");
		ponto8.getHorarios().addElement("17:43");
		ponto8.getHorarios().addElement("18:17");
		ponto8.getHorarios().addElement("18:27");
		ponto8.getHorarios().addElement("18:37");
		ponto8.getHorarios().addElement("21:56");
		ponto8.getHorarios().addElement("22:16");
		ponto8.getHorarios().addElement("22:36");
		ponto8.getHorarios().addElement("22:58");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("TERMINAL CIC");
		ponto9.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto9.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("06:48");
		ponto9.getHorarios().addElement("06:53");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("TERMINAL FAZENDINHA");
		ponto10.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto10.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("06:33");
		ponto10.getHorarios().addElement("06:41");
		ponto10.getHorarios().addElement("06:49");
		ponto10.getHorarios().addElement("06:58");
		ponto10.getHorarios().addElement("07:07");
		ponto10.getHorarios().addElement("07:16");
		ponto10.getHorarios().addElement("07:24");
		ponto10.getHorarios().addElement("07:38");
		ponto10.getHorarios().addElement("07:42");
		ponto10.getHorarios().addElement("07:51");
		ponto10.getHorarios().addElement("08:00");
		ponto10.getHorarios().addElement("08:08");
		ponto10.getHorarios().addElement("12:04");
		ponto10.getHorarios().addElement("12:21");
		ponto10.getHorarios().addElement("12:54");
		ponto10.getHorarios().addElement("13:11");
		ponto10.getHorarios().addElement("13:27");
		ponto10.getHorarios().addElement("17:42");
		ponto10.getHorarios().addElement("17:52");
		ponto10.getHorarios().addElement("18:01");
		ponto10.getHorarios().addElement("18:20");
		ponto10.getHorarios().addElement("18:57");
		ponto10.getHorarios().addElement("22:27");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("TERMINAL PINHEIRINHO");
		ponto11.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto11.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("06:55");
		Ponto ponto12 = new Ponto();
		ponto12.setNome("EMPRESA KRAFT");
		ponto12.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto12.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto12);
		ponto12.getHorarios().addElement("06:35");
		Ponto ponto13 = new Ponto();
		ponto13.setNome("BAIRRO RIO BONITO");
		ponto13.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto13.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto13);
		ponto13.getHorarios().addElement("06:24");
		Ponto ponto14 = new Ponto();
		ponto14.setNome("T.S.CERCADO SENT.FAZENDINHA");
		ponto14.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto14.setValidoAPartirDe("23/07/2012");
		onibus.getPontos().addElement(ponto14);
		ponto14.getHorarios().addElement("06:12");
		return onibus;
		}
	}