
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusA78 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("CTBA / V.  MARTA");
		onibus.setCodigo("A78");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("PRACA 19 DE DEZEMBRO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("11/07/2011");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:30");
		ponto0.getHorarios().addElement("07:05");
		ponto0.getHorarios().addElement("07:40");
		ponto0.getHorarios().addElement("08:58");
		ponto0.getHorarios().addElement("10:13");
		ponto0.getHorarios().addElement("11:28");
		ponto0.getHorarios().addElement("12:43");
		ponto0.getHorarios().addElement("13:58");
		ponto0.getHorarios().addElement("15:13");
		ponto0.getHorarios().addElement("16:28");
		ponto0.getHorarios().addElement("17:05");
		ponto0.getHorarios().addElement("17:40");
		ponto0.getHorarios().addElement("18:15");
		ponto0.getHorarios().addElement("18:50");
		ponto0.getHorarios().addElement("19:30");
		ponto0.getHorarios().addElement("20:10");
		ponto0.getHorarios().addElement("21:40");
		ponto0.getHorarios().addElement("23:00");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("VILA MARTA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("11/07/2011");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:55");
		ponto1.getHorarios().addElement("06:30");
		ponto1.getHorarios().addElement("07:05");
		ponto1.getHorarios().addElement("07:40");
		ponto1.getHorarios().addElement("08:19");
		ponto1.getHorarios().addElement("09:33");
		ponto1.getHorarios().addElement("10:48");
		ponto1.getHorarios().addElement("12:03");
		ponto1.getHorarios().addElement("13:18");
		ponto1.getHorarios().addElement("14:33");
		ponto1.getHorarios().addElement("15:48");
		ponto1.getHorarios().addElement("17:05");
		ponto1.getHorarios().addElement("17:40");
		ponto1.getHorarios().addElement("18:15");
		ponto1.getHorarios().addElement("18:50");
		ponto1.getHorarios().addElement("19:25");
		ponto1.getHorarios().addElement("20:45");
		ponto1.getHorarios().addElement("22:15");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("PRACA 19 DE DEZEMBRO");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("02/07/2011");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("07:35");
		ponto2.getHorarios().addElement("08:45");
		ponto2.getHorarios().addElement("09:55");
		ponto2.getHorarios().addElement("11:05");
		ponto2.getHorarios().addElement("12:15");
		ponto2.getHorarios().addElement("13:25");
		ponto2.getHorarios().addElement("14:35");
		ponto2.getHorarios().addElement("15:45");
		ponto2.getHorarios().addElement("16:55");
		ponto2.getHorarios().addElement("18:05");
		ponto2.getHorarios().addElement("19:15");
		ponto2.getHorarios().addElement("20:20");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("VILA MARTA");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("02/07/2011");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("07:00");
		ponto3.getHorarios().addElement("08:10");
		ponto3.getHorarios().addElement("09:20");
		ponto3.getHorarios().addElement("10:30");
		ponto3.getHorarios().addElement("11:40");
		ponto3.getHorarios().addElement("12:50");
		ponto3.getHorarios().addElement("14:00");
		ponto3.getHorarios().addElement("15:10");
		ponto3.getHorarios().addElement("16:20");
		ponto3.getHorarios().addElement("17:30");
		ponto3.getHorarios().addElement("18:40");
		ponto3.getHorarios().addElement("19:50");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("PRACA 19 DE DEZEMBRO");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("03/07/2011");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("07:30");
		ponto4.getHorarios().addElement("08:30");
		ponto4.getHorarios().addElement("09:30");
		ponto4.getHorarios().addElement("10:30");
		ponto4.getHorarios().addElement("11:30");
		ponto4.getHorarios().addElement("12:30");
		ponto4.getHorarios().addElement("13:30");
		ponto4.getHorarios().addElement("14:30");
		ponto4.getHorarios().addElement("15:30");
		ponto4.getHorarios().addElement("16:30");
		ponto4.getHorarios().addElement("17:30");
		ponto4.getHorarios().addElement("18:30");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("VILA MARTA");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("03/07/2011");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("07:00");
		ponto5.getHorarios().addElement("08:00");
		ponto5.getHorarios().addElement("09:00");
		ponto5.getHorarios().addElement("10:00");
		ponto5.getHorarios().addElement("11:00");
		ponto5.getHorarios().addElement("12:00");
		ponto5.getHorarios().addElement("13:00");
		ponto5.getHorarios().addElement("14:00");
		ponto5.getHorarios().addElement("15:00");
		ponto5.getHorarios().addElement("16:00");
		ponto5.getHorarios().addElement("17:00");
		ponto5.getHorarios().addElement("18:00");
		return onibus;
		}
	}