
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class Onibus536 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("ZOOLÓGICO");
		onibus.setCodigo("536");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO ZOOLOGICO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("25/09/2006");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("06:00");
		ponto0.getHorarios().addElement("07:00");
		ponto0.getHorarios().addElement("08:00");
		ponto0.getHorarios().addElement("09:00");
		ponto0.getHorarios().addElement("10:00");
		ponto0.getHorarios().addElement("11:00");
		ponto0.getHorarios().addElement("12:00");
		ponto0.getHorarios().addElement("13:00");
		ponto0.getHorarios().addElement("14:00");
		ponto0.getHorarios().addElement("15:00");
		ponto0.getHorarios().addElement("16:00");
		ponto0.getHorarios().addElement("17:00");
		ponto0.getHorarios().addElement("18:00");
		ponto0.getHorarios().addElement("19:00");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("T.BOQUEIRAO SENT. V.NOVA");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("25/09/2006");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:30");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("08:30");
		ponto1.getHorarios().addElement("09:30");
		ponto1.getHorarios().addElement("10:30");
		ponto1.getHorarios().addElement("11:30");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:30");
		ponto1.getHorarios().addElement("14:30");
		ponto1.getHorarios().addElement("15:30");
		ponto1.getHorarios().addElement("16:30");
		ponto1.getHorarios().addElement("17:30");
		ponto1.getHorarios().addElement("18:30");
		ponto1.getHorarios().addElement("19:30");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("BAIRRO ZOOLOGICO");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("08/12/2007");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:00");
		ponto2.getHorarios().addElement("07:00");
		ponto2.getHorarios().addElement("08:00");
		ponto2.getHorarios().addElement("09:00");
		ponto2.getHorarios().addElement("10:00");
		ponto2.getHorarios().addElement("11:00");
		ponto2.getHorarios().addElement("12:00");
		ponto2.getHorarios().addElement("13:00");
		ponto2.getHorarios().addElement("14:00");
		ponto2.getHorarios().addElement("15:00");
		ponto2.getHorarios().addElement("16:00");
		ponto2.getHorarios().addElement("17:00");
		ponto2.getHorarios().addElement("18:00");
		ponto2.getHorarios().addElement("19:00");
		ponto2.getHorarios().addElement("20:00");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("T.BOQUEIRAO SENT. V.NOVA");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("08/12/2007");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:30");
		ponto3.getHorarios().addElement("07:30");
		ponto3.getHorarios().addElement("08:30");
		ponto3.getHorarios().addElement("09:30");
		ponto3.getHorarios().addElement("10:30");
		ponto3.getHorarios().addElement("11:30");
		ponto3.getHorarios().addElement("12:30");
		ponto3.getHorarios().addElement("13:30");
		ponto3.getHorarios().addElement("14:30");
		ponto3.getHorarios().addElement("15:30");
		ponto3.getHorarios().addElement("16:30");
		ponto3.getHorarios().addElement("17:30");
		ponto3.getHorarios().addElement("18:30");
		ponto3.getHorarios().addElement("19:30");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO ZOOLOGICO");
		ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto4.setValidoAPartirDe("13/04/2008");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:00");
		ponto4.getHorarios().addElement("07:00");
		ponto4.getHorarios().addElement("08:00");
		ponto4.getHorarios().addElement("09:00");
		ponto4.getHorarios().addElement("10:00");
		ponto4.getHorarios().addElement("10:30");
		ponto4.getHorarios().addElement("11:00");
		ponto4.getHorarios().addElement("11:30");
		ponto4.getHorarios().addElement("12:00");
		ponto4.getHorarios().addElement("12:30");
		ponto4.getHorarios().addElement("13:00");
		ponto4.getHorarios().addElement("13:30");
		ponto4.getHorarios().addElement("14:00");
		ponto4.getHorarios().addElement("14:30");
		ponto4.getHorarios().addElement("15:00");
		ponto4.getHorarios().addElement("15:30");
		ponto4.getHorarios().addElement("16:00");
		ponto4.getHorarios().addElement("16:30");
		ponto4.getHorarios().addElement("17:00");
		ponto4.getHorarios().addElement("17:30");
		ponto4.getHorarios().addElement("18:00");
		ponto4.getHorarios().addElement("18:30");
		ponto4.getHorarios().addElement("19:00");
		ponto4.getHorarios().addElement("19:30");
		ponto4.getHorarios().addElement("20:00");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("T.BOQUEIRAO SENT. V.NOVA");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("13/04/2008");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:30");
		ponto5.getHorarios().addElement("07:30");
		ponto5.getHorarios().addElement("08:30");
		ponto5.getHorarios().addElement("09:30");
		ponto5.getHorarios().addElement("10:30");
		ponto5.getHorarios().addElement("11:30");
		ponto5.getHorarios().addElement("12:30");
		ponto5.getHorarios().addElement("13:30");
		ponto5.getHorarios().addElement("14:30");
		ponto5.getHorarios().addElement("15:30");
		ponto5.getHorarios().addElement("16:30");
		ponto5.getHorarios().addElement("17:30");
		ponto5.getHorarios().addElement("18:30");
		ponto5.getHorarios().addElement("19:30");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("T.BOQUEIRAO - DIRETO");
		ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto6.setValidoAPartirDe("13/04/2008");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("10:00");
		ponto6.getHorarios().addElement("11:00");
		ponto6.getHorarios().addElement("12:00");
		ponto6.getHorarios().addElement("13:00");
		ponto6.getHorarios().addElement("14:00");
		ponto6.getHorarios().addElement("15:00");
		ponto6.getHorarios().addElement("16:00");
		ponto6.getHorarios().addElement("17:00");
		ponto6.getHorarios().addElement("18:00");
		ponto6.getHorarios().addElement("19:00");
		return onibus;
		}
	}