
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus150 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("150 - C. MÚSICA / V. ALEGRE");
		  onibus.setCodigo("150");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("CANAL DA MUSICA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("02/07/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("06:00");
		  ponto0.getHorarios().addElement("06:19");
		  ponto0.getHorarios().addElement("06:38");
		  ponto0.getHorarios().addElement("06:56");
		  ponto0.getHorarios().addElement("07:15");
		  ponto0.getHorarios().addElement("07:34");
		  ponto0.getHorarios().addElement("07:54");
		  ponto0.getHorarios().addElement("08:14");
		  ponto0.getHorarios().addElement("08:34");
		  ponto0.getHorarios().addElement("09:00");
		  ponto0.getHorarios().addElement("09:30");
		  ponto0.getHorarios().addElement("10:00");
		  ponto0.getHorarios().addElement("10:30");
		  ponto0.getHorarios().addElement("11:00");
		  ponto0.getHorarios().addElement("11:30");
		  ponto0.getHorarios().addElement("12:00");
		  ponto0.getHorarios().addElement("12:22");
		  ponto0.getHorarios().addElement("12:44");
		  ponto0.getHorarios().addElement("13:06");
		  ponto0.getHorarios().addElement("13:30");
		  ponto0.getHorarios().addElement("14:02");
		  ponto0.getHorarios().addElement("14:34");
		  ponto0.getHorarios().addElement("15:06");
		  ponto0.getHorarios().addElement("15:38");
		  ponto0.getHorarios().addElement("16:10");
		  ponto0.getHorarios().addElement("16:42");
		  ponto0.getHorarios().addElement("17:15");
		  ponto0.getHorarios().addElement("17:47");
		  ponto0.getHorarios().addElement("18:10");
		  ponto0.getHorarios().addElement("18:33");
		  ponto0.getHorarios().addElement("18:55");
		  ponto0.getHorarios().addElement("19:18");
		  ponto0.getHorarios().addElement("19:41");
		  ponto0.getHorarios().addElement("20:10");
		  ponto0.getHorarios().addElement("20:39");
		  ponto0.getHorarios().addElement("21:04");
		  ponto0.getHorarios().addElement("21:29");
		  ponto0.getHorarios().addElement("21:54");
		  ponto0.getHorarios().addElement("22:19");
		  ponto0.getHorarios().addElement("22:44");
		  ponto0.getHorarios().addElement("23:09");
		  ponto0.getHorarios().addElement("23:34");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TEATRO GUAIRA");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("02/07/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("06:28");
		  ponto1.getHorarios().addElement("06:47");
		  ponto1.getHorarios().addElement("07:06");
		  ponto1.getHorarios().addElement("07:25");
		  ponto1.getHorarios().addElement("07:45");
		  ponto1.getHorarios().addElement("08:05");
		  ponto1.getHorarios().addElement("08:30");
		  ponto1.getHorarios().addElement("09:02");
		  ponto1.getHorarios().addElement("09:30");
		  ponto1.getHorarios().addElement("10:00");
		  ponto1.getHorarios().addElement("10:30");
		  ponto1.getHorarios().addElement("11:00");
		  ponto1.getHorarios().addElement("11:28");
		  ponto1.getHorarios().addElement("11:49");
		  ponto1.getHorarios().addElement("12:11");
		  ponto1.getHorarios().addElement("12:34");
		  ponto1.getHorarios().addElement("13:01");
		  ponto1.getHorarios().addElement("13:34");
		  ponto1.getHorarios().addElement("14:02");
		  ponto1.getHorarios().addElement("14:34");
		  ponto1.getHorarios().addElement("15:06");
		  ponto1.getHorarios().addElement("15:38");
		  ponto1.getHorarios().addElement("16:10");
		  ponto1.getHorarios().addElement("16:41");
		  ponto1.getHorarios().addElement("17:12");
		  ponto1.getHorarios().addElement("17:35");
		  ponto1.getHorarios().addElement("17:58");
		  ponto1.getHorarios().addElement("18:20");
		  ponto1.getHorarios().addElement("18:43");
		  ponto1.getHorarios().addElement("19:06");
		  ponto1.getHorarios().addElement("19:28");
		  ponto1.getHorarios().addElement("19:51");
		  ponto1.getHorarios().addElement("20:14");
		  ponto1.getHorarios().addElement("20:38");
		  ponto1.getHorarios().addElement("21:04");
		  ponto1.getHorarios().addElement("21:29");
		  ponto1.getHorarios().addElement("21:54");
		  ponto1.getHorarios().addElement("22:19");
		  ponto1.getHorarios().addElement("22:44");
		  ponto1.getHorarios().addElement("23:09");
		  ponto1.getHorarios().addElement("23:40");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("CANAL DA MUSICA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("30/06/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:00");
		  ponto2.getHorarios().addElement("06:46");
		  ponto2.getHorarios().addElement("07:32");
		  ponto2.getHorarios().addElement("08:20");
		  ponto2.getHorarios().addElement("09:10");
		  ponto2.getHorarios().addElement("10:00");
		  ponto2.getHorarios().addElement("10:50");
		  ponto2.getHorarios().addElement("11:40");
		  ponto2.getHorarios().addElement("12:30");
		  ponto2.getHorarios().addElement("13:25");
		  ponto2.getHorarios().addElement("14:20");
		  ponto2.getHorarios().addElement("15:20");
		  ponto2.getHorarios().addElement("16:20");
		  ponto2.getHorarios().addElement("17:20");
		  ponto2.getHorarios().addElement("18:20");
		  ponto2.getHorarios().addElement("19:15");
		  ponto2.getHorarios().addElement("20:10");
		  ponto2.getHorarios().addElement("21:03");
		  ponto2.getHorarios().addElement("21:55");
		  ponto2.getHorarios().addElement("22:45");
		  ponto2.getHorarios().addElement("23:35");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TEATRO GUAIRA");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("30/06/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:23");
		  ponto3.getHorarios().addElement("07:09");
		  ponto3.getHorarios().addElement("07:55");
		  ponto3.getHorarios().addElement("08:45");
		  ponto3.getHorarios().addElement("09:35");
		  ponto3.getHorarios().addElement("10:25");
		  ponto3.getHorarios().addElement("11:15");
		  ponto3.getHorarios().addElement("12:05");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("13:55");
		  ponto3.getHorarios().addElement("14:50");
		  ponto3.getHorarios().addElement("15:50");
		  ponto3.getHorarios().addElement("16:50");
		  ponto3.getHorarios().addElement("17:50");
		  ponto3.getHorarios().addElement("18:45");
		  ponto3.getHorarios().addElement("19:40");
		  ponto3.getHorarios().addElement("20:35");
		  ponto3.getHorarios().addElement("21:30");
		  ponto3.getHorarios().addElement("22:20");
		  ponto3.getHorarios().addElement("23:10");
		  ponto3.getHorarios().addElement("00:00");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("CANAL DA MUSICA");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("01/07/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:00");
		  ponto4.getHorarios().addElement("06:46");
		  ponto4.getHorarios().addElement("07:32");
		  ponto4.getHorarios().addElement("08:20");
		  ponto4.getHorarios().addElement("09:10");
		  ponto4.getHorarios().addElement("10:00");
		  ponto4.getHorarios().addElement("10:50");
		  ponto4.getHorarios().addElement("11:40");
		  ponto4.getHorarios().addElement("12:30");
		  ponto4.getHorarios().addElement("13:25");
		  ponto4.getHorarios().addElement("14:20");
		  ponto4.getHorarios().addElement("15:20");
		  ponto4.getHorarios().addElement("16:20");
		  ponto4.getHorarios().addElement("17:20");
		  ponto4.getHorarios().addElement("18:20");
		  ponto4.getHorarios().addElement("19:15");
		  ponto4.getHorarios().addElement("20:10");
		  ponto4.getHorarios().addElement("21:03");
		  ponto4.getHorarios().addElement("21:55");
		  ponto4.getHorarios().addElement("22:45");
		  ponto4.getHorarios().addElement("23:35");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TEATRO GUAIRA");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("01/07/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:23");
		  ponto5.getHorarios().addElement("07:09");
		  ponto5.getHorarios().addElement("07:55");
		  ponto5.getHorarios().addElement("08:45");
		  ponto5.getHorarios().addElement("09:35");
		  ponto5.getHorarios().addElement("10:25");
		  ponto5.getHorarios().addElement("11:15");
		  ponto5.getHorarios().addElement("12:05");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:55");
		  ponto5.getHorarios().addElement("14:50");
		  ponto5.getHorarios().addElement("15:50");
		  ponto5.getHorarios().addElement("16:50");
		  ponto5.getHorarios().addElement("17:50");
		  ponto5.getHorarios().addElement("18:50");
		  ponto5.getHorarios().addElement("19:40");
		  ponto5.getHorarios().addElement("20:35");
		  ponto5.getHorarios().addElement("21:30");
		  ponto5.getHorarios().addElement("22:20");
		  ponto5.getHorarios().addElement("23:10");
		  ponto5.getHorarios().addElement("00:00");
		  return onibus;
		  }
	  }