
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class Onibus209 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("209 - MAD. S. CÂNDIDA / C. RASO");
		onibus.setCodigo("209");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("CORREIO SENTIDO NORTE");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("10/12/2007");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("00:50");
		ponto0.getHorarios().addElement("01:17");
		ponto0.getHorarios().addElement("02:20");
		ponto0.getHorarios().addElement("03:00");
		ponto0.getHorarios().addElement("03:55");
		ponto0.getHorarios().addElement("04:50");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("CORREIO SENTIDO SUL");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("10/12/2007");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("00:30");
		ponto1.getHorarios().addElement("01:30");
		ponto1.getHorarios().addElement("01:55");
		ponto1.getHorarios().addElement("02:55");
		ponto1.getHorarios().addElement("03:55");
		ponto1.getHorarios().addElement("04:45");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL CAPAO RASO");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("10/12/2007");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("00:30");
		ponto2.getHorarios().addElement("00:55");
		ponto2.getHorarios().addElement("01:55");
		ponto2.getHorarios().addElement("02:30");
		ponto2.getHorarios().addElement("03:30");
		ponto2.getHorarios().addElement("04:20");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL SANTA CANDIDA");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("10/12/2007");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("00:10");
		ponto3.getHorarios().addElement("01:10");
		ponto3.getHorarios().addElement("01:37");
		ponto3.getHorarios().addElement("02:40");
		ponto3.getHorarios().addElement("03:30");
		ponto3.getHorarios().addElement("04:20");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("CORREIO SENTIDO NORTE");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("08/12/2007");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("00:50");
		ponto4.getHorarios().addElement("01:17");
		ponto4.getHorarios().addElement("02:20");
		ponto4.getHorarios().addElement("03:00");
		ponto4.getHorarios().addElement("03:55");
		ponto4.getHorarios().addElement("04:50");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("CORREIO SENTIDO SUL");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("08/12/2007");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("00:30");
		ponto5.getHorarios().addElement("01:30");
		ponto5.getHorarios().addElement("01:55");
		ponto5.getHorarios().addElement("02:55");
		ponto5.getHorarios().addElement("03:55");
		ponto5.getHorarios().addElement("04:45");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL CAPAO RASO");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("08/12/2007");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("00:30");
		ponto6.getHorarios().addElement("00:55");
		ponto6.getHorarios().addElement("01:55");
		ponto6.getHorarios().addElement("02:30");
		ponto6.getHorarios().addElement("03:30");
		ponto6.getHorarios().addElement("04:20");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("TERMINAL SANTA CANDIDA");
		ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto7.setValidoAPartirDe("08/12/2007");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("00:10");
		ponto7.getHorarios().addElement("01:10");
		ponto7.getHorarios().addElement("01:37");
		ponto7.getHorarios().addElement("02:40");
		ponto7.getHorarios().addElement("03:30");
		ponto7.getHorarios().addElement("04:20");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("CORREIO SENTIDO NORTE");
		ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto8.setValidoAPartirDe("09/12/2007");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("00:50");
		ponto8.getHorarios().addElement("01:17");
		ponto8.getHorarios().addElement("02:20");
		ponto8.getHorarios().addElement("03:00");
		ponto8.getHorarios().addElement("03:55");
		ponto8.getHorarios().addElement("04:50");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("CORREIO SENTIDO SUL");
		ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto9.setValidoAPartirDe("09/12/2007");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("00:30");
		ponto9.getHorarios().addElement("01:30");
		ponto9.getHorarios().addElement("01:57");
		ponto9.getHorarios().addElement("02:55");
		ponto9.getHorarios().addElement("03:55");
		ponto9.getHorarios().addElement("04:45");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("TERMINAL CAPAO RASO");
		ponto10.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto10.setValidoAPartirDe("09/12/2007");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("00:30");
		ponto10.getHorarios().addElement("00:55");
		ponto10.getHorarios().addElement("01:55");
		ponto10.getHorarios().addElement("02:30");
		ponto10.getHorarios().addElement("03:30");
		ponto10.getHorarios().addElement("04:20");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("TERMINAL SANTA CANDIDA");
		ponto11.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto11.setValidoAPartirDe("09/12/2007");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("00:10");
		ponto11.getHorarios().addElement("01:10");
		ponto11.getHorarios().addElement("01:37");
		ponto11.getHorarios().addElement("02:40");
		ponto11.getHorarios().addElement("03:30");
		ponto11.getHorarios().addElement("04:20");
		return onibus;
		}
	}