
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus630 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("630 - VITÓRIA RÉGIA");
		  onibus.setCodigo("630");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("KRAFT FOODS (SENT.PINHEIRINHO)");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("23/07/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("23:00");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL PINHEIRINHO");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("23/07/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:00");
		  ponto1.getHorarios().addElement("05:22");
		  ponto1.getHorarios().addElement("05:44");
		  ponto1.getHorarios().addElement("06:00");
		  ponto1.getHorarios().addElement("06:17");
		  ponto1.getHorarios().addElement("06:34");
		  ponto1.getHorarios().addElement("06:51");
		  ponto1.getHorarios().addElement("07:08");
		  ponto1.getHorarios().addElement("07:25");
		  ponto1.getHorarios().addElement("07:41");
		  ponto1.getHorarios().addElement("07:57");
		  ponto1.getHorarios().addElement("08:14");
		  ponto1.getHorarios().addElement("08:31");
		  ponto1.getHorarios().addElement("08:53");
		  ponto1.getHorarios().addElement("09:18");
		  ponto1.getHorarios().addElement("09:43");
		  ponto1.getHorarios().addElement("10:08");
		  ponto1.getHorarios().addElement("10:33");
		  ponto1.getHorarios().addElement("10:58");
		  ponto1.getHorarios().addElement("11:23");
		  ponto1.getHorarios().addElement("11:48");
		  ponto1.getHorarios().addElement("12:13");
		  ponto1.getHorarios().addElement("12:38");
		  ponto1.getHorarios().addElement("13:03");
		  ponto1.getHorarios().addElement("13:28");
		  ponto1.getHorarios().addElement("13:53");
		  ponto1.getHorarios().addElement("14:18");
		  ponto1.getHorarios().addElement("14:43");
		  ponto1.getHorarios().addElement("15:08");
		  ponto1.getHorarios().addElement("15:33");
		  ponto1.getHorarios().addElement("15:58");
		  ponto1.getHorarios().addElement("16:23");
		  ponto1.getHorarios().addElement("16:48");
		  ponto1.getHorarios().addElement("17:03");
		  ponto1.getHorarios().addElement("17:18");
		  ponto1.getHorarios().addElement("17:36");
		  ponto1.getHorarios().addElement("17:54");
		  ponto1.getHorarios().addElement("18:14");
		  ponto1.getHorarios().addElement("18:30");
		  ponto1.getHorarios().addElement("18:46");
		  ponto1.getHorarios().addElement("19:02");
		  ponto1.getHorarios().addElement("19:18");
		  ponto1.getHorarios().addElement("19:39");
		  ponto1.getHorarios().addElement("20:00");
		  ponto1.getHorarios().addElement("20:25");
		  ponto1.getHorarios().addElement("20:50");
		  ponto1.getHorarios().addElement("21:14");
		  ponto1.getHorarios().addElement("21:38");
		  ponto1.getHorarios().addElement("22:02");
		  ponto1.getHorarios().addElement("22:26");
		  ponto1.getHorarios().addElement("22:50");
		  ponto1.getHorarios().addElement("23:15");
		  ponto1.getHorarios().addElement("23:40");
		  ponto1.getHorarios().addElement("00:10");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("VITORIA REGIA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("23/07/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:00");
		  ponto2.getHorarios().addElement("05:17");
		  ponto2.getHorarios().addElement("05:33");
		  ponto2.getHorarios().addElement("05:50");
		  ponto2.getHorarios().addElement("06:07");
		  ponto2.getHorarios().addElement("06:20");
		  ponto2.getHorarios().addElement("06:44");
		  ponto2.getHorarios().addElement("06:59");
		  ponto2.getHorarios().addElement("07:15");
		  ponto2.getHorarios().addElement("07:30");
		  ponto2.getHorarios().addElement("07:47");
		  ponto2.getHorarios().addElement("08:04");
		  ponto2.getHorarios().addElement("08:21");
		  ponto2.getHorarios().addElement("08:36");
		  ponto2.getHorarios().addElement("08:51");
		  ponto2.getHorarios().addElement("09:16");
		  ponto2.getHorarios().addElement("09:41");
		  ponto2.getHorarios().addElement("10:06");
		  ponto2.getHorarios().addElement("10:31");
		  ponto2.getHorarios().addElement("10:56");
		  ponto2.getHorarios().addElement("11:21");
		  ponto2.getHorarios().addElement("11:46");
		  ponto2.getHorarios().addElement("12:11");
		  ponto2.getHorarios().addElement("12:36");
		  ponto2.getHorarios().addElement("13:01");
		  ponto2.getHorarios().addElement("13:26");
		  ponto2.getHorarios().addElement("13:51");
		  ponto2.getHorarios().addElement("14:16");
		  ponto2.getHorarios().addElement("14:41");
		  ponto2.getHorarios().addElement("15:06");
		  ponto2.getHorarios().addElement("15:31");
		  ponto2.getHorarios().addElement("15:56");
		  ponto2.getHorarios().addElement("16:21");
		  ponto2.getHorarios().addElement("16:46");
		  ponto2.getHorarios().addElement("17:11");
		  ponto2.getHorarios().addElement("17:28");
		  ponto2.getHorarios().addElement("17:45");
		  ponto2.getHorarios().addElement("18:03");
		  ponto2.getHorarios().addElement("18:21");
		  ponto2.getHorarios().addElement("18:39");
		  ponto2.getHorarios().addElement("18:57");
		  ponto2.getHorarios().addElement("19:15");
		  ponto2.getHorarios().addElement("19:33");
		  ponto2.getHorarios().addElement("19:58");
		  ponto2.getHorarios().addElement("20:23");
		  ponto2.getHorarios().addElement("20:48");
		  ponto2.getHorarios().addElement("21:13");
		  ponto2.getHorarios().addElement("21:38");
		  ponto2.getHorarios().addElement("22:02");
		  ponto2.getHorarios().addElement("22:26");
		  ponto2.getHorarios().addElement("22:50");
		  ponto2.getHorarios().addElement("23:16");
		  ponto2.getHorarios().addElement("23:41");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("KRAFT FOODS (SENT.PINHEIRINHO)");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("01/09/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("22:50");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TERMINAL PINHEIRINHO");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("01/09/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("05:30");
		  ponto4.getHorarios().addElement("06:15");
		  ponto4.getHorarios().addElement("06:40");
		  ponto4.getHorarios().addElement("07:03");
		  ponto4.getHorarios().addElement("07:28");
		  ponto4.getHorarios().addElement("07:51");
		  ponto4.getHorarios().addElement("08:16");
		  ponto4.getHorarios().addElement("08:39");
		  ponto4.getHorarios().addElement("09:06");
		  ponto4.getHorarios().addElement("09:29");
		  ponto4.getHorarios().addElement("09:56");
		  ponto4.getHorarios().addElement("10:19");
		  ponto4.getHorarios().addElement("10:46");
		  ponto4.getHorarios().addElement("11:09");
		  ponto4.getHorarios().addElement("11:34");
		  ponto4.getHorarios().addElement("11:57");
		  ponto4.getHorarios().addElement("12:22");
		  ponto4.getHorarios().addElement("12:47");
		  ponto4.getHorarios().addElement("13:12");
		  ponto4.getHorarios().addElement("13:37");
		  ponto4.getHorarios().addElement("14:03");
		  ponto4.getHorarios().addElement("14:29");
		  ponto4.getHorarios().addElement("14:54");
		  ponto4.getHorarios().addElement("15:19");
		  ponto4.getHorarios().addElement("15:44");
		  ponto4.getHorarios().addElement("16:09");
		  ponto4.getHorarios().addElement("16:34");
		  ponto4.getHorarios().addElement("16:59");
		  ponto4.getHorarios().addElement("17:24");
		  ponto4.getHorarios().addElement("17:49");
		  ponto4.getHorarios().addElement("18:14");
		  ponto4.getHorarios().addElement("18:39");
		  ponto4.getHorarios().addElement("19:04");
		  ponto4.getHorarios().addElement("19:29");
		  ponto4.getHorarios().addElement("20:15");
		  ponto4.getHorarios().addElement("21:00");
		  ponto4.getHorarios().addElement("21:45");
		  ponto4.getHorarios().addElement("22:25");
		  ponto4.getHorarios().addElement("23:17");
		  ponto4.getHorarios().addElement("00:03");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("VITORIA REGIA");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("01/09/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:00");
		  ponto5.getHorarios().addElement("05:50");
		  ponto5.getHorarios().addElement("06:15");
		  ponto5.getHorarios().addElement("06:38");
		  ponto5.getHorarios().addElement("07:03");
		  ponto5.getHorarios().addElement("07:26");
		  ponto5.getHorarios().addElement("07:51");
		  ponto5.getHorarios().addElement("08:14");
		  ponto5.getHorarios().addElement("08:39");
		  ponto5.getHorarios().addElement("09:02");
		  ponto5.getHorarios().addElement("09:29");
		  ponto5.getHorarios().addElement("09:52");
		  ponto5.getHorarios().addElement("10:19");
		  ponto5.getHorarios().addElement("10:42");
		  ponto5.getHorarios().addElement("11:09");
		  ponto5.getHorarios().addElement("11:32");
		  ponto5.getHorarios().addElement("11:57");
		  ponto5.getHorarios().addElement("12:22");
		  ponto5.getHorarios().addElement("12:47");
		  ponto5.getHorarios().addElement("13:12");
		  ponto5.getHorarios().addElement("13:37");
		  ponto5.getHorarios().addElement("14:02");
		  ponto5.getHorarios().addElement("14:27");
		  ponto5.getHorarios().addElement("14:52");
		  ponto5.getHorarios().addElement("15:17");
		  ponto5.getHorarios().addElement("15:42");
		  ponto5.getHorarios().addElement("16:07");
		  ponto5.getHorarios().addElement("16:32");
		  ponto5.getHorarios().addElement("16:57");
		  ponto5.getHorarios().addElement("17:22");
		  ponto5.getHorarios().addElement("17:47");
		  ponto5.getHorarios().addElement("18:12");
		  ponto5.getHorarios().addElement("18:37");
		  ponto5.getHorarios().addElement("19:02");
		  ponto5.getHorarios().addElement("19:50");
		  ponto5.getHorarios().addElement("20:35");
		  ponto5.getHorarios().addElement("21:20");
		  ponto5.getHorarios().addElement("22:03");
		  ponto5.getHorarios().addElement("22:44");
		  ponto5.getHorarios().addElement("23:40");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("KRAFT FOODS (SENT.PINHEIRINHO)");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("13/05/2012");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("22:50");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("TERMINAL PINHEIRINHO");
		  ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto7.setValidoAPartirDe("13/05/2012");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("05:40");
		  ponto7.getHorarios().addElement("06:30");
		  ponto7.getHorarios().addElement("07:18");
		  ponto7.getHorarios().addElement("08:08");
		  ponto7.getHorarios().addElement("08:58");
		  ponto7.getHorarios().addElement("09:48");
		  ponto7.getHorarios().addElement("10:38");
		  ponto7.getHorarios().addElement("11:28");
		  ponto7.getHorarios().addElement("12:18");
		  ponto7.getHorarios().addElement("13:08");
		  ponto7.getHorarios().addElement("13:58");
		  ponto7.getHorarios().addElement("14:48");
		  ponto7.getHorarios().addElement("15:38");
		  ponto7.getHorarios().addElement("16:28");
		  ponto7.getHorarios().addElement("17:18");
		  ponto7.getHorarios().addElement("18:08");
		  ponto7.getHorarios().addElement("18:58");
		  ponto7.getHorarios().addElement("19:48");
		  ponto7.getHorarios().addElement("20:40");
		  ponto7.getHorarios().addElement("21:32");
		  ponto7.getHorarios().addElement("22:25");
		  ponto7.getHorarios().addElement("23:17");
		  ponto7.getHorarios().addElement("00:01");
		  Ponto ponto8 = new Ponto();
		  ponto8.setNome("VITORIA REGIA");
		  ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto8.setValidoAPartirDe("13/05/2012");
		  onibus.getPontos().addElement(ponto8);
		  ponto8.getHorarios().addElement("05:15");
		  ponto8.getHorarios().addElement("06:05");
		  ponto8.getHorarios().addElement("06:53");
		  ponto8.getHorarios().addElement("07:43");
		  ponto8.getHorarios().addElement("08:33");
		  ponto8.getHorarios().addElement("09:21");
		  ponto8.getHorarios().addElement("10:11");
		  ponto8.getHorarios().addElement("11:01");
		  ponto8.getHorarios().addElement("11:53");
		  ponto8.getHorarios().addElement("12:43");
		  ponto8.getHorarios().addElement("13:33");
		  ponto8.getHorarios().addElement("14:23");
		  ponto8.getHorarios().addElement("15:11");
		  ponto8.getHorarios().addElement("16:01");
		  ponto8.getHorarios().addElement("16:51");
		  ponto8.getHorarios().addElement("17:41");
		  ponto8.getHorarios().addElement("18:31");
		  ponto8.getHorarios().addElement("19:23");
		  ponto8.getHorarios().addElement("20:13");
		  ponto8.getHorarios().addElement("21:05");
		  ponto8.getHorarios().addElement("21:57");
		  ponto8.getHorarios().addElement("22:44");
		  ponto8.getHorarios().addElement("23:38");
		  return onibus;
		  }
	  }