
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus967 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("967 - JÚLIO GRAF");
		  onibus.setCodigo("967");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO JULIO GRAF");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("22/10/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("05:48");
		  ponto0.getHorarios().addElement("06:06");
		  ponto0.getHorarios().addElement("06:22");
		  ponto0.getHorarios().addElement("06:41");
		  ponto0.getHorarios().addElement("07:00");
		  ponto0.getHorarios().addElement("07:12");
		  ponto0.getHorarios().addElement("07:30");
		  ponto0.getHorarios().addElement("07:50");
		  ponto0.getHorarios().addElement("08:12");
		  ponto0.getHorarios().addElement("08:35");
		  ponto0.getHorarios().addElement("09:00");
		  ponto0.getHorarios().addElement("09:30");
		  ponto0.getHorarios().addElement("10:00");
		  ponto0.getHorarios().addElement("10:30");
		  ponto0.getHorarios().addElement("11:00");
		  ponto0.getHorarios().addElement("11:30");
		  ponto0.getHorarios().addElement("12:00");
		  ponto0.getHorarios().addElement("12:30");
		  ponto0.getHorarios().addElement("13:00");
		  ponto0.getHorarios().addElement("13:30");
		  ponto0.getHorarios().addElement("14:00");
		  ponto0.getHorarios().addElement("14:30");
		  ponto0.getHorarios().addElement("15:00");
		  ponto0.getHorarios().addElement("15:31");
		  ponto0.getHorarios().addElement("16:02");
		  ponto0.getHorarios().addElement("16:34");
		  ponto0.getHorarios().addElement("17:04");
		  ponto0.getHorarios().addElement("17:25");
		  ponto0.getHorarios().addElement("17:45");
		  ponto0.getHorarios().addElement("18:04");
		  ponto0.getHorarios().addElement("18:24");
		  ponto0.getHorarios().addElement("18:45");
		  ponto0.getHorarios().addElement("19:06");
		  ponto0.getHorarios().addElement("19:26");
		  ponto0.getHorarios().addElement("19:48");
		  ponto0.getHorarios().addElement("20:23");
		  ponto0.getHorarios().addElement("21:16");
		  ponto0.getHorarios().addElement("22:09");
		  ponto0.getHorarios().addElement("23:02");
		  ponto0.getHorarios().addElement("23:55");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("RUA BARAO DO CERRO AZUL");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("22/10/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:55");
		  ponto1.getHorarios().addElement("06:14");
		  ponto1.getHorarios().addElement("06:32");
		  ponto1.getHorarios().addElement("06:46");
		  ponto1.getHorarios().addElement("07:06");
		  ponto1.getHorarios().addElement("07:26");
		  ponto1.getHorarios().addElement("07:44");
		  ponto1.getHorarios().addElement("08:05");
		  ponto1.getHorarios().addElement("08:31");
		  ponto1.getHorarios().addElement("09:02");
		  ponto1.getHorarios().addElement("09:30");
		  ponto1.getHorarios().addElement("10:00");
		  ponto1.getHorarios().addElement("10:30");
		  ponto1.getHorarios().addElement("11:00");
		  ponto1.getHorarios().addElement("11:30");
		  ponto1.getHorarios().addElement("12:00");
		  ponto1.getHorarios().addElement("12:30");
		  ponto1.getHorarios().addElement("13:00");
		  ponto1.getHorarios().addElement("13:30");
		  ponto1.getHorarios().addElement("14:00");
		  ponto1.getHorarios().addElement("14:30");
		  ponto1.getHorarios().addElement("15:00");
		  ponto1.getHorarios().addElement("15:31");
		  ponto1.getHorarios().addElement("16:02");
		  ponto1.getHorarios().addElement("16:32");
		  ponto1.getHorarios().addElement("16:53");
		  ponto1.getHorarios().addElement("17:13");
		  ponto1.getHorarios().addElement("17:33");
		  ponto1.getHorarios().addElement("17:53");
		  ponto1.getHorarios().addElement("18:13");
		  ponto1.getHorarios().addElement("18:32");
		  ponto1.getHorarios().addElement("18:52");
		  ponto1.getHorarios().addElement("19:13");
		  ponto1.getHorarios().addElement("19:34");
		  ponto1.getHorarios().addElement("19:55");
		  ponto1.getHorarios().addElement("20:20");
		  ponto1.getHorarios().addElement("20:50");
		  ponto1.getHorarios().addElement("21:42");
		  ponto1.getHorarios().addElement("22:35");
		  ponto1.getHorarios().addElement("23:33");
		  ponto1.getHorarios().addElement("00:15");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TROMBINI");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("22/10/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("23:10");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("BAIRRO JULIO GRAF");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("18/03/2006");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:30");
		  ponto3.getHorarios().addElement("06:18");
		  ponto3.getHorarios().addElement("07:10");
		  ponto3.getHorarios().addElement("07:54");
		  ponto3.getHorarios().addElement("08:42");
		  ponto3.getHorarios().addElement("09:32");
		  ponto3.getHorarios().addElement("10:22");
		  ponto3.getHorarios().addElement("11:12");
		  ponto3.getHorarios().addElement("12:02");
		  ponto3.getHorarios().addElement("12:52");
		  ponto3.getHorarios().addElement("13:44");
		  ponto3.getHorarios().addElement("14:36");
		  ponto3.getHorarios().addElement("15:22");
		  ponto3.getHorarios().addElement("16:12");
		  ponto3.getHorarios().addElement("17:02");
		  ponto3.getHorarios().addElement("17:52");
		  ponto3.getHorarios().addElement("18:42");
		  ponto3.getHorarios().addElement("19:35");
		  ponto3.getHorarios().addElement("20:25");
		  ponto3.getHorarios().addElement("21:15");
		  ponto3.getHorarios().addElement("22:05");
		  ponto3.getHorarios().addElement("23:05");
		  ponto3.getHorarios().addElement("23:50");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("RUA BARAO DO CERRO AZUL");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("18/03/2006");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("05:55");
		  ponto4.getHorarios().addElement("06:43");
		  ponto4.getHorarios().addElement("07:33");
		  ponto4.getHorarios().addElement("08:19");
		  ponto4.getHorarios().addElement("09:07");
		  ponto4.getHorarios().addElement("09:57");
		  ponto4.getHorarios().addElement("10:47");
		  ponto4.getHorarios().addElement("11:37");
		  ponto4.getHorarios().addElement("12:27");
		  ponto4.getHorarios().addElement("13:17");
		  ponto4.getHorarios().addElement("14:11");
		  ponto4.getHorarios().addElement("14:59");
		  ponto4.getHorarios().addElement("15:47");
		  ponto4.getHorarios().addElement("16:37");
		  ponto4.getHorarios().addElement("17:27");
		  ponto4.getHorarios().addElement("18:17");
		  ponto4.getHorarios().addElement("19:07");
		  ponto4.getHorarios().addElement("20:02");
		  ponto4.getHorarios().addElement("20:50");
		  ponto4.getHorarios().addElement("21:40");
		  ponto4.getHorarios().addElement("22:30");
		  ponto4.getHorarios().addElement("23:30");
		  ponto4.getHorarios().addElement("00:15");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("BAIRRO JULIO GRAF");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("19/03/2006");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:30");
		  ponto5.getHorarios().addElement("06:18");
		  ponto5.getHorarios().addElement("07:10");
		  ponto5.getHorarios().addElement("07:54");
		  ponto5.getHorarios().addElement("08:42");
		  ponto5.getHorarios().addElement("09:32");
		  ponto5.getHorarios().addElement("10:22");
		  ponto5.getHorarios().addElement("11:12");
		  ponto5.getHorarios().addElement("12:02");
		  ponto5.getHorarios().addElement("12:52");
		  ponto5.getHorarios().addElement("13:44");
		  ponto5.getHorarios().addElement("14:36");
		  ponto5.getHorarios().addElement("15:22");
		  ponto5.getHorarios().addElement("16:12");
		  ponto5.getHorarios().addElement("17:02");
		  ponto5.getHorarios().addElement("17:52");
		  ponto5.getHorarios().addElement("18:42");
		  ponto5.getHorarios().addElement("19:35");
		  ponto5.getHorarios().addElement("20:25");
		  ponto5.getHorarios().addElement("21:15");
		  ponto5.getHorarios().addElement("22:05");
		  ponto5.getHorarios().addElement("23:00");
		  ponto5.getHorarios().addElement("23:45");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("RUA BARAO DO CERRO AZUL");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("19/03/2006");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("05:55");
		  ponto6.getHorarios().addElement("06:43");
		  ponto6.getHorarios().addElement("07:33");
		  ponto6.getHorarios().addElement("08:19");
		  ponto6.getHorarios().addElement("09:07");
		  ponto6.getHorarios().addElement("09:57");
		  ponto6.getHorarios().addElement("10:47");
		  ponto6.getHorarios().addElement("11:37");
		  ponto6.getHorarios().addElement("12:27");
		  ponto6.getHorarios().addElement("13:17");
		  ponto6.getHorarios().addElement("14:11");
		  ponto6.getHorarios().addElement("14:59");
		  ponto6.getHorarios().addElement("15:47");
		  ponto6.getHorarios().addElement("16:37");
		  ponto6.getHorarios().addElement("17:27");
		  ponto6.getHorarios().addElement("18:17");
		  ponto6.getHorarios().addElement("19:07");
		  ponto6.getHorarios().addElement("20:02");
		  ponto6.getHorarios().addElement("20:50");
		  ponto6.getHorarios().addElement("21:40");
		  ponto6.getHorarios().addElement("22:30");
		  ponto6.getHorarios().addElement("23:25");
		  ponto6.getHorarios().addElement("00:15");
		  return onibus;
		  }
	  }