
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus921 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("921 - JD. PIONEIRO");
		  onibus.setCodigo("921");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO JARDIM PIONEIRO");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("23/11/2009");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:30");
		  ponto0.getHorarios().addElement("05:52");
		  ponto0.getHorarios().addElement("06:15");
		  ponto0.getHorarios().addElement("06:40");
		  ponto0.getHorarios().addElement("07:02");
		  ponto0.getHorarios().addElement("07:24");
		  ponto0.getHorarios().addElement("07:45");
		  ponto0.getHorarios().addElement("08:30");
		  ponto0.getHorarios().addElement("09:19");
		  ponto0.getHorarios().addElement("10:12");
		  ponto0.getHorarios().addElement("11:05");
		  ponto0.getHorarios().addElement("11:56");
		  ponto0.getHorarios().addElement("12:49");
		  ponto0.getHorarios().addElement("13:44");
		  ponto0.getHorarios().addElement("14:37");
		  ponto0.getHorarios().addElement("15:30");
		  ponto0.getHorarios().addElement("16:20");
		  ponto0.getHorarios().addElement("17:10");
		  ponto0.getHorarios().addElement("17:35");
		  ponto0.getHorarios().addElement("18:00");
		  ponto0.getHorarios().addElement("18:25");
		  ponto0.getHorarios().addElement("18:50");
		  ponto0.getHorarios().addElement("19:44");
		  ponto0.getHorarios().addElement("20:42");
		  ponto0.getHorarios().addElement("21:40");
		  ponto0.getHorarios().addElement("22:40");
		  ponto0.getHorarios().addElement("23:35");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("TERMINAL SANTA FELICIDADE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("23/11/2009");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:52");
		  ponto1.getHorarios().addElement("06:15");
		  ponto1.getHorarios().addElement("06:40");
		  ponto1.getHorarios().addElement("07:02");
		  ponto1.getHorarios().addElement("07:24");
		  ponto1.getHorarios().addElement("08:07");
		  ponto1.getHorarios().addElement("08:52");
		  ponto1.getHorarios().addElement("09:45");
		  ponto1.getHorarios().addElement("10:38");
		  ponto1.getHorarios().addElement("11:29");
		  ponto1.getHorarios().addElement("12:20");
		  ponto1.getHorarios().addElement("13:17");
		  ponto1.getHorarios().addElement("14:10");
		  ponto1.getHorarios().addElement("15:03");
		  ponto1.getHorarios().addElement("15:55");
		  ponto1.getHorarios().addElement("16:45");
		  ponto1.getHorarios().addElement("17:10");
		  ponto1.getHorarios().addElement("17:35");
		  ponto1.getHorarios().addElement("18:00");
		  ponto1.getHorarios().addElement("18:25");
		  ponto1.getHorarios().addElement("18:50");
		  ponto1.getHorarios().addElement("19:15");
		  ponto1.getHorarios().addElement("20:13");
		  ponto1.getHorarios().addElement("21:11");
		  ponto1.getHorarios().addElement("22:10");
		  ponto1.getHorarios().addElement("23:10");
		  ponto1.getHorarios().addElement("00:00");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("BAIRRO JARDIM PIONEIRO");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("15/08/2009");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:45");
		  ponto2.getHorarios().addElement("06:45");
		  ponto2.getHorarios().addElement("07:35");
		  ponto2.getHorarios().addElement("08:25");
		  ponto2.getHorarios().addElement("09:15");
		  ponto2.getHorarios().addElement("10:05");
		  ponto2.getHorarios().addElement("10:55");
		  ponto2.getHorarios().addElement("11:45");
		  ponto2.getHorarios().addElement("12:35");
		  ponto2.getHorarios().addElement("13:25");
		  ponto2.getHorarios().addElement("14:15");
		  ponto2.getHorarios().addElement("15:05");
		  ponto2.getHorarios().addElement("15:55");
		  ponto2.getHorarios().addElement("16:45");
		  ponto2.getHorarios().addElement("17:35");
		  ponto2.getHorarios().addElement("18:25");
		  ponto2.getHorarios().addElement("19:15");
		  ponto2.getHorarios().addElement("20:05");
		  ponto2.getHorarios().addElement("20:55");
		  ponto2.getHorarios().addElement("21:45");
		  ponto2.getHorarios().addElement("22:45");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TERMINAL SANTA FELICIDADE");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("15/08/2009");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("06:15");
		  ponto3.getHorarios().addElement("07:10");
		  ponto3.getHorarios().addElement("08:00");
		  ponto3.getHorarios().addElement("08:50");
		  ponto3.getHorarios().addElement("09:40");
		  ponto3.getHorarios().addElement("10:30");
		  ponto3.getHorarios().addElement("11:20");
		  ponto3.getHorarios().addElement("12:10");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("13:50");
		  ponto3.getHorarios().addElement("14:40");
		  ponto3.getHorarios().addElement("15:30");
		  ponto3.getHorarios().addElement("16:20");
		  ponto3.getHorarios().addElement("17:10");
		  ponto3.getHorarios().addElement("18:00");
		  ponto3.getHorarios().addElement("18:50");
		  ponto3.getHorarios().addElement("19:40");
		  ponto3.getHorarios().addElement("20:30");
		  ponto3.getHorarios().addElement("21:20");
		  ponto3.getHorarios().addElement("22:15");
		  ponto3.getHorarios().addElement("23:15");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO JARDIM PIONEIRO");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("16/08/2009");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("05:45");
		  ponto4.getHorarios().addElement("06:45");
		  ponto4.getHorarios().addElement("07:35");
		  ponto4.getHorarios().addElement("08:25");
		  ponto4.getHorarios().addElement("09:15");
		  ponto4.getHorarios().addElement("10:05");
		  ponto4.getHorarios().addElement("10:55");
		  ponto4.getHorarios().addElement("11:45");
		  ponto4.getHorarios().addElement("12:35");
		  ponto4.getHorarios().addElement("13:25");
		  ponto4.getHorarios().addElement("14:15");
		  ponto4.getHorarios().addElement("15:05");
		  ponto4.getHorarios().addElement("15:55");
		  ponto4.getHorarios().addElement("16:45");
		  ponto4.getHorarios().addElement("17:35");
		  ponto4.getHorarios().addElement("18:25");
		  ponto4.getHorarios().addElement("19:15");
		  ponto4.getHorarios().addElement("20:05");
		  ponto4.getHorarios().addElement("20:55");
		  ponto4.getHorarios().addElement("21:45");
		  ponto4.getHorarios().addElement("22:35");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL SANTA FELICIDADE");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("16/08/2009");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:15");
		  ponto5.getHorarios().addElement("07:10");
		  ponto5.getHorarios().addElement("08:00");
		  ponto5.getHorarios().addElement("08:50");
		  ponto5.getHorarios().addElement("09:40");
		  ponto5.getHorarios().addElement("10:30");
		  ponto5.getHorarios().addElement("11:20");
		  ponto5.getHorarios().addElement("12:10");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:50");
		  ponto5.getHorarios().addElement("14:40");
		  ponto5.getHorarios().addElement("15:30");
		  ponto5.getHorarios().addElement("16:20");
		  ponto5.getHorarios().addElement("17:10");
		  ponto5.getHorarios().addElement("18:00");
		  ponto5.getHorarios().addElement("18:50");
		  ponto5.getHorarios().addElement("19:40");
		  ponto5.getHorarios().addElement("20:30");
		  ponto5.getHorarios().addElement("21:20");
		  ponto5.getHorarios().addElement("22:10");
		  ponto5.getHorarios().addElement("23:00");
		  return onibus;
		  }
	  }