
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus683 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("683 - FUTURAMA / S. CERCADO");
		  onibus.setCodigo("683");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("TERMINAL SITIO CERCADO");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("15/10/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("05:25");
		  ponto0.getHorarios().addElement("06:05");
		  ponto0.getHorarios().addElement("06:45");
		  ponto0.getHorarios().addElement("07:24");
		  ponto0.getHorarios().addElement("08:03");
		  ponto0.getHorarios().addElement("08:42");
		  ponto0.getHorarios().addElement("09:21");
		  ponto0.getHorarios().addElement("10:00");
		  ponto0.getHorarios().addElement("10:39");
		  ponto0.getHorarios().addElement("11:18");
		  ponto0.getHorarios().addElement("11:57");
		  ponto0.getHorarios().addElement("12:36");
		  ponto0.getHorarios().addElement("13:15");
		  ponto0.getHorarios().addElement("13:54");
		  ponto0.getHorarios().addElement("14:33");
		  ponto0.getHorarios().addElement("15:12");
		  ponto0.getHorarios().addElement("15:51");
		  ponto0.getHorarios().addElement("16:30");
		  ponto0.getHorarios().addElement("17:09");
		  ponto0.getHorarios().addElement("17:48");
		  ponto0.getHorarios().addElement("18:27");
		  ponto0.getHorarios().addElement("19:06");
		  ponto0.getHorarios().addElement("19:45");
		  ponto0.getHorarios().addElement("20:24");
		  ponto0.getHorarios().addElement("21:05");
		  ponto0.getHorarios().addElement("21:55");
		  ponto0.getHorarios().addElement("22:45");
		  ponto0.getHorarios().addElement("23:45");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("BAIRRO FUTURAMA VIA S.CERCADO");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("15/10/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:05");
		  ponto1.getHorarios().addElement("05:45");
		  ponto1.getHorarios().addElement("06:24");
		  ponto1.getHorarios().addElement("07:03");
		  ponto1.getHorarios().addElement("07:42");
		  ponto1.getHorarios().addElement("08:21");
		  ponto1.getHorarios().addElement("09:00");
		  ponto1.getHorarios().addElement("09:39");
		  ponto1.getHorarios().addElement("10:18");
		  ponto1.getHorarios().addElement("10:57");
		  ponto1.getHorarios().addElement("11:36");
		  ponto1.getHorarios().addElement("12:15");
		  ponto1.getHorarios().addElement("12:54");
		  ponto1.getHorarios().addElement("13:33");
		  ponto1.getHorarios().addElement("14:12");
		  ponto1.getHorarios().addElement("14:51");
		  ponto1.getHorarios().addElement("15:30");
		  ponto1.getHorarios().addElement("16:09");
		  ponto1.getHorarios().addElement("16:48");
		  ponto1.getHorarios().addElement("17:27");
		  ponto1.getHorarios().addElement("18:06");
		  ponto1.getHorarios().addElement("18:45");
		  ponto1.getHorarios().addElement("19:24");
		  ponto1.getHorarios().addElement("20:03");
		  ponto1.getHorarios().addElement("20:40");
		  ponto1.getHorarios().addElement("21:30");
		  ponto1.getHorarios().addElement("22:20");
		  ponto1.getHorarios().addElement("23:15");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL SITIO CERCADO");
		  ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto2.setValidoAPartirDe("09/12/2006");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("05:59");
		  ponto2.getHorarios().addElement("06:48");
		  ponto2.getHorarios().addElement("07:38");
		  ponto2.getHorarios().addElement("08:26");
		  ponto2.getHorarios().addElement("09:17");
		  ponto2.getHorarios().addElement("10:07");
		  ponto2.getHorarios().addElement("10:57");
		  ponto2.getHorarios().addElement("11:47");
		  ponto2.getHorarios().addElement("12:37");
		  ponto2.getHorarios().addElement("13:27");
		  ponto2.getHorarios().addElement("14:17");
		  ponto2.getHorarios().addElement("15:07");
		  ponto2.getHorarios().addElement("15:57");
		  ponto2.getHorarios().addElement("16:47");
		  ponto2.getHorarios().addElement("17:37");
		  ponto2.getHorarios().addElement("18:27");
		  ponto2.getHorarios().addElement("19:17");
		  ponto2.getHorarios().addElement("20:07");
		  ponto2.getHorarios().addElement("20:55");
		  ponto2.getHorarios().addElement("21:35");
		  ponto2.getHorarios().addElement("22:23");
		  ponto2.getHorarios().addElement("23:11");
		  ponto2.getHorarios().addElement("00:00");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("BAIRRO FUTURAMA VIA S.CERCADO");
		  ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto3.setValidoAPartirDe("09/12/2006");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:33");
		  ponto3.getHorarios().addElement("06:23");
		  ponto3.getHorarios().addElement("07:13");
		  ponto3.getHorarios().addElement("08:03");
		  ponto3.getHorarios().addElement("08:52");
		  ponto3.getHorarios().addElement("09:42");
		  ponto3.getHorarios().addElement("10:32");
		  ponto3.getHorarios().addElement("11:22");
		  ponto3.getHorarios().addElement("12:12");
		  ponto3.getHorarios().addElement("13:02");
		  ponto3.getHorarios().addElement("13:52");
		  ponto3.getHorarios().addElement("14:42");
		  ponto3.getHorarios().addElement("15:32");
		  ponto3.getHorarios().addElement("16:22");
		  ponto3.getHorarios().addElement("17:12");
		  ponto3.getHorarios().addElement("18:02");
		  ponto3.getHorarios().addElement("18:52");
		  ponto3.getHorarios().addElement("19:42");
		  ponto3.getHorarios().addElement("20:32");
		  ponto3.getHorarios().addElement("21:15");
		  ponto3.getHorarios().addElement("21:59");
		  ponto3.getHorarios().addElement("22:47");
		  ponto3.getHorarios().addElement("23:35");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TERMINAL SITIO CERCADO");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto4.setValidoAPartirDe("10/12/2006");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:18");
		  ponto4.getHorarios().addElement("07:08");
		  ponto4.getHorarios().addElement("07:58");
		  ponto4.getHorarios().addElement("08:48");
		  ponto4.getHorarios().addElement("09:38");
		  ponto4.getHorarios().addElement("10:28");
		  ponto4.getHorarios().addElement("11:18");
		  ponto4.getHorarios().addElement("12:08");
		  ponto4.getHorarios().addElement("12:58");
		  ponto4.getHorarios().addElement("13:48");
		  ponto4.getHorarios().addElement("14:38");
		  ponto4.getHorarios().addElement("15:28");
		  ponto4.getHorarios().addElement("16:18");
		  ponto4.getHorarios().addElement("17:08");
		  ponto4.getHorarios().addElement("17:58");
		  ponto4.getHorarios().addElement("18:48");
		  ponto4.getHorarios().addElement("19:45");
		  ponto4.getHorarios().addElement("20:40");
		  ponto4.getHorarios().addElement("21:30");
		  ponto4.getHorarios().addElement("22:20");
		  ponto4.getHorarios().addElement("23:10");
		  ponto4.getHorarios().addElement("00:00");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("BAIRRO FUTURAMA VIA S.CERCADO");
		  ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto5.setValidoAPartirDe("10/12/2006");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:53");
		  ponto5.getHorarios().addElement("06:43");
		  ponto5.getHorarios().addElement("07:33");
		  ponto5.getHorarios().addElement("08:23");
		  ponto5.getHorarios().addElement("09:13");
		  ponto5.getHorarios().addElement("10:03");
		  ponto5.getHorarios().addElement("10:53");
		  ponto5.getHorarios().addElement("11:43");
		  ponto5.getHorarios().addElement("12:33");
		  ponto5.getHorarios().addElement("13:23");
		  ponto5.getHorarios().addElement("14:13");
		  ponto5.getHorarios().addElement("15:03");
		  ponto5.getHorarios().addElement("15:53");
		  ponto5.getHorarios().addElement("16:43");
		  ponto5.getHorarios().addElement("17:33");
		  ponto5.getHorarios().addElement("18:23");
		  ponto5.getHorarios().addElement("19:13");
		  ponto5.getHorarios().addElement("20:10");
		  ponto5.getHorarios().addElement("21:05");
		  ponto5.getHorarios().addElement("21:55");
		  ponto5.getHorarios().addElement("22:45");
		  ponto5.getHorarios().addElement("23:35");
		  return onibus;
		  }
	  }