
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class OnibusI50 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("I50 - Q. BARRAS/T.PAULISTA-HORARIO");
		  onibus.setCodigo("I50");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("TREVO DO ATUBA");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("09/04/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("00:00");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("T.Q.BARRAS(VIA MENINO DEUS)");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("09/04/2012");
		  onibus.getPontos().addElement(ponto1);
		  ponto1.getHorarios().addElement("05:18");
		  ponto1.getHorarios().addElement("06:18");
		  ponto1.getHorarios().addElement("07:18");
		  ponto1.getHorarios().addElement("08:18");
		  ponto1.getHorarios().addElement("09:18");
		  ponto1.getHorarios().addElement("10:18");
		  ponto1.getHorarios().addElement("11:18");
		  ponto1.getHorarios().addElement("12:18");
		  ponto1.getHorarios().addElement("13:18");
		  ponto1.getHorarios().addElement("14:18");
		  ponto1.getHorarios().addElement("15:18");
		  ponto1.getHorarios().addElement("16:18");
		  ponto1.getHorarios().addElement("17:18");
		  ponto1.getHorarios().addElement("18:18");
		  ponto1.getHorarios().addElement("19:18");
		  ponto1.getHorarios().addElement("20:18");
		  ponto1.getHorarios().addElement("21:18");
		  ponto1.getHorarios().addElement("22:18");
		  ponto1.getHorarios().addElement("23:18");
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("JD.PAULISTA(E.MARIA VIA PNEU)");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("09/04/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("04:35");
		  ponto2.getHorarios().addElement("05:35");
		  ponto2.getHorarios().addElement("06:35");
		  ponto2.getHorarios().addElement("07:35");
		  ponto2.getHorarios().addElement("08:35");
		  ponto2.getHorarios().addElement("09:35");
		  ponto2.getHorarios().addElement("10:35");
		  ponto2.getHorarios().addElement("11:35");
		  ponto2.getHorarios().addElement("12:35");
		  ponto2.getHorarios().addElement("13:35");
		  ponto2.getHorarios().addElement("14:35");
		  ponto2.getHorarios().addElement("15:35");
		  ponto2.getHorarios().addElement("16:35");
		  ponto2.getHorarios().addElement("17:35");
		  ponto2.getHorarios().addElement("18:35");
		  ponto2.getHorarios().addElement("19:35");
		  ponto2.getHorarios().addElement("20:35");
		  ponto2.getHorarios().addElement("21:35");
		  ponto2.getHorarios().addElement("22:35");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("JD.PAULISTA(VIA CARON)");
		  ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto3.setValidoAPartirDe("09/04/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("05:00");
		  ponto3.getHorarios().addElement("06:00");
		  ponto3.getHorarios().addElement("07:00");
		  ponto3.getHorarios().addElement("08:00");
		  ponto3.getHorarios().addElement("09:00");
		  ponto3.getHorarios().addElement("10:00");
		  ponto3.getHorarios().addElement("11:00");
		  ponto3.getHorarios().addElement("12:00");
		  ponto3.getHorarios().addElement("13:00");
		  ponto3.getHorarios().addElement("14:00");
		  ponto3.getHorarios().addElement("15:00");
		  ponto3.getHorarios().addElement("16:00");
		  ponto3.getHorarios().addElement("17:00");
		  ponto3.getHorarios().addElement("18:00");
		  ponto3.getHorarios().addElement("19:00");
		  ponto3.getHorarios().addElement("20:00");
		  ponto3.getHorarios().addElement("21:00");
		  ponto3.getHorarios().addElement("22:00");
		  ponto3.getHorarios().addElement("23:00");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("TREVES");
		  ponto4.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto4.setValidoAPartirDe("09/04/2012");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("23:40");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("T.Q.BARRAS(VIA MENINO DEUS)");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("07/04/2012");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("05:08");
		  ponto5.getHorarios().addElement("06:08");
		  ponto5.getHorarios().addElement("07:08");
		  ponto5.getHorarios().addElement("08:08");
		  ponto5.getHorarios().addElement("09:08");
		  ponto5.getHorarios().addElement("10:08");
		  ponto5.getHorarios().addElement("11:08");
		  ponto5.getHorarios().addElement("12:08");
		  ponto5.getHorarios().addElement("13:08");
		  ponto5.getHorarios().addElement("14:08");
		  ponto5.getHorarios().addElement("15:08");
		  ponto5.getHorarios().addElement("16:08");
		  ponto5.getHorarios().addElement("17:08");
		  ponto5.getHorarios().addElement("18:08");
		  ponto5.getHorarios().addElement("19:08");
		  ponto5.getHorarios().addElement("20:08");
		  ponto5.getHorarios().addElement("21:08");
		  ponto5.getHorarios().addElement("22:08");
		  ponto5.getHorarios().addElement("23:08");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("JD.PAULISTA(E.MARIA VIA PNEU)");
		  ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto6.setValidoAPartirDe("07/04/2012");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("05:25");
		  ponto6.getHorarios().addElement("06:25");
		  ponto6.getHorarios().addElement("07:25");
		  ponto6.getHorarios().addElement("08:25");
		  ponto6.getHorarios().addElement("09:25");
		  ponto6.getHorarios().addElement("10:25");
		  ponto6.getHorarios().addElement("11:25");
		  ponto6.getHorarios().addElement("12:25");
		  ponto6.getHorarios().addElement("13:25");
		  ponto6.getHorarios().addElement("14:25");
		  ponto6.getHorarios().addElement("15:25");
		  ponto6.getHorarios().addElement("16:25");
		  ponto6.getHorarios().addElement("17:25");
		  ponto6.getHorarios().addElement("18:25");
		  ponto6.getHorarios().addElement("19:25");
		  ponto6.getHorarios().addElement("20:25");
		  ponto6.getHorarios().addElement("21:25");
		  ponto6.getHorarios().addElement("22:25");
		  ponto6.getHorarios().addElement("23:25");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("JD.PAULISTA(VIA CARON)");
		  ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto7.setValidoAPartirDe("07/04/2012");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("04:50");
		  ponto7.getHorarios().addElement("05:50");
		  ponto7.getHorarios().addElement("06:50");
		  ponto7.getHorarios().addElement("07:50");
		  ponto7.getHorarios().addElement("08:50");
		  ponto7.getHorarios().addElement("09:50");
		  ponto7.getHorarios().addElement("10:50");
		  ponto7.getHorarios().addElement("11:50");
		  ponto7.getHorarios().addElement("12:50");
		  ponto7.getHorarios().addElement("13:50");
		  ponto7.getHorarios().addElement("14:50");
		  ponto7.getHorarios().addElement("15:50");
		  ponto7.getHorarios().addElement("16:50");
		  ponto7.getHorarios().addElement("17:50");
		  ponto7.getHorarios().addElement("18:50");
		  ponto7.getHorarios().addElement("19:50");
		  ponto7.getHorarios().addElement("20:50");
		  ponto7.getHorarios().addElement("21:50");
		  ponto7.getHorarios().addElement("22:50");
		  ponto7.getHorarios().addElement("23:50");
		  return onibus;
		  }
	  }