
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.*;
	
	/**
	 * Código gerado automaticamente
	 * 
	 * @author will
	 */
	public class OnibusI40 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("Q. BARRAS / PIRAQUARA");
		onibus.setCodigo("I40");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("TERMINAL PIRAQUARA");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("01/06/2010");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:35");
		ponto0.getHorarios().addElement("06:01");
		ponto0.getHorarios().addElement("06:25");
		ponto0.getHorarios().addElement("07:13");
		ponto0.getHorarios().addElement("08:05");
		ponto0.getHorarios().addElement("08:50");
		ponto0.getHorarios().addElement("10:10");
		ponto0.getHorarios().addElement("11:30");
		ponto0.getHorarios().addElement("12:30");
		ponto0.getHorarios().addElement("13:05");
		ponto0.getHorarios().addElement("13:30");
		ponto0.getHorarios().addElement("14:40");
		ponto0.getHorarios().addElement("15:35");
		ponto0.getHorarios().addElement("16:35");
		ponto0.getHorarios().addElement("17:30");
		ponto0.getHorarios().addElement("18:10");
		ponto0.getHorarios().addElement("18:50");
		ponto0.getHorarios().addElement("20:00");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL QUATRO BARRAS");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("01/06/2010");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:15");
		ponto1.getHorarios().addElement("06:00");
		ponto1.getHorarios().addElement("06:24");
		ponto1.getHorarios().addElement("06:50");
		ponto1.getHorarios().addElement("07:40");
		ponto1.getHorarios().addElement("08:25");
		ponto1.getHorarios().addElement("09:40");
		ponto1.getHorarios().addElement("10:40");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:05");
		ponto1.getHorarios().addElement("14:00");
		ponto1.getHorarios().addElement("15:10");
		ponto1.getHorarios().addElement("16:10");
		ponto1.getHorarios().addElement("17:00");
		ponto1.getHorarios().addElement("17:50");
		ponto1.getHorarios().addElement("18:15");
		ponto1.getHorarios().addElement("18:30");
		ponto1.getHorarios().addElement("19:30");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("BRITANITE");
		ponto2.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto2.setValidoAPartirDe("11/02/2006");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:15");
		ponto2.getHorarios().addElement("06:25");
		ponto2.getHorarios().addElement("07:40");
		ponto2.getHorarios().addElement("10:15");
		ponto2.getHorarios().addElement("11:35");
		ponto2.getHorarios().addElement("13:00");
		ponto2.getHorarios().addElement("17:55");
		ponto2.getHorarios().addElement("19:10");
		ponto2.getHorarios().addElement("20:40");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("TERMINAL PIRAQUARA");
		ponto3.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto3.setValidoAPartirDe("11/02/2006");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("06:06");
		ponto3.getHorarios().addElement("09:42");
		ponto3.getHorarios().addElement("10:55");
		ponto3.getHorarios().addElement("12:20");
		ponto3.getHorarios().addElement("13:40");
		ponto3.getHorarios().addElement("14:40");
		ponto3.getHorarios().addElement("15:35");
		ponto3.getHorarios().addElement("16:25");
		ponto3.getHorarios().addElement("17:15");
		ponto3.getHorarios().addElement("18:30");
		ponto3.getHorarios().addElement("20:00");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL QUATRO BARRAS");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("11/02/2006");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:30");
		ponto4.getHorarios().addElement("06:40");
		ponto4.getHorarios().addElement("09:15");
		ponto4.getHorarios().addElement("10:30");
		ponto4.getHorarios().addElement("11:50");
		ponto4.getHorarios().addElement("13:15");
		ponto4.getHorarios().addElement("15:10");
		ponto4.getHorarios().addElement("16:00");
		ponto4.getHorarios().addElement("16:50");
		ponto4.getHorarios().addElement("17:40");
		ponto4.getHorarios().addElement("18:05");
		ponto4.getHorarios().addElement("19:30");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("BRITANITE");
		ponto5.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto5.setValidoAPartirDe("08/07/2012");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("09:00");
		ponto5.getHorarios().addElement("11:25");
		ponto5.getHorarios().addElement("12:35");
		ponto5.getHorarios().addElement("17:55");
		ponto5.getHorarios().addElement("19:00");
		ponto5.getHorarios().addElement("20:15");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL PIRAQUARA");
		ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto6.setValidoAPartirDe("08/07/2012");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("06:37");
		ponto6.getHorarios().addElement("09:42");
		ponto6.getHorarios().addElement("10:50");
		ponto6.getHorarios().addElement("12:00");
		ponto6.getHorarios().addElement("13:10");
		ponto6.getHorarios().addElement("14:40");
		ponto6.getHorarios().addElement("15:35");
		ponto6.getHorarios().addElement("16:25");
		ponto6.getHorarios().addElement("17:12");
		ponto6.getHorarios().addElement("19:40");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("TERMINAL QUATRO BARRAS");
		ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto7.setValidoAPartirDe("08/07/2012");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("07:12");
		ponto7.getHorarios().addElement("08:50");
		ponto7.getHorarios().addElement("09:15");
		ponto7.getHorarios().addElement("10:10");
		ponto7.getHorarios().addElement("11:15");
		ponto7.getHorarios().addElement("11:35");
		ponto7.getHorarios().addElement("12:25");
		ponto7.getHorarios().addElement("12:45");
		ponto7.getHorarios().addElement("15:10");
		ponto7.getHorarios().addElement("16:00");
		ponto7.getHorarios().addElement("16:48");
		ponto7.getHorarios().addElement("17:36");
		ponto7.getHorarios().addElement("17:45");
		ponto7.getHorarios().addElement("18:40");
		ponto7.getHorarios().addElement("19:15");
		ponto7.getHorarios().addElement("20:05");
		return onibus;
		}
	}