
	  package br.will.graviola.model.onibus;
	
	  import br.will.graviola.model.*;
	
	  /**
	   * Código gerado automaticamente
	   * 
	   * @author will
	   */
	  public class Onibus814 {
		  public static Onibus create() {
		  Onibus onibus = new Onibus();
		  onibus.setNome("814 - MOSSUNGUÊ");
		  onibus.setCodigo("814");
		  Ponto ponto0 = new Ponto();
		  ponto0.setNome("BAIRRO MOSSUNGUE");
		  ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto0.setValidoAPartirDe("03/09/2012");
		  onibus.getPontos().addElement(ponto0);
		  ponto0.getHorarios().addElement("06:00");
		  ponto0.getHorarios().addElement("06:20");
		  ponto0.getHorarios().addElement("06:40");
		  ponto0.getHorarios().addElement("07:00");
		  ponto0.getHorarios().addElement("07:20");
		  ponto0.getHorarios().addElement("07:40");
		  ponto0.getHorarios().addElement("08:00");
		  ponto0.getHorarios().addElement("08:20");
		  ponto0.getHorarios().addElement("08:40");
		  ponto0.getHorarios().addElement("09:20");
		  ponto0.getHorarios().addElement("10:00");
		  ponto0.getHorarios().addElement("10:40");
		  ponto0.getHorarios().addElement("11:20");
		  ponto0.getHorarios().addElement("11:40");
		  ponto0.getHorarios().addElement("12:03");
		  ponto0.getHorarios().addElement("12:25");
		  ponto0.getHorarios().addElement("12:48");
		  ponto0.getHorarios().addElement("13:10");
		  ponto0.getHorarios().addElement("13:33");
		  ponto0.getHorarios().addElement("14:18");
		  ponto0.getHorarios().addElement("15:03");
		  ponto0.getHorarios().addElement("15:48");
		  ponto0.getHorarios().addElement("16:33");
		  ponto0.getHorarios().addElement("16:55");
		  ponto0.getHorarios().addElement("17:20");
		  ponto0.getHorarios().addElement("17:45");
		  ponto0.getHorarios().addElement("18:10");
		  ponto0.getHorarios().addElement("18:35");
		  ponto0.getHorarios().addElement("19:00");
		  ponto0.getHorarios().addElement("19:25");
		  ponto0.getHorarios().addElement("19:45");
		  ponto0.getHorarios().addElement("20:05");
		  ponto0.getHorarios().addElement("20:24");
		  ponto0.getHorarios().addElement("20:43");
		  ponto0.getHorarios().addElement("21:02");
		  ponto0.getHorarios().addElement("21:21");
		  ponto0.getHorarios().addElement("21:40");
		  ponto0.getHorarios().addElement("22:00");
		  ponto0.getHorarios().addElement("22:20");
		  ponto0.getHorarios().addElement("22:40");
		  ponto0.getHorarios().addElement("23:30");
		  Ponto ponto1 = new Ponto();
		  ponto1.setNome("COPEL MOSSUNGUE");
		  ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto1.setValidoAPartirDe("03/09/2012");
		  onibus.getPontos().addElement(ponto1);
		  Ponto ponto2 = new Ponto();
		  ponto2.setNome("TERMINAL CAMPINA DO SIQUEIRA");
		  ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto2.setValidoAPartirDe("03/09/2012");
		  onibus.getPontos().addElement(ponto2);
		  ponto2.getHorarios().addElement("06:20");
		  ponto2.getHorarios().addElement("06:40");
		  ponto2.getHorarios().addElement("07:00");
		  ponto2.getHorarios().addElement("07:18");
		  ponto2.getHorarios().addElement("07:20");
		  ponto2.getHorarios().addElement("07:38");
		  ponto2.getHorarios().addElement("07:40");
		  ponto2.getHorarios().addElement("08:00");
		  ponto2.getHorarios().addElement("08:10");
		  ponto2.getHorarios().addElement("08:20");
		  ponto2.getHorarios().addElement("08:40");
		  ponto2.getHorarios().addElement("09:00");
		  ponto2.getHorarios().addElement("09:40");
		  ponto2.getHorarios().addElement("10:20");
		  ponto2.getHorarios().addElement("11:00");
		  ponto2.getHorarios().addElement("11:20");
		  ponto2.getHorarios().addElement("11:40");
		  ponto2.getHorarios().addElement("12:02");
		  ponto2.getHorarios().addElement("12:25");
		  ponto2.getHorarios().addElement("12:47");
		  ponto2.getHorarios().addElement("13:10");
		  ponto2.getHorarios().addElement("13:55");
		  ponto2.getHorarios().addElement("14:40");
		  ponto2.getHorarios().addElement("15:25");
		  ponto2.getHorarios().addElement("16:10");
		  ponto2.getHorarios().addElement("16:55");
		  ponto2.getHorarios().addElement("17:20");
		  ponto2.getHorarios().addElement("17:45");
		  ponto2.getHorarios().addElement("18:05");
		  ponto2.getHorarios().addElement("18:10");
		  ponto2.getHorarios().addElement("18:30");
		  ponto2.getHorarios().addElement("18:35");
		  ponto2.getHorarios().addElement("18:50");
		  ponto2.getHorarios().addElement("19:00");
		  ponto2.getHorarios().addElement("19:25");
		  ponto2.getHorarios().addElement("19:45");
		  ponto2.getHorarios().addElement("20:05");
		  ponto2.getHorarios().addElement("20:24");
		  ponto2.getHorarios().addElement("20:43");
		  ponto2.getHorarios().addElement("21:02");
		  ponto2.getHorarios().addElement("21:21");
		  ponto2.getHorarios().addElement("21:40");
		  ponto2.getHorarios().addElement("22:00");
		  ponto2.getHorarios().addElement("22:20");
		  ponto2.getHorarios().addElement("22:30");
		  ponto2.getHorarios().addElement("22:40");
		  ponto2.getHorarios().addElement("23:10");
		  ponto2.getHorarios().addElement("00:00");
		  Ponto ponto3 = new Ponto();
		  ponto3.setNome("TUIUTI MOSSUNGUE");
		  ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		  ponto3.setValidoAPartirDe("03/09/2012");
		  onibus.getPontos().addElement(ponto3);
		  ponto3.getHorarios().addElement("18:15");
		  ponto3.getHorarios().addElement("18:40");
		  ponto3.getHorarios().addElement("22:20");
		  ponto3.getHorarios().addElement("22:40");
		  Ponto ponto4 = new Ponto();
		  ponto4.setNome("BAIRRO MOSSUNGUE");
		  ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto4.setValidoAPartirDe("29/11/2008");
		  onibus.getPontos().addElement(ponto4);
		  ponto4.getHorarios().addElement("06:00");
		  ponto4.getHorarios().addElement("06:40");
		  ponto4.getHorarios().addElement("07:20");
		  ponto4.getHorarios().addElement("08:00");
		  ponto4.getHorarios().addElement("08:40");
		  ponto4.getHorarios().addElement("09:20");
		  ponto4.getHorarios().addElement("10:00");
		  ponto4.getHorarios().addElement("10:40");
		  ponto4.getHorarios().addElement("11:20");
		  ponto4.getHorarios().addElement("12:00");
		  ponto4.getHorarios().addElement("12:40");
		  ponto4.getHorarios().addElement("13:20");
		  ponto4.getHorarios().addElement("14:00");
		  ponto4.getHorarios().addElement("14:40");
		  ponto4.getHorarios().addElement("15:20");
		  ponto4.getHorarios().addElement("16:00");
		  ponto4.getHorarios().addElement("16:40");
		  ponto4.getHorarios().addElement("17:20");
		  ponto4.getHorarios().addElement("18:00");
		  ponto4.getHorarios().addElement("18:40");
		  ponto4.getHorarios().addElement("19:20");
		  ponto4.getHorarios().addElement("20:00");
		  ponto4.getHorarios().addElement("20:40");
		  ponto4.getHorarios().addElement("21:20");
		  ponto4.getHorarios().addElement("22:00");
		  ponto4.getHorarios().addElement("22:40");
		  ponto4.getHorarios().addElement("23:20");
		  Ponto ponto5 = new Ponto();
		  ponto5.setNome("TERMINAL CAMPINA DO SIQUEIRA");
		  ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		  ponto5.setValidoAPartirDe("29/11/2008");
		  onibus.getPontos().addElement(ponto5);
		  ponto5.getHorarios().addElement("06:20");
		  ponto5.getHorarios().addElement("07:00");
		  ponto5.getHorarios().addElement("07:40");
		  ponto5.getHorarios().addElement("08:20");
		  ponto5.getHorarios().addElement("09:00");
		  ponto5.getHorarios().addElement("09:40");
		  ponto5.getHorarios().addElement("10:20");
		  ponto5.getHorarios().addElement("11:00");
		  ponto5.getHorarios().addElement("11:40");
		  ponto5.getHorarios().addElement("12:20");
		  ponto5.getHorarios().addElement("13:00");
		  ponto5.getHorarios().addElement("13:40");
		  ponto5.getHorarios().addElement("14:20");
		  ponto5.getHorarios().addElement("15:00");
		  ponto5.getHorarios().addElement("15:40");
		  ponto5.getHorarios().addElement("16:20");
		  ponto5.getHorarios().addElement("17:00");
		  ponto5.getHorarios().addElement("17:40");
		  ponto5.getHorarios().addElement("18:20");
		  ponto5.getHorarios().addElement("19:00");
		  ponto5.getHorarios().addElement("19:40");
		  ponto5.getHorarios().addElement("20:20");
		  ponto5.getHorarios().addElement("21:00");
		  ponto5.getHorarios().addElement("21:40");
		  ponto5.getHorarios().addElement("22:20");
		  ponto5.getHorarios().addElement("23:00");
		  ponto5.getHorarios().addElement("23:40");
		  Ponto ponto6 = new Ponto();
		  ponto6.setNome("BAIRRO MOSSUNGUE");
		  ponto6.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto6.setValidoAPartirDe("30/11/2008");
		  onibus.getPontos().addElement(ponto6);
		  ponto6.getHorarios().addElement("06:00");
		  ponto6.getHorarios().addElement("06:40");
		  ponto6.getHorarios().addElement("07:20");
		  ponto6.getHorarios().addElement("08:00");
		  ponto6.getHorarios().addElement("08:40");
		  ponto6.getHorarios().addElement("09:20");
		  ponto6.getHorarios().addElement("10:00");
		  ponto6.getHorarios().addElement("10:40");
		  ponto6.getHorarios().addElement("11:20");
		  ponto6.getHorarios().addElement("12:00");
		  ponto6.getHorarios().addElement("12:40");
		  ponto6.getHorarios().addElement("13:20");
		  ponto6.getHorarios().addElement("14:00");
		  ponto6.getHorarios().addElement("14:40");
		  ponto6.getHorarios().addElement("15:20");
		  ponto6.getHorarios().addElement("16:00");
		  ponto6.getHorarios().addElement("16:40");
		  ponto6.getHorarios().addElement("17:20");
		  ponto6.getHorarios().addElement("18:00");
		  ponto6.getHorarios().addElement("18:40");
		  ponto6.getHorarios().addElement("19:20");
		  ponto6.getHorarios().addElement("20:00");
		  ponto6.getHorarios().addElement("20:40");
		  ponto6.getHorarios().addElement("21:20");
		  ponto6.getHorarios().addElement("22:00");
		  ponto6.getHorarios().addElement("22:40");
		  ponto6.getHorarios().addElement("23:20");
		  Ponto ponto7 = new Ponto();
		  ponto7.setNome("TERMINAL CAMPINA DO SIQUEIRA");
		  ponto7.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		  ponto7.setValidoAPartirDe("30/11/2008");
		  onibus.getPontos().addElement(ponto7);
		  ponto7.getHorarios().addElement("06:20");
		  ponto7.getHorarios().addElement("07:00");
		  ponto7.getHorarios().addElement("07:40");
		  ponto7.getHorarios().addElement("08:20");
		  ponto7.getHorarios().addElement("09:00");
		  ponto7.getHorarios().addElement("09:40");
		  ponto7.getHorarios().addElement("10:20");
		  ponto7.getHorarios().addElement("11:00");
		  ponto7.getHorarios().addElement("11:40");
		  ponto7.getHorarios().addElement("12:20");
		  ponto7.getHorarios().addElement("13:00");
		  ponto7.getHorarios().addElement("13:40");
		  ponto7.getHorarios().addElement("14:20");
		  ponto7.getHorarios().addElement("15:00");
		  ponto7.getHorarios().addElement("15:40");
		  ponto7.getHorarios().addElement("16:20");
		  ponto7.getHorarios().addElement("17:00");
		  ponto7.getHorarios().addElement("17:40");
		  ponto7.getHorarios().addElement("18:20");
		  ponto7.getHorarios().addElement("19:00");
		  ponto7.getHorarios().addElement("19:40");
		  ponto7.getHorarios().addElement("20:20");
		  ponto7.getHorarios().addElement("21:00");
		  ponto7.getHorarios().addElement("21:40");
		  ponto7.getHorarios().addElement("22:20");
		  ponto7.getHorarios().addElement("23:00");
		  ponto7.getHorarios().addElement("23:40");
		  return onibus;
		  }
	  }