
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class OnibusN73 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("CTBA / TIMBÚ");
		onibus.setCodigo("N73");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO EUGENIA MARIA");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("28/05/2012");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("00:00");
		ponto0.getHorarios().addElement("00:50");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL GUADALUPE");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("28/05/2012");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("05:50");
		ponto1.getHorarios().addElement("06:15");
		ponto1.getHorarios().addElement("06:40");
		ponto1.getHorarios().addElement("07:05");
		ponto1.getHorarios().addElement("07:30");
		ponto1.getHorarios().addElement("07:55");
		ponto1.getHorarios().addElement("08:20");
		ponto1.getHorarios().addElement("09:10");
		ponto1.getHorarios().addElement("09:35");
		ponto1.getHorarios().addElement("10:08");
		ponto1.getHorarios().addElement("10:50");
		ponto1.getHorarios().addElement("11:23");
		ponto1.getHorarios().addElement("11:56");
		ponto1.getHorarios().addElement("12:30");
		ponto1.getHorarios().addElement("13:03");
		ponto1.getHorarios().addElement("13:36");
		ponto1.getHorarios().addElement("14:10");
		ponto1.getHorarios().addElement("14:43");
		ponto1.getHorarios().addElement("15:16");
		ponto1.getHorarios().addElement("15:50");
		ponto1.getHorarios().addElement("16:23");
		ponto1.getHorarios().addElement("16:56");
		ponto1.getHorarios().addElement("17:21");
		ponto1.getHorarios().addElement("17:46");
		ponto1.getHorarios().addElement("18:11");
		ponto1.getHorarios().addElement("18:36");
		ponto1.getHorarios().addElement("19:01");
		ponto1.getHorarios().addElement("19:26");
		ponto1.getHorarios().addElement("19:51");
		ponto1.getHorarios().addElement("20:16");
		ponto1.getHorarios().addElement("20:55");
		ponto1.getHorarios().addElement("21:28");
		ponto1.getHorarios().addElement("22:01");
		ponto1.getHorarios().addElement("23:20");
		ponto1.getHorarios().addElement("00:10");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL JD.PAULISTA");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("28/05/2012");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("05:00");
		ponto2.getHorarios().addElement("05:25");
		ponto2.getHorarios().addElement("05:50");
		ponto2.getHorarios().addElement("06:15");
		ponto2.getHorarios().addElement("06:40");
		ponto2.getHorarios().addElement("07:05");
		ponto2.getHorarios().addElement("07:30");
		ponto2.getHorarios().addElement("07:50");
		ponto2.getHorarios().addElement("08:20");
		ponto2.getHorarios().addElement("08:45");
		ponto2.getHorarios().addElement("09:18");
		ponto2.getHorarios().addElement("10:00");
		ponto2.getHorarios().addElement("10:33");
		ponto2.getHorarios().addElement("11:06");
		ponto2.getHorarios().addElement("11:40");
		ponto2.getHorarios().addElement("12:13");
		ponto2.getHorarios().addElement("12:46");
		ponto2.getHorarios().addElement("13:20");
		ponto2.getHorarios().addElement("13:53");
		ponto2.getHorarios().addElement("14:26");
		ponto2.getHorarios().addElement("15:00");
		ponto2.getHorarios().addElement("15:33");
		ponto2.getHorarios().addElement("16:06");
		ponto2.getHorarios().addElement("16:40");
		ponto2.getHorarios().addElement("17:13");
		ponto2.getHorarios().addElement("17:46");
		ponto2.getHorarios().addElement("18:11");
		ponto2.getHorarios().addElement("18:36");
		ponto2.getHorarios().addElement("19:01");
		ponto2.getHorarios().addElement("19:26");
		ponto2.getHorarios().addElement("20:10");
		ponto2.getHorarios().addElement("20:36");
		ponto2.getHorarios().addElement("21:06");
		ponto2.getHorarios().addElement("21:45");
		ponto2.getHorarios().addElement("22:47");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("EMPRESA CHOCOLATES BARION");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("28/05/2012");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("23:05");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("TERMINAL GUADALUPE");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("12/05/2012");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("05:56");
		ponto4.getHorarios().addElement("06:33");
		ponto4.getHorarios().addElement("07:10");
		ponto4.getHorarios().addElement("07:47");
		ponto4.getHorarios().addElement("08:24");
		ponto4.getHorarios().addElement("09:01");
		ponto4.getHorarios().addElement("09:38");
		ponto4.getHorarios().addElement("10:15");
		ponto4.getHorarios().addElement("10:52");
		ponto4.getHorarios().addElement("11:29");
		ponto4.getHorarios().addElement("12:06");
		ponto4.getHorarios().addElement("12:43");
		ponto4.getHorarios().addElement("13:20");
		ponto4.getHorarios().addElement("13:57");
		ponto4.getHorarios().addElement("14:34");
		ponto4.getHorarios().addElement("15:11");
		ponto4.getHorarios().addElement("15:42");
		ponto4.getHorarios().addElement("16:25");
		ponto4.getHorarios().addElement("17:02");
		ponto4.getHorarios().addElement("17:39");
		ponto4.getHorarios().addElement("18:16");
		ponto4.getHorarios().addElement("18:53");
		ponto4.getHorarios().addElement("19:30");
		ponto4.getHorarios().addElement("20:07");
		ponto4.getHorarios().addElement("20:33");
		ponto4.getHorarios().addElement("21:18");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL JD.PAULISTA");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("12/05/2012");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("05:00");
		ponto5.getHorarios().addElement("05:37");
		ponto5.getHorarios().addElement("06:14");
		ponto5.getHorarios().addElement("06:48");
		ponto5.getHorarios().addElement("07:28");
		ponto5.getHorarios().addElement("08:05");
		ponto5.getHorarios().addElement("08:42");
		ponto5.getHorarios().addElement("09:19");
		ponto5.getHorarios().addElement("09:53");
		ponto5.getHorarios().addElement("10:33");
		ponto5.getHorarios().addElement("11:10");
		ponto5.getHorarios().addElement("11:45");
		ponto5.getHorarios().addElement("12:24");
		ponto5.getHorarios().addElement("13:01");
		ponto5.getHorarios().addElement("13:38");
		ponto5.getHorarios().addElement("14:15");
		ponto5.getHorarios().addElement("14:52");
		ponto5.getHorarios().addElement("15:29");
		ponto5.getHorarios().addElement("16:06");
		ponto5.getHorarios().addElement("16:43");
		ponto5.getHorarios().addElement("17:20");
		ponto5.getHorarios().addElement("17:57");
		ponto5.getHorarios().addElement("18:34");
		ponto5.getHorarios().addElement("19:11");
		ponto5.getHorarios().addElement("19:48");
		ponto5.getHorarios().addElement("20:33");
		return onibus;
		}
	}