
	package br.will.graviola.model.onibus;
	
	import br.will.graviola.model.Onibus;
	import br.will.graviola.model.Ponto;
	import br.will.graviola.model.TipoDia;
	
	public class Onibus825 {
		public static Onibus create() {
		Onibus onibus = new Onibus();
		onibus.setNome("V. MARQUETO");
		onibus.setCodigo("825");
		Ponto ponto0 = new Ponto();
		ponto0.setNome("BAIRRO VILA MARQUETO");
		ponto0.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto0.setValidoAPartirDe("22/09/2008");
		onibus.getPontos().addElement(ponto0);
		ponto0.getHorarios().addElement("05:35");
		ponto0.getHorarios().addElement("06:25");
		ponto0.getHorarios().addElement("07:16");
		ponto0.getHorarios().addElement("08:06");
		ponto0.getHorarios().addElement("08:55");
		ponto0.getHorarios().addElement("09:48");
		ponto0.getHorarios().addElement("10:35");
		ponto0.getHorarios().addElement("11:25");
		ponto0.getHorarios().addElement("12:16");
		ponto0.getHorarios().addElement("13:05");
		ponto0.getHorarios().addElement("13:55");
		ponto0.getHorarios().addElement("14:45");
		ponto0.getHorarios().addElement("15:45");
		ponto0.getHorarios().addElement("16:45");
		ponto0.getHorarios().addElement("17:45");
		ponto0.getHorarios().addElement("18:45");
		ponto0.getHorarios().addElement("19:45");
		ponto0.getHorarios().addElement("20:45");
		ponto0.getHorarios().addElement("21:35");
		ponto0.getHorarios().addElement("22:25");
		ponto0.getHorarios().addElement("23:06");
		Ponto ponto1 = new Ponto();
		ponto1.setNome("TERMINAL CAMPO COMPRIDO");
		ponto1.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto1.setValidoAPartirDe("22/09/2008");
		onibus.getPontos().addElement(ponto1);
		ponto1.getHorarios().addElement("06:00");
		ponto1.getHorarios().addElement("08:30");
		ponto1.getHorarios().addElement("09:25");
		ponto1.getHorarios().addElement("10:15");
		ponto1.getHorarios().addElement("11:00");
		ponto1.getHorarios().addElement("13:32");
		ponto1.getHorarios().addElement("14:20");
		ponto1.getHorarios().addElement("15:19");
		ponto1.getHorarios().addElement("16:10");
		Ponto ponto2 = new Ponto();
		ponto2.setNome("TERMINAL SENTIDO V.MORO");
		ponto2.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto2.setValidoAPartirDe("22/09/2008");
		onibus.getPontos().addElement(ponto2);
		ponto2.getHorarios().addElement("06:51");
		ponto2.getHorarios().addElement("07:37");
		ponto2.getHorarios().addElement("11:52");
		ponto2.getHorarios().addElement("12:40");
		ponto2.getHorarios().addElement("17:20");
		ponto2.getHorarios().addElement("18:15");
		ponto2.getHorarios().addElement("19:20");
		ponto2.getHorarios().addElement("20:15");
		ponto2.getHorarios().addElement("21:13");
		ponto2.getHorarios().addElement("22:00");
		ponto2.getHorarios().addElement("22:45");
		ponto2.getHorarios().addElement("23:45");
		Ponto ponto3 = new Ponto();
		ponto3.setNome("VILA MORO SENTIDO TERMINAL");
		ponto3.setTipoDia(TipoDia.getTipoDia("DIA_UTIL"));
		ponto3.setValidoAPartirDe("22/09/2008");
		onibus.getPontos().addElement(ponto3);
		ponto3.getHorarios().addElement("05:41");
		ponto3.getHorarios().addElement("06:32");
		ponto3.getHorarios().addElement("07:22");
		ponto3.getHorarios().addElement("08:13");
		ponto3.getHorarios().addElement("11:31");
		ponto3.getHorarios().addElement("12:22");
		ponto3.getHorarios().addElement("13:13");
		ponto3.getHorarios().addElement("16:53");
		ponto3.getHorarios().addElement("17:52");
		ponto3.getHorarios().addElement("18:52");
		ponto3.getHorarios().addElement("19:52");
		Ponto ponto4 = new Ponto();
		ponto4.setNome("BAIRRO VILA MARQUETO");
		ponto4.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto4.setValidoAPartirDe("16/08/2008");
		onibus.getPontos().addElement(ponto4);
		ponto4.getHorarios().addElement("06:20");
		ponto4.getHorarios().addElement("07:10");
		ponto4.getHorarios().addElement("08:00");
		ponto4.getHorarios().addElement("08:50");
		ponto4.getHorarios().addElement("09:40");
		ponto4.getHorarios().addElement("10:30");
		ponto4.getHorarios().addElement("11:30");
		ponto4.getHorarios().addElement("12:30");
		ponto4.getHorarios().addElement("13:30");
		ponto4.getHorarios().addElement("14:30");
		ponto4.getHorarios().addElement("15:30");
		ponto4.getHorarios().addElement("16:30");
		ponto4.getHorarios().addElement("17:30");
		ponto4.getHorarios().addElement("18:20");
		ponto4.getHorarios().addElement("18:50");
		Ponto ponto5 = new Ponto();
		ponto5.setNome("TERMINAL CAMPO COMPRIDO");
		ponto5.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto5.setValidoAPartirDe("16/08/2008");
		onibus.getPontos().addElement(ponto5);
		ponto5.getHorarios().addElement("06:40");
		ponto5.getHorarios().addElement("07:35");
		ponto5.getHorarios().addElement("08:26");
		ponto5.getHorarios().addElement("09:10");
		ponto5.getHorarios().addElement("10:00");
		ponto5.getHorarios().addElement("10:55");
		ponto5.getHorarios().addElement("12:00");
		Ponto ponto6 = new Ponto();
		ponto6.setNome("TERMINAL SENTIDO V.MORO");
		ponto6.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto6.setValidoAPartirDe("16/08/2008");
		onibus.getPontos().addElement(ponto6);
		ponto6.getHorarios().addElement("12:55");
		ponto6.getHorarios().addElement("14:02");
		ponto6.getHorarios().addElement("14:55");
		ponto6.getHorarios().addElement("15:55");
		ponto6.getHorarios().addElement("16:58");
		ponto6.getHorarios().addElement("17:57");
		ponto6.getHorarios().addElement("18:40");
		Ponto ponto7 = new Ponto();
		ponto7.setNome("VILA MORO SENTIDO TERMINAL");
		ponto7.setTipoDia(TipoDia.getTipoDia("SABADO"));
		ponto7.setValidoAPartirDe("16/08/2008");
		onibus.getPontos().addElement(ponto7);
		ponto7.getHorarios().addElement("06:25");
		ponto7.getHorarios().addElement("07:16");
		ponto7.getHorarios().addElement("08:06");
		Ponto ponto8 = new Ponto();
		ponto8.setNome("BAIRRO VILA MARQUETO");
		ponto8.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto8.setValidoAPartirDe("21/09/2008");
		onibus.getPontos().addElement(ponto8);
		ponto8.getHorarios().addElement("06:30");
		ponto8.getHorarios().addElement("07:30");
		ponto8.getHorarios().addElement("08:20");
		ponto8.getHorarios().addElement("09:05");
		ponto8.getHorarios().addElement("09:55");
		ponto8.getHorarios().addElement("10:45");
		ponto8.getHorarios().addElement("11:45");
		ponto8.getHorarios().addElement("12:45");
		ponto8.getHorarios().addElement("13:45");
		ponto8.getHorarios().addElement("14:45");
		ponto8.getHorarios().addElement("15:45");
		ponto8.getHorarios().addElement("16:45");
		ponto8.getHorarios().addElement("17:45");
		ponto8.getHorarios().addElement("18:45");
		ponto8.getHorarios().addElement("19:45");
		Ponto ponto9 = new Ponto();
		ponto9.setNome("TERMINAL CAMPO COMPRIDO");
		ponto9.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto9.setValidoAPartirDe("21/09/2008");
		onibus.getPontos().addElement(ponto9);
		ponto9.getHorarios().addElement("06:55");
		ponto9.getHorarios().addElement("08:05");
		ponto9.getHorarios().addElement("08:40");
		ponto9.getHorarios().addElement("09:25");
		ponto9.getHorarios().addElement("10:10");
		ponto9.getHorarios().addElement("11:15");
		ponto9.getHorarios().addElement("12:15");
		Ponto ponto10 = new Ponto();
		ponto10.setNome("TERMINAL SENTIDO V.MORO");
		ponto10.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto10.setValidoAPartirDe("21/09/2008");
		onibus.getPontos().addElement(ponto10);
		ponto10.getHorarios().addElement("13:15");
		ponto10.getHorarios().addElement("14:10");
		ponto10.getHorarios().addElement("15:15");
		ponto10.getHorarios().addElement("16:10");
		ponto10.getHorarios().addElement("17:15");
		ponto10.getHorarios().addElement("18:10");
		ponto10.getHorarios().addElement("19:15");
		Ponto ponto11 = new Ponto();
		ponto11.setNome("VILA MORO SENTIDO TERMINAL");
		ponto11.setTipoDia(TipoDia.getTipoDia("DOMINGO"));
		ponto11.setValidoAPartirDe("21/09/2008");
		onibus.getPontos().addElement(ponto11);
		ponto11.getHorarios().addElement("06:35");
		ponto11.getHorarios().addElement("07:35");
		ponto11.getHorarios().addElement("08:25");
		return onibus;
		}
	}